<?php $this->layout()->setLayout('none'); ?>
<?php
switch($this->status_id) {
case 0: 
    $type = "success"; 
    $label = "OK";
    break;//OK
case 1: 
    $type = "warning";
    $label = "Warning";
    break;//OK
case 2: 
    $type = "important"; 
    $label = "Critical";
    break;//OK
default: 
    $label = "N/A";
    $type = ""; //default - gray
}
echo "<p><span class=\"label label-$type\">$label</span> ";
if($label != $this->status) echo $this->escape($this->status);
echo "</p>";
echo "<pre>".$this->escape($this->detail->result->message)."</pre>";
?>

<table class="table table-condensed">

<?php
//show result message

foreach($this->detail->parameters as $key=>$value) {
    echo "<tr><th>$key</th>";
    echo "<td>$value</td>";
    echo "</tr>";
}

?>
</table>
