<?=$this->header?>
<?
if(user()->isGuest()) {
    echo "<!--";
    echo "NOTE: Email address and phone number of contacts are displayed only to authorized users who have there DN loaded in their web-browser or wget/curl type web client, and are registered in OIM with appropriate authorization level(s).";
    echo "-->";
}
?>
<PerfsonarMatrix xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://myosg.grid.iu.edu/schema/rgpfstatus.xsd">
<!-- TODO -->
</PerfsonarMatrix>
