<?=$this->header?>
<VOVOMSStatus xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://my.opensciencegrid.org/schema/vovomsstatus.xsd">
<VOs>
<?

foreach($this->voms_status as $voms_status) {
    $info = $voms_status["info"];
    $vomses = $voms_status["voms"];

    $id = $info->id;
    $name = $info->name;

    echo "<VO>";
    echo "<ID>$id</ID>";
    echo "<Name>".htmlsafe($name)."</Name>";
    echo "<VOMSes>";
    echo outputStatus($info, $vomses);
    echo "</VOMSes>";
    echo "</VO>";
}

function outputStatus($info, $vomses) {
    $out = "";
    if(count($vomses) != 0) {
        foreach($vomses as $voms) {
            $out .= "<VOMS>";
            $status = $voms->Status;
            $out .= "<Status>".$status."</Status>";
            $server_url = $voms->VOMSServerURL;
            $out .= "<URL>".htmlsafe($server_url)."</URL>";
            $out .= "<Description>".htmlsafe($voms->Note)."</Description>";
            $out .= "</VOMS>";
        }
    }
    return $out;
}
?>
</VOs>
</VOVOMSStatus>
