<?

header("Content-Type: text/x-vCalendar");
echo "BEGIN:VCALENDAR\n";
echo "PRODID:-//GOC/".config()->app_name." ".config()->version."//EN\n";
echo "VERSION:2.0\n";
echo "CALSCALE:GREGORIAN\n";
echo "METHOD:PUBLISH\n";
echo "X-WR-CALNAME:OSG Downtime Calendar\n";
echo "X-WR-TIMEZONE:America/New_York\n";

foreach($this->downtimes as $downtime)
{
    //only show event that we have pulled resource for
    $resource_name = getResourceName($this->resources, $downtime->resource_id);
    if($resource_name !== null) {
        echo "BEGIN:VEVENT\n";

        //non-all day event
        //$format = "Ymd\THis\Z";
        //$start = date($format, $downtime->unix_start_time);
        //$end = date($format, $downtime->unix_end_time);
        //echo "DTSTART:$start\n";
        //echo "DTEND:$end\n";

        $format = "Ymd";
        $start = date($format, $downtime->unix_start_time);
        $end = date($format, $downtime->unix_end_time);
        echo "DTSTART;VALUE=DATE:$start\n";
        echo "DTEND;VALUE=DATE:$end\n";

        $summary = $resource_name;
        echo "SUMMARY:$summary\n";

        $start_human = date(config()->date_format_full, $downtime->unix_start_time);
        $end_human = date(config()->date_format_full, $downtime->unix_end_time);
        $desc = "(From $start_human To $end_human) ";
        $desc .= $downtime->downtime_summary;

        //append affected services
        $desc .= "(Affected Services:";
        foreach($this->downtime_services as $service) {
            if($service->downtime_id == $downtime->downtime_id) {
                $desc .= $service->service_id;
            }
        } 
        $desc .= ")";
        
        $desc = str_replace(array("\n", "\r"), "", $desc);
        echo "DESCRIPTION:$desc\n";

        echo "END:VEVENT\n";
    }
}

function getResourceName($resources, $id)
{
    foreach($resources as $resource) {
        if($resource->id == $id) return $resource->name;
    }
    return null;
}

echo "END:VCALENDAR\n";



