<?
foreach($this->cpuinfos as $info)
{
    //header
    echo "<div class=\"header round\">$info->name</div>";

    ?>
    <table class="summary_table">
    <tr>
        <th>Normalization Constant</th>
        <td><?=htmlsafe($info->normalization_constant)?></td>
    </tr>
    <tr>
        <th>HEPSPEC Constant</th>
        <td><?=htmlsafe($info->hepspec_normalization_constant)?></td>
    </tr>
    <tr>
        <th>Notes</th>
        <td><?=htmlsafe($info->notes)?></td>
    </tr>
    </table>
    <?
}
