<?
foreach($this->cpuinfos as $info)
{
    //header
    echo "<div class=\"cpuinfo_header round\">";
    echo "<span class=\"h3\">$info->name</span>";
    echo "</div>";

    ?>
    <table class="summary_table">
    <tr>
        <th>Normalization Constant</th>
        <td><?=htmlsafe($info->normalization_constant)?></td>
    </tr>
    <tr>
        <th>Notes</th>
        <td><?=htmlsafe($info->notes)?></td>
    </tr>
    </table>
    <?
}
