<?=$this->header?>
<CPUInfos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://myosg.grid.iu.edu/schema/misccpuinfo.xsd">
<?
foreach($this->cpuinfos as $info)
{
    //header
    ?><CPUInfo>
<ID><?=htmlsafe($info->id)?></ID>
<Name><?=htmlsafe($info->name)?></Name>
<NormalizationConstant><?=htmlsafe($info->normalization_constant)?></NormalizationConstant>
<HEPSPEC><?=htmlsafe($info->hepspec_normalization_constant)?></HEPSPEC>
<Notes><?=htmlsafe($info->notes)?></Notes>
</CPUInfo>
<?
}
?>
</CPUInfos>
