<?=$this->header?>
<!-- This page has been depricated. Please do not use -->
<BDIITreeMap xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://my.opensciencegrid.org/schema/rgbdiitree.xsd">
    <TotalArea><?=$this->total_area?></TotalArea>
    <GroupBy><?=$this->sub_title?></GroupBy>
    <ResourceGroups>
<?
    foreach($this->rgs as $rgid=>$rg) {
        $group_info = $rg["info"];
        $resources = $rg["resources"];
        if(count($resources) == 0) continue;

        $subinfo = "<Resources>";
        $rgtotal = 0;
        foreach($resources as $rid=>$resource) {
            $resource_info = $resource["info"];
            $area = $resource["agg"]->get($this->key);
            $rgtotal += $area;

            $subinfo .= "<Resource>";
            $subinfo .= "<ID>".$resource_info->id."</ID>";
            $subinfo .= "<Name>".$resource_info->name."</Name>";
            $subinfo .= "<FQDN>".$resource_info->fqdn."</FQDN>";
            $subinfo .= "<Area>$area</Area>";
            $subinfo .= "</Resource>";
        }
        $subinfo .= "</Resources>";

        echo "<ResourceGroup>";
        echo "<GroupID>".$group_info->id."</GroupID>";
        echo "<GroupName>".$group_info->name."</GroupName>";
        echo "<GroupArea>$rgtotal</GroupArea>";
        echo $subinfo;
        echo "</ResourceGroup>";

    }
?>
    </ResourceGroups>
</BDIITreeMap>
