<?=$this->render("full_header.phtml", true)?>

        <div id="primaryContentContainer">
            <div id="primaryContent">
                <div class="error_message">Everything you see on this page is a mockup. GOC takes no responsiblity whatsoever on these contents.</strong></div>
                <h2>Welcome to <?=config()->app_name?>!</h2>

                <p><strong><?=config()->app_name?></strong> is a central web interface for information related to OSG and its operations. Most of the pages displayed here can be exported into several different formats as well as various content aggregation systems such as Netvibes or iGoogle in order for you to create your own dashbaord where you display information relavant to your day to day activities.</p>

                <h3>Voices from our Users</h3>
                <blockquote>
                        <p>"<?=config()->app_name?> is a great place where I can quickly pull infomration I need without looking around many different webpages. Once I found the information I am looking for, I can export it into my Netvibe homepage so that I don't ever have to look for the same page again."</p>
                </blockquote>
                <h3>Information currently Avilable</h3>
                <ul>
                    <li><a href="#">Current RSV results resource / service status</a></li>
                    <li><a href="#">History chart for past resource / service status.</a></li>
                    <li><a href="#">Various OIM related information such as VO matrix.</a></li>
                    <li><a href="#">BDII / GIP information</a></li>
                    <li><a href="#">Links to OSG support systems</a></li>
                </ul>
                <h3>Development Timeline</h3>
                <table>
                    <tr class="rowH">
                        <th>Date</th>
                        <th>State</th>
                        <th>Description</th>
                    </tr>
                    <tr class="rowA">
                        <td>October 1, 2008</td>
                        <td>Requirement Gathering</td>
                        <td>Alpha version will be lunched for public to gain insight as to what feature should be implemented .</td>
                    </tr>
                    <tr class="rowB">
                        <td>XXX, 2008</td>
                        <td>Development Begins</td>
                        <td>Official development cycle will begin given go ahead from our management.</td>
                    </tr>
                    <tr class="rowA">
                        <td>XXX, 2008</td>
                        <td>First ITB Release</td>
                        <td>ITB Version will be send to selected users for testing.</td>
                    </tr>
                    <tr class="rowB">
                        <td>XXX, 2009</td>
                        <td>Version 1 Release</td>
                        <td>First version will be released for public.</td>
                    </tr>
                    <tr class="rowA">
                        <td>XXX, 2009</td>
                        <td>VORS Shutdown</td>
                        <td>VORS will be phased down and shutdown.</td>
                    </tr>
</table>
            </div>

        </div>
        <div id="sideContent">
            <h3>Home</h3>
            <p>Side content for home</p>
        </div>
<?=$this->render("full_footer.phtml", true)?>
