<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<link href="images/favicon.ico" rel="icon" type="image/x-icon" />
<title><?=config()->app_name?></title>

<!-- CSS used to display loading dialog -->
<style>
#loading {
    position: absolute;
    left: 45%;
    top: 40%;
    margin-left: -50px;
    padding: 2px;
    z-index: 20001;
    height: auto;
    border: 1px solid #ccc;
}

#loading a {
    color: #225588;
}

#loading .loading-indicator {
    background: white;
    color: #444;
    font: bold 13px tahoma, arial, helvetica;
    padding: 10px;
    margin: 0;
    height: auto;
}

#loading .loading-indicator img {
    margin-right:8px;
    float:left;
    vertical-align:top;
}

#loading-msg {
    font: normal 10px arial, tahoma, sans-serif;
}

</style>

</head>

<body id="body" style="overflow: hidden">
<div id="loading">
    <div class="loading-indicator">
    <img src="images/large-loading.gif" width="32" height="32"/><?=config()->app_name?><br />
    <span id="loading-msg">Loading ...</span>
    </div>
</div>

<link rel="stylesheet" type="text/css" href="lib/ext-2.2/resources/css/ext-all.css" />
<link rel="stylesheet" type="text/css" href="lib/ext-2.2/resources/css/xtheme-gray.css" />
<link rel="stylesheet" type="text/css" href="css/main.css" />

<script language='javascript' src='lib/jquery-1.2.6/jquery.js'></script>
<script language='javascript' src='lib/ext-2.2/adapter/jquery/ext-jquery-adapter.js'></script>
<script language='javascript' src='lib/ext-2.2/ext-all.js'></script>
<script language='javascript' src="http://maps.google.com/maps?file=api&amp;v=2&amp;key=<?=config()->gmap_key?>" type="text/javascript"></script>

<script langauge='javascript' src="js/gmap.js"></script>
<script langauge='javascript'>
function getBase()
{
    return "<?=base()?>";
}
function getURLBase()
{
    return "<?=$_SERVER["SERVER_NAME"]?>"+getBase();
}
function getFullURLBase()
{
    return "http://"+getURLBase();
}
function getInitialPage()
{
    return "<?=$this->initial_page?>";
}
function getInitialParam()
{
    <?if(isset($_REQUEST["param"])) {
        echo "return unescape(\"".$_REQUEST["param"]."\");\n";
    } else {
        echo "return \"\";\n";
    }?>
}
var vonames = [    
<?
    $vo_model = new VO();
    $vos = $vo_model->fetchAll();
    $first = true;
    foreach($vos as $vo) {
        if(!$first) echo ",";
        $first = false;
    ?>
        { id: '<?=$vo->vo_id?>', short_name: '<?=$vo->short_name?>', long_name: '<?=$vo->long_name?>' }
<?
}
?>
];

</script>
<script langauge='javascript' src="index/js"></script>

<?php include("app/views/header.php");?>
<div id="viewportarea" class="hidden">
    <?php include("app/views/scripts/index/static_content.php");?>
</div>

<!-- following 2 javascript blocks are for Google Analytics Stuff... Why 2 blocks? I don't know.. 
-->
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
var pageTracker = _gat._getTracker("UA-69012-6");
pageTracker._initData();
pageTracker._trackPageview();
</script>

</body>
</html>
