<p>In order to see various information that are specific to Resource Groups, do following ...</p>
<ol class="step_list">
    <li>
        <div class="step_num">1</div> <p>Selecting an item under "Information to display" on the right.</p>
        <br clear="all"/>
    </li>

    <li>
        <div class="step_num">2</div> <p>Select resource groups that you'd like to see the information you have selected.</p>
        <br clear="all"/>
    </li>

    <li>
        <div class="step_num">3</div> <p>Click "Update Page" button.</p>
        <br clear="all"/>
    </li>

    <li>
        <div class="step_num">4</div> <p>Optionally, filter the list of resource group by applying various filters.</p>
        <br clear="all"/>
    </li>
</ol>
