<p>Various information that are specific to OSG Resource Groups</p>
<br/>
<h4>In order to display information...</h4>
<p><b>1.</b> Selecting an item under "Information to display" on the right.</p>
<p><b>2.</b> Select resource groups that you'd like to see the information you have selected.</p>
<p><b>3.</b> Click "Update Page" button.</p>
<p><b>4.</b> Optionally, filter the list of resource group by applying various filters.</p>
<br/>

