<?$checked = "";
if(isset($_REQUEST["summary_attrs_showpflatematrix"])) { $checked = "checked=checked"; }?>
<input type="checkbox" name="summary_attrs_showpflatematrix" <?=$checked?>/> Latency<br/>

<?$checked = "";
if(isset($_REQUEST["summary_attrs_showpfbandmatrix"])) { $checked = "checked=checked"; }?>
<input type="checkbox" name="summary_attrs_showpfbandmatrix" <?=$checked?>/> Bandwidth<br/>


