Show Accounting Data for: 
<select name="account_type">
<option value="cumulative_hours">Cumulative Wall Hours (by VO)</option>
<option value="daily_hours_byvo">Daily Wall Hours (by VO)</option>
<option value="daily_hours_byusername">Daily Wall Hours (by Username)</option>
<option value="job_count_byvo">Job Count (by VO)</option>
<option value="wall_success">VO "Wall Success" Rate</option>
<option value="cpu_efficiency">CPU Efficiency</option>
</select>
<?if(isset($_REQUEST["account_type"])) {
    $account_type = $_REQUEST["account_type"];
    ?>
    <script type="text/javascript">
    $(document).ready(function() {
            $("select[name=account_type] option[value=<?=$account_type?>]").attr('selected', 'selected');
    });
    </script>
<?}?>

