<?$checked = "";
if(isset($_REQUEST["gip_status_attrs_showtestresults"])) { $checked = "checked=checked"; }?>
<input type="checkbox" name="gip_status_attrs_showtestresults" <?=$checked?>/> GIP Validation Results<br/>

<?$checked = "";
if(isset($_REQUEST["gip_status_attrs_showwlcgstatus"])) { $checked = "checked=checked"; }?>
<input type="checkbox" name="gip_status_attrs_showwlcgstatus" <?=$checked?>/> WLCG Status<br/>


<?$checked = "";
if(isset($_REQUEST["gip_status_attrs_showresource"])) { $checked = "checked=checked"; }?>
<input type="checkbox" name="gip_status_attrs_showresource" <?=$checked?> onclick="$('#resource_details').toggle('fast');"/> Resources<br/>

<div id="resource_details" class="hidden list">
<?$checked = "";
if(isset($_REQUEST["gip_status_attrs_showcemondata"])) { $checked = "checked=checked"; }?>
<input type="checkbox" name="gip_status_attrs_showcemondata" <?=$checked?>/> LDIF URLs<br/>
</div>
<script type="text/javascript">
if($("input[name='gip_status_attrs_showresource']").attr('checked')) {
    $("#resource_details").show();
} else {
    $("#resource_details").hide();
}
</script>


