<h4>For Resource Group</h4>

<?$checked = "";
if(isset($_REQUEST["summary_attrs_showdesc"])) { $checked = "checked=checked"; }?>
<input type="checkbox" name="summary_attrs_showdesc" <?=$checked?>/> Description<br/>

<?$checked = "";
if(isset($_REQUEST["summary_attrs_showgipstatus"])) { $checked = "checked=checked"; }?>
<input type="checkbox" name="summary_attrs_showgipstatus" <?=$checked?>/> Current GIP Validation Status<br/>

<?$checked = "";
if(isset($_REQUEST["summary_attrs_showhierarchy"])) { $checked = "checked=checked"; }?>
<input type="checkbox" name="summary_attrs_showhierarchy" <?=$checked?>/> OIM Hierarchy<br/>

<h4>For Resource</h4>

<?$checked = "";
if(isset($_REQUEST["summary_attrs_showwlcg"])) { $checked = "checked=checked"; }?>
<input type="checkbox" name="summary_attrs_showwlcg" <?=$checked?>/> WLCG Information<br/>

<?$checked = "";
if(isset($_REQUEST["summary_attrs_showservice"])) { $checked = "checked=checked"; }?>
<input type="checkbox" name="summary_attrs_showservice" <?=$checked?>/> Services<br/>

<?$checked = "";
if(isset($_REQUEST["summary_attrs_showrsvstatus"])) { $checked = "checked=checked"; }?>
<input type="checkbox" name="summary_attrs_showrsvstatus" <?=$checked?>/> Current RSV Status<br/>

<?$checked = "";
if(isset($_REQUEST["summary_attrs_showfqdn"])) { $checked = "checked=checked"; }?>
<input type="checkbox" name="summary_attrs_showfqdn" <?=$checked?>/> FQDN Aliases<br/>

<?$checked = "";
if(isset($_REQUEST["summary_attrs_showvomembership"])) { $checked = "checked=checked"; }?>
<input type="checkbox" name="summary_attrs_showvomembership" <?=$checked?>/> Supported VOs<br/>

<?$checked = "";
if(isset($_REQUEST["summary_attrs_showvoownership"])) { $checked = "checked=checked"; }?>
<input type="checkbox" name="summary_attrs_showvoownership" <?=$checked?>/> VO Ownership<br/>

<?$checked = "";
if(isset($_REQUEST["summary_attrs_showenv"])) { $checked = "checked=checked"; }?>
<input type="checkbox" name="summary_attrs_showenv" <?=$checked?>/> Environment Parameters<br/>

<?$checked = "";
if(isset($_REQUEST["summary_attrs_showcontact"])) { $checked = "checked=checked"; }?>
<input type="checkbox" name="summary_attrs_showcontact" <?=$checked?>/> Contact Information<br/>

<?$checked = "";
if(isset($_REQUEST["summary_attrs_showticket"])) { $checked = "checked=checked"; }?>
<input type="checkbox" name="summary_attrs_showticket" <?=$checked?>/> Open GOC Tickets<br/>


