Start Date:<br/>
<select name="start_type">
<option value="yesterday">Yesterday (0AM)</option>
<option value="7daysago">7 Days Ago</option>
<option value="30daysago">30 Days Ago</option>
<option value="specific">Specific Date</option>
</select>
<?if(isset($_REQUEST["start_date"])) {
    $start_date = $_REQUEST["start_date"];
} else {
    $start_date = date("m/d/Y", time());
}?>
<input size="10" type="text" name="start_date" class="hidden" value="<?=$start_date?>"></input>
<br/>
End Date:<br/>
<select name="end_type">
<option value="today">Today (0AM)</option>
<option value="now">Now</option>
<option value="specific">Specific Date</option>
</select>
<?if(isset($_REQUEST["end_date"])) {
    $end_date = $_REQUEST["end_date"];
} else {
    $end_date = date("m/d/Y", time());
}?>
<input size="10" type="text" name="end_date" class="hidden" value="<?=$end_date?>"></input>
<br/><br/>
<p class="info">0AM of the specifed date will be used for both start &amp; end time of the graph.</p>

<script type="text/javascript">
<?if(isset($_REQUEST["start_type"])) {
    echo "$('select[name=start_type] option[value=\"".$_REQUEST["start_type"]."\"]').attr('selected', 'selected');showhide_start_picker();";
}?>
<?if(isset($_REQUEST["end_type"])) {
    echo "$('select[name=end_type] option[value=".$_REQUEST["end_type"]."]').attr('selected', 'selected');showhide_end_picker();";
}?>
$(document).ready(function() {
    $("input[name=start_date]").datepicker();
    $("input[name=end_date]").datepicker();
    $("select[name=start_type]").change(showhide_start_picker);
    $("select[name=end_type]").change(showhide_end_picker);
});

function showhide_start_picker()
{
    var v = $("select[name=start_type]").val();
    if(v == "specific") {
        $("input[name=start_date]").show();
    } else {
        $("input[name=start_date]").hide();
    }
}
function showhide_end_picker()
{
    var v = $("select[name=end_type]").val();
    if(v == "specific") {
        $("input[name=end_date]").show();
    } else {
        $("input[name=end_date]").hide();
    }
}
</script>
