<p class="info">Information collected from BDII consolidator. This page only shows BDII resource groups / resources that matches OIM registration information.</p>

<?$checked = "";
if(isset($_REQUEST["bdii_attrs_showversion"])) { $checked = "checked=checked"; }?>
<input type="checkbox" name="bdii_attrs_showversion" <?=$checked?>/> Show Version Numbers<br/>

<?$checked = "";
if(isset($_REQUEST["bdii_attrs_showstat"])) { $checked = "checked=checked"; }?>
<input type="checkbox" name="bdii_attrs_showstat" <?=$checked?> onclick="$('#resource_details').toggle('fast');"/> Show BDII Statistics<br/>

