<?
echo "<div style='min-height: 400px'>";

if(!uwa()) {
    echo "<div class='well'>";
    $title = "Resources that are used to generate this graph";
    echo outputToggle("Show $title", "Hide $title", $this->resource_names);
    echo "</div>";
    echo "<img src=\"".$this->url."&width=750&height=400&text_size=9&title_size=0&text_padding=3&figure_padding=50&group=resource_group\"/>\n";
} else {
    //UWA Graph
    echo "<img src=\"".$this->url."&width=450&height=400&text_size=11&title_size=0&text_padding=3&figure_padding=50&group=resource_group\"/>\n";
}

echo "</div>";
