<?=$this->render("full_header.phtml", true)?>
<script language='javascript' src='<?=base()?>/lib/jquery-1.2.6/dimensions_1.2/jquery.dimensions.min.js'></script>

        <div id="primaryContentContainer">
            <div id="primaryContent">
                <div id="breadcrumb"><p>You are here &gt; <a href="<?=fullbase()?>/iframe">Other Contents</a> &gt; <?=$this->page_title?></p> </div>
                <iframe frameborder="0" id="frame" width="100%" src="<?=$this->url?>" onload="resizeIframe();"></iframe>
            </div>
        </div>
        <div id="sideContent">
            <h3>Subscribe</h3>
        </div>
<script language="JavaScript">
function resizeIframe() {
    var height = document.documentElement.clientHeight;
    height -= 220;
    $("#frame").css("height", height+"px");
    
};
$(window).resize(resizeIframe);
</script>

<?=$this->render("full_footer.phtml", true)?>
