<?=$this->render("full_header.phtml", true)?>

        <div id="primaryContentContainer">
            <div id="primaryContent">
                <div id="breadcrumb"><p>You are here &gt; <?=$this->page_title?></p> </div>
                <h2><?=$this->page_title?></h2>
                <a href="<?=fullbase()?>/<?=pagename()?>/oim">OIM</a>
            </div>
        </div>
        <div id="sideContent">
            <h3>Subscribe</h3>
        </div>
<?=$this->render("full_footer.phtml", true)?>
