
<style type="text/css">
.list
{
    padding: 2px;
    background-color: #eee;
    margin-bottom: 10px;
    margin-left: 16px;
    width: 90%;
}
.scrolled_list
{
    height: 160px;
    overflow: auto;
}
#datasource {
margin-bottom: 5px;
}
</style>

<form method="get" id="wizard">
    <div class="form-actions">
    <input type="button" class="btn btn-primary" onclick="wizard_submit('index');" value="&nbsp;&nbsp;&nbsp;Update Page&nbsp;&nbsp;&nbsp;"/>
    </div>
    <h3>Information to Display</h3>
    <div id="datasource_area">
        <select id="datasource">
        <option value="">(Please Select)</option>
        <option value="rgsummary">Resource Group Summary</option>
        <option value="rgcurrentstatus">Current RSV Status</option>
        <option value="rgstatushistory">RSV Status History</option>
        <option value="rgarhistory">Availability History</option>
        <option value="rgarmetric">Availability Metrics</option>
        <option value="rgdowntime">Downtime Information</option>
      <!--  <option value="rgaccount">GRACC Accounting</option>
      <option value="rgce">GRACC Accounting (CE Specific)</option>
        <option value="rgse">GRACC Accounting (SE Specific)</option>
       <option value="rgbdii">BDII Information</option>-->
        </select>
        
        <div id="rgsummary_attrs" class="attrs hidden">
            <?=$this->render("rg/wizard_summary.phtml")?>
        </div>

        <div id="rgcurrentstatus_attrs" class="attrs hidden">
            <?=$this->render("rg/wizard_currentstatus.phtml")?>
        </div>

        <div id="rggipstatus_attrs" class="attrs hidden">
            <?=$this->render("rg/wizard_gipstatus.phtml")?>
        </div>

        <div id="rgstatushistory_attrs" class="attrs hidden">
            <?=$this->render("rg/wizard_statushistory.phtml")?>
        </div>

        <div id="rgarhistory_attrs" class="attrs hidden">
            <?=$this->render("rg/wizard_arhistory.phtml")?>
        </div>

        <div id="rgarmetric_attrs" class="attrs hidden">
            <?=$this->render("rg/wizard_armetric.phtml")?>
        </div>

        <div id="rgdowntime_attrs" class="attrs hidden">
            <?=$this->render("rg/wizard_downtime.phtml")?>
        </div>

        <div id="rgaccount_attrs" class="attrs hidden">
            <?=$this->render("rg/wizard_account.phtml")?>
        </div>

        <div id="rgce_attrs" class="attrs hidden">
            <?=$this->render("rg/wizard_ce.phtml")?>
        </div>

        <div id="rgse_attrs" class="attrs hidden">
            <?=$this->render("rg/wizard_se.phtml")?>
        </div>

        <div id="rgbdiitree_attrs" class="attrs hidden">
            <?=$this->render("rg/wizard_bdiitree.phtml")?>
        </div>

        <div id="rgbdii_attrs" class="attrs hidden">
            <?=$this->render("rg/wizard_bdii.phtml")?>
        </div>

        <div id="rgevent_attrs" class="attrs hidden">
            <?=$this->render("rg/wizard_event.phtml")?>
        </div>

        <div id="_daterange_attrs" class="attrs hidden">
            <?=$this->render("rg/wizard__daterange.phtml")?>
        </div>

        <div id="gratia_notes" class="attrs hidden">
            <p class="info">This page uses <a target="_blank" href="http://gracc.opensciencegrid.org">GRACC service</a> to render graphs. 
        </div>

    </div>

    <h3>Resource Groups to Display</h3>
    <div class="">
        <div id="resource_area_standby">
            <p>Please select the information to display first.</p>
        </div>
        <div id="resource_area" class="hidden">
            <?
            $checked = "";
            if(isset($_REQUEST["all_resources"])) { $checked = "checked=checked"; }
            echo "<input type=\"checkbox\" name=\"all_resources\" $checked onclick=\"if(this.checked) { uncheck_sibs(this);}\"/> All Resource Groups<br/>";

            $model = new Facilities();
            $list = $model->get();
            $kv = array();
            foreach($list as $item) { 
                $name = $item->name;
                if($item->disable == 1) {
                    $name .= " (Removed)";
                }
                $kv[$item->id] = array($name, ""); //$item->description
            }
            echo fblist("facility", "Resource Groups in Facility ".helpbutton("Facility"), $kv);

            $model = new Site();
            $list = $model->get();
            $kv = array();
            foreach($list as $item) { 
                $name = $item->name;
                if($item->disable == 1) {
                    $name .= " (Removed)";
                }
                $kv[$item->id] = array($name, ""); //$item->long_name
            }
            echo fblist("site", "Resource Groups in Sites ".helpbutton("Site"), $kv);

            $model = new ResourceGroup();
            $list = $model->get();
            $kv = array();
            foreach($list as $item) { 
                $name = $item->name;
                if($item->disable == 1) {
                    $name .= " (Removed)";
                }
                $kv[$item->id] = array($name, ""); 
            }
            echo fblist("rg", "Specific Resource Groups ".helpbutton("Resource_Group"), $kv);

            $model = new SupportCenters();
            $list = $model->get();
            $kv = array();
            foreach($list as $item) { 
                $name = $item->name;
                if($item->disable == 1) {
                    $name .= " (Removed)";
                }
                $kv[$item->id] = array($name, $item->long_name);
            }
            echo fblist("sc", "Resources Supported by following SC".helpbutton("Support_Center"), $kv);
            ?>
        </div>
    </div>

    <h3>Filter By</h3>
    <div class="">
        <div id="filter_area_standby">
            <p>Please select the information to display first.</p>
        </div>
        <div id="filter_area" class="hidden">

            <h4>For Resource Group</h4>
            <?
            $model = new GridTypes();
            $list = $model->get();
            $kv = array();
            foreach($list as $item) { $kv[$item->id] = $item->name; }
            echo checklist("gridtype", "Grid Type", $kv);

            $kv = array("OK"=>"OK", "FAIL"=>"FAIL", "UNKNOWN"=>"UNKNOWN");

            ?>
            <h4 style="margin-top: 5px;">For Resource</h4>
            <?
            $model = new Status();
            $list = $model->get();
            $kv = array();
            foreach($list as $item) { $kv[$item->id] = $item->description; }
            echo checklist("status", "Current RSV Status", $kv);

            $sgmodel = new ServiceGroup();
            $sgs = $sgmodel->getindex();
            $model = new Service();
            //$list = $model->get(array("service_group_id"=>1));
            $list = $model->get();
            $kv = array();
            foreach($list as $item) { 
                $service_group_name = $sgs[$item->service_group_id][0]->name;
                $kv[$item->id] = array($service_group_name. " / ".$item->name, "");
            }
            echo fblist("service", "Provides following Services", $kv);

            $model = new VirtualOrganization();
            $list = $model->get();
            $kv = array();
            foreach($list as $item) { 
                if($item->active == 1 and $item->disable == 0) {
                    $kv[$item->id] = array($item->name, $item->long_name);
                }
            }
            echo fblist("vosup", "Allows following VO to access", $kv);

            $model = new VirtualOrganization();
            $list = $model->get();
            $kv = array();
            foreach($list as $item) { 
                if($item->active == 1 and $item->disable == 0) {
                    $kv[$item->id] = array($item->name, $item->long_name); 
                }
            }
            echo fblist("voown", "Owned by VOs", $kv);

            $checked = "";
            if(isset($_REQUEST["has_status"])) { $checked = "checked=checked"; }
            echo "<input type=\"checkbox\" name=\"has_status\" $checked/> RSV Monitoring Status is available<br/>";

            $kv = array();
            $kv[0] = "Inactive";
            $kv[1] = "Active";
            echo radiolist("active", "Active Status", $kv, 1); //1 by default

            $kv = array();
            $kv[0] = "Not Disabled (Normal)";
            $kv[1] = "Disabled (Removed)";
            echo radiolist("disable", "Disable (Removed) Status", $kv, 1); //1 by default

            $checked = "";
            if(isset($_REQUEST["has_wlcg"])) { $checked = "checked=checked"; }
            echo "<input type=\"checkbox\" name=\"has_wlcg\" $checked/> At least one WLCG interop. flag is True<br/>";

            ?>
        </div>
    </div>
    <div class="form-actions">
        <input type="button" class="btn btn-primary" onclick="wizard_submit('index');" value="&nbsp;&nbsp;&nbsp;Update Page&nbsp;&nbsp;&nbsp;"/>
    </div>

    <?=$this->render("subscribe.phtml")?>

</form>

<script type="text/javascript">

function showhide_attrs(v, show_speed)
{
    //var v = $("select[name=datasource]").val();
    $(".attrs").hide();
    if(v != "") {
        $("#"+v+"_attrs").show(show_speed);
        $("#resource_area").show(show_speed);
        $("#filter_area").show(show_speed);
        $("#resource_area_standby").hide();
        $("#filter_area_standby").hide();

        //pages that uses date range contoller
        if( v == "rgstatushistory" ||
            v == "rgarhistory" ||
            v == "rgarmetric" ||
            v == "rgaccount" ||
            v == "rgse" ||
            v == "rgce") {
            $("#_daterange_attrs").show(show_speed);
        }
        //pages that uses gratia notes
        if( v == "rgaccount" ||
            v == "rgse" ||
            v == "rgce" ) {
            $("#gratia_notes").show(show_speed);
        }
    } else {
        $("#resource_area").hide();
        $("#filter_area").hide();
        $("#resource_area_standby").show();
        $("#filter_area_standby").show();
    }
}

$(document).ready(function() {

    //setup form
    $("#datasource").change(function() {
        showhide_attrs(this.value, 'normal');
    });

    function list_click()
    {
        if(this.checked) { $("input[name=all_resources]").removeAttr("checked"); }
    }
    var items = $("input[name=all_resources]").siblings("input"); 
    $(items).click(list_click);

    <?php
    //select currently selected datasouce
    $front = Zend_Controller_Front::getInstance();
    $controllerName = $front->getRequest()->getControllerName();
    echo "$('#datasource option[value=$controllerName]').attr('selected', 'selected');\n";
    echo "showhide_attrs('$controllerName');\n";

    ?>
});

function wizard_submit(format)
{
    var action = '<?=fullbase()?>/'+$('#datasource').val(); 
    action += "/"+format;
    $('#wizard').attr('action', action);
    $('#wizard').submit(); 
    return false;
}

function uncheck_sibs(e)
{
    $('#resource_area .fblist_container').hide(); 
    var items = $(e).siblings("input"); 
    $(items).removeAttr("checked");
}

</script>
