<?
echo "<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?>\n";
$total_count = count($this->recs);

echo "<history resource_count=\"$total_count\">";

$first = true;
foreach($this->recs as $rec) {
    echo "<resource>";
        echo "<resource_id>".$rec["resource_id"]."</resource_id>";
        echo "<name>".$rec["name"]."</name>";
        echo "<fqdn>".$rec["fqdn"]."</fqdn>";
        echo "<graph>".htmlspecialchars($rec["graph"])."</graph>";
        echo "<url>".$rec["url"]."</url>";
        echo "<service_types>".$rec["service_types"]."</service_types>";
    echo "</resource>";
}

echo "</history>";
