<script type="text/javascript" src="<?=fullbase()?>/lib/jquery-1.2.6/jquery-ui.js"></script>
<script type="text/javascript" src="<?=fullbase()?>/lib/jquery-1.2.6/daterange/daterangepicker.jQuery.js"></script>
<link type="text/css" href="<?=fullbase()?>/lib/jquery-1.2.6/ui.core.css" rel="Stylesheet" />
<link rel="stylesheet" href="<?=fullbase()?>/lib/jquery-1.2.6/ui.theme.css" type="text/css" title="ui-theme" />
<link rel="stylesheet" href="<?=fullbase()?>/lib/jquery-1.2.6/ui.datepicker.css" type="text/css" />
<link rel="stylesheet" href="<?=fullbase()?>/lib/jquery-1.2.6/daterange/ui.daterangepicker.css" type="text/css" />

<style type="text/css">
.list
{
    padding: 2px;
    background-color: #eee;
    margin-bottom: 10px;
    margin-left: 16px;
    width: 400px;
}
.scrolled_list
{
    height: 150px;
    overflow: auto;
}
</style>

<h3>Choose information to display</h3>
<div class="indent">
    <select name="datasource">
    <option value="summary">Current Status Summary</option>
    <option value="current_status">Current Status</option>
    <option value="status_history">Status History</option>
    <option value="availability_history">Availability History</option>
    <option value="downtime">Downtime Schedule</option>
    <option value="vo_membership">VO Membership</option>
    <option value="vo_ownership">VO Ownership</option>
    </select>
    <p>
        <div id="summary_attrs" class="attrs indent hidden">
            <p>* Show basic information about a resource.</p>
            <input type="checkbox" name="summary_attrs_showdesc"/>
            Display description: <br/>
        </div>

        <div id="current_status_attrs" class="attrs indent hidden">
            <input type="checkbox" name="current_status_attrs_shownc"/>
            Display information for non-critical metrics: <br/>
        </div>

        <div id="status_history_attrs" class="attrs indent hidden">
            Date Range: 
            <input type="text" name="status_history_attrs_daterange"/>
            <div id="status_history_attrs_daterange_area"></div>
        </div>

        <div id="availability_history_attrs" class="attrs indent hidden">
            Date Range: 
            <input type="text" name="availability_history_attrs_daterange"/>
            <div id="availability_history_attrs_daterange_area"></div>
        </div>

        <div id="downtime_attrs" class="attrs indent hidden">
            <input type="checkbox" name="downtime_attrs_showpast"/>
            Show Past Downtime information: <br/>
            Number of Items to Show: <input type="text" name="downtime_attrs_items" value="5"/>
        </div>

        <div id="vo_membership_attrs" class="attrs indent hidden">
            <p>* Show list of VOs that a resource supports.</p>
        </div>

        <div id="vo_ownership_attrs" class="attrs indent hidden">
            <p>* Show which VOs owns the resource and how much.</p>
        </div>
    </p>
</div>

<br/>

<h3>Choose resources to display the information</h3>
<div class="indent">
    
    <?
    function checklist($id, $title, $kv)
    {
        //output title check box
        $title = "<input type=\"checkbox\" value=\"$id\" onclick=\"if(this.checked) {\$('#${id}__list').show('normal');} else {\$('#${id}__list').hide();}\"/> <span>$title</span><br/>";

        //determine list class
        $c = "hidden ";
        if(count($kv) > 8) { 
            $c .= "scrolled_list ";
        }

        //output list
        $list = "";
        $list .= "<div class=\"$c list\" id=\"${id}__list\">";
        foreach($kv as $key=>$value) {
            $list .= "<input type=\"checkbox\" value=\"${id}_$key\"/> <span>$value</span><br/>";
        }
        $list .= "</div>";

        return "<div id=\"$id\">".$title.$list."</div>";
    }
    
    echo "<input type=\"checkbox\" value=\"rall\" onclick=\"var items = $(this).siblings(); if(this.checked) { disable(items);} else {enable(items);}\"/> All Resources<br/>";

    $model = new SupportCenters();
    $scs = $model->get();
    $kv = array();
    foreach($scs as $sc) { $kv[$sc->sc_id] = $sc->short_name; }
    echo checklist("sc", "Resources in Support Centers", $kv);

    $model = new Site();
    $list = $model->get();
    $kv = array();
    foreach($list as $site) { $kv[$site->site_id] = $site->name; }
    echo checklist("site", "Resources in Sites", $kv);

    $model = new ResourceGroup();
    $list = $model->get();
    $kv = array();
    foreach($list as $item) { $kv[$item->resource_group_id] = $item->name; }
    echo checklist("rg", "Resources in Resource Groups", $kv);

    $model = new Resource();
    $list = $model->get();
    $kv = array();
    foreach($list as $item) { $kv[$item->id] = $item->name; }
    echo checklist("r", "Specific Resources", $kv);
    ?>
</div>

<br/>

<h3>Only display resources with</h3>
<div class="indent">

    <?
    $model = new GridTypes();
    $list = $model->get();
    $kv = array();
    foreach($list as $item) { $kv[$item->grid_type_id] = $item->short_name; }
    echo checklist("gt", "Grid Type", $kv);

    $model = new Status();
    $list = $model->get();
    $kv = array();
    foreach($list as $item) { $kv[$item->metric_status_description] = $item->metric_status_description; }
    echo checklist("status", "Resource Status", $kv);

    $model = new ServiceTypes();
    $list = $model->get(array("service_group_id"=>1));
    $kv = array();
    foreach($list as $item) { $kv[$item->service_id] = $item->name; }
    echo checklist("service", "Services", $kv);

    $model = new VirtualOrganization();
    $list = $model->get();
    $kv = array();
    foreach($list as $item) { $kv[$item->vo_id] = $item->short_name; }
    echo checklist("vosup", "Supporting VOs", $kv);

    $model = new VirtualOrganization();
    $list = $model->get();
    $kv = array();
    foreach($list as $item) { $kv[$item->vo_id] = $item->short_name; }
    echo checklist("voown", "Owner VOs", $kv);
    ?>

</div>
 
<script type="text/javascript">

$('input[name=status_history_attrs_daterange]').daterangepicker({
appendTo: $('#status_history_attrs_daterange_area'),
arrows: true
}); 

$('input[name=availability_history_attrs_daterange]').daterangepicker({
appendTo: $('#availability_history_attrs_daterange_area'),
arrows: true
}); 

$("select[name=datasource]").change(function() {
var v = $(this).val();
$(".attrs").hide();
$("#"+v+"_attrs").show('normal');
});
function disable(e)
{
    $(e).find('input').attr('disabled', 'disabled');
    $(e).find('span').css('color', 'gray');
}
function enable(e)
{
    $(e).find('input').removeAttr('disabled');
    $(e).find('span').css('color', 'black');
}
</script>
