<p class="info">Resource admin enters resource downtime information on OIM. This page shows all current and future downtime information. Downtime information allows accurate calculation of resource reliability.</p>

<?$checked = "";
if(isset($_REQUEST["downtime_attrs_showpast"])) { $checked = "checked=checked"; }?>
<input type="checkbox" name="downtime_attrs_showpast" <?=$checked?>/> Show Past Downtime<br/>
