
<script type="text/javascript" src="<?=fullbase()?>/lib/jquery-1.3.1/ui/ui.datepicker.js"></script>
<link type="text/css" href="<?=fullbase()?>/lib/jquery-1.3.1/themes/base/ui.core.css" rel="Stylesheet" />
<link type="text/css" href="<?=fullbase()?>/lib/jquery-1.3.1/themes/base/ui.theme.css" rel="Stylesheet" />
<link type="text/css" href="<?=fullbase()?>/lib/jquery-1.3.1/themes/base/ui.datepicker.css" rel="Stylesheet" />

<style type="text/css">
.list
{
    padding: 2px;
    background-color: #eee;
    margin-bottom: 10px;
    margin-left: 16px;
    width: 90%;
}
.scrolled_list
{
    height: 160px;
    overflow: auto;
}
span.disabled_span
{
    color: gray;
}
</style>

<form method="get" id="wizard">
    <input type="button" onclick="wizard_submit('index');" value="&nbsp;&nbsp;&nbsp;Update Page&nbsp;&nbsp;&nbsp;"/>
    <h3>Information to display</h3>
    <div class="indent" id="datasource_area">
        <select name="datasource">
        <option value="">(Please Select)</option>
        <option value="summary">Resource Summary</option>
        <option value="currentstatus">Current RSV Status</option>
        <option value="gipstatus">Current GIP Validation Status</option>
        <option value="statushistory">RSV Status History</option>
        <option value="arhistory">Availability History</option>
        <option value="armetric">Availability Metrics</option>
        <option value="downtime">Downtime Schedule</option>
        <option value="account">Gratia Accounting</option>
        <option value="ce">Gratia Accounting (CE Specific)</option>
        <option value="se">Gratia Accounting (SE Specific)</option>
        </select>

        <div id="summary_attrs" class="attrs indent hidden">
            <?=$this->render("wizard/wizard_summary.phtml")?>
        </div>

        <div id="currentstatus_attrs" class="attrs indent hidden">
            <?=$this->render("wizard/wizard_currentstatus.phtml")?>
        </div>

        <div id="gipstatus_attrs" class="attrs indent hidden">
            <?=$this->render("wizard/wizard_gipstatus.phtml")?>
        </div>

        <div id="statushistory_attrs" class="attrs indent hidden">
            <?=$this->render("wizard/wizard_statushistory.phtml")?>
        </div>

        <div id="arhistory_attrs" class="attrs indent hidden">
            <?=$this->render("wizard/wizard_arhistory.phtml")?>
        </div>

        <div id="armetric_attrs" class="attrs indent hidden">
            <?=$this->render("wizard/wizard_armetric.phtml")?>
        </div>

        <div id="downtime_attrs" class="attrs indent hidden">
            <?=$this->render("wizard/wizard_downtime.phtml")?>
        </div>

        <div id="account_attrs" class="attrs indent hidden">
            <?=$this->render("wizard/wizard_account.phtml")?>
        </div>

        <div id="ce_attrs" class="attrs indent hidden">
            <?=$this->render("wizard/wizard_ce.phtml")?>
        </div>

        <div id="se_attrs" class="attrs indent hidden">
            <?=$this->render("wizard/wizard_se.phtml")?>
        </div>

        <div id="_daterange_attrs" class="attrs indent hidden">
            <?=$this->render("wizard/wizard__daterange.phtml")?>
        </div>

    </div>

    <h3>Resources to display</h3>
    <div class="indent">
        <div id="resource_area_standby">
            <p>Please select the information to display first.</p>
        </div>
        <div id="resource_area" class="hidden">
            <p>Select resources that you want to show above information (conditions are or-ed).</p>
            <?
            function checklist($id, $title, $kv)
            {
                //output title check box
                $checked = "";
                if(isset($_REQUEST[$id])) { 
                    $checked = "checked=checked"; 
                    ?>
                    <script type="text/javascript">
                    $(document).ready(function() {
                        $("#<?=$id?>__list").show();
                    });
                    </script>
                    <?
                }
                $title = "<input type=\"checkbox\" name=\"$id\" $checked onclick=\"if(this.checked) {\$('#${id}__list').show('normal');} else {\$('#${id}__list').hide();}\"/> <span>$title</span><br/>";

                //determine list class
                $c = "hidden ";
                if(count($kv) > 8) { 
                    $c .= "scrolled_list ";
                }

                //output list
                $list = "";
                $list .= "<div class=\"$c list\" id=\"${id}__list\">";
                foreach($kv as $key=>$value) {
                    $name = "${id}_$key";
                    $checked = "";
                    if(isset($_REQUEST[$name])) {
                        $checked = "checked=checked";
                    }
                    $list .= "<input type=\"checkbox\" name=\"$name\" $checked/> <span>$value</span><br/>";
                }
                $list .= "</div>";

                return "<div id=\"$id\">".$title.$list."</div>";
            }

            function radiolist($id, $title, $kv, $default)
            {
                //output title check box
                $checked = "";
                if(isset($_REQUEST[$id])) { 
                    $checked = "checked=checked"; 
                    ?>
                    <script type="text/javascript">
                    $(document).ready(function() {
                        $("#<?=$id?>__list").show();
                    });
                    </script>
                    <?
                }
                $title = "<input type=\"checkbox\" name=\"$id\" $checked onclick=\"if(this.checked) {\$('#${id}__list').show('normal');} else {\$('#${id}__list').hide();}\"/> <span>$title</span><br/>";

                //determine list class
                $c = "hidden ";
                if(count($kv) > 8) { 
                    $c .= "scrolled_list ";
                }

                //output list
                $list = "";
                $list .= "<div class=\"$c list\" id=\"${id}__list\">";

                //set default 
                $current_value = $default; 
                $name = "${id}_value";
                if(isset($_REQUEST[$name])) {
                    $current_value = $_REQUEST[$name];
                }

                foreach($kv as $key=>$value) {
                    $checked = "";
                    if($current_value == $key) {
                        $checked = "checked=checked";
                    }
                    $list .= "<input type=\"radio\" name=\"$name\" value=\"$key\" $checked/> <span>$value</span><br/>";
                }
                $list .= "</div>";

                return "<div id=\"$id\">".$title.$list."</div>";
            }
             
            $checked = "";
            if(isset($_REQUEST["all_resources"])) { $checked = "checked=checked"; }
            echo "<input type=\"checkbox\" name=\"all_resources\" $checked onclick=\"if(this.checked) { disable(this);} else {enable(this);}\"/> All Resources<br/>";
            echo "<div class=\"list\" id=\"all_resources_attrs\">";
                $checked = "";
                if(isset($_REQUEST["show_disabled"])) { $checked = "checked=checked"; }
                echo "<input type=\"checkbox\" name=\"show_disabled\" $checked/> Show Removed Resources<br/>";
            echo "</div>";

            function helpbutton($type)
            {
                return "<a target=\"_help\" href=\"https://twiki.grid.iu.edu/bin/view/Operations/OIMTermDefinition#$type\"><img src=\"".fullbase()."/images/help.png"."\"/></a>";
            }

            $model = new Facilities();
            $fs = $model->get();
            $kv = array();
            foreach($fs as $f) { $kv[$f->id] = $f->name; }
            echo checklist("facility", "Resources in Facility ".helpbutton("Facility"), $kv);

            $model = new Site();
            $list = $model->get();
            $kv = array();
            foreach($list as $site) { $kv[$site->id] = $site->name; }
            echo checklist("site", "Resources in Sites ".helpbutton("Site"), $kv);

            $model = new ResourceGroup();
            $list = $model->get();
            $kv = array();
            foreach($list as $item) { $kv[$item->id] = $item->name; }
            echo checklist("rg", "Resources in Resource Groups".helpbutton("Resource_Group"), $kv);

            $model = new SupportCenters();
            $scs = $model->get();
            $kv = array();
            foreach($scs as $sc) { 
                //grab active, non-disabled records
                if($sc->active == 1 and $sc->disable == 0) {
                    $kv[$sc->id] = $sc->name; 
                }
            }
            echo checklist("sc", "Resource supported by Support Centers ".helpbutton("Support_Center"), $kv);

            $model = new Resource();
            $list = $model->get();
            $kv = array();
            foreach($list as $item) { $kv[$item->id] = $item->name; }
            echo checklist("r", "Specific Resources ".helpbutton("Resource"), $kv);
            
            ?>
        </div>
    </div>

    <h3>Filter</h3>
    <div class="indent">
        <div id="filter_area_standby">
            <p>Please select the information to display first.</p>
        </div>
        <div id="filter_area" class="hidden">
            <p>Only show resources that matches following criteria (conditions are and-ed).</p>

            <?
            $model = new GridTypes();
            $list = $model->get();
            $kv = array();
            foreach($list as $item) { $kv[$item->id] = $item->name; }
            echo checklist("gridtype", "Grid Type", $kv);

            $model = new Status();
            $list = $model->get();
            $kv = array();
            foreach($list as $item) { $kv[$item->id] = $item->description; }
            echo checklist("status", "Current RSV Status", $kv);

            $kv = array("OK"=>"OK", "FAIL"=>"FAIL", "UNKNOWN"=>"UNKNOWN");
            echo checklist("gipstatus", "Current GIP Status", $kv);

            $model = new ServiceTypes();
            $list = $model->get(array("service_group_id"=>1));
            $kv = array();
            foreach($list as $item) { $kv[$item->id] = $item->name; }
            echo checklist("service", "Provides following Services", $kv);

            $model = new VirtualOrganization();
            $list = $model->get();
            $kv = array();
            foreach($list as $item) { 
                if($item->active == 1 and $item->disable == 0) {
                    $kv[$item->id] = $item->name; 
                }
            }
            echo checklist("vosup", "Allows following VO to access", $kv);

            $model = new VirtualOrganization();
            $list = $model->get();
            $kv = array();
            foreach($list as $item) { 
                if($item->active == 1 and $item->disable == 0) {
                    $kv[$item->id] = $item->name; 
                }
            }
            echo checklist("voown", "Owned by VOs", $kv);

            $checked = "";
            if(isset($_REQUEST["has_status"])) { $checked = "checked=checked"; }
            echo "<input type=\"checkbox\" name=\"has_status\" $checked/> RSV Monitoring Status is available<br/>";

            $kv = array();
            $kv[0] = "Inactive";
            $kv[1] = "Active";
            echo radiolist("active", "Active Status", $kv, 1); //1 by default

            $checked = "";
            if(isset($_REQUEST["has_wlcg"])) { $checked = "checked=checked"; }
            echo "<input type=\"checkbox\" name=\"has_wlcg\" $checked/> Has WLCG Information<br/>";

            ?>
        </div>
    </div>

    <br/>
    <input type="button" onclick="wizard_submit('index');" value="&nbsp;&nbsp;&nbsp;Update Page&nbsp;&nbsp;&nbsp;"/>

    <?=$this->render("subscribe.phtml")?>

</form>

<script type="text/javascript">

function showhide_attrs(show_speed)
{
    var v = $("select[name=datasource]").val();
    $(".attrs").hide();
    if(v != "") {
        $("#"+v+"_attrs").show(show_speed);
        $("#resource_area").show(show_speed);
        $("#filter_area").show(show_speed);
        $("#resource_area_standby").hide();
        $("#filter_area_standby").hide();

        if(
            v == "statushistory" ||
            v == "arhistory" ||
            v == "armetric" ||
            v == "account" ||
            v == "se" ||
            v == "ce") {
            $("#_daterange_attrs").show(show_speed);
        }
    } else {
        $("#resource_area").hide();
        $("#filter_area").hide();
        $("#resource_area_standby").show();
        $("#filter_area_standby").show();
    }
}

$(document).ready(function() {

    //setup form
    $("select[name=datasource]").change(function() {
        showhide_attrs('normal');
    });

    <?
    //select currently selected datasouce
    if(isset($_REQUEST["datasource"])) {
        $datasource = $_REQUEST["datasource"];
        switch($datasource) {
        case "summary":
        case "currentstatus":
        case "gipstatus":
        case "statushistory":
        case "arhistory":
        case "armetric":
        case "downtime":
        case "account":
        case "se":
        case "ce":
            echo "$('select[name=datasource] option[value=$datasource]').attr('selected', 'selected');\n";
            echo "showhide_attrs();\n";
        }
    }

    if(isset($_REQUEST["all_resources"])) {
        echo "disable($('input[name=all_resources]'));";
    }
    ?>
});

function wizard_submit(format)
{
    var action = '<?=fullbase()?>/wizard'+$('select[name=datasource]').val(); 
    action += "/"+format;
    $('#wizard').attr('action', action);
    $('#wizard').submit(); 
    return false;
}

function disable(e)
{
    var items = $(e).siblings(); 
    $(items).find('input').attr('disabled', 'disabled');
    $(items).find('span').addClass('disabled_span');
    $("#all_resources_attrs").show();
    $("#all_resources_attrs").find('input').removeAttr('disabled');
}
function enable(e)
{
    var items = $(e).siblings(); 
    $(items).find('input').removeAttr('disabled');
    $(items).find('span').removeClass('disabled_span');
    $("#all_resources_attrs").hide();
    $("#all_resources_attrs").find('input').addAttr('disabled');
}
</script>
