Show SE Specific Accounting Data for: 
<select name="se_account_type">
<option value="vo_transfer_volume">Transfer volume (Grouped by VO)</option>
<option value="user_transfer_volume">Transfer volume (Grouped by Username)</option>
<option value="se_space">Total disk space</option>
<option value="se_space_free">Free disk space</option>
</select>
<?if(isset($_REQUEST["se_account_type"])) {
    $account_type = $_REQUEST["se_account_type"];
    ?>
    <script type="text/javascript">
    $(document).ready(function() {
            $("select[name=se_account_type] option[value=<?=$account_type?>]").attr('selected', 'selected');
    });
    </script>
<?}?>
