<p class="info">RSV runs common set of tests on OSG resources to check their availability and discover potential issues. This page shows the current result from the RSV probes. For more information - <a href="http://rsv.grid.iu.edu/documentation/" target="_blank">RSV Documentation</a></p>

<?$checked = "";
if(isset($_REQUEST["current_status_attrs_shownc"])) { $checked = "checked=checked"; }?>
<input type="checkbox" name="current_status_attrs_shownc" <?=$checked?>/>
Display information for non-critical metrics: <br/>
<br/>


