<p class="info">Show basic information about resources.</p>

<?$checked = "";
if(isset($_REQUEST["summary_attrs_showdesc"])) { $checked = "checked=checked"; }?>
<input type="checkbox" name="summary_attrs_showdesc" <?=$checked?>/> Show Description<br/>

<?$checked = "";
if(isset($_REQUEST["summary_attrs_showservice"])) { $checked = "checked=checked"; }?>
<input type="checkbox" name="summary_attrs_showservice" <?=$checked?>/> Show Services<br/>

<?$checked = "";
if(isset($_REQUEST["summary_attrs_showrsvstatus"])) { $checked = "checked=checked"; }?>
<input type="checkbox" name="summary_attrs_showrsvstatus" <?=$checked?>/> Show Current RSV Status<br/>

<?$checked = "";
if(isset($_REQUEST["summary_attrs_showgipstatus"])) { $checked = "checked=checked"; }?>
<input type="checkbox" name="summary_attrs_showgipstatus" <?=$checked?>/> Show Current GIP Validation Status<br/>

<?$checked = "";
if(isset($_REQUEST["summary_attrs_showfqdn"])) { $checked = "checked=checked"; }?>
<input type="checkbox" name="summary_attrs_showfqdn" <?=$checked?>/> Show FQDN<br/>

<?$checked = "";
if(isset($_REQUEST["summary_attrs_showvomembership"])) { $checked = "checked=checked"; }?>
<input type="checkbox" name="summary_attrs_showvomembership" <?=$checked?>/> Show Supported VOs<br/>

<?$checked = "";
if(isset($_REQUEST["summary_attrs_showvoownership"])) { $checked = "checked=checked"; }?>
<input type="checkbox" name="summary_attrs_showvoownership" <?=$checked?>/> Show VO Ownership<br/>

<?$checked = "";
if(isset($_REQUEST["summary_attrs_showwlcg"])) { $checked = "checked=checked"; }?>
<input type="checkbox" name="summary_attrs_showwlcg" <?=$checked?>/> Show WLCG Information<br/>

<?$checked = "";
if(isset($_REQUEST["summary_attrs_showenv"])) { $checked = "checked=checked"; }?>
<input type="checkbox" name="summary_attrs_showenv" <?=$checked?>/> Show Environment Parameters<br/>

<?$checked = "";
if(isset($_REQUEST["summary_attrs_showcontact"])) { $checked = "checked=checked"; }?>
<input type="checkbox" name="summary_attrs_showcontact" <?=$checked?>/> Show Contact Information<br/>

<?$checked = "";
if(isset($_REQUEST["summary_attrs_showalias"])) { $checked = "checked=checked"; }?>
<input type="checkbox" name="summary_attrs_showalias" <?=$checked?>/> Show Aliases<br/>


