<p>* Show basic information about a resource.</p>
<?$checked = "";
if(isset($_REQUEST["summary_attrs_showdesc"])) { $checked = "checked=checked"; }?>
<input type="checkbox" name="summary_attrs_showdesc" <?=$checked?>/> Display description<br/>

<?$checked = "";
if(isset($_REQUEST["summary_attrs_showfqdn"])) { $checked = "checked=checked"; }?>
<input type="checkbox" name="summary_attrs_showfqdn" <?=$checked?>/> Display FQDN<br/>

<?$checked = "";
if(isset($_REQUEST["summary_attrs_showvomembership"])) { $checked = "checked=checked"; }?>
<input type="checkbox" name="summary_attrs_showvomembership" <?=$checked?>/> Display Supported VOs<br/>

<?$checked = "";
if(isset($_REQUEST["summary_attrs_showvoownership"])) { $checked = "checked=checked"; }?>
<input type="checkbox" name="summary_attrs_showvoownership" <?=$checked?>/> Display VO Ownership<br/>
