
<script type="text/javascript" src="<?=fullbase()?>/lib/jquery-1.2.6/jquery-ui.js"></script>
<script type="text/javascript" src="<?=fullbase()?>/lib/jquery-1.2.6/daterange/daterangepicker.jQuery.js"></script>
<link type="text/css" href="<?=fullbase()?>/lib/jquery-1.2.6/ui.core.css" rel="Stylesheet" />
<link rel="stylesheet" href="<?=fullbase()?>/lib/jquery-1.2.6/ui.theme.css" type="text/css" title="ui-theme" />
<link rel="stylesheet" href="<?=fullbase()?>/lib/jquery-1.2.6/ui.datepicker.css" type="text/css" />
<link rel="stylesheet" href="<?=fullbase()?>/lib/jquery-1.2.6/daterange/ui.daterangepicker.css" type="text/css" />

<style type="text/css">
.list
{
    padding: 2px;
    background-color: #eee;
    margin-bottom: 10px;
    margin-left: 16px;
    width: 90%;
}
.scrolled_list
{
    height: 80px;
    overflow: auto;
}
</style>

<form method="get">
    <h3>Information to display</h3>
    <div class="indent" id="datasource_area">
        <select name="datasource">
        <option value="">(Please Select)</option>
        <option value="summary">Current Status Summary</option>
        <option value="current_status">Current Status</option>
        <option value="status_history">Status History</option>
        <option value="availability_history">Availability History</option>
        <option value="downtime">Downtime Schedule</option>
        <option value="vo_membership">VO Membership</option>
        <option value="vo_ownership">VO Ownership</option>
        </select>
        <p>
            <div id="summary_attrs" class="attrs indent hidden">
                <?=$this->render("wizard_summary/wizard.phtml")?>
            </div>

            <div id="current_status_attrs" class="attrs indent hidden">
                <?=$this->render("wizard_current_status/wizard.phtml")?>
            </div>

            <div id="status_history_attrs" class="attrs indent hidden">
                <?=$this->render("wizard_status_history/wizard.phtml")?>
            </div>

            <div id="availability_history_attrs" class="attrs indent hidden">
                <?=$this->render("wizard_availability_history/wizard.phtml")?>
            </div>

            <div id="downtime_attrs" class="attrs indent hidden">
                <?=$this->render("wizard_downtime/wizard.phtml")?>
            </div>

            <div id="vo_membership_attrs" class="attrs indent hidden">
                <?=$this->render("wizard_vo_membership/wizard.phtml")?>
            </div>

            <div id="vo_ownership_attrs" class="attrs indent hidden">
                <?=$this->render("wizard_vo_ownership/wizard.phtml")?>
            </div>
        </p>
    </div>

    <h3>Resources to display</h3>
    <div class="indent">
        <div id="resource_area_standby">
            <p>Please select the information to display first.</p>
        </div>
        <div id="resource_area" class="hidden">
            <p>Select resources that you want to show above information.</p>
            <?
            function checklist($id, $title, $kv)
            {
                //output title check box
                $checked = "";
                if(isset($_REQUEST[$id])) { 
                    $checked = "checked=checked"; 
                    ?>
                    <script type="text/javascript">
                    $(document).ready(function() {
                        $("#<?=$id?>__list").show();
                    });
                    </script>
                    <?
                }
                $title = "<input type=\"checkbox\" name=\"$id\" $checked onclick=\"if(this.checked) {\$('#${id}__list').show('normal');} else {\$('#${id}__list').hide();}\"/> <span>$title</span><br/>";

                //determine list class
                $c = "hidden ";
                if(count($kv) > 8) { 
                    $c .= "scrolled_list ";
                }

                //output list
                $list = "";
                $list .= "<div class=\"$c list\" id=\"${id}__list\">";
                foreach($kv as $key=>$value) {
                    $name = "${id}_$key";
                    $checked = "";
                    if(isset($_REQUEST[$name])) {
                        $checked = "checked=checked";
                    }
                    $list .= "<input type=\"checkbox\" name=\"$name\" $checked/> <span>$value</span><br/>";
                }
                $list .= "</div>";

                return "<div id=\"$id\">".$title.$list."</div>";
            }
            
            $checked = "";
            if(isset($_REQUEST["all_resources"])) { $checked = "checked=checked"; }
            echo "<input type=\"checkbox\" name=\"all_resources\" $checked onclick=\"if(this.checked) { disable(this);} else {enable(this);}\"/> All Resources<br/>";

            $model = new SupportCenters();
            $scs = $model->get();
            $kv = array();
            foreach($scs as $sc) { $kv[$sc->sc_id] = $sc->short_name; }
            echo checklist("sc", "Resources in Support Centers", $kv);

            $model = new Site();
            $list = $model->get();
            $kv = array();
            foreach($list as $site) { $kv[$site->site_id] = $site->name; }
            echo checklist("site", "Resources in Sites", $kv);

            $model = new ResourceGroup();
            $list = $model->get();
            $kv = array();
            foreach($list as $item) { $kv[$item->resource_group_id] = $item->name; }
            echo checklist("rg", "Resources in Resource Groups", $kv);

            $model = new Resource();
            $list = $model->get();
            $kv = array();
            foreach($list as $item) { $kv[$item->id] = $item->name; }
            echo checklist("r", "Specific Resources", $kv);
            ?>
        </div>
    </div>

    <h3>Filter</h3>
    <div class="indent">
        <div id="filter_area_standby">
            <p>Please select the information to display first.</p>
        </div>
        <div id="filter_area" class="hidden">
            <p>Only show resources that matches following criteria.</p>

            <?
            $model = new GridTypes();
            $list = $model->get();
            $kv = array();
            foreach($list as $item) { $kv[$item->grid_type_id] = $item->short_name; }
            echo checklist("gt", "Grid Type", $kv);

            $model = new Status();
            $list = $model->get();
            $kv = array();
            foreach($list as $item) { $kv[$item->metric_status_id] = $item->metric_status_description; }
            echo checklist("status", "Resource Status", $kv);

            $model = new ServiceTypes();
            $list = $model->get(array("service_group_id"=>1));
            $kv = array();
            foreach($list as $item) { $kv[$item->service_id] = $item->name; }
            echo checklist("service", "Provides following Services", $kv);

            $model = new VirtualOrganization();
            $list = $model->get();
            $kv = array();
            foreach($list as $item) { $kv[$item->vo_id] = $item->short_name; }
            echo checklist("vosup", "Supporting VOs", $kv);

            $model = new VirtualOrganization();
            $list = $model->get();
            $kv = array();
            foreach($list as $item) { $kv[$item->vo_id] = $item->short_name; }
            echo checklist("voown", "Owned by VOs", $kv);

            $checked = "";
            if(isset($_REQUEST["has_status"])) { $checked = "checked=checked"; }
            echo "<input type=\"checkbox\" name=\"has_status\" $checked/> Resource Status Calculated<br/>";
            ?>

        </div>
    </div>

    <br/>
    <div class="indent">
        <input type="submit" value="&nbsp;&nbsp;&nbsp;Update View&nbsp;&nbsp;&nbsp;"/>
    </div>
</form>
 
<script type="text/javascript">

$(document).ready(function() {

    //setup form
    $("select[name=datasource]").change(function() {
        var v = $(this).val();
        $(".attrs").hide();
        if(v != "") {
            $("#"+v+"_attrs").show('normal');
            $("#resource_area").show('normal');
            $("#filter_area").show('normal');
            $("#resource_area_standby").hide();
            $("#filter_area_standby").hide();
            //showhide_filterarea();
        } else {
            $("#resource_area").hide();
            $("#filter_area").hide();
            $("#resource_area_standby").show();
            $("#filter_area_standby").show();
        }
    });

    //find if there is any checkbox that is selected in resource_area
    //$("#resource_area").click(showhide_filterarea);

    <?
    //select currently selected datasouce
    if(isset($_REQUEST["datasource"])) {
        $datasource = $_REQUEST["datasource"];
        switch($datasource) {
        case "summary":
        case "current_status":
        case "status_history":
        case "availability_history":
        case "downtime":
        case "vo_membership":
        case "vo_ownership":
            echo "$('#".$_REQUEST["datasource"]."_attrs').show();\n";
            echo "$('select[name=datasource] option[value=$datasource]').attr('selected', 'selected');\n";
            echo '$("#resource_area").show();/*showhide_filterarea();*/';
            echo '$("#filter_area").show();';
            echo '$("#resource_area_standby").hide();/*showhide_filterarea();*/';
            echo '$("#filter_area_standby").hide();';
        }
    }

    if(isset($_REQUEST["all_resources"])) {
        echo "disable($('input[name=all_resources]'));";
    }
    ?>
});

/*
function showhide_filterarea() {
    var checks = $(document).find("#resource_area").find(".resource_check");
    var hascheck = false;
    checks.each(function(id) {
        if($(this)[0].checked) {
            hascheck = true;
        }
    });
    if(hascheck) {
        $("#filter_area").show('normal');
    } else {
        $("#filter_area").hide();
    }
}
*/

function disable(e)
{
    var items = $(e).siblings(); 
    $(items).find('input').attr('disabled', 'disabled');
    $(items).find('span').css('color', 'gray');
}
function enable(e)
{
    var items = $(e).siblings(); 
    $(items).find('input').removeAttr('disabled');
    $(items).find('span').css('color', 'inherit');
}
</script>
