<style>
table th {
max-width: 300px;
}
.table th, 
.table td {
padding: 3px;
}
tr.noborder > th,
tr.noborder > td {
border-top: none;
}
</style>
<h2><?php echo $this->page_title?> 
<small>
Between <?php echo date(config()->date_format, $this->start_time);?> 
and <?php echo date(config()->date_format, $this->end_time)?></span><br>
</small>
</h2>
<?php
echo "<table class=\"table\">";
foreach($this->rgs as $rgid=>$rg) {
    //show resource group header
    $resource_group = $this->resource_groups[$rgid][0];
    echo "<tr class=\"noborder\"><td colspan=\"3\">";
    echo "<div class=\"group_header\">";
    echo "<span class='h3'>".$resource_group->name."</span>";
    echo " <small>".$resource_group->grid_type."</small>";
    echo "</div>";
    //echo $this->ruler;
    echo "</td></tr>";

    foreach($rg as $rid=>$resource_info) {
        $services = $this->services[$rid];
        asort($services);
        $resource_th = "<th>";
        $resource_th .= "<div class=\"resource\">";
        $resource_th .= "<span class=\"h4\">".$resource_info->name."</span>";
        $resource_th .= "<br><code>$resource_info->fqdn</code>";
        $resource_th .= "</div>";
        $resource_th .= "</th>";
        if(count($services) == 0) {
            echo "<tr>";
            echo $resource_th;
            echo "<td colspan=2>";
            echo "<p class=\"muted\">No availability history available for this duration.</p>";
            echo "</td>";
            echo "</tr>";
        } else {
            $first = true;
            foreach($services as $service_id=>$recs)
            {
                if($first) {
                    echo "<tr>";
                    echo $resource_th;
                    $first = false;
                } else {
                    //dont show resource name.. 
                    echo "<tr><th style=\"border: none\"></th>";
                }

                $service_info = $this->service_info[$service_id];
                $service_name = $service_info[0]->name; //description is sometimes too long..
                echo "<td>$service_name</td>";
                $ax = "0";
                $ay = "-1";
                $rx = "0";
                $ry = "-1";
                $start_date = date(config()->date_format, $this->start_time);
                $mid_date = date(config()->date_format, $this->start_time + ($this->end_time-$this->start_time)/2);
                $end_date = date(config()->date_format, $this->end_time);
                $period = $this->end_time - $this->start_time;
            
                $previous_x = -1;
                $previous_a = -1;
                $previous_r = -1;
                $skipped_x = -1;
                foreach($recs as $rec) {
                    $x = round(($rec->timestamp - $this->start_time) / $period * 100);
                    $a = round($rec->availability*100, 1);
                    $r = round($rec->reliability*100, 1);

                    //skip if at the same x - position
                    if($previous_x == $x) continue; 

                    //skip if both a&r are the same as previous
                    if($previous_a == $a && $previous_r == $r) {
                        $skipped_x = $x;
                        continue; 
                    }

                    //add last skipped value
                    if($previous_x != $skipped_x) {
                        if($ax != "") {
                            $ax .= ",";
                            $ay .= ",";
                            $rx .= ",";
                            $ry .= ",";
                        }
                        $ax .= $skipped_x;
                        $ay .= $previous_a;
                        $rx .= $skipped_x;
                        $ry .= $previous_r;
                    }

                    //enter current value
                    if($ax != "") {
                        $ax .= ",";
                        $ay .= ",";
                        $rx .= ",";
                        $ry .= ",";
                    }
                    $ax .= $x;
                    $ay .= $a;
                    $rx .= $x;
                    $ry .= $r;

                    //record previous value
                    $previous_x = $x;
                    $skipped_x = $x;
                    $previous_a = $a;
                    $previous_r = $r;
                }

                //add last skipped value
                if($previous_x != $skipped_x) {
                    if($ax != "") {
                        $ax .= ",";
                        $ay .= ",";
                        $rx .= ",";
                        $ry .= ",";
                    }
                    $ax .= $skipped_x;
                    $ay .= $previous_a;
                    $rx .= $skipped_x;
                    $ry .= $previous_r;
                }

                if(uwa()) {
                    $size = "270x100";
                } else {
                    $size = "450x100";
                }
                $url = "http://chart.apis.google.com/chart?chs=$size";
                $url .= "&cht=lxy&chxt=x,y";
                $url .= "&chxl=0:|$start_date|$mid_date|$end_date|1:|0%|25%|50%|75%|100%";
                if(!uwa()) {
                    //legend
                    $url .= "&chdl=Availability|Reliability";
                }
                $url .= "&chco=00ff00,0000ff";
                $url .= "&chm=B,99ff99,0,-1,0";
                $url .= "&chd=t:$ax|$ay|$rx|$ry";
                $url .= "&chg=10,25,1";
                $url .= "&chls=2,1,0|2,1,0";
                echo "<td><img src='$url'/></td>";
                echo "</tr>";
            }

        }
    }
}
echo "</table>";
