<!DOCTYPE html>
<html lang="en">
<head>
    <base href="<?php echo base()?>/">
    <!--[if IE]>
    <script type="text/javascript">
        //fix ie's broken base href handling
        function toAbsURL(s) {
         var l = location, h, p, f, i;
         if (/^\w+:/.test(s)) { return s; }
         h = l.protocol + '//' + l.host + (l.port!=''?(':' + l.port):'');
         if (s.indexOf('/') == 0) { return h + s; }
         p = l.pathname.replace(/\/[^\/]*$/, '');
         f = s.match(/\.\.\//g);
         if (f) {
           s = s.substring(f.length * 3);
           for (i = f.length; i--;) { p = p.substring(0, p.lastIndexOf('/')); }
         }
         return h + p + '/' + s;
       }
    var base = document.getElementsByTagName('base')[0];
    base.href = toAbsURL(base.href);
    </script>
    <![endif]-->

    <meta charset="utf-8">
    <meta name="verify-v1" content="na5IcAJsZVOfEkboRxuIiZ1zpZgnZiWra+nKcS7nA/o=" />
    <title><?php
    if(isset($this->page_title)) {
        echo $this->page_title." - ";
    }
    echo config()->app_name;
    ?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="images/favicon.ico" rel="icon" type="image/vnd.microsoft.icon" />

    <!-- Le styles -->
    <link href="lib/bootstrap-2.0.4/css/bootstrap.css" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
      .sidebar-nav {
        padding: 9px 0;
      }
        #search {
            width: 120px;
        }
    </style>
    <link href="lib/bootstrap-2.0.4/css/bootstrap-responsive.css" rel="stylesheet">
    <link href="lib/jquery-ui-1.8.21/css/ui-lightness/jquery-ui-1.8.21.custom.css" rel="stylesheet">
    <link href="lib/jquery.autocomplete.css" rel="stylesheet" type="text/css" />
    <!--link href="css/emerald/default.css" rel="stylesheet" type="text/css" />-->
    <link href="css/myosg.css" rel="stylesheet" type="text/css" />

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="lib/jquery-ui-1.8.21/js/jquery-1.7.2.min.js"></script>
    <script src="lib/jquery-ui-1.8.21/js/jquery-ui-1.8.21.custom.min.js"></script>
    <script src="lib/bootstrap-2.0.4/plugin/bootstrap-alert.js"></script>
    <script src="lib/bootstrap-2.0.4/plugin/bootstrap-dropdown.js"></script>
    <script src="lib/bootstrap-2.0.4/plugin/bootstrap-collapse.js"></script>
    <script src="lib/bootstrap-2.0.4/plugin/bootstrap-modal.js"></script>

    <script src="lib/bootstrap-2.0.4/plugin/bootstrap-tooltip.js"></script>
    <script src="lib/bootstrap-2.0.4/plugin/bootstrap-popover.js"></script>
<!--
    <script src="lib/bootstrap-2.3.1/js/bootstrap-tooltip.js"></script>
    <script src="lib/bootstrap-2.3.1/js/bootstrap-popover.js"></script>
-->
    <script src="lib/jquery.autocomplete.min.js"></script>
    <?php if(isset($this->include_cometd)) { ?>
    <script type='text/javascript' src='<?php echo base()?>/lib/cometd-2.3.1/cometd.js'></script>
    <script type='text/javascript' src='<?php echo base()?>/lib/cometd-2.3.1/jquery/jquery.cometd.js'></script>
    <?php } ?>
    <?php if(isset($this->include_timeago)) { ?>
    <script type='text/javascript' src='<?php echo base()?>/lib/jquery.timeago.js'></script>
    <?php } ?>
    <?php if(!is_null(config()->google_analytics_id)) {?>
    <script type="text/javascript">
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', '<?php echo config()->google_analytics_id?>']);
      _gaq.push(['_setDomainName', 'grid.iu.edu']);
      _gaq.push(['_setAllowLinker', true]);
      _gaq.push(['_trackPageview']);
      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();

    </script>
    <?php } ?>
    <?php echo $this->headScript(); ?>
    <?php echo $this->headStyle(); ?>
</head>
<body>
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container-fluid">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <a class="brand" href="http://opensciencegrid.org"><img src="images/osglogo.40x30.png"></a>
            <ul class="nav">
                <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown"><?php echo config()->app_name?> <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                    <li class="active"><a href="index">MyOSG</a></li>
                    <li><a href="https://oim.grid.iu.edu">OIM</a></li>
                    <li><a href="https://ticket.grid.iu.edu/goc">Ticket</a></li>
                    <li><a href="https://twiki.grid.iu.edu">TWiki</a></li>
                    <li class="divider"></li>
                    <li><a href="http://repo.grid.iu.edu">Repo</a></li>
                    <!--<li><a href="http://software.grid.iu.edu">Software Cache</a></li>-->
                    <li><a href="http://is.grid.iu.edu">OSG BDII</a></li>
                    <li class="divider"></li>
                    <li><a href="http://blogs.grid.iu.edu">Blog</a></li>
                    <li><a href="http://display.grid.iu.edu">Display</a></li>
                    <li><a href="http://osggoc.blogspot.com/">News</a></li>
                    </ul>
                </li>
            </ul>
            <ul class="nav pull-right">
                <?php 
                if(!user()->isGuest()) {
                    //user
                    echo "<div class=\"btn-group\">";
                    echo "<a href=\"#\" onclick=\"return false;\" class=\"btn dropdown-toggle\" data-toggle=\"dropdown\"><i class=\"icon-user\"></i> ".user()->getPersonName()." <span class=\"caret\"></span></a>";
                    echo "<ul class=\"dropdown-menu\">";
                    echo "<li><a href=\"miscuser".config()->default_url("misc")."\">OSG Users</a></li>";
                    //echo "<li><a href=\"notification\">Notification Settings</a></li>";
                    echo "<li class=\"divider\"></li>";
                    echo "<li><a href=\"http://".$_SERVER["SERVER_NAME"].base()."\">Logoff</a></li>";
                    echo "</ul>";
                    echo "</div>";
                } else if(@$_SERVER['HTTPS'] == "on") {
                    if(Zend_Registry::isRegistered("unregistered_dn")) {
                        echo "<li><a href=\"https://oim.grid.iu.edu/oim/register\">Register</a></li>";
                    } else if(Zend_Registry::isRegistered("disabled_dn")) {
                        echo "<li><a href=\"http://".$_SERVER["SERVER_NAME"].base()."\">(Disabled)</a></li>";
                    } else {
                        echo "<li><a href=\"http://".$_SERVER["SERVER_NAME"].base()."\">(NoCert)</a></li>";
                    }
                } else {
                    //probably via http
                    echo "<li><a href=\"https:".$_SERVER["SERVER_NAME"].$_SERVER["REQUEST_URI"]."\">Login</a></li>";
                }
                ?>
            </ul>
            <div class="nav-collapse">
                <ul class="nav">
                    <li id="menu_about"><a href="about<?php config()->default_url("about")?>">Home</a></li>
                    <li id="menu_rg" class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Resource Group <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                        <li id="menu_rgsummary"><a href="rgsummary<?php echo config()->default_url("rg")?>">Resource Group Summary</a></li>
                        <li class="divider"></li>
                        <li id="menu_rgcurrentstatus"><a href="rgcurrentstatus<?php echo config()->default_url("rg")?>">Current RSV Status</a></li>
                        <li id="menu_rgstatushistory"><a href="rgstatushistory<?php echo config()->default_url("rg")?>">RSV Status History</a></li>
                        <li class="divider"></li>
                        <li id="menu_rgarhistory"><a href="rgarhistory<?php echo config()->default_url("rg")?>">Availability History</a></li>
                        <li id="menu_rgarmetric"><a href="rgarmetric<?php echo config()->default_url("rg")?>">Availability Metrics</a></li>
                        <li class="divider"></li>
                        <li id="menu_rgdowntime"><a href="rgdowntime<?php echo config()->default_url("rg")?>">Downtime Schedule</a></li>
                        <li id="menu_rggipstatus"><a href="rggipstatus<?php echo config()->default_url("rg")?>">Current GIP Validation Status</a></li>
                        <li id="menu_rgbdii"><a href="rgbdii<?php echo config()->default_url("rg")?>&bdii_server=is-osg&bdii_object=cluster">BDII Information Browser</a></li>
                        <li class="divider"></li>
                        <li id="menu_rgaccount"><a href="rgaccount<?php echo config()->default_url("rg")?>&account_type=cumulative_hours">Gratia Accounting Graphs</a></li>
                        <li id="menu_rgce"><a href="rgce<?php echo config()->default_url("rg")?>&ce_account_type=gip_vo">Gratia Accounting Graphs (for CE)</a></li>
                        <li id="menu_rgse"><a href="rgse<?php echo config()->default_url("rg")?>&se_account_type=vo_transfer_volume">Gratia Accounting Graphs (for SE)</a></li>
                        <li class="divider"></li>
                        <li id="menu_rgpfstatus"><a href="<?php echo config()->default_url("rgpfstatus")?>">Perfsonar Status</a></li>
                        <li id="menu_rgpfmatrix"><a href="<?php echo config()->default_url("rgpfmatrix")?>">Perfsonar Full OSG Matrix</a></li>
                        </ul>
                    </li>
                    <li id="menu_vo" class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Virtual Organization<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                        <li id="menu_vosummary"><a href="vosummary<?php echo config()->default_url("vo")?>">Virtual Organization Summary</a></li>
                        <li class="divider"></li>
                        <li id="menu_voactivation"><a href="voactivation<?php echo config()->default_url("vo")?>">Activation Status</a></li>
                        <li id="menu_vovomsstatus"><a href="vovomsstatus<?php echo config()->default_url("vo")?>">VOMS Status</a></li>
                        <li id="menu_vopfmatrix"><a href="vopfmatrix?vo=on&vo_35=on&vo_3=on&active_value=1&oasis_value=1&sort_key=name">Perfsonar VO Matrix</a></li>
                        </ul>
                    </li>
                    <li id="menu_map"><a href="map<?php echo config()->default_url("map");?>">Status Map</a></li>
                    <li id="menu_misc" class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Misc<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                        <li id="menu_sc"><a href="scsummary<?php echo config()->default_url("sc")?>">Support Center Summary</a></li>
                        <li id="menu_miscmetric"><a href="miscmetric<?php echo config()->default_url("misc")?>">RSV Metrics</a></li>
                        <li id="menu_misccpuinfo"><a href="misccpuinfo<?php echo config()->default_url("misc")?>">CPU Information</a></li>
                        <li id="menu_miscproject"><a href="miscproject<?php echo config()->default_url("misc")?>">Projects</a></li>
                        <li id="menu_misccount"><a href="misccount<?php echo config()->default_url("misc")?>&count_sg_1=on&count_active=on&count_enabled=on">Resource Service Count</a></li>
                        <li id="menu_miscstatus"><a href="miscstatus<?php echo config()->default_url("misc")?>">Operations Status Overview</a></li>
                        <li id="menu_miscevent"><a href="miscevent<?php echo config()->default_url("misc")?>">GOC Realtime Events</a></li>
                        <li id="menu_miscpfmesh"><a href="miscpfmesh<?php echo config()->default_url("misc")?>">Perfsonar Mesh Configurations</a></li>
                        </ul>
                    </li>
                </ul>
                <form class="navbar-search pull-left" action="search">
                    <input id="search" type="text" name="q" class="search-query span2" placeholder="Search" value="<?php echo @$this->query?>">
                </form>
            </div><!--collapse-->
        </div>
    </div>
</div>
</head>
<body>
