
<script>
var query = {};
function uwa() { return false; }
function parseQuery() {
    var q = window.location.search.substring(1);
    var vars = q.split("&");
    for (var i=0;i<vars.length;i++) {
        var pair = vars[i].split("=");
        if(pair.length == 2) {
            query[pair[0]] = pair[1];
        }
    }
}

//used by searchbox
function parseValue(value) {
    var obj = new Object();
    var tokens = value.split("\t");
    obj.name = tokens[0];
    obj.sub = tokens[1];
    obj.type = tokens[2];
    obj.type_name = tokens[2].replace("_", " ");
    return obj; 
}

$(function() {
    $(".alert-message").alert();
    $(".dropdown-toggle").dropdown();
    $("*[rel='tooltip']").tooltip();
    parseQuery();

    //activate menu that user is currently on
    $("#menu_<?php echo $this->menu_selected?>").addClass("active"); 
    <?php
    $front = Zend_Controller_Front::getInstance();
    $controllerName = $front->getRequest()->getControllerName();
    ?>
    $("#menu_<?php echo $controllerName?>").addClass("active"); 

    //enable autocomplete for search box
    $("#search").autocomplete({
        source: function( request, response ) {
            $.ajax({
                url: "<?php echo fullbase()?>/search/autocomplete",
                dataType: "text",
                data: {
                    //featureClass: "P",
                    //style: "full",
                    //maxRows: 12,
                    //name_startsWith: request.term
                    q: request.term
                },
                success: function( data ) {
                    response( $.map( data.split("\n"), function( item ) {
                        if(item == "") return null;
                        var tokens = item.split("\t");
                        return {
                            value: tokens[0],
                            label: tokens[0] + " - " + tokens[1] + " (" + tokens[2] + ")"
                        }
                    }));
                }
            });
        },
        select: function(event, ui) {
            document.location = "search?q="+ui.item.value;
        }
    });

    /*

        formatItem: function(data, i, n, value) {
            var obj = parseValue(value);
            return obj.name + "<span class=\"tag "+obj.type+"\">"+obj.type_name+"</span><br>"+obj.sub;
        },
        formatResult: function(data, value) {
            var obj = parseValue(value);
            //return type+ ": " + name;
            return obj.name;
        },
    }).result(function(input, value) {
        value = value[0];
        var obj = parseValue(value);
        document.location = "<?=fullbase()?>/search?q="+escape(obj.name)+"&type="+obj.type;
    });
    */
});
</script>

</body>
</html>
