<h3>Delicious Tags</h3>
<div class="indent">
<p>You can add your link to this list by tagging a page with "opensciencegrid" or "myosg" as a <a target="_blank" href="http://delicious.com/about">delicious</a> tag.</p>

<?
require_once "app/rss/rss_fetch.php";

$url = "http://feeds.delicious.com/v2/rss/tag/opensciencegrid?count=15";
$rss = fetch_rss($url);
echo "<h4>opensciencegrid</h4>";
showrss($rss);

echo "<br/>";

$url = "http://feeds.delicious.com/v2/rss/tag/myosg?count=15";
$rss = fetch_rss($url);
echo "<h4>myosg</h4>";
showrss($rss);

function showrss($rss) {
    foreach ($rss->items as $item ) {
        $title = htmlentities($item[title]);
        $url   = htmlentities($item[link]);
        $creator = htmlentities($item[dc][creator]);
        echo "<a target=\"_blank\" href=$url>$title</a> (by $creator)<br/>";
        echo "<div class=\"indent\">";
        if(isset($item[description])) {
            echo "<i>".htmlentities($item[description])."</i><br/>";
        }
        //var_dump($item);
        echo "</div>";
    }
}
?>

</div>

