<h3>Feedback</h3>
<p>Do you have an idea to make this tool more useful? Please tell us!</p>
<form action="<?=base()."/comment/submit"?>" method="post">
Your Name:<br/>
<input type="text" name="name"/><br/>
Your Email:<br/>
<input type="text" name="email"/><br/>
Comment:<br/>
<textarea rows="5" name="comment"></textarea><br/>
<input type="submit" value="Submit"/>
<input type="hidden" name="page" value="<?=$_SERVER["SERVER_NAME"].$_SERVER["REQUEST_URI"]?>"/>
</form>
<br/>
<p>Report bugs at <a href="http://code.google.com/p/osggoc/issues/entry">GOC Bug Tracker</a>.</p>
