<hr>
<footer>
<?php
if(user()->isGuest()) {
    $ticket_url = "http://ticket.grid.iu.edu/goc";
} else {
    $ticket_url = "https://ticket.grid.iu.edu/goc";
}
echo "<p>".config()->app_name." Version ".config()->version;
?> 
| <a href="<?php echo $ticket_url?>/submit?app_issue_check=on&app_issue_type=goc&app_goc_url=<?=urlencode(fullurl())?>">Report Bugs</a>
| <a href="https://twiki.grid.iu.edu/bin/view/Operations/IUPrivacyPolicy">Privacy Policy</a>
<?
if(config()->debug) {
    exec("svn info | grep \"Revision:\" |  awk '{print $2}'", $out);
    echo " (Rev. ".$out[0].")";
}
echo "</p>";
?>
<p><img src="images/myosg_favi.png" align="top">&nbsp; Copyright 2013 - The Trustees of Indiana University - Developed for Open Science Grid</p>
</footer>
