<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<?
function format() { return "html"; }
?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!--meta http-equiv="refresh" content="60"-->
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title><?=config()->app_name?></title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<link href="images/myosg_favi.ico" rel="icon" type="image/x-icon" />

<link href="<?=base()?>/css/emerald/default.css" rel="stylesheet" type="text/css" />
<link href="<?=base()?>/css/osg.css" rel="stylesheet" type="text/css" />
<script language='javascript' src='<?=base()?>/lib/jquery-1.2.6/jquery.js'></script>
<script language='javascript'>
var query = {};
function uwa() { return false; }
function parseQuery() {
    var q = window.location.search.substring(1);
    var vars = q.split("&");
    for (var i=0;i<vars.length;i++) {
        var pair = vars[i].split("=");
        if(pair.length == 2) {
            query[pair[0]] = pair[1];
        }
    }
}
parseQuery();
//console.log(jQuery.param(query));
</script>

</head>
<body>

<div id="outer">
    <div id="header">
        <img id="logo" src="images/myosg.png"/>
        <h1><a href="<?=base()?>"><?=config()->app_name?></a></h1>
        <h2><?=config()->app_subname?></h2>
    </div>

    <div id="menu">
        <ul>
            <li id="menu_rsv" class="first"><a href="<?=base()?>/resources">RSV</a></li>
            <li id="menu_gratia"><a href="<?=base()?>/gratiajob">Gratia</a></li>
            <li id="menu_about"><a href="<?=base()?>/about">About</a></li>
        </ul>
    </div>

    <div class="submenu hidden" id="submenu_rsv">
        <span id="submenu_rsv_resources"><a href="<?=base()?>/resources">Resource Groups</a></span>
        <span id="submenu_rsv_vo"><a href="<?=base()?>/vo">Virtual Organizations</a></span>
        <span id="submenu_rsv_map"><a href="<?=base()?>/map">RSV Status Map</a></span>
        <span id="submenu_rsv_aandr"><a href="<?=base()?>/aandr">Availability</a></span>
        <span id="submenu_rsv_doc"><a target="_blank" href="http://rsv.grid.iu.edu/documentation/">Documentation (External)</a></span>
        <span id="submenu_rsv_rsv"><a href="<?=base()?>/rsv">About RSV</a></span>
    </div>

    <div class="submenu hidden" id="submenu_gratia">
        <span id="submenu_gratia_gratiajob"><a href="<?=base()?>/gratiajob">Job Activity</a></span>
        <span id="submenu_gratia_gratia"><a href="<?=base()?>/gratia">About Gratia</a></span>
    </div>

    <div class="submenu hidden" id="submenu_about">
        <span id="submenu_about_about"><a href="<?=base()?>/about">MyOSG</a></span>
    </div>



    <script type="text/javascript">
        $("#menu_<?=$this->menu_selected?>").addClass("selected");
        $("#submenu_<?=$this->menu_selected?>").removeClass("hidden");
        $("#submenu_<?=$this->menu_selected?>_<?=$this->submenu_selected?>").addClass("selected");
    </script>

    <div id="content">
<?
    if(config()->banner) {
        echo "<div id=\"banner\">".config()->banner."</div>";
    }
?>

