<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title><?=config()->app_name?></title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<link href="images/myosg_favi.ico" rel="icon" type="image/x-icon" />

<link href="<?=base()?>/css/emerald/default.css" rel="stylesheet" type="text/css" />
<link href="<?=base()?>/css/osg.css" rel="stylesheet" type="text/css" />
<script type='text/javascript' src='<?=base()?>/lib/jquery-1.3.1/jquery.js'></script>
<script language='javascript'>
var query = {};
function uwa() { return false; }
function parseQuery() {
    var q = window.location.search.substring(1);
    var vars = q.split("&");
    for (var i=0;i<vars.length;i++) {
        var pair = vars[i].split("=");
        if(pair.length == 2) {
            query[pair[0]] = pair[1];
        }
    }
}
parseQuery();
</script>

</head>
<body>

<div id="outer">
    <div id="header">
        <img id="logo" src="<?=base()?>/images/myosg.png"/>
        <h1><a href="<?=base()?>"><?=config()->app_name?></a></h1>
        <h2><?=config()->app_subname?></h2>
    </div>

    <?function default_url($page) {
        $param = "";
        switch($page) {
        case 'wizard':
            $param = "?all_resources=on&amp;has_status=on&amp;gt=on&amp;gt_1=on";
        }
        return base()."/".$page.$param;
    }?>

    <div id="menu">
        <ul>
            <li id="menu_about"><a href="<?=default_url("about")?>">About</a></li>
            <li id="menu_rsv" class="first"><a href="<?=default_url("wizard")?>">RSV</a></li>
            <li id="menu_gratia"><a href="<?=default_url("gratiajob")?>">Gratia</a></li>
        </ul>
    </div>

    <div class="submenu hidden" id="submenu_rsv">
        <span id="submenu_rsv_wizard"><a href="<?=default_url("wizard")?>">Resource Wizard</a></span>
        <span id="submenu_rsv_map"><a href="<?=default_url("map")?>">Status Map</a></span>
        <span id="submenu_rsv_vo"><a href="<?=default_url("vo")?>">Virtual Organizations</a></span>
        <span id="submenu_rsv_doc"><a target="_blank" href="http://rsv.grid.iu.edu/documentation/">Documentation (External)</a></span>
        <span id="submenu_rsv_rsv"><a href="<?=default_url("rsv")?>">About RSV</a></span>
    </div>

    <div class="submenu hidden" id="submenu_gratia">
        <span id="submenu_gratia_gratiajob"><a href="<?=default_url("gratiajob")?>">Job Activity</a></span>
        <span id="submenu_gratia_gratia"><a href="<?=default_url("gratia")?>">About Gratia</a></span>
    </div>

    <div class="submenu hidden" id="submenu_about">
        <span id="submenu_about_about"><a href="<?=default_url("about")?>">MyOSG</a></span>
    </div>

    <script type="text/javascript">
        $("#menu_<?=$this->menu_selected?>").addClass("selected");
        $("#submenu_<?=$this->menu_selected?>").removeClass("hidden");
        $("#submenu_<?=$this->menu_selected?>_<?=$this->submenu_selected?>").addClass("selected");
    </script>
    <div id="content">
<?
    if(config()->banner) {
        echo "<div id=\"banner\">".config()->banner."</div>";
    }
    if(config()->debug) {
        echo "<p class=\"warning\">Running in Debug mode</p>";
    }
?>

