        <div class="clear"></div>
    </div>
    <div id="footer">
    <?
    exec("svn info | grep \"Revision:\" |  awk '{print $2}'", $out);
    echo "<p style=\"float: right\">".config()->app_name." Version ".config()->version." (Rev. ".$out[0].")</p>";
    ?>
        <img src="images/myosg_favi.ico" align="left"/><p>&nbsp;<?=config()->copyright?></p>
    </div>
</div>

<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
var pageTracker = _gat._getTracker("<?=config()->urchin_account?>");
pageTracker._initData();
pageTracker._trackPageview();
</script>

</body>
</html>
