<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<?
function format() { return "html"; }
?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title><?=config()->app_name?></title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<link href="images/favicon.ico" rel="icon" type="image/x-icon" />

<link href="<?=base()?>/css/emerald/default.css" rel="stylesheet" type="text/css" />
<link href="<?=base()?>/css/osg.css" rel="stylesheet" type="text/css" />
<script language='javascript' src='<?=base()?>/lib/jquery-1.2.6/jquery.js'></script>
<script language='javascript'>
var query = {};
function uwa() { return false; }
function parseQuery() {
    var q = window.location.search.substring(1);
    var vars = q.split("&");
    for (var i=0;i<vars.length;i++) {
        var pair = vars[i].split("=");
        if(pair.length == 2) {
            query[pair[0]] = pair[1];
        }
    }
}
parseQuery();
//console.log(jQuery.param(query));
</script>

</head>
<body>

<div id="outer">
    <div id="header">
        <h1><a href="<?=base()?>"><?=config()->app_name?></a></h1>
        <h2><?=config()->app_subname?></h2>
    </div>

    <div id="menu">
        <ul>
            <li id="menu_rsv" class="first"><a href="<?=base()?>/rsv" accesskey="2" title="">RSV</a></li>
        </ul>
    </div>

    <div class="submenu hidden" id="submenu_rsv">
        <span id="submenu_rsv_rsv"><a href="<?=base()?>/rsv" accesskey="1" title="">Home</a></span>
        <span id="submenu_rsv_resources"><a href="<?=base()?>/resources" accesskey="2" title="">Resource Groups</a></span>
        <span id="submenu_rsv_vo"><a href="<?=base()?>/vo" accesskey="3" title="">Virtual Organizations</a></span>
        <span id="submenu_rsv_map"><a href="<?=base()?>/map" accesskey="4" title="">RSV Status Map</a></span>
        <span id="submenu_rsv_doc"><a target="_blank" href="http://rsv.grid.iu.edu/documentation/" accesskey="5" title="">Documentation (External)</a></span>
    </div>

    <script type="text/javascript">
        $("#menu_<?=$this->menu_selected?>").addClass("selected");
        $("#submenu_<?=$this->menu_selected?>").removeClass("hidden");
        $("#submenu_<?=$this->menu_selected?>_<?=$this->submenu_selected?>").addClass("selected");
    </script>

    <div id="content">
