        <div class="clear"></div>
    </div>
    <div id="footer">
<?
echo "<p>Logged in as <b>";
if(user()->isGuest()) {
    echo "Guest";
} else {
    echo user()->getDN()." (".user()->getTimeZone().")";
}
echo "</b></p>";


echo "<p>".config()->app_name." Version ".config()->version;
?> 
| <a href="https://ticket.grid.iu.edu/goc/myosg?ref=<?=urlencode(fullurl())?>">Report Bugs</a> 
| <a href="https://twiki.grid.iu.edu/bin/view/Operations/IUPrivacyPolicy">Privacy Policy</a>
<?
if(config()->debug) {
    exec("svn info | grep \"Revision:\" |  awk '{print $2}'", $out);
    echo " (Rev. ".$out[0].")";
}
echo "</p>";

?>

<p><img src="<?=fullbase();?>/images/myosg_favi.png" align="top"/>&nbsp;<?=config()->copyright?></p>
</div>
<script type="text/javascript">
$(document).ready(function() {
    $(".delay_load").each(function(index) { $(this).attr('src', $(this).attr('name') ); });
});
</script>


<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
var pageTracker = _gat._getTracker("<?=config()->urchin_account?>");
pageTracker._initData();
pageTracker._trackPageview();
</script>

</body>
</html>
