<h3>Legend</h3>
<div class="indent">
<p><img align="top" src="<?=fullbase()?>/images/status_ok_map.png"/> OK</p>
<p><img align="top" src="<?=fullbase()?>/images/status_warning_map.png"/> Warning</p>
<p><img align="top" src="<?=fullbase()?>/images/status_unknown_map.png"/> Unknown</p>
<p><img align="top" src="<?=fullbase()?>/images/status_critical_map.png"/> Critical</p>
<p><img align="top" src="<?=fullbase()?>/images/status_downtime_map.png"/> Downtime</p>
<p>Please see <a target="_blank" href="http://docs.google.com/View?id=ddtgc5bt_371fz2hqpcd">Calculation Logic</a> for more information.</p>
</div>


