<div class="">
<h4>Legend</h4>
<p><span class="label" style="background-color: <?=config()->graph_color[-1];?>;">&nbsp;&nbsp;&nbsp;</span> N/A</p>
<p><span class="label" style="background-color: <?=config()->graph_color[1];?>;">&nbsp;&nbsp;&nbsp;</span> OK</p>
<p><span class="label" style="background-color: <?=config()->graph_color[2];?>;">&nbsp;&nbsp;&nbsp;</span> WARNING</p>
<p><span class="label" style="background-color: <?=config()->graph_color[3];?>;">&nbsp;&nbsp;&nbsp;</span> CRITICAL</p>
<p><span class="label" style="background-color: <?=config()->graph_color[4];?>;">&nbsp;&nbsp;&nbsp;</span> UNKNOWN</p>
<p><span class="label" style="background-color: <?=config()->graph_color[99];?>;">&nbsp;&nbsp;&nbsp;</span> DOWNTIME</p>
</div>


