<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="<?=base()?>/lib/jquery-ui-1.8.1/css/smoothness/jquery-ui-1.8.1.custom.css" rel="stylesheet" type="text/css" />
<script type='text/javascript' src='<?=base()?>/lib/jquery-ui-1.8.1/js/jquery-1.4.2.min.js'></script>
<script type='text/javascript' src='<?=base()?>/lib/jquery-ui-1.8.1/js/jquery-ui-1.8.1.custom.min.js'></script>
<style type="text/css">
    <?include("css/mobile.css.php");?>
</style>
</head>
<body>
    <?echo file_get_contents(fullbase()."/".pagename()."/html?uwa=true&".$_SERVER["QUERY_STRING"]);?>
</body>
</html>
