<?
//what's all these complexity? 
//first of all, I can't use simpl a-href tag because I have to dynamically create
//the link target based on the document.location which may include anchor..
//
//secondly.. I have to pass anchor somehow down to the receiving widget - not to
//the widget compiler.. since anchor isn't passed to the server, I have to convert 
//it to a query parameter "__anchor", and let uwa handler convert it back to anchor.
?>
<h3>Subscribe</h3>
<div class="indent">
    <p>Subscribe to the content of this page.</p>

<?if($this->has_subscribe_igoogle) {?>
    <span class="external_link" onclick="window.open('<?=fullbase()."/".pagename()?>/addigoogle'+document.location.search+'&__anchor='+escape(document.location.hash.substr(1)));">iGoogle</span><br/>
<?}?>

<?if($this->has_subscribe_uwa) {?>
    <span class="external_link" onclick="window.open('<?=fullbase()."/".pagename()?>/adduwa'+document.location.search+'&__anchor='+escape(document.location.hash.substr(1)));">Netvibes</span><br/>
<?}?>

<?if($this->has_subscribe_mobile) {?>
    <span class="external_link" onclick="window.open('<?=fullbase()."/".pagename()?>/mobile'+document.location.search+'&__anchor='+escape(document.location.hash.substr(1)));">Mobile Content</span><br/>
<?}?>

<?if($this->has_subscribe_xml) {?>
    <span class="external_link" onclick="window.open('<?=fullbase()."/".pagename()?>/xml'+(document.location.search));">XML</span><br/>
<?}?>

<?if($this->has_subscribe_csv) {?>
    <span class="external_link" onclick="alert('CSV data should not be used programmatically. \nThe number of column and order depends on data it contains.'); window.open('<?=fullbase()."/".pagename()?>/csv'+(document.location.search));">CSV</span><br/>
<?}?>

    <br/>

    <div class="tinyurl" id="tinyurl_area" onclick="create_tinyurl();"><span class="button">Create TinuURL</span></div>
</div>

<script type="text/javascript">
function create_tinyurl() {
    $("#tinyurl_area").load("<?=fullbase()."/proxy/tinyurl?url=";?>"+escape(document.location), function() {
        $("#tinyurl_area input").select();
    });
}
</script>
