<?echo "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n";?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" 
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" 
  xmlns:widget="http://www.netvibes.com/ns/">
  <head>
 
    <meta name="author" content="OSG GOC" />
    <meta name="description" content="A descriptive description" />
 
    <meta name="apiVersion" content="1.0" />
    <meta name="autoRefresh" content="60" />
    <meta name="debugMode" content="true" />
 
    <link rel="stylesheet" type="text/css" href="http://www.netvibes.com/themes/uwa/style.css" />
    <script type="text/javascript" src="http://www.netvibes.com/js/UWA/load.js.php?env=Standalone"></script>
 
    <title><?=$this->page_title?></title>
    <link rel="icon" type="image/png" 
      href="http://www.example.com/favicon.ico" />
 
<!-- Add your UWA preferences as needed -->
    <widget:preferences>
    </widget:preferences>

<style type="text/css">
<?
echo file_get_contents(fullbase()."/css/myosg.css.php?uwa");
?>
</style>
 
    <script type="text/javascript">
var CurrentStatusWidget = {};
CurrentStatusWidget.yourVariable = "My value";
CurrentStatusWidget.dataInit = function() {
    UWA.Data.getText(
        '<?=fullbase()?>/<?=pagename()?>/html?uwa=true&<?=$_SERVER["QUERY_STRING"]?>',
        CurrentStatusWidget.dataProcessor
    );
}
CurrentStatusWidget.dataProcessor = function(text)
{
    widget.setBody(text);
}

widget.onLoad = function() {
    CurrentStatusWidget.dataInit();
}
// you can move your start up code to your own method:
// simply use widget.onLoad = myObject.myStartupMethod;
</script>
  </head>
  <body>
    <p>Loading...</p>
  </body>
</html>
