<?
echo "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n";?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" 
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" 
  xmlns:widget="http://www.netvibes.com/ns/">
  <head>

    <meta name="author" content="OSG GOC" />
    <meta name="description" content="A descriptive description" />

    <meta name="apiVersion" content="1.0" />
    <meta name="autoRefresh" content="60" />
    <meta name="debugMode" content="false" />

    <script type="text/javascript" src="http://www.netvibes.com/js/UWA/load.js.php?env=Standalone"></script>

    <title><?=$this->page_title?></title>
    <link rel="icon" type="image/png" href="<?=fullbase()?>/images/myosg_favi.ico" />

<style type="text/css">
<?include("css/mobile.css.php");?>
</style>

<script type="text/javascript">
function display(text)
{
    widget.setBody(text);
}
widget.onLoad = function() {
    UWA.Data.getText( '<?=fullbase()?>/<?=pagename()?>/html?uwa=true&<?=$_SERVER["QUERY_STRING"]?>', display);
}
// you can move your start up code to your own method:
// simply use widget.onLoad = myObject.myStartupMethod;
</script>
  </head>
  <body>
    <p>Loading...</p>
  </body>
</html>
