<style>
#primaryContent h3 {
border-bottom: none;
}
.contact_info {
margin-right: 200px;
}
#result_table td,
#result_table th {
vertical-align: top;
}
.entry .title {
font-size: 14px;
font-weight: bold;
margin-bottom: 5px;
/*color: #D98719;*/
}
.entry a {
text-decoration: underline;
}
.entry .table {
margin-bottom: inherit;
}
.entry .table th {
width: 150px;
}
</style>
<h2>Search Result</h2>
<div id="result">
<?
if(count($this->recs) == 0) {
    echo "<p>No matching result.</p>";
} else {
    echo "<table id=\"result_table\">";
    foreach($this->recs as $rec) {
        switch($rec->type) {
        case "resource": show_resource($rec);break;
        case "resource_group": show_resourcegroup($rec);break;
        case "sc": show_sc($rec);break;
        case "vo": show_vo($rec);break;
        case "facility": show_facility($rec);break;
        case "site": show_site($rec);break;
        case "contact": show_contact($rec);break;
        case "gocticket": show_gocticket($rec);break;
        default:
            elog("unknown search record type ".$rec->type);
        }
    }
    echo "</table>";
}

//search OSG link
echo "<br><p><a class=\"btn\" href=\"http://www.google.com/cse?cx=016752695275174109936:697frha0tfi&q=".urlencode($this->query)."\">Search Entire OSG</a></p>";

//NOTE -- there is also show_contact() function
function show_contacts($contacts) {
    $shown_names = array();//used to group names for guest access
    foreach($contacts as $contact) {
        if(user()->isGuest()) {
            //TODO -- need to group by name since user only see a list of names
            if(!in_array($contact->name, $shown_names)) {
                echo htmlsafe($contact->name)."<br/>";
                $shown_names[] = $contact->name;
            }
        } else {
            echo "<div class=\"contact_info\">";
            echo "<b>".htmlsafe($contact->name)."</b>";
            echo "<table class=\"table\">"; 
            echo "<tr><th>Email</th><td>".emailaddress($contact->primary_email)."</td></tr>";
            echo "<tr><th>Phone</th><td>".htmlsafe($contact->primary_phone)."</td></tr>";
            echo "<tr><th>DN</th><td>".htmlsafe($contact->dn)."</td></tr>";
            if($contact->sms_address != null) {
                echo "<tr><th>SMS Address</th><td>".htmlsafe($contact->sms_address)."</td></tr>";
            }
            echo "</table>";
            echo "</div>";
        }
    }
}

function show_resource($rec) {
    echo "<tr class=\"entry\">";
    echo "<td><span class=\"tag resource\">Resource</span></td>";
    echo "<td>";
    echo "<div class=\"title\">".$rec->v1." <code>".$rec->fqdn."</code></div>";
    echo "<p class=\"desc\">".$rec->description."</p>";
    foreach($rec->contacts as $type_name=>$contacts) {
        echo "<h4 class=\"muted\">$type_name</h4>";
        show_contacts($contacts);
    }
    echo "<a href=\"".fullbase()."/rgsummary/index?datasource=summary&summary_attrs_showdesc=on&summary_attrs_showgipstatus=on&summary_attrs_showhierarchy=on&summary_attrs_showwlcg=on&summary_attrs_showservice=on&summary_attrs_showrsvstatus=on&summary_attrs_showfqdn=on&summary_attrs_showvomembership=on&summary_attrs_showvoownership=on&summary_attrs_showenv=on&summary_attrs_showcontact=on&summary_attrs_showticket=on&gip_status_attrs_showtestresults=on&downtime_attrs_showpast=&account_type=cumulative_hours&ce_account_type=gip_vo&se_account_type=vo_transfer_volume&bdiitree_type=total_jobs&start_type=7daysago&start_date=02%2F11%2F2011&end_type=now&end_date=02%2F11%2F2011&facility_10009=on&rg=on&rg_".$rec->resource_group_id."=on&gridtype_1=on&service_1=on&service_5=on&service_2=on&service_3=on&service_central_value=0&service_hidden_value=0&active_value=1&disable_value=1/\">Resource Group Summary</a>";
    echo "<a href=\"".fullbase()."/rgcurrentstatus/index?datasource=currentstatus&summary_attrs_showdesc=on&summary_attrs_showgipstatus=on&summary_attrs_showhierarchy=on&summary_attrs_showwlcg=on&summary_attrs_showservice=on&summary_attrs_showrsvstatus=on&summary_attrs_showfqdn=on&summary_attrs_showvomembership=on&summary_attrs_showvoownership=on&summary_attrs_showenv=on&summary_attrs_showcontact=on&summary_attrs_showticket=on&gip_status_attrs_showtestresults=on&downtime_attrs_showpast=&account_type=cumulative_hours&ce_account_type=gip_vo&se_account_type=vo_transfer_volume&bdiitree_type=total_jobs&start_type=7daysago&start_date=02%2F11%2F2011&end_type=now&end_date=02%2F11%2F2011&facility_10009=on&rg=on&rg_".$rec->resource_group_id."=on&gridtype_1=on&service_1=on&service_5=on&service_2=on&service_3=on&service_central_value=0&service_hidden_value=0&active_value=1&disable_value=1/\">Current RSV Status</a>";
    echo "<a href=\"https://oim.grid.iu.edu/oim/resourceedit?id=".$rec->id."\">Edit OIM Detail</a>"; 
    echo "<a href=\"https://ticket.grid.iu.edu/goc/resource?resource_id=".$rec->id."\">Submit Ticket</a>"; 
    echo "<a href=\"".$rec->url."\">".$rec->url."</a>"; 
    echo "</td></tr>";
}

function show_resourcegroup($rec) {
    echo "<tr class=\"entry\">";
    echo "<td><span class=\"tag resource_group\">Resource&nbsp;Group</span></td>";
    echo "<td>";
    echo "<div class=\"title\">".$rec->v1."</div>";
    echo "<p class=\"desc\">".$rec->description."</p>";
    echo "<a href=\"".fullbase()."/rgsummary/index?datasource=summary&summary_attrs_showdesc=on&summary_attrs_showgipstatus=on&summary_attrs_showhierarchy=on&summary_attrs_showwlcg=on&summary_attrs_showservice=on&summary_attrs_showrsvstatus=on&summary_attrs_showfqdn=on&summary_attrs_showvomembership=on&summary_attrs_showvoownership=on&summary_attrs_showenv=on&summary_attrs_showcontact=on&summary_attrs_showticket=on&gip_status_attrs_showtestresults=on&downtime_attrs_showpast=&account_type=cumulative_hours&ce_account_type=gip_vo&se_account_type=vo_transfer_volume&bdiitree_type=total_jobs&start_type=7daysago&start_date=02%2F11%2F2011&end_type=now&end_date=02%2F11%2F2011&facility_10009=on&rg=on&rg_".$rec->id."=on&gridtype_1=on&service_1=on&service_5=on&service_2=on&service_3=on&service_central_value=0&service_hidden_value=0&active_value=1&disable_value=1/\">Resource Group Summary</a>";
    echo "<a href=\"".fullbase()."/rgcurrentstatus/index?datasource=currentstatus&summary_attrs_showdesc=on&summary_attrs_showgipstatus=on&summary_attrs_showhierarchy=on&summary_attrs_showwlcg=on&summary_attrs_showservice=on&summary_attrs_showrsvstatus=on&summary_attrs_showfqdn=on&summary_attrs_showvomembership=on&summary_attrs_showvoownership=on&summary_attrs_showenv=on&summary_attrs_showcontact=on&summary_attrs_showticket=on&gip_status_attrs_showtestresults=on&downtime_attrs_showpast=&account_type=cumulative_hours&ce_account_type=gip_vo&se_account_type=vo_transfer_volume&bdiitree_type=total_jobs&start_type=7daysago&start_date=02%2F11%2F2011&end_type=now&end_date=02%2F11%2F2011&facility_10009=on&rg=on&rg_".$rec->id."=on&gridtype_1=on&service_1=on&service_5=on&service_2=on&service_3=on&service_central_value=0&service_hidden_value=0&active_value=1&disable_value=1/\">Current RSV Status</a>";
    echo "<a href=\"https://oim.grid.iu.edu/oim/resourcegroupedit?id=".$rec->id."\">Edit Detail</a>"; 
    echo "</td></tr>";
}
function show_sc($rec) {
    echo "<tr class=\"entry\">";
    echo "<td><span class=\"tag sc\">Support&nbsp;Center</span></td>";
    echo "<td>";
    echo "<div class=\"title\">".$rec->v1."</div>";
    echo "<p class=\"desc\">".$rec->description."</p>";
    echo "<p><span class=\"header\">Long Name</span>".$rec->long_name."</p>";
    echo "<p><span class=\"header\">Community</span>".$rec->community."</p>";
    foreach($rec->contacts as $type_name=>$contacts) {
        echo "<h4 class=\"muted\">$type_name</h4>";
        show_contacts($contacts);
        /*
        foreach($contacts as $contact) {
            if(user()->isGuest()) {
                echo htmlsafe($contact->name)."<br/>";
            } else {
                echo "<div class=\"contact_info\">";
                echo "<b>".htmlsafe($contact->name)."</b>";
                echo "<table class=\"table\">"; 
                echo "<tr><th>Email</th><td>".emailaddress($contact->primary_email)."</td></tr>";
                echo "<tr><th>Phone</th><td>".htmlsafe($contact->primary_phone)."</td></tr>";
                echo "<tr><th>DN</th><td>".htmlsafe($contact->dn)."</td></tr>";
                if($contact->sms_address != null) {
                    echo "<tr><th>SMS Address</th><td>".htmlsafe($contact->sms_address)."</td></tr>";
                }
                echo "</table>";
                echo "</div>";
            }
        }
        */
    }
    echo "<a href=\"".fullbase()."/scsummary/index?datasource=summary&summary_attrs_showdesc=on&summary_attrs_showcontact=on&summary_attrs_showsites=on&sc=on&sc_".$rec->id."=on&active_value=1\">Show Detail</a>";
    if(user()->hasRole("admin")) {
        echo "<a href=\"https://oim.grid.iu.edu/oim/scedit?id=".$rec->id."\">Edit Detail (Admin)</a>"; 
    }
    echo "</td></tr>";
}
function show_vo($rec) {
    echo "<tr class=\"entry\">";
    echo "<td><span class=\"tag vo\">VO</span></td>";
    echo "<td>";
    echo "<div class=\"title\">".$rec->v1."</div>";
    if($rec->v1 != $rec->description) {
        echo "<p class=\"desc\">".$rec->description."</p>";
    }
    echo "<p><span class=\"header\">Long Name</span>".$rec->long_name."</p>";
    foreach($rec->contacts as $type_name=>$contacts) {
        echo "<h4 class=\"muted\">$type_name</h4>";
        show_contacts($contacts);
        /*
        foreach($contacts as $contact) {
            if(user()->isGuest()) {
                echo htmlsafe($contact->name)."<br/>";
            } else {
                echo "<div class=\"contact_info\">";
                echo "<b>".htmlsafe($contact->name)."</b>";
                echo "<table class=\"table\">"; 
                echo "<tr><th>Email</th><td>".emailaddress($contact->primary_email)."</td></tr>";
                echo "<tr><th>Phone</th><td>".htmlsafe($contact->primary_phone)."</td></tr>";
                if($contact->sms_address != null) {
                    echo "<tr><th>SMS Address</th><td>".htmlsafe($contact->sms_address)."</td></tr>";
                }
                echo "</table>";
                echo "</div>";
            }
        }
        */
    }
    echo "<a href=\"".fullbase()."/vosummary/index?datasource=summary&summary_attrs_showdesc=on&summary_attrs_showmember_resource=on&summary_attrs_showfield_of_science=on&summary_attrs_showreporting_group=on&summary_attrs_showparent_vo=on&summary_attrs_showcontact=on&start_type=7daysago&start_date=02%2F11%2F2011&end_type=now&end_date=02%2F11%2F2011&vo=on&vo_".$rec->id."=on&active=on&active_value=1&sort_key=name\">Show Summary</a>";
    echo "<a href=\"".$rec->primary_url."\">".$rec->primary_url."</a>";
    if(user()->hasRole("admin")) {
        echo "<a href=\"https://oim.grid.iu.edu/oim/voedit?id=".$rec->id."\">Edit Detail (Admin)</a>"; 
    }
    echo "</td></tr>";
}
function show_facility($rec) {
    echo "<tr class=\"entry\">";
    echo "<td><span class=\"tag facility\">Facility</span></td>";
    echo "<td>";
    echo "<div class=\"title\">".$rec->v1."</div>";
    if(isset($rec->description)) {
        echo "<p class=\"desc\">".$rec->description."</p>";
    }
    echo "<a href=\"https://oim.grid.iu.edu/oim/facilityedit?facility_id=".$rec->id."\">Edit Detail</a>";
    echo "</td></tr>";
}
function show_site($rec) {
    echo "<tr class=\"entry\">";
    echo "<td><span class=\"tag site\">Site</span></td>";
    echo "<td>";
    echo "<div class=\"title\">".$rec->v1."</div>";
    if(isset($rec->description)) {
        echo "<p class=\"desc\">".$rec->description."</p>";
    }
    echo "<p><span class=\"header\">Location</span>".$rec->city.", ".$rec->state." ".$rec->country."</p>";
    echo "<a href=\"https://oim.grid.iu.edu/oim/siteedit?site_id=".$rec->id."\">Edit Detail</a>";
    echo "</td></tr>";
}
function show_contact($rec) {
    $contact = $rec;

    echo "<tr class=\"entry\">";
    echo "<td><span class=\"tag contact\">Contact</span></td>";
    echo "<td>";
    echo "<div class=\"title\">".$rec->v1."</div>";
    if(trim($contact->photo_url) != "") {
        echo "<img class=\"avatar\" src=\"$contact->photo_url\" style=\"float: right;\">";
    }
/*
        //show gravatar
        $url = "http://www.gravatar.com/avatar/".md5($contact->primary_email);
        echo "<img class=\"avatar\" src=\"$url\"/>";
*/


    echo "<div class=\"contact_info\">";
    echo "<table class=\"table\">"; 

    //show public profile info
    if(trim($contact->profile) != "") {
        echo "<tr><th>Profile</th>";
        echo "<td>".htmlsafe($contact->profile)."</td></tr>";
    }
    if(trim($contact->contact_preference) != "") {
        echo "<tr><th>Contact Preference</th>";
        echo "<td><p class=\"contact_preference\">".htmlsafe($contact->contact_preference)."</td></tr>";
    }

    //show personal profile info
    if(!user()->isGuest()) {
        echo "<tr><th>Email</th><td>".emailaddress($contact->primary_email)."<br>".formatEmail($contact->secondary_email)."</td></tr>";
        echo "<tr><th>Phone</th><td>".htmlsafe($contact->primary_phone)."</td></tr>";
        //echo "<tr><th>DN</th><td>".htmlsafe($contact->dn)."</td></tr>";
        if($contact->sms_address != null) {
            echo "<tr><th>SMS Address</th><td>".htmlsafe($contact->sms_address)."</td></tr>";
        }
        if($contact->im != null) {
            echo "<tr><th>IM</th><td>".htmlsafe($contact->im)."</td></tr>";
        }
    }
    echo "</table>";
    echo "</div>";//end contact info

    if(user()->getPersonID() == $rec->id) {
        echo "<p><a href=\"https://oim.grid.iu.edu/oim/profileedit\">Edit My Profile</a></p>";
    } else {
        if(user()->hasRole("admin") || user()->hasRole("admin_contacts")) {
            echo "<a href=\"https://oim.grid.iu.edu/oim/contactedit?id=".$rec->id."\">Edit Detail (Admin)</a>"; 
        }
    }
    echo "</td></tr>";
}
function show_gocticket($rec) {
    echo "<tr class=\"entry\">";
    echo "<td><span class=\"tag gocticket\">GOC Ticket</span></td>";
    echo "<td>";
    echo "<div class=\"title\"><a href=\"".config()->gocticket_url."/".$rec->ID."\">".$rec->ID.": ".$rec->Title."</a></div>";
    if(isset($rec->Metadatas)) {
        echo "<table class=\"table\">"; 
        foreach($rec->Metadatas->Metadata as $metadata) {
            echo "<tr><th>".htmlsafe($metadata->Key)."</th><td>".htmlsafe($metadata->Value)."</td></tr>";
        }
        echo "</table>";
    }
    echo "</td></tr>";
}
function formatEmail($email) {
    if(trim($email) == "") return "";
    $out = "<img align=\"top\" src=\"".fullbase()."/images/email.png\"/> <a href=\"mailto: $email\">".htmlsafe($email)."</a><br>";
    return $out;
}

function formatPhone($phone, $ext) {
    if(trim($phone) == "") return "";
    $out = "<img align=\"top\" src=\"".fullbase()."/images/telephone.png\"/> ".htmlsafe($phone)." ";
    if(trim($ext) != "") {
        $out .= "(ext. ".htmlsafe($ext).")";
    }
    $out .= "<br>";
    return $out;
}


?>
</div>


