<?

foreach($this->vos as $vo_id=>$vo) {
    $name = htmlentities($vo->name);
    $ex_class = "";
    if($vo->disable == 1) {
        $name .= " (Removed)";
        $ex_class = "disabled";
    }
    if($vo->active == 0) {
        $name .= " (Inactive)";
    }

    echo "<div class=\"border $ex_class\">";
    echo "<span class=\"h3\">".$name."</span>";

    if(isset($_REQUEST["summary_attrs_showdesc"])) {
        echo "<br/>";
        echo htmlentities($vo->description);
    }

    echo "<table class='summary_table'>";
    echo "<tr><th>Long Name</th><td>".htmlentities($vo->long_name)."</td></tr>";
    echo "<tr><th>Primary URL</th><td>".htmlentities($vo->primary_url)."</td></tr>";
    echo "<tr><th>Membership Services URL</th><td>".htmlentities($vo->membership_services_url)."</td></tr>";
    echo "<tr><th>Purpose URL</th><td>".htmlentities($vo->purpose_url)."</td></tr>";
    echo "<tr><th>Support URL</th><td>".htmlentities($vo->support_url)."</td></tr>";
    echo "<tr><th>App Description</th><td>".htmlentities($vo->app_description)."</td></tr>";
    echo "<tr><th>Community</th><td>".htmlentities($vo->community)."</td></tr>";

    $scid = $vo->sc->id;
    echo "<tr><th>Support Center</th><td><a href=\"".fullbase()."/scsummary/index?datasource=summary&sc=on&sc_$scid=on\">".htmlentities($vo->sc->name)."</a></td></tr>";

    if(isset($_REQUEST["summary_attrs_showmember_resource"])) {
        echo "<tr><th>Member Resources</th><td>";
        $resource_ownerships = $this->resource_ownerships[$vo_id];
        foreach($resource_ownerships as $resource_ownership) {
            $rid = $resource_ownership->id;
            echo "<a href=\"".fullbase()."/wizardsummary?datasource=summary&r=on&r_$rid&summary_attrs_showdesc=on&summary_attrs_showservice=on&summary_attrs_showrsvstatus=on\">".htmlentities($resource_ownership->name)."</a> ";
        }
        echo "</td></tr>";
    }

    echo "</table>";
    echo "</div>";
}
