<style>
span[onclick].label{
color: white;
}
table th {
width: 180px;
}
.table,
pre {
margin-bottom: 0;
}
</style>
<?
function resource_ownership_cmp($a, $b) {
    if($a->name == $b->name) {
        return 0;
    } 
    return ($a->name < $b->name) ? -1 : 1;
}

foreach($this->vos as $vo_id=>$vo) {
    $name = htmlsafe($vo->header);

    $ex_class = "";
    if($vo->disable == 1) {
        $name .= " (Removed)";
        $ex_class = "disabled";
    }
    if($vo->active == 0) {
        $name .= " (Inactive)";
    }

    echo "<div class=\"group_header\">";
    echo "<span class=\"h3\">$name</span>";
    echo "</div>";
    if(isset($_REQUEST["summary_attrs_showdesc"])) {
        echo htmlsafe($vo->description);
    }
    echo "<table class=\"table table-bordered $ex_class\">";
    echo "<tr><th>Name / Long Name</th><td>".htmlsafe($vo->name)." / ".htmlsafe($vo->long_name)."</td></tr>";

    //cert only flag
    echo "<tr><th>Certificate Only</th>";
    if($vo->cert_only == 1) {
        echo "<td colspan=\"2\">True</td>";
    } else {
        echo "<td colspan=\"2\">False</td>";
    }
    echo "</tr>";

    echo "<tr><th>Primary URL</th><td>".externalurl($vo->primary_url)."</td></tr>";
    echo "<tr><th>Membership Services URL</th><td>".externalurl($vo->membership_services_url)."</td></tr>";
    echo "<tr><th>Purpose URL</th><td>".externalurl($vo->purpose_url)."</td></tr>";
    echo "<tr><th>Support URL</th><td>".externalurl($vo->support_url)."</td></tr>";
    echo "<tr><th>App Description</th><td>".htmlsafe($vo->app_description)."</td></tr>";
    echo "<tr><th>Community</th><td>".htmlsafe($vo->community)."</td></tr>";

    if(isset($_REQUEST["summary_attrs_showparent_vo"])) {
        echo "<tr><th>Parent VO</th><td>";
        if(isset($this->vovo[$vo_id]) && $this->vovo[$vo_id] == "") {
            $parent_vo_id = $this->vovo[$vo_id][0]->parent_vo_id;
            $parent_vo = $this->vos[$parent_vo_id];
            echo "<a href=\"".
                fullbase().
                "/vosummary?datasource=summary&summary_attrs_showparent_vo=on&vo=on&vo_".
                $parent_vo_id.
                "=on&active_value=1\">".htmlsafe($parent_vo->name)."</a> ";
        } else {
            echo "<span class=\"muted\">No Parent VO</span>";
        }
        echo "</td></tr>";
    }

    $scid = $vo->sc->id;
    echo "<tr><th>Support Center</th><td><a href=\"".fullbase()."/scsummary/index?datasource=summary&sc=on&sc_$scid=on\">".htmlsafe($vo->sc->name)."</a></td></tr>";

    if(isset($_REQUEST["summary_attrs_showmember_resource"])) {
        echo "<tr><th>Member Resources</th><td>";
        $resource_ownerships = $this->resource_ownerships[$vo_id];
        usort($resource_ownerships, "resource_ownership_cmp");
        if(count($resource_ownerships) != 0) {
            echo "<table class=\"table table-bordered table-condensed\">";
            foreach($resource_ownerships as $resource_ownership) {
                $rid = $resource_ownership->id;
                echo "<tr>";
                echo "<th>$resource_ownership->name</th><td><code>$resource_ownership->fqdn</code></td>";
                echo "</tr>";
            }
            echo "</table>";
        } else {
            echo "<span class=\"muted\">No member resources</span>";
        }
        echo "</td></tr>";
    }

    if(isset($_REQUEST["summary_attrs_showfield_of_science"])) {
        echo "<tr><th>Field Of Science</th><td>";
        $ranks = $this->field_of_science[$vo_id];
        foreach($ranks as $rank_id=>$fss) {
            switch($rank_id) {
            case 1: $rank = "primary";break;
            case 2: $rank = "secondary";break;
            case 3: $rank = "tertiary";break;
            default: echo "unknown rank $rank";
            }
            ksort($fss);
            foreach($fss as $name=>$fs) {
                echo "<div class=\"rank rank-$rank\">".htmlsafe($name)."</div> ";
            }
        }
        echo "</td></tr>";
    }

    if(isset($_REQUEST["summary_attrs_showreporting_group"])) {
        echo "<tr><th>Reporting Groups</th><td>";
        $reports = $this->reports[$vo_id];
        foreach($reports as $report) {
            echo "<div class=\"group_header\">".htmlsafe($report->name)."</div>";
            echo "<table class=\"table table-bordered\">";

            echo "<tr><th>FQANs</th><td>";
            if($report->fqans !== null) {
                echo "<table class=\"table table-bordered table-striped\">";
                echo "<tr><th>Group Name</th><th>Role</th></tr>";
                foreach($report->fqans as $fqan) {
                    echo "<tr><td>".htmlsafe($fqan->group_name)."</td><td>".htmlsafe($fqan->role)."</td></tr>";
                }
                echo "</table>";
            }
            echo "</td></tr>";

            echo "<tr><th>Report Contacts</th><td>";
            if($report->contacts !== null) {
                $group = array();//used to group same contact with different dn together
                foreach($report->contacts as $contact) {
                    if(!isset($group[$contact->id])) {
                        $group[$contact->id] = 1;
                        switch($contact->contact_rank_id) {
                        case 1: $rank = "primary";break;
                        case 2: $rank = "secondary";break;
                        case 3: $rank = "tertiary";break;
                        default: echo "unknown rank $rank";
                        }
                        echo "<div class=\"rank rank-$rank\">";
                        if(user()->isGuest()) {
                            echo htmlsafe($contact->name)."<br/>";
                        } else {
                            echo "<a href=\"mailto:".htmlsafe($contact->primary_email)."\">".htmlsafe($contact->name)."</a><br>";
                            echo "Telephone: ".htmlsafe($contact->primary_phone)."<br>";
                            //echo "<tr><th>DN</th><td>".htmlsafe($contact->dn)."</td></tr>";
                            if($contact->sms_address != null) {
                                echo "SMS Address: ".htmlsafe($contact->sms_address)."<br>";
                            }
                        }
                        echo "</div>";
                    } else {
                            $group[$contact->id]++;//just count number of records for this person (not used right now..)
                    }
                }
            } else {
                echo "<span class=\"muted\">No report contacts</span>";
            }
            echo "</td></tr>";
            echo "</table>";
        }
        echo "</td></tr>";
    }

    if(isset($_REQUEST["summary_attrs_showcontact"])) {
        echo "<tr><th>Contacts</th><td>";
        if(isset($this->contacts[$vo_id])) {
            $contact_types = $this->contacts[$vo_id];
            echo "<table class=\"table table-bordered table-striped\">";
            foreach($contact_types as $type_name=>$contacts) {
                echo "<tr><th>$type_name</th><td>";
                $group = array();
                foreach($contacts as $contact) {
                    if(!isset($group[$contact->id])) {
                        $group[$contact->id] = 1;
                        switch($contact->contact_rank_id) {
                        case 1: $rank = "primary";break;
                        case 2: $rank = "secondary";break;
                        case 3: $rank = "tertiary";break;
                        default: echo "unknown rank $rank";
                        }
                        echo "<div class=\"rank rank-$rank\">";
                        if(user()->isGuest()) {
                            echo htmlsafe($contact->name)."<br>";
                        } else {
                            echo "<a href=\"mailto:".htmlsafe($contact->primary_email)."\">".htmlsafe($contact->name)."</a> ";
                            echo "<span class=\"muted\">".htmlsafe($contact->primary_phone)."</span><br>";
                            //echo "<tr><th>DN</th><td>".htmlsafe($contact->dn)."</td></tr>";
                            if($contact->sms_address != null) {
                                echo "SMS Address: ".htmlsafe($contact->sms_address)."<br>";
                            }
                        }
                        echo "</div>";
                    } else {
                        $group[$contact->id]++;//just count number of records for this person (not used right now..)
                    }
                }
                echo "</td></tr>";
            }
            echo "</table>";
        }
        echo "</td></tr>";
    }

    if(isset($_REQUEST["summary_attrs_showoasis"])) {
        echo "<tr><th>Oasis Managers</th><td>";
        echo "<table class=\"table table-bordered table-striped\">";

        //use oasis flag
        echo "<tr><th>Use Oasis</th>";
        if($vo->use_oasis == 1) {
            echo "<td colspan=\"2\">True</td>";
        } else {
            echo "<td colspan=\"2\">False</td>";
        }
        echo "</tr>";

        //managers
        $oasis_managers = @$this->oasis_managers[$vo_id];
        echo "<tr><th rowspan=\"".(count($oasis_managers)+1)."\">Managers</th>";
        if($oasis_managers !== null) {
            echo "<th>Name</th><th>DNs</th></tr>";
            foreach($oasis_managers as $contact_id=>$manager) {
                echo "<tr>";
                echo "<td>";
                if(user()->isGuest()) {
                    echo htmlsafe($manager["name"])."<br/>";
                } else {
                    echo "<a href=\"mailto:".htmlsafe($manager["primary_email"])."\">".htmlsafe($manager["name"])."</a><br>";
                    echo "Telephone: ".htmlsafe($manager["primary_phone"])."<br>";
                    /*
                    if($contact->sms_address != null) {
                        echo "SMS Address: ".htmlsafe($manager->sms_address)."<br>";
                    }
                    */
                }
                echo "</td>";

                echo "<td><ul>";
                foreach($manager["dns"] as $dn) {
                    echo "<li>".htmlsafe($dn)."</li>";
                }
                echo "</ul></td>";

                echo "</tr>";
            }
        } else {
            echo "<td colspan=\"2\">None</td>";
        }
        echo "</tr>";

        echo "</table>";//end of striped table
        echo "</td></tr>";

        //repo urls
        echo "<tr><th>OASIS Repository URLs</th><td>";
        $repo_urls = $vo->oasis_repo_urls;
        if(count($repo_urls) == 0) {
            echo "<span class=\"muted\">None registered</span>";
        } else {
            echo "<ul>";
            foreach($repo_urls as $url) {
                echo "<li><a target=\"_blank\" href=\"$url\">".htmlsafe($url)."</a></li>";
            }
            echo "</ul>";
        }
        echo "</td></tr>";
    }

    echo "</table>";
}
