<?=$this->header?>
<?
if(user()->isGuest()) {
    echo "<!--";
    echo "NOTE: Email address and phone number of contacts are not displayed only to authorized users who have there DN loaded in their web-browser or wget/curl type web client, and are registered in OIM with appropriate authorization level(s).";
    echo "-->";
}
?>
<VOSummary xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://myosg.grid.iu.edu/schema/vosummary.xsd">
<?
foreach($this->vos as $vo_id=>$vo) {
    echo "<VO>";
    echo "<ID>$vo_id</ID>";
    echo "<Name>".htmlsafe($vo->name)."</Name>";

    echo "<LongName>".htmlsafe($vo->long_name)."</LongName>";

    //cert only flag
    echo "<CertificateOnly>";
    if($vo->cert_only == 1) {
        echo "True";
    } else {
        echo "False";
    }
    echo "</CertificateOnly>";

    echo "<PrimaryURL>".htmlsafe($vo->primary_url)."</PrimaryURL>";
    echo "<MembershipServicesURL>".htmlsafe($vo->membership_services_url)."</MembershipServicesURL>";
    echo "<PurposeURL>".htmlsafe($vo->purpose_url)."</PurposeURL>";
    echo "<SupportURL>".htmlsafe($vo->support_url)."</SupportURL>";
    echo "<AppDescription>".htmlsafe($vo->app_description)."</AppDescription>";
    echo "<Community>".htmlsafe($vo->community)."</Community>";

    if(isset($_REQUEST["summary_attrs_showmember_resource"])) {
        echo "<MemeberResources>";
        $resource_ownerships = $this->resource_ownerships[$vo_id];
        foreach($resource_ownerships as $resource_ownership) {
            $rid = $resource_ownership->id;
            echo "<Resource>";
            echo "<ID>$rid</ID>";
            echo "<Name>".htmlsafe($resource_ownership->name)."</Name>";
            echo "</Resource>";
        }
        echo "</MemeberResources>";
    }
    if(isset($_REQUEST["summary_attrs_showfield_of_science"])) {
        echo "<FieldsOfScience>";
        $ranks = $this->field_of_science[$vo_id];
        foreach($ranks as $rank_id=>$fss) {
            switch($rank_id) {
            case 1: $elem = "Primary";break;
            case 2: $elem = "Secondary";break;
            }
            echo "<${elem}Fields>";
            foreach($fss as $name=>$fs) {
                echo "<Field>".htmlsafe($name)."</Field>";
            }
            echo "</${elem}Fields>";
        }
        echo "</FieldsOfScience>";
    }

    if(isset($_REQUEST["summary_attrs_showparent_vo"])) {
        echo "<ParentVO>";
        if(isset($this->vovo[$vo_id])) {
            $parent_vo_id = $this->vovo[$vo_id][0]->parent_vo_id;
            echo "<ID>$parent_vo_id</ID>";
            $parent_vo = $this->vos[$parent_vo_id];
            echo "<Name>".htmlsafe($parent_vo->name)."</Name>";
        }
        echo "</ParentVO>";
    }

    if(isset($_REQUEST["summary_attrs_showreporting_group"])) {
        echo "<ReportingGroups>";
        $reports = $this->reports[$vo_id];
        foreach($reports as $report) {
            echo "<ReportingGroup>";
            echo "<Name>".htmlsafe($report->name)."</Name>";
            echo "<FQANs>";
            if($report->fqans !== null) {
                foreach($report->fqans as $fqan) {
                    echo "<FQAN>";
                    echo "<GroupName>".$fqan->group_name."</GroupName>";
                    echo "<Role>".$fqan->role."</Role>";
                    echo "</FQAN>";
                }
            }
            echo "</FQANs>";
            echo "<Contacts>";
            if($report->contacts !== null) {
                foreach($report->contacts as $contact) {
                    echo "<Contact>";
                    echo "<Name>".$contact->name."</Name>";
                    if(!user()->isGuest()) {
                        echo "<Email>".htmlsafe($contact->primary_email)."</Email>";
                        echo "<Phone>".htmlsafe($contact->primary_phone)."</Phone>";
                        echo "<SMSAddress>".htmlsafe($contact->sms_address)."</SMSAddress>";
                        echo "<DN>".htmlsafe($contact->dn)."</DN>";
                    }
                    echo "</Contact>";
                }
            }
            echo "</Contacts>";
            echo "</ReportingGroup>";
        }
        echo "</ReportingGroups>";
    }

    if($vo->active == 1) {
        echo "<Active>True</Active>";
    } else {
        echo "<Active>False</Active>";
    }
    if($vo->disable == 1) {
        echo "<Disable>True</Disable>";
    } else {
        echo "<Disable>False</Disable>";
    }

    if(isset($_REQUEST["summary_attrs_showcontact"])) {
        echo "<ContactTypes>";
        if(isset($this->contacts[$vo_id])) {
            $contact_types = $this->contacts[$vo_id];
            foreach($contact_types as $type_name=>$contacts) {
                echo "<ContactType><Type>$type_name</Type>";
                echo "<Contacts>";
                foreach($contacts as $contact) {
                    echo "<Contact>";
                    echo "<Name>".htmlsafe($contact->name)."</Name>";
                    if(!user()->isGuest()) {
                        echo "<Email>".htmlsafe($contact->primary_email)."</Email>";
                        echo "<Phone>".htmlsafe($contact->primary_phone)."</Phone>";
                        echo "<SMSAddress>".htmlsafe($contact->sms_address)."</SMSAddress>";
                        echo "<DN>".htmlsafe($contact->dn)."</DN>";
                    }
                    echo "</Contact>";
                }
                echo "</Contacts>";
                echo "</ContactType>";
            }
        }
        echo "</ContactTypes>";
    }

    if(isset($_REQUEST["summary_attrs_showoasis"])) {
        echo "<OASIS>";

        echo "<UseOASIS>";
        if($vo->use_oasis == 1) {
            echo "True";
        } else {
            echo "False";
        }
        echo "</UseOASIS>";

        echo "<Managers>";
        $oasis_managers = @$this->oasis_managers[$vo_id];
        if($oasis_managers !== null) {
            foreach($oasis_managers as $manager) {
                echo "<Manager>";
                echo "<Name>".htmlsafe($manager->name)."</Name>";
                echo "<DN>".htmlsafe($manager->dn)."</DN>";
                echo "</Manager>";
            }
        }
        echo "</Managers>";
    
        echo "<OASISRepoURLs>";
        if(isset($vo->oasis_repo_urls)) {
                foreach($vo->oasis_repo_urls as $url) {
                    echo "<URL>".htmlsafe($url)."</URL>";
                }
        }
        echo "</OASISRepoURLs>";

        echo "</OASIS>";
    }

    echo "</VO>";
}
?>
</VOSummary>
