<!--
This XML contains the requested support center summary information.

Structure:
    * () shows number of elements. N means there could be any number of them

    VOSummary (1)
         VO (N)
            ID (1)                            VO id in OIM database
            Name (1)                            Name of the resource
            LongName (1)
            PrimaryURL (1)
            MembershipServicesURL (1)
            PurposeURL (1)
            SupportURL (1)
            AppDescription (1)
            Community (1)
            MemberResources (optional)
                Resource (N)
                    ID (1)
                    Name (1)
            ParentVO (optional)              Optional, and shown only if parent vo is set
                ID (1) 
                Name (1)
            FieldsOfScience (optional)
                Field (N)
            ReportingGroups (optional)
                Name (1)
                FQANs (0 or 1)
                    FQAN (N)
                        GroupName (1)
                        Role (1)
                Contacts (0 or 1)
                    Contact (N)
                        Name (1)
                        Email (0 or 1)      * shows only if you access via https with correct DN
                        Phone (0 or 1)      * shows only if you access via https with correct DN
            Active (1)                          Show Active / Inactive Status flag
            Disable (1)                         Show Disable flag
            ContactTypes (1)
                ContactType (N)
                    Type (1)
                    Contacts (1)
                        Contact (N)
                            Name (1)
                            Email (0 or 1)      * shows only if you access via https with correct DN
                            Phone (0 or 1)      * shows only if you access via https with correct DN
<?
if(user()->isGuest()) {
    echo "NOTE: Email address and phone number of contacts are not displayed only to authorized users who have there DN loaded in their web-browser or wget/curl type web client, and are registered in OIM with appropriate authorization level(s).";
}
?>
-->
<VOSummary>
<?
foreach($this->vos as $vo_id=>$vo) {
    echo "<VO>";
    echo "<ID>$vo_id</ID>";
    echo "<Name>".htmlentities($vo->name)."</Name>";

    echo "<LongName>".htmlentities($vo->long_name)."</LongName>";
    echo "<PrimaryURL>".htmlentities($vo->primary_url)."</PrimaryURL>";
    echo "<MembershipServicesURL>".htmlentities($vo->membership_services_url)."</MembershipServicesURL>";
    echo "<PurposeURL>".htmlentities($vo->purpose_url)."</PurposeURL>";
    echo "<SupportURL>".htmlentities($vo->support_url)."</SupportURL>";
    echo "<AppDescription>".htmlentities($vo->app_description)."</AppDescription>";
    echo "<Community>".htmlentities($vo->community)."</Community>";

    if(isset($_REQUEST["summary_attrs_showmember_resource"])) {
        echo "<MemeberResources>";
        $resource_ownerships = $this->resource_ownerships[$vo_id];
        foreach($resource_ownerships as $resource_ownership) {
            $rid = $resource_ownership->id;
            echo "<Resource>";
            echo "<ID>$rid</ID>";
            echo "<Name>".htmlentities($resource_ownership->name)."</Name>";
            echo "</Resource>";
        }
        echo "</MemeberResources>";
    }
    if(isset($_REQUEST["summary_attrs_showfield_of_science"])) {
        echo "<FieldsOfScience>";
        $fss = $this->field_of_science[$vo_id];
        foreach($fss as $fs) {
            echo "<Field>".htmlentities($fs->name)."</Field>";
        }
        echo "</FieldsOfScience>";
    }

    if(isset($_REQUEST["summary_attrs_showparent_vo"])) {
        echo "<ParentVO>";
        if(isset($this->vovo[$vo_id])) {
            $parent_vo_id = $this->vovo[$vo_id][0]->parent_vo_id;
            echo "<ID>$parent_vo_id</ID>";
            $parent_vo = $this->vos[$parent_vo_id];
            echo "<Name>".htmlentities($parent_vo->name)."</Name>";
        }
        echo "</ParentVO>";
    }

    if(isset($_REQUEST["summary_attrs_showreporting_group"])) {
        echo "<ReportingGroups>";
        $reports = $this->reports[$vo_id];
        foreach($reports as $report) {
            echo "<ReportingGroup>";
            echo "<Name>".htmlentities($report->name)."</Name>";
            if($report->fqans !== null) {
                echo "<FQANs>";
                foreach($report->fqans as $fqan) {
                    echo "<FQAN>";
                    echo "<GroupName>".$fqan->group_name."</GroupName>";
                    echo "<Role>".$fqan->role."</Role>";
                    echo "</FQAN>";
                }
                echo "</FQANs>";
            }
            if($report->contacts !== null) {
                echo "<Contacts>";
                foreach($report->contacts as $contact) {
                    echo "<Contact>";
                    echo "<Name>".$contact->name."</Name>";
                    if(!user()->isGuest()) {
                        echo "<Email>".$contact->primary_email."</Email>";
                        echo "<Phone>".$contact->primary_phone."</Phone>";
                    }
                    echo "</Contact>";
                }
                echo "</Contacts>";
            }
            echo "</ReportingGroup>";
        }
        echo "</ReportingGroups>";
    }

    if($vo->active == 1) {
        echo "<Active>True</Active>";
    } else {
        echo "<Active>False</Active>";
    }
    if($vo->disable == 1) {
        echo "<Disable>True</Disable>";
    } else {
        echo "<Disable>False</Disable>";
    }

    if(isset($_REQUEST["summary_attrs_showcontact"])) {
        echo "<ContactTypes>";
        if(isset($this->contacts[$vo_id])) {
            $contact_types = $this->contacts[$vo_id];
            foreach($contact_types as $type_name=>$contacts) {
                echo "<ContactType><Type>$type_name</Type>";
                echo "<Contacts>";
                foreach($contacts as $contact) {
                    echo "<Contact>";
                    echo "<Name>".htmlentities($contact->name)."</Name>";
                    if(!user()->isGuest()) {
                        echo "<Email>".htmlentities($contact->primary_email)."</Email>";
                        echo "<Phone>".htmlentities($contact->primary_phone)."</Phone>";
                    }
                    echo "</Contact>";
                }
                echo "</Contacts>";
                echo "</ContactType>";
            }
        }
        echo "</ContactTypes>";
    }

    echo "</VO>";
}
?>
</VOSummary>
