<?

if(isset($this->downtime)) {
    //this is in downtime..
    echo "<div class=\"status_DOWNTIME\">";
    echo "This resource is currently under maintenance.<br/>";
    echo "<div class=\"downtime\">";
    echo "<b>Maintenance Summary:</b><div>".$this->downtime->downtime_summary."</div>";
    echo "<table width=\"100%\"><tr>";
    $start = date(config()->date_format_full, $this->downtime->unix_start_time);
    $end = date(config()->date_format_full, $this->downtime->unix_end_time);

    echo "<td><b>From:</b><div>$start</div></td>";
    echo "<td><b>To:</b><div>$end</div></td>";
    echo "</tr></table>";
    if($this->detail_service_status !== null) {
        $status = Status::getStatus($this->detail_service_status->status_id);
        echo "<b>Internal Status:</b><div class=\"status_$status\">";
        echo $this->detail_service_status->detail."</div>";
    }
    echo "</div>";
} else {
    //process normal status
    if($this->detail_service_status !== null) {
        $status = Status::getStatus($this->detail_service_status->status_id);
        echo "<div class=\"status_".$status."\">";
        $status_time = $this->detail_service_status->timestamp;
        echo "Status changed to $status at ".date(config()->date_format_full, $status_time)."<br/>";
        echo $this->detail_service_status->detail."<br/>";
        if($this->detail_time != $status_time) {
            echo "(Above reason is applicable at the time when this status change occured.)<br/>";
        }
    } else {
        echo "<div class=\"status_UNKNOWN\">";
        echo "No status change has ever occured for this service.";
    }
}

$title = "<span class=\"h3\">Critical Metrics</span>";
echo outputToggle($title, $title, showmetrics($this->detail_critical_metrics, $this->metric_details, $this->detail_time), true);

$content = showmetrics($this->detail_noncritical_metrics, $this->metric_details, $this->detail_time, true);
if($content != "") {
    $title = "<span class=\"h3\">Non-Critical Metrics</span>";
    echo outputToggle($title, $title, $content);
}
echo "</div>"; //closeing status_XXX div

function showmetrics($metrics, $metric_details, $timestamp, $hide_empty = false) 
{
    $out = "";
    foreach($metrics as $metric) {
        $out .= showmetric($metric, $metric_details, $timestamp, $hide_empty);
    }
    return $out;
}

function showmetric($metric, $metric_details, $timestamp, $hide_empty)
{
    $out = "";

    $metric_id = (int)$metric["metric_id"];
    $metric_detail = $metric_details[$metric_id][0];

    $freshfor = $metric_detail->fresh_for;
    $reported = isset($metric["detail_id"]);
    if(isset($metric["timestamp"])) {
        $expired = !MetricData::isFresh((int)$metric["timestamp"], (int)$freshfor, $timestamp);
        $detail = $metric["detail"]->detail;
        $gathered_at = $metric["detail"]->gathered_at;
        $service_uri = $metric["detail"]->service_uri;
    } else {
        //detail not available..
        $expired = null;
        $detail = "";
        $gathered_at = "N/A";
        $service_uri = "N/A";
    }

    $name = $metric_detail->common_name;
    $desc = $metric_detail->description;
    $help_url = config()->default_rsvforum;
    if(isset(config()->rsvforum[$metric_id])) {
        $help_url = config()->rsvforum[$metric_id];
    }

    if($reported) {
        $css = "";
        if($expired) $css = "expired";
        $out .= "<div class=\"bottom_border status_".$metric["status"]." $css\">";
        $out .= "<div class=\"sidenote\">Reported at ".date(config()->date_format_full, (int)$metric["timestamp"])."</div>";
        if($expired) $name .= " (Expired)";
    } else {
        $out .= "<div class=\"bottom_border status_UNKNOWN notreported\">";
        $name .= " (Not Reported)";
    }

    $out .= "<span class=\"h4\">$name</span>";
    if(!uwa()) {
        $out .= " <a target=\"_help\" href=\"$help_url\"><img src=\"".fullbase()."/images/help.png\" style='align: bottom;'/></a>";
        $out .= "<br/><span class=\"note\">$desc</span>";
        if(trim($detail) != "") {
            $detail = "<pre>$detail</pre>";
            $detail .= "Fresh for: ".humanDuration($freshfor);
            $detail .= "&nbsp;&nbsp;&nbsp;Service URI: ".$service_uri;

            $detail .= "&nbsp;&nbsp;&nbsp;Gathered At: $gathered_at";
            //check if service_uri and gathered_at are on the same domain
            preg_match("/[^\.\/]+\.[^\.\/]+$/", $service_uri, $matches);
            $service_uri_domain = $matches[0];
            preg_match("/[^\.\/]+\.[^\.\/]+$/", $gathered_at, $matches);
            $gathered_at_domain = $matches[0];
            if($service_uri_domain != $gathered_at_domain) {
                $detail .= " <span class=\"warning\">Not on the same domain</span>";
            }

            $detail .= "<br/>";
            $out .= outputToggle("Show Detail", "Hide Detail", $detail);
        }
    }
    $out .= "</div>";
    return $out;
} 


