<style>
#time-tooltip
{
    position: absolute;
    padding-bottom: 8px;
    background: transparent url(<?=fullbase();?>/images/tooltip_arrow.gif) no-repeat 0px 20px;
    opacity: 0.8;
}
.graph
{
    cursor: pointer;
}
#time-tooltip time
{
    font-size: 80%;
    color: white;
    background-color: black;
    padding: 5px;
    border-top-left-radius: 5px 5px;
    border-top-right-radius: 5px 5px;
    border-bottom-right-radius: 5px 5px;
}
.mark
{
    position: absolute;
    width: 30px;
    height: 25px;
    background: transparent url(images/pin.png) no-repeat 0px 0px;
}
.history_graph
{
    line-height: 100%;
}
.history_graph img.graph
{
    width: 100%;
    height: 17px; 
}
.table td,
.table th {
border-top: none;
}
.table tr.graph_row:hover {
background-color: #eee;
}
</style>

<script language='javascript' src='<?=base()?>/lib/jquery-scrollstop/jquery.scrollstop.js'></script>
<script type="text/javascript">
function convertXtoUnixTime(graph, x)
{
    //convert posititon to unixtimestamp
    var start_time = <?=$this->start_time?>;
    var end_time = <?=$this->end_time?>;
    var time_width = end_time - start_time;
    var width = $(graph).width();
    var time = (time_width / width) * x + start_time;
    return parseInt(time);
}
function convertUnixTimeToX(graph, time)
{
    var start_time = <?=$this->start_time?>;
    var end_time = <?=$this->end_time?>;
    var time_width = end_time - start_time;
    var width = $(graph).width();
    var x = (time - start_time)*(width / time_width);
    return x;
}
function mark(rid, sid,time) {
    var graph = $("img[data-sid="+sid+"][data-rid="+rid+"]");
    var pos = graph.position();
    var x = pos.left + convertUnixTimeToX(graph, time)-8;
    var y = pos.top-20;

    var mark = $("#mark");
    mark.css("left", x);
    mark.css("top", y);
    mark.show();
}

$(function() {
    //load currently selected history detail
    currentAnchor = document.location.hash;
    if(currentAnchor)
    {
        var anchor = unescape(currentAnchor.substring(1));
        var splits = anchor.split('&');

        //store current mark info
        rid = splits[0].split('=')[1];
        sid = splits[1].split('=')[1];
        time = splits[2].split('=')[1];

        //load detail content
        $("#history_detail_"+rid+"_"+sid).html("<img src='<?=fullbase()?>/images/loading_animation_small.gif'/> Loading...").load("<?=fullbase()."/".pagename()?>/"+anchor, 
            function() {
                mark(rid,sid,time);
                window.scroll(0, $(this).parent().position().top);
                $("span[rel='tooltip']").tooltip();
                convert_time_to_local(this);
            }
        );
    }

    $(".graph").click(function(event) {
        rid = $(this).data("rid");
        sid = $(this).data("sid");
        var imgpos = $(this).position();
        var x = event.pageX - imgpos.left;
        time = convertXtoUnixTime(this, x);

        //update anchor
        var anchor = "detail?resource_id="+rid+"&service_id="+sid+"&time="+time;
        document.location.hash = anchor;
    
        //hide all previously opened detail (we have only one mark..)
        $(".history_detail").hide();

        //load detail content
        mark(rid, sid, time);
        $("#history_detail_"+rid+"_"+sid)
        .html("<img src='images/loading_animation_small.gif'/> Loading...")
        .load("<?=fullbase()."/".pagename()?>/"+anchor, function() {
            $(this).slideDown();
            $("span[rel='tooltip']").tooltip();
            convert_time_to_local(this);
        });
    });

    $(".graph").mousemove(function(event) {
        var imgpos = $(this).position();
        var x = event.pageX - imgpos.left;
        var y = event.pageY - imgpos.top;

        var tool = $("#time-tooltip");
        tool.css("left", imgpos.left + x);
        tool.css("top", imgpos.top - 28 );

        //convert timestamp to human readable time
        var d = new Date(convertXtoUnixTime(this, x)* 1000);
        $(tool).html("<time>"+d+"</time>");
        tool.show();
    });
    $(".graph").mouseout(function(event) {
        var tool = $("#time-tooltip");
        tool.hide();
    });
    $(window).resize(function() {
        currentAnchor = document.location.hash;
        if(currentAnchor) {
            var anchor = unescape(currentAnchor.substring(1));
            var splits = anchor.split('&');

            //store current mark info
            rid = splits[0].split('=')[1];
            sid = splits[1].split('=')[1];
            time = splits[2].split('=')[1];

            mark(rid,sid,time);
        }
    });

    //Do Lazyloading of the history graph
    //$(window).scroll(function() {
    $(window).on('scrollstop', function(){
        processGraphScroll();
    });
    processGraphScroll(); //initial processing
});

function processGraphScroll() {
    var docViewTop = $(window).scrollTop();
    var docViewBottom = docViewTop + $(window).height();

    $("img.graph").each(function() {
        var jthis = $(this);
        if(jthis.data("url") != "") {
            if(isScrolledIntoView(jthis, docViewTop, docViewBottom)) {
                $(this).attr('src', $(this).data('url'));
                $(this).data("url", "");
            }
        }
    });
}

function isScrolledIntoView(jthis, docViewTop, docViewBottom)
{
    var elemTop = jthis.offset().top;
    var elemBottom = elemTop + 24; //for some reason, height() function is super slow... let's just hardcoded it for now
    return ((elemBottom >= docViewTop) && (elemTop <= docViewBottom));
}

function convert_time_to_local(target) {
    $(target).find("time").each(function() {
        var d = new Date($(this).attr("datetime"));
        //$(this).html(d.toLocaleDateString() + " " + d.toLocaleTimeString());
        $(this).html(d.toString());
    });
}

</script>
<div id="mark" class="hidden mark">&nbsp;</div>
<div id="time-tooltip" class="hidden time-tooltip">
</div>

<h2><?php echo $this->page_title?> 
<small>
Between <?php echo date(config()->date_format, $this->start_time);?> 
and <?php echo date(config()->date_format, $this->end_time)?></span><br>
</small>
</h2>
<?php

foreach($this->rgs as $rgid=>$rg) {

    echo "<div style=\"padding-bottom: 10px;\">"; //parent where position() is called

    //show resource group header
    $resource_group = $this->resource_groups[$rgid][0];
    echo "<div class=\"group_header\">";
    echo "<span class='h3'>".$resource_group->name."</span>";
    echo " <small>".$resource_group->grid_type."</small>";
    echo "</div>";
    //echo $this->ruler;

    echo "<table class=\"table table-rsvhistory\">";
    foreach($rg as $rid=>$resource)
    {
        if(count($this->services[$rid]) == 0) {
            echo "<tr>";
            echo "<th width=\"190px\"><div class=\"resource round\">".$resource->name."</div></th><td colspan=2>(No Service)</td>";
            echo "</tr>";
        } else {
            $first = true;
            foreach($this->services[$rid] as $service) {
                if($first) {
                    echo "<tr class=\"graph_row\"><th width=\"190px\"><div class=\"resource\">".$resource->name."</div></th>";
                    $first = false;
                } else {
                    echo "<tr class=\"graph_row\"><th></th>";//already shown resource name
                }
                echo "<td width=\"130px\">$service->name</td>";
                echo "<td class=\"history_graph\">";
                echo "<img data-sid=\"".$service->service_id."\" data-rid=\"$rid\" class=\"graph\" src=\"images/graph_notloaded.png\" data-url=\"history/graph?resource_id=$rid&amp;&service_id=$service->service_id&amp;start=$this->start_time&amp;end=$this->end_time\"/>";
                echo "</td>";
                echo "</tr>";//close each lines at this point

                //row to store history_detail
                echo "<tr>";
                echo "<td colspan=2></td><td><div class=\"history_detail\" id=\"history_detail_".$rid."_".$service->service_id."\"></div></td>"; 
                echo "</tr>";
            }
        }
    }
    echo "</table>";

    echo "</div>";
}
