<?
foreach($this->resources as $rid=>$record) {
    $resource_name = $record["name"];
    $resource_fqdn = $record["fqdn"];
    $tests = $record["tests"];
    //$interop_bdii = $record["interop_bdii"];
    //$type = $record["type"];
    $rawdata = $record["rawdata"];

    ?>
    <div class="border">
<?
    if(!uwa()) {
        echo "<div style='float: right; background-color: #eee; padding: 5px; width: 220px;'>";

        $raw = "";
        //show raw data link
        $link = $rawdata["cemon_raw_data"][0]->link;
        $age = $rawdata["cemon_raw_data"][0]->age;
        if($link == "") {
            $raw .= "(No Incoming Data)<br/>";
        } else {
            $raw .= "<a target='_blank' href='$link'>Incoming Data (Age $age)</a><br/>";
        }
        //show osg processed link
        $link = $rawdata["processed_osg_data"][0]->link;
        $age = $rawdata["processed_osg_data"][0]->age;
        if($link == "") {
            $raw .= "(No OSG Data)<br/>";
        } else {
            $raw .= "<a target='_blank' href='$link' title='Port - 2170'>Fed to OSG BDII (Age $age)</a><br/>";
        }
        //show wlcg processed link
        $link = $rawdata["processed_wlcg_interop_data"][0]->link;
        $age = $rawdata["processed_wlcg_interop_data"][0]->age;
        if($link == "") {
            $raw .= "(No WLCG Data)<br/>";
        } else {
            $raw .= "<a target='_blank' href='$link' title='Port - 2180'>Fed to Interop BDII (Age $age)</a><br/>";
        }

        echo "<b>LDIF Data</b><br/>$raw";
        echo "</div>";
    }
 
?>
    <div class="resource"><h4><?=$resource_name?></h4></div>
    <div class="indent">
    <?
    if(count($tests) == 0) {
        echo "(No GIP Validation Status is available for this resource)";
    } else {
        foreach($tests as $name=>$test) {

            $gip_status = $test["status"];
            $reason= $test["reason"];

            $status = "UNKNOWN";
            switch($gip_status) {
            case "FAIL":
                $status = "CRITICAL";
                break;
            case "OK":
                $status = "OK";
                break;
            }
            echo outputTestInfo($name, $status, $reason, $rid);
        }
    }
    echo "</div>";//indent
    echo "<div style='clear: both'></div>";
    echo "</div>";//border
}

function outputTestInfo($name, $status, $reason, $rid)
{
    $out = "";
    $out .= "<div class=\"bottom_border status_".$status."\">";

    $out .= "<span class=\"h4\">".$name."</span>";
    if(!uwa()) {
        if($reason != "") {
            $out .= "<br/>$reason";
        }
        if($status == "CRITICAL") {
            $out .= outputAjaxToggle("Issue Detail", base()."/wizardgipstatus/detail?rid=".$rid."&name=".$name);
        } else {
            $out .= "<br/>No issues found for this test.";
        }
    }
    $out .= "</div>";

    return $out;
}

