<?
foreach($this->resources as $rid=>$record) {
    $resource_name = $record["name"];
    $tests = $record["tests"];
    $interop_bdii = $record["interop_bdii"];

    ?>
    <div class="border">
<?
    echo "<div style='float: right; background-color: #eee; padding: 5px; width: 200px;'>";
    
    $raw = "";
    $raw .= "<a target='_blank' href='http://is.grid.iu.edu/data/cemon_raw_incoming/gate01.aglt2.org?which=$resource_name'>Incoming Data</a><br/>";
    $raw .= "<a target='_blank' href='http://is.grid.iu.edu/data/cemon_processed_osg/gate01.aglt2.org.processed?which=$resource_name'>Fed to OSG BDII (port 2170)</a><br/>";
    if($interop_bdii) {
        $raw .= "<a target='_blank' href='http://is.grid.iu.edu/data/cemon_processed_wlcg_interop/gate01.aglt2.org.processed?which=$resource_name'>Fed to Interop BDII (port 2180)</a><br/>";
    }
    echo outputToggle("Raw CEMon Data", "Raw CEMon Data", $raw);
    echo "</div>";
 
?>
    <div class="resource" style="font-size: 13px;"><h4><?=$resource_name?></h4></div>

    <div class="indent">
    <?
   
    if(count($tests) == 0) {
        echo "(No GIP Validation Status is available for this resource)";
    } else {
        foreach($tests as $name=>$test) {

            $gip_status = $test["status"];
            $reason= $test["reason"];

            $status = "UNKNOWN";
            switch($gip_status) {
            case "FAIL":
                $status = "CRITICAL";
                break;
            case "OK":
                $status = "OK";
                break;
            }
            echo outputTestInfo($name, $status, $reason, $rid);
        }
    }
    echo "</div>";//indent
    echo "<div style='clear: both'></div>";
    echo "</div>";//border
}

function outputTestInfo($name, $status, $reason, $rid)
{
    $out = "";
    $out .= "<div class=\"bottom_border status_".$status."\">";

    $out .= "<span class=\"h4\">".$name."</span>";
    if(!isset($_REQUEST["uwa"])) { 
        if($reason != "") {
            $out .= "<br/>$reason";
        }
        $out .= outputAjaxToggle("Detail", base()."/wizardgipstatus/detail?rid=".$rid."&name=".$name);
    }
    $out .= "</div>";

    return $out;
}

