<meta http-equiv="refresh" content="300">
<style>
tr.noborder > th,
tr.noborder > td {
border-top: none;
}
.content a {
text-decoration: underline;
}
.table {
margin-bottom: 0;
}
.table th,
.table td {
padding: 3px;
}
table th {
width: 200px;
}
</style>
<?
echo "<table class=\"table\">";
foreach($this->statuses as $priority=>$statuses) {

    echo "<tr class=\"noborder\"><th colspan=\"3\">";
    echo "<div class=\"group_header\"><span class=\"h3\">$priority Priority Services</span></div>";
    echo "</th></tr>";

    foreach($statuses as $status) {
        echo "<tr>";
        echo "<th>".$status["name"]."</th>";

        if(isset($status["resource_group_id"])) {
            $resource_group_id = $status["resource_group_id"];
            $detail_url = htmlsafe(fullbase()."/rgcurrentstatus/index?datasource=currentstatus&rg=on&rg_$resource_group_id=on&end_type=now&active=on&active_value=1");
            $history_url = htmlsafe(fullbase()."/rgstatushistory/index?datasource=statushistory&start_type=7daysago&end_type=now&rg=on&rg_$resource_group_id=on&active=on&active_value=1");
            echo "<td width=\"120px;\">".showStatus($status["status"])."</td>";
            if(!uwa()) {
                echo "<td><a href=\"$detail_url\">Current Status Detail</a>&nbsp;&nbsp;&nbsp;";
                echo "<a href=\"$history_url\">Status History</a>&nbsp;&nbsp;&nbsp;";
                echo "<a target=\"_blank\" href=\"".$status["url"]."\">SLA</a>";
                echo "</td>";
            } else {
                echo "<td></td>";
            }
        } else {
            //no link..
            echo "<td width=\"120px;\">".showStatus($status["status"])."</td>";
            echo "<td></td>";
        }
        echo "</tr>";
    }
}
echo "</table>";

function showStatus($status) {
    $img = "status_unknown.png";
    if($status == "OK") $img = "status_ok.png";
    if($status == "WARNING") $img = "status_warning.png";
    if($status == "CRITICAL") $img = "status_critical.png";
    if($status == "DOWNTIME") $img = "status_downtime.png";
    return "<img src=\"".fullbase()."/images/$img\" align=\"top\"> <b>$status</b>";
}
