<!--- TODO - don't load script inline...causes browser init issue --->
<link href="<?=base()?>/lib/osgtable/osgtable.css" rel="stylesheet" type="text/css" />
<script src="<?=base()?>/lib/osgtable/osgtable.js" type="text/javascript"></script>
<?
if($this->error !== null) {
    echo "<p class=\"warning\">$this->error</p>";
} else {
    require_once("app/json.php");
    $json = new Services_JSON();
    ?> 
    <div id="osgtable"></div>
    <script> 
    var headers =
    <?
        echo $json->encode($this->headers);
    ?>
    ;
    var recs = [ 
    <?
        $first = true;
        foreach($this->rgs as $rgid=>$rg) {
            $rginfo = $this->resource_groups[$rgid][0];
            if(isset($this->detail_groups[$rgid])) {
                $aggregator = $this->detail_groups[$rgid];
                $recs = $aggregator->records();
                foreach($recs as $id=>$rec) {
                    if($first) {
                        $first = false;
                    } else {
                        echo ",\n";
                    }
                    echo $json->encode($rec);
                }
            } else {
                //output dummy record
                if($first) { $first = false; } else { echo ",\n"; }
                echo "[\"".$rginfo->name."\", \"(no data)\"]";
            }
        }
    ?> 
    ];
    $("#osgtable").osgtable({
        headers: headers,
        recs: recs,
        fetch_detail : function(rec_id, callback) {
            "<?echo fullbase()."/rgbdii/detail";?>"
            $.getJSON("<?echo fullbase()?>/rgbdii/detail?bdii_server=<?echo $_REQUEST["bdii_server"]?>&bdii_object=<?echo $_REQUEST["bdii_object"]?>&rec_id="+encodeURI(rec_id), callback);
        }
    });
    </script> 
    <?
}
