<?

foreach($this->scs as $sc_id=>$sc) {

    $name = $sc->name;
    $ex_class = "";
    if($sc->disable == 1) {
        $name .= " (Removed)";
        $ex_class = "disabled";
    }
    if($sc->active == 0) {
        $name .= " (Inactive)";
    }

    echo "<div class=\"support_center round\">";
    echo "<span class=\"h3\">".htmlsafe($name)."</span>";
    if(isset($_REQUEST["summary_attrs_showdesc"])) {
        echo "<br/>";
        echo htmlsafe($sc->description);
    }
    echo "</div>";

    echo "<table class='summary_table'>";
    echo "<tr><th>Long Name</th><td>".htmlsafe(@$sc->long_name)."</td></tr>";
    echo "<tr><th>Community</th><td>".htmlsafe(@$sc->community)."</td></tr>";

    if(isset($_REQUEST["summary_attrs_showcontact"])) {
        echo "<tr><th>Contacts</th><td>";
        if(isset($this->contacts[$sc_id])) {
            $contact_types = $this->contacts[$sc_id];
            foreach($contact_types as $type_name=>$contacts) {
                echo "<h4>$type_name</h4>";
                foreach($contacts as $contact) {
                    if(user()->isGuest()) {
                        echo htmlsafe($contact->name)."<br/>";
                    } else {
                        echo "<div class=\"contact_info\">";
                        echo "<h3>".htmlsafe($contact->name)."</h3>";
                        echo "<table class=\"summary_subtable\">"; 
                        echo "<tr><th>Email</th><td>".emailaddress($contact->primary_email)."</td></tr>";
                        echo "<tr><th>Phone</th><td>".htmlsafe($contact->primary_phone)."</td></tr>";
                        if($contact->sms_address != null) {
                            echo "<tr><th>SMS Address</th><td>".htmlsafe($contact->sms_address)."</td></tr>";
                        }
                        echo "<tr><th>DN</th><td>".htmlsafe($contact->dn)."</td></tr>";
                        echo "</table>";
                        echo "</div>";
                    }
                }
            }
        }
        echo "</td></tr>";
    }

    if(isset($_REQUEST["summary_attrs_showsites"])) {
        echo "<tr><th>Supported Sites</th><td>";
        if(isset($this->sites[$sc_id])) {
            $sites = $this->sites[$sc_id];
            foreach($sites as $site) {
                $name = str_replace(" ", "&nbsp;", $site->name);
                echo "<span class=\"round tag\" style=\"background-color: gray;\">$name</span> ";
            }
        } else {
            echo "(No sites are supported)";
        }
        echo "</td></tr>";
    }

    echo "</td></tr>";
    echo "</table>";
}
