<style>
span[onclick].label{
color: white;
}
table th {
width: 180px;
}
.table,
pre {
margin-bottom: 0;
}
</style>
<?
foreach($this->scs as $sc_id=>$sc) {
    $name = $sc->name;
    $ex_class = "";
    if($sc->disable == 1) {
        $name .= " (Removed)";
        $ex_class = "disabled";
    }

    echo "<div class=\"group_header\">";
    echo "<span class=\"h3\">".htmlsafe($name)."</span>";
    echo "</div>";
    if(isset($_REQUEST["summary_attrs_showdesc"])) {
        echo htmlsafe($sc->description);
    }

    echo "<table class='table'>";
    echo "<tr><th>Long Name</th><td>".htmlsafe(@$sc->long_name)."</td></tr>";
    echo "<tr><th>Community</th><td>".htmlsafe(@$sc->community)."</td></tr>";

    if(isset($_REQUEST["summary_attrs_showcontact"])) {
        echo "<tr><th>Contacts</th><td>";
        if(isset($this->contacts[$sc_id])) {
            $contact_types = $this->contacts[$sc_id];
            echo "<table class=\"table table-bordered table-striped\">";
            foreach($contact_types as $type_name=>$contacts) {
                echo "<tr><th>$type_name</th><td>";
                $group = array();
                foreach($contacts as $contact) {
                    if(!isset($group[$contact->id])) {
                        $group[$contact->id] = 1;
                        if(user()->isGuest()) {
                            echo htmlsafe($contact->name)."<br/>";
                        } else {
                            echo "<a href=\"mailto:".htmlsafe($contact->primary_email)."\">".htmlsafe($contact->name)."</a><br>";
                            echo "Telephone: ".htmlsafe($contact->primary_phone)."<br>";
                            //echo "<tr><th>DN</th><td>".htmlsafe($contact->dn)."</td></tr>";
                            if($contact->sms_address != null) {
                                echo "SMS Address: ".htmlsafe($contact->sms_address)."<br>";
                            }
                        }
                    } else {
                        $group[$contact->id]++;//just count number of records for this person (not used right now..)
                    }
                }
                echo "</td></tr>";
            }
            echo "</table>";
        }
        echo "</td></tr>";
    }

    if(isset($_REQUEST["summary_attrs_showsites"])) {
        echo "<tr><th>Supported OIM Sites</th><td>";
        if(isset($this->sites[$sc_id])) {
            $sites = $this->sites[$sc_id];
            echo "<ul>";
            foreach($sites as $site) {
                echo "<li>".htmlsafe($site->name)."</li>";
            }
            echo "</ul>";
        } else {
            echo "<span class=\"muted\">No sites supported</span>";
        }
        echo "</td></tr>";
    }

    echo "</td></tr>";
    echo "</table>";
}
