<!--
This XML contains the requested support center summary information.

Structure:
    * () shows number of elements. N means there could be any number of them

    SupportCenterSummary (1)
         SupportCenter (N)
            ID (1)                              Support Center id in OIM database
            Name (1)                            Name of the resource
            LongName (1)
            Community (1)
            PrimaryOperationsContact (optional) Only available if the Support Center has this information 
                Name (1)
                Email (1)
                Phone (1)
            Active (1)                         
            Disable (1)                         Show Disable flag

-->
<SupportCenterSummary>
<?
foreach($this->scs as $sc_id=>$sc) {
    echo "<SupportCenter>";
    echo "<ID>$sc->id</ID>";
    echo "<Name>".htmlentities($sc->name)."</Name>";
    echo "<LongName>".htmlentities($sc->long_name)."</LongName>";
    echo "<Community>".htmlentities($sc->community)."</Community>";

    if(count($sc->contact) > 0) {
        echo "<PrimaryOperationsContact>";
        $contact = $sc->contact[0];
        echo "<Name>".htmlentities($contact->name)."</Name>";
        echo "<Email>".htmlentities($contact->primary_email)."</Email>";
        echo "<Phone>".htmlentities($contact->primary_phone)."</Phone>";
        echo "</PrimaryOperationsContact>";
    }

    if($sc->active == 1) {
        echo "<Active>True</Active>";
    } else {
        echo "<Active>False</Active>";
    }
    if($sc->disable == 1) {
        echo "<Disable>True</Disable>";
    } else {
        echo "<Disable>False</Disable>";
    }
    echo "</SupportCenter>";
}
?>
</SupportCenterSummary>
