<!--
This XML contains the requested support center summary information.

Structure:
    * () shows number of elements. N means there could be any number of them

    SupportCenterSummary (1)
         SupportCenter (N)
            ID (1)                              Support Center id in OIM database
            Name (1)                            Name of the resource
            LongName (1)
            Community (1)
            Active (1)                         
            Disable (1)                         Show Disable flag
            ContactTypes (1)
                ContactType (N)
                    Type (1)
                    Contacts (1)
                        Contact (N)
                            Name (1)
                            Email (0 or 1)      * shows only if you access via https with correct DN
                            Phone (0 or 1)      * shows only if you access via https with correct DN
                            SMSAddress(0 or 1)      * shows only if you access via https with correct DN
<?
if(user()->isGuest()) {
    echo "NOTE: Email address and phone number of contacts are not displayed only to authorized users who have there DN loaded in their web-browser or wget/curl type web client, and are registered in OIM with appropriate authorization level(s).";
}
?>
-->
<SupportCenterSummary>
<?
foreach($this->scs as $sc_id=>$sc) {
    echo "<SupportCenter>";
    echo "<ID>$sc->id</ID>";
    echo "<Name>".htmlentities($sc->name)."</Name>";
    echo "<LongName>".htmlentities($sc->long_name)."</LongName>";
    echo "<Community>".htmlentities($sc->community)."</Community>";

/*
    if(count($sc->contact) > 0) {
        echo "<PrimaryOperationsContact>";
        $contact = $sc->contact[0];
        echo "<Name>".htmlentities($contact->name)."</Name>";
        if(!user()->isGuest()) {
            echo "<Email>".htmlentities($contact->primary_email)."</Email>";
            echo "<Phone>".htmlentities($contact->primary_phone)."</Phone>";
            echo "<SMSAddress>".htmlentities($contact->sms_address)."</SMSAddress>";
        }
        echo "</PrimaryOperationsContact>";
    }
*/
    if($sc->active == 1) {
        echo "<Active>True</Active>";
    } else {
        echo "<Active>False</Active>";
    }
    if($sc->disable == 1) {
        echo "<Disable>True</Disable>";
    } else {
        echo "<Disable>False</Disable>";
    }

    if(isset($_REQUEST["summary_attrs_showcontact"])) {
        echo "<ContactTypes>";
        if(isset($this->contacts[$sc_id])) {
            $contact_types = $this->contacts[$sc_id];
            foreach($contact_types as $type_name=>$contacts) {
                echo "<ContactType><Type>$type_name</Type>";
                echo "<Contacts>";
                foreach($contacts as $contact) {
                    echo "<Contact>";
                    echo "<Name>".htmlentities($contact->name)."</Name>";
                    if(!user()->isGuest()) {
                        echo "<Email>".htmlentities($contact->primary_email)."</Email>";
                        echo "<Phone>".htmlentities($contact->primary_phone)."</Phone>";
                        echo "<SMSAddress>".htmlentities($contact->sms_address)."</SMSAddress>";
                    }
                    echo "</Contact>";
                }
                echo "</Contacts>";
                echo "</ContactType>";
            }
        }
        echo "</ContactTypes>";
    }

    echo "</SupportCenter>";
}
?>
</SupportCenterSummary>
