<?
foreach($this->resource_groups as $rgid=>$record) {
    $testtime = agoCalculation($record["testtime"]);
    $group_name = $record["name"];
    $tests = $record["tests"];
    $overallstatus = $record["overallstatus"];
    $gridtype = $record["gridtype"];
    $resources = $record["resources"];

    switch($overallstatus) {
    case "FAIL":
        $overall = "CRITICAL";
        $overall_detail = "At least one test is failing.";
        break;
    case "OK":
        $overall = "OK";
        $overall_detail = "No issue found for this resource.";
        break;
    case "NA":
        $overall = "UNKNOWN";
        $overall_detail = "GIP validation result is not available for this resource.";
        break;
    default:
        //????
        $overall = "UNKNOWN";
        $overall_detail = "Validation script is returning unknown overall status.";
    }
?>
    <div class="resource_group_header round">
    <?
    if(!uwa()) {
        echo "<div class=\"sidenote\">";
        echo $gridtype. " Group";
        echo "</div>";
    }
    echo "<span class='h3'>".$group_name."</span>";
    ?>
    </div>

    <div class="status_<?=$overall?>">
    <p><?=$overall_detail?></p>
    </div>
    
    <div class="indent">
    <?
    if($testtime !== null) {
        echo "<div>Tests performed $testtime ago</div>";
    }
    if ((count($tests) != 0) and isset($_REQUEST["gip_status_attrs_showtestresults"])) {
        foreach($tests as $name=>$test) {
            $gip_status = $test["status"];
            $reason = $test["reason"];

            $status = "UNKNOWN";
            switch($gip_status) {
            case "FAIL":
              $status = "CRITICAL";
              break;
            case "OK":
              $status = "OK";
              break;
            }
            echo outputTestInfo($name, $status, $reason, $rgid);
        }
    }
    echo "</div>";//indent
    echo "<div style='clear: both'></div>";

    if(isset($_REQUEST["gip_status_attrs_showresource"])) { 
        //show resources
        foreach($resources as $rid=>$resource) {
            echo "<div class=\"resource h4 round\">";
            echo "<div class=\"sidenote\"><span class=\"fqdn\">".$resource->fqdn."</span></div>";
            echo $resource->name."<br/>";
            echo "</div>";

            //resource details
            $details = $this->resource_details[$rid];
            echo "<table class=\"summary_table\">";

            if(isset($_REQUEST["gip_status_attrs_showcemondata"])) { 
                if(!uwa()) {
                    echo "<th>LDIF URLs</th>";
                    echo "<td style='padding: 0px;'>";
                    
                    if(isset($details["cemon_raw_data"])) {
                        echo "<table width='100%'><tr>";

                        //show raw data link
                        $data = $details["cemon_raw_data"];

                        echo "<td width='33%' style='padding: 0; border: none;'>";

                        $link = $data->cemon_raw_data[0]->link;
                        $age = $data->cemon_raw_data[0]->age;
                        if($link == "") {
                            echo "(No Incoming Data)<br/>";
                        } else {
                            echo "<a target='_blank' href='$link'>Incoming Data<br>(Age $age)</a>";
                        }
                        echo "</td><td width='33%' style='padding: 0; border: none;'>";
                        //show osg processed link
                        $link = $data->processed_osg_data[0]->link;
                        $age = $data->processed_osg_data[0]->age;
                        if($link == "") {
                            echo "(No OSG Data)<br/>";
                        } else {
                            echo "<a target='_blank' href='$link' title='Port - 2170'>Fed to OSG BDII<br>(Age $age)</a>";
                        }
                        echo "</td><td style='padding: 0; border: none;'>";
                        //show wlcg processed link
                        $link = $data->processed_wlcg_interop_data[0]->link;
                        $age = $data->processed_wlcg_interop_data[0]->age;
                        if($link == "") {
                            echo "(No WLCG Data)<br/>";
                        } else {
                            echo "<a target='_blank' href='$link' title='Port - 2180'>Fed to Interop BDII<br>(Age $age)</a>";
                        }
                        echo "</td></tr></table>";

                    } else {
                        echo "Raw data not available";
                    }
                    echo "</td>";
                }
            }
            echo "</table>"; //end - resource detail
        }
    }
}

function outputTestInfo($name, $status, $reason, $rid)
{
    $out = "";
    $out .= "<div class=\"bottom_border status_".$status."\">";

    $out .= "<span class=\"h4\">".$name."</span>";
    if(!uwa()) {
        if($reason != "") {
            $out .= "<br/>$reason";
        }
        if($status == "CRITICAL") {
            $out .= outputAjaxToggle("Issue Detail", base()."/rggipstatus/detail?rid=".$rid."&name=".$name);
        } else {
            $out .= "<br/>No issues found for this test.";
        }
    }
    $out .= "</div>";

    return $out;
}

