<style>
div.resource {
background-color: inherit;
border: none;
}
.content a {
text-decoration: underline;
}
.table,
pre {
margin-bottom: 0;
}
.table th,
.table td {
padding: 2px;
}
tr.noborder > th,
tr.noborder > td {
border-top: none;
}
table th {
max-width: 300px;
margin: 0px;
}
.label {
font-weight: normal;
}
.service {
background-color: gray;
display: inline-block;
color: white;
padding: 1px 6px;
font-weight: bold;
margin-left: 3px;
}
</style>
<table class="table">
<?
foreach($this->resource_groups as $rgid=>$record) {
    $gipstatus = $record["gipstatus"];
    if($gipstatus != null) {
        $testtime = agoCalculation($gipstatus->UnixTimestamp);
        $messages = $gipstatus->Messages;
        $overallstatus = $gipstatus->Result;
    } else {
        $testtime = null;
        $messages = null;
        $overallstatus = null;
    }
    $group_name = $record["name"];
    $gridtype = $record["gridtype"];
    $resources = $record["resources"];
    $wlcgstatus = $record["wlcgstatus"];

    echo "<tr class=\"noborder\"><td colspan=\"4\">";
    echo "<div class=\"group_header\">";
    echo "<span class='h3'>".$group_name."</span>";
    echo " <small>$gridtype</small>";
    echo "</div>";
    echo "</tr>";

    if (isset($_REQUEST["gip_status_attrs_showtestresults"])) {
        switch($overallstatus) {
        case "CRIT":
            $overall = "CRITICAL";
            $overall_detail = "At least one GIP test is failing";
            break;
        case "INFO":
            $overall = "WARNING";
            $overall_detail = "At least one GIP test is reporting information";
            break;
        case "PASS":
            $overall = "OK";
            $overall_detail = "No issues found";
            break;
        case "UNKNOWN":
            $overall = "UNKNOWN";
            $overall_detail = "GIP Validation script is returning unknown overall status";
            break;
        default:
            $overall = "UNKNOWN";
            $overall_detail = "GIP validation result is not available for this resource";
        }

        echo "<tr><th width=\"140px\">GIP Validation Status</th>";
        echo "<td colspan=3>";
        if($testtime !== null) {
            echo "<div class=\"sidenote\">Tests performed $testtime ago</div>";
        }
        echo "<div class=\"status_$overall\">";
        echo "<p>$overall_detail</p>";
        $count = 0;
        $errors = "";
        if(isset($messages->Message)) {
            foreach($messages->Message as $message) {
                if($count < 3) { 
                    echo "<p><pre>$message</pre>";
                } else {
                    //we have too many errors... hide the rest
                    if(trim($message) == "") continue;
                    $errors .= "<p><pre>$message</pre></p>";
                }
                $count++;
            }
        } else {
            //echo "<p class=\"muted\">No Messages</p>";
        }
        if($errors != "") {
            echo outputtoggle("Show All Error Messages", "Hide Some Error Messages", $errors);
        }
        echo "</div>";//status_
        echo "</td></tr>";
    }

    if(isset($_REQUEST["gip_status_attrs_showwlcgstatus"])) {
        echo "<tr><th>WLCG Status</th>";
        echo "<td colspan=3>";
        if(isset($this->wlcgstatus_updatetime)) {
            $testtime = agoCalculation($this->wlcgstatus_updatetime);
            echo "<div class=\"sidenote\">Tests performed $testtime ago</div>";
        }
        if($wlcgstatus != null) {
            foreach($wlcgstatus as $hostname => $status_package) { 
                $groupstatus = $status_package[0];
                $statuses = $status_package[1];
                echo "<div class=\"status_$groupstatus\" style=\"min-height: 25px;\">";
                echo "<span>$hostname</span>";
                foreach($statuses as $status) {
                    if($status->Status != "OK") {
                        echo "<p>Test failed on ".$status->LDAPURI;
                        echo "<pre>".$status->Notes."</pre></p>";
                    }
                }
            }
        } else {
            echo "<div class=\"status_UNKNOWN\" style=\"min-height: 25px;\">";
            echo "<p>WLCG Status information not reported</p>";
            echo "</div>";
        }
        echo "</td></tr>";
    }

    if(isset($_REQUEST["gip_status_attrs_showresource"])) { 
        //show resources
        foreach($resources as $rid=>$resource) {
            echo "<tr>";

            //resource name
            echo "<th><div class=\"resource\">";
            echo $resource->name."<br/>";
            echo "<code>".$resource->fqdn."</code>";
            echo "</div></th>";

            //resource details
            if(isset($_REQUEST["gip_status_attrs_showcemondata"])) { 
                if(!uwa()) {
                    $details = $this->resource_details[$rid];
                    if(isset($details["cemon_raw_data"])) {
                        //show raw data link
                        $data = $details["cemon_raw_data"];
                        echo "<td>";

                        $link = $data->cemon_raw_data[0]->link;
                        $age = $data->cemon_raw_data[0]->age;
                        if($link == "") {
                            echo "(No Incoming Data)<br/>";
                        } else {
                            echo "<a target='_blank' href='$link'>Incoming Data<br>(Age $age)</a>";
                        }
                        echo "</td><td>";
                        //show osg processed link
                        $link = $data->processed_osg_data[0]->link;
                        $age = $data->processed_osg_data[0]->age;
                        if($link == "") {
                            echo "(No OSG Data)<br/>";
                        } else {
                            echo "<a target='_blank' href='$link' title='Port - 2170'>Fed to OSG BDII<br>(Age $age)</a>";
                        }
                        echo "</td><td>";
                        //show wlcg processed link
                        $link = $data->processed_wlcg_interop_data[0]->link;
                        $age = $data->processed_wlcg_interop_data[0]->age;
                        if($link == "") {
                            echo "(No WLCG Data)<br/>";
                        } else {
                            echo "<a target='_blank' href='$link' title='Port - 2180'>Fed to Interop BDII<br>(Age $age)</a>";
                        }
                        echo "</td>";

                    } else {
                        echo "<td colspan=3><p class=\"muted\">LDIF data not available</p></td>";
                    }
                }
            } else {
                //for now, ldif url is the only posssible information to display
                echo "<td colspan=3></td>";
            }
            echo "</tr>";
        }
    }
}
?>
</table>
