<?
foreach($this->resource_groups as $rgid=>$record) {
    $gipstatus = $record["gipstatus"];
    if($gipstatus != null) {
        $testtime = agoCalculation($gipstatus->UnixTimestamp);
        $messages = $gipstatus->Messages;
        $overallstatus = $gipstatus->Result;
    } else {
        $testtime = null;
        $messages = null;
        $overallstatus = null;
    }
    $group_name = $record["name"];
    $gridtype = $record["gridtype"];
    $resources = $record["resources"];
    $wlcgstatus = $record["wlcgstatus"];

?>
    <div class="resource_group_header round">
    <?
    if(!uwa()) {
        echo "<div class=\"sidenote\">";
        echo $gridtype. " Group";
        echo "</div>";
    }
    echo "<span class='h3'>".$group_name."</span>";
    echo "</div>";

    if (isset($_REQUEST["gip_status_attrs_showtestresults"])) {
        switch($overallstatus) {
        case "CRIT":
            $overall = "CRITICAL";
            $overall_detail = "At leat one GIP test is failing";
            break;
        case "INFO":
            $overall = "WARNING";
            $overall_detail = "At least one GIP test is reporting information";
            break;
        case "PASS":
            $overall = "OK";
            $overall_detail = "No issues found";
            break;
        case "UNKNOWN":
            $overall = "UNKNOWN";
            $overall_detail = "GIP Validation script is returning unknown overall status";
            break;
        default:
            $overall = "UNKNOWN";
            $overall_detail = "GIP validation result is not available for this resource";
        }

        if($testtime !== null) {
            echo "<div class=\"sidenote\">Tests performed $testtime ago</div>";
        }
        echo "<h3>GIP Validation Status</h3>";
        echo "<div class=\"status_$overall\">";
        if($messages == null || count($messages->Message) == 0) {
            echo "<p>$overall_detail</p>";
        } else {
            $count = 0;
            $errors = "";
            foreach($messages->Message as $message) {
                if($count < 3) { 
                    echo "<p><pre>$message</pre>";
                } else {
                    //we have too many errors... hide the rest
                    if(trim($message) == "") continue;
                    $errors .= "<p><pre>$message</pre></p>";
                }
                $count++;
            }
            if($errors != "") {
                echo outputtoggle("Show All Error Messages", "Hide Some Error Messages", $errors);
            }
        }
        echo "</div>";//indent
    }

    if(isset($_REQUEST["gip_status_attrs_showwlcgstatus"])) { 
        if(isset($this->wlcgstatus_updatetime)) {
            $testtime = agoCalculation($this->wlcgstatus_updatetime);
            echo "<div class=\"sidenote\">Tests performed $testtime ago</div>";
        }
        echo "<h3>WLCG Status</h3>";
        if($wlcgstatus != null) {
            echo "<table width=\"100%\"><tr>";
            foreach($wlcgstatus as $hostname => $status_package) { 
                echo "<td width=\"50%\">"; //TODO - adjust width based on number of hosts
                $groupstatus = $status_package[0];
                $statuses = $status_package[1];
                echo "<div class=\"status_$groupstatus\" style=\"min-height: 25px;\">";
                echo "<span><b>$hostname</b></p>";
                foreach($statuses as $status) {
                    if($status->Status != "OK") {
                        echo "<div class=\"bottom_border\">";
                        echo "<p>Test failed on ".$status->LDAPURI. "</p>";
                        echo "<pre>".$status->Notes."</pre>";
                        echo "</div>";
                    }
                }
                echo "</div>"; //status indent
                echo "</td>";
            }
            echo "</tr></table>";
        } else {
            echo "<div class=\"status_UNKNOWN\" style=\"min-height: 25px;\">";
            echo "<p>WLCG Status information not reported</p>";
            echo "</div>";
        }
    }

    if(isset($_REQUEST["gip_status_attrs_showresource"])) { 
        //show resources
        foreach($resources as $rid=>$resource) {
            echo "<div class=\"resource h4 round\">";
            echo "<div class=\"sidenote\"><span class=\"fqdn\">".$resource->fqdn."</span></div>";
            echo $resource->name."<br/>";
            echo "</div>";

            //resource details
            $details = $this->resource_details[$rid];
            echo "<table class=\"summary_table\">";

            if(isset($_REQUEST["gip_status_attrs_showcemondata"])) { 
                if(!uwa()) {
                    echo "<th>LDIF URLs</th>";
                    echo "<td style='padding: 0px;'>";
                    
                    if(isset($details["cemon_raw_data"])) {
                        echo "<table width='100%'><tr>";

                        //show raw data link
                        $data = $details["cemon_raw_data"];

                        echo "<td width='33%' style='padding: 0; border: none;'>";

                        $link = $data->cemon_raw_data[0]->link;
                        $age = $data->cemon_raw_data[0]->age;
                        if($link == "") {
                            echo "(No Incoming Data)<br/>";
                        } else {
                            echo "<a target='_blank' href='$link'>Incoming Data<br>(Age $age)</a>";
                        }
                        echo "</td><td width='33%' style='padding: 0; border: none;'>";
                        //show osg processed link
                        $link = $data->processed_osg_data[0]->link;
                        $age = $data->processed_osg_data[0]->age;
                        if($link == "") {
                            echo "(No OSG Data)<br/>";
                        } else {
                            echo "<a target='_blank' href='$link' title='Port - 2170'>Fed to OSG BDII<br>(Age $age)</a>";
                        }
                        echo "</td><td style='padding: 0; border: none;'>";
                        //show wlcg processed link
                        $link = $data->processed_wlcg_interop_data[0]->link;
                        $age = $data->processed_wlcg_interop_data[0]->age;
                        if($link == "") {
                            echo "(No WLCG Data)<br/>";
                        } else {
                            echo "<a target='_blank' href='$link' title='Port - 2180'>Fed to Interop BDII<br>(Age $age)</a>";
                        }
                        echo "</td></tr></table>";

                    } else {
                        echo "&nbsp;Raw data not available";
                    }
                    echo "</td>";
                }
            }
            echo "</table>"; //end - resource detail
        }
    }
}

function outputTestInfo($name, $status, $reason, $rid)
{
    $out = "";
    $out .= "<div class=\"bottom_border status_".$status."\">";

    $out .= "<span class=\"h4\">".$name."</span>";
    if(!uwa()) {
        if($reason != "") {
            $out .= "<br/>$reason";
        }
        if($status == "CRITICAL") {
            $out .= outputAjaxToggle("Issue Detail", base()."/rggipstatus/detail?rid=".$rid."&name=".$name);
        } else {
            $out .= "<br/>No issues found for this test.";
        }
    }
    $out .= "</div>";

    return $out;
}

