<?=$this->header?>
<GIPValidation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://myosg.grid.iu.edu/schema/rggipstatus.xsd">
<?
foreach($this->resource_groups as $rgid=>$record) {
    $gipstatus = $record["gipstatus"];
    if($gipstatus != null) {
        $testtime = agoCalculation($gipstatus->UnixTimestamp);
        $messages = $gipstatus->Messages;
        $overallstatus = $gipstatus->Result;
    } else {
        $testtime = null;
        $messages = null;
        $overallstatus = null;
    }
    $group_name = $record["name"];
    $gridtype = $record["gridtype"];
    $resources = $record["resources"];
    $wlcgstatus = $record["wlcgstatus"];

    echo "<ResourceGroup>";
    echo "<GroupName>$group_name</GroupName>";
    echo "<ID>$rgid</ID>";

    if (isset($_REQUEST["gip_status_attrs_showtestresults"])) {
        //GIP Status
        switch($overallstatus) {
        case "CRIT":
            $overall = "CRITICAL";
            $overall_detail = "At leat one GIP test is failing";
            break;
        case "INFO":
            $overall = "WARNING";
            $overall_detail = "At least one GIP test is reporting information";
            break;
        case "PASS":
            $overall = "OK";
            $overall_detail = "No issues found";
            break;
        case "UNKNOWN":
            $overall = "UNKNOWN";
            $overall_detail = "GIP Validation script is returning unknown overall status";
            break;
        default:
            $overall = "UNKNOWN";
            $overall_detail = "GIP validation result is not available for this resource";
        }
        echo "<GIPStatus>";
        echo "<Status>$overall</Status>";
        echo "<Note>$overall_detail</Note>";
        echo "<Messages>";
        if($messages !== null) {
            foreach($messages->Message as $message) {
                echo "<Message>".htmlsafe($message)."</Message>";
            }
        }
        echo "</Messages>";
        echo "</GIPStatus>";
    }

    if(isset($_REQUEST["gip_status_attrs_showwlcgstatus"])) {
/*
        if($wlcgstatus !== null) {
            echo "<WLCGStatus>";
            echo "<!-- Following XML data comes directly from WLCG consolidator. Format of the data could change without warning -->";
            foreach($wlcgstatus->children() as $child) {
                echo $child->asXML();
            }
            echo "</WLCGStatus>";
        }
*/
        if($wlcgstatus != null) {
            echo "<WLCGStatus>";
            echo "<HostGroups>";
            foreach($wlcgstatus as $hostname => $status_package) { 
                $groupstatus = $status_package[0];
                $statuses = $status_package[1];
                echo "<HostGroup><Name>$hostname</Name>";
                echo "<Status>$groupstatus</Status>";
                echo "<Errors>";
                foreach($statuses as $status) {
                    if($status->Status != "OK") {
                        echo "<Error>Test failed on ".$status->LDAPURI. "</Error>";
                    }
                }
                echo "</Errors>";
                echo "</HostGroup>";
            }
            echo "</HostGroups>";
            echo "</WLCGStatus>";
        }
   }

    if(isset($_REQUEST["gip_status_attrs_showresource"])) { 
        echo "<Resources>";
        foreach($resources as $rid=>$resource) {
            echo "<Resource>";
            echo "<Name>".$resource->name."</Name>";
            echo "<ID>".$resource->id."</ID>";
            echo "<Fqdn>".$resource->fqdn."</Fqdn>";

            //resource details
            $details = $this->resource_details[$rid];

            if(isset($_REQUEST["gip_status_attrs_showcemondata"])) { 
                if(isset($details["cemon_raw_data"])) {
                    $data = $details["cemon_raw_data"];
                    $raw = "";

                    //show raw data link
                    $link = $data->cemon_raw_data[0]->link;
                    $age = $data->cemon_raw_data[0]->age;
                    if($link != "") {
                        $raw .= "<RawLDIF>";
                        $raw .= "<URL>$link</URL><Age>$age</Age>";
                        $raw .= "</RawLDIF>";
                    }

                    //show osg processed link
                    $link = $data->processed_osg_data[0]->link;
                    $age = $data->processed_osg_data[0]->age;
                    if($link != "") {
                        $raw .= "<ProcessedOsgLDIF>";
                        $raw .= "<URL>$link</URL><Age>$age</Age>";
                        $raw .= "</ProcessedOsgLDIF>";
                    }

                    //show wlcg processed link
                    $link = $data->processed_wlcg_interop_data[0]->link;
                    $age = $data->processed_wlcg_interop_data[0]->age;
                    if($link != "") {
                        $raw .= "<ProcessedWlcgInteropLDIF>";
                        $raw .= "<URL>$link</URL><Age>$age</Age>";
                        $raw .= "</ProcessedWlcgInteropLDIF>";
                    }
                }
                echo "<LDIFUrls>$raw</LDIFUrls>";
            }

            echo "</Resource>";
        }
        echo "</Resources>";
    }    


    echo "</ResourceGroup>";
}
?>
</GIPValidation>
