<?=$this->header?>
<GIPValidation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://myosg.grid.iu.edu/schema/rggipstatus.xsd">
<?
foreach($this->resource_groups as $rgid=>$record) {
    $resource_name = $record["name"];
    $tests = $record["tests"];
    $overallstatus = $record["overallstatus"];
    $resources = $record["resources"];
    $wlcgstatus = $record["wlcgstatus"];

    echo "<ResourceGroup>";
    echo "<GroupName>$resource_name</GroupName>";

    if(isset($_REQUEST["gip_status_attrs_showresource"])) { 
        echo "<Resources>";
        foreach($resources as $rid=>$resource) {
            echo "<Resource>";
            echo "<Name>".$resource->name."</Name>";
            echo "<ID>".$resource->id."</ID>";
            echo "<Fqdn>".$resource->fqdn."</Fqdn>";

            //resource details
            $details = $this->resource_details[$rid];

            if(isset($_REQUEST["gip_status_attrs_showcemondata"])) { 
                if(isset($details["cemon_raw_data"])) {
                    $data = $details["cemon_raw_data"];
                    $raw = "";

                    //show raw data link
                    $link = $data->cemon_raw_data[0]->link;
                    $age = $data->cemon_raw_data[0]->age;
                    if($link != "") {
                        $raw .= "<RawLDIF>";
                        $raw .= "<URL>$link</URL><Age>$age</Age>";
                        $raw .= "</RawLDIF>";
                    }

                    //show osg processed link
                    $link = $data->processed_osg_data[0]->link;
                    $age = $data->processed_osg_data[0]->age;
                    if($link != "") {
                        $raw .= "<ProcessedOsgLDIF>";
                        $raw .= "<URL>$link</URL><Age>$age</Age>";
                        $raw .= "</ProcessedOsgLDIF>";
                    }

                    //show wlcg processed link
                    $link = $data->processed_wlcg_interop_data[0]->link;
                    $age = $data->processed_wlcg_interop_data[0]->age;
                    if($link != "") {
                        $raw .= "<ProcessedWlcgInteropLDIF>";
                        $raw .= "<URL>$link</URL><Age>$age</Age>";
                        $raw .= "</ProcessedWlcgInteropLDIF>";
                    }
                }
                echo "<LDIFUrls>$raw</LDIFUrls>";
            }

            echo "</Resource>";
        }
        echo "</Resources>";
    }    


    echo "<OverallStatus>$overallstatus</OverallStatus>";
    echo "<ID>$rgid</ID>";

    echo "<Tests>";
    foreach($tests as $name=>$test) {
        $gip_status = $test["status"];
        $reason = $test["reason"];
        echo "<Test>";
        echo "<Name>$name</Name>";
        echo "<Status>$gip_status</Status>";
        echo "<Reason>$reason</Reason>";
        echo "</Test>";
    }
    echo "</Tests>";

    if(isset($_REQUEST["gip_status_attrs_showwlcgstatus"])) {
        if($wlcgstatus !== null) {
            echo "<WLCGStatus>";
            echo "<!-- Following XML data comes directly from WLCG consolidator. Format of the data could change without warning -->";
            foreach($wlcgstatus->children() as $child) {
                echo $child->asXML();
            }
            echo "</WLCGStatus>";
        }
    }

    echo "</ResourceGroup>";
}
?>
</GIPValidation>
