<GIPValidation>
<?
foreach($this->resources as $rid=>$record) {
    $resource_name = $record["name"];
    $resource_fqdn = $record["fqdn"];
    $tests = $record["tests"];
    $overallstatus = $record["overallstatus"];

    echo "<Resource>";
    echo "<Name>$resource_name</Name>";
    echo "<Fqdn>$resource_fqdn</Fqdn>";

    $rawdata = $record["rawdata"]; 
    if(isset($rawdata["cemon_raw_data"])) {
        $raw = "";

        //show raw data link
        $link = $rawdata["cemon_raw_data"][0]->link;
        $age = $rawdata["cemon_raw_data"][0]->age;
        if($link != "") {
            $raw .= "<RawLDIF>";
            $raw .= "<URL>$link</URL><Age>$age</Age>";
            $raw .= "</RawLDIF>";
        }
        //show osg processed link
        $link = $rawdata["processed_osg_data"][0]->link;
        $age = $rawdata["processed_osg_data"][0]->age;
        if($link != "") {
            $raw .= "<ProcessedOsgLDIF>";
            $raw .= "<URL>$link</URL><Age>$age</Age>";
            $raw .= "</ProcessedOsgLDIF>";
        }
        //show wlcg processed link
        $link = $rawdata["processed_wlcg_interop_data"][0]->link;
        $age = $rawdata["processed_wlcg_interop_data"][0]->age;
        if($link != "") {
            $raw .= "<ProcessedWlcgInteropLDIF>";
            $raw .= "<URL>$link</URL><Age>$age</Age>";
            $raw .= "</ProcessedWlcgInteropLDIF>";
        }
        echo "<LDIFUrls>$raw</LDIFUrls>";
    }

    echo "<OverallStatus>$overallstatus</OverallStatus>";
    echo "<ID>$rid</ID>";

    echo "<Tests>";
    foreach($tests as $name=>$test) {
        $gip_status = $test["status"];
        $reason = $test["reason"];
        echo "<Test>";
        echo "<Name>$name</Name>";
        echo "<Status>$gip_status</Status>";
        echo "<Reason>$reason</Reason>";
        echo "</Test>";
    }
    echo "</Tests>";
    echo "</Resource>";
}
?>
</GIPValidation>
