<?
$js = "";
echo "<div class='indent'>";
foreach($this->rs as $r)
{
    echo "<div class='resource'>".$r->name."</div>";
    $id = $r->resource_id;

    $count = $this->service_counts[$id];
    if($count == 0) {
        echo "<div class=\"indent\">Has no service</div>";
    } else {
        $url = fullbase()."/tree/item?type=resource_service&id=".$id;
        echo "<div class='indent'>";
        echo outputAjaxToggle("Services ($count)" , $url);
        echo "</div>";
    }

    $count = $this->contact_counts[$id];
    if($count == 0) {
        echo "<div class=\"indent\">Has no resource contact</div>";
    } else {
        $url = fullbase()."/tree/item?type=resource_contact&id=".$id;
        echo "<div class='indent'>";
        echo outputAjaxToggle("Resource Contacts ($count)" , $url);
        echo "</div>";
    }
}
echo "</div>";

?>
<script type="text/javascript">
$(document).ready(function() {
<?=$js?>
});
</script>
