<?
$js = "";
echo "<div class='indent'>";

foreach($this->gridtypes as $gridtype=>$rgs) {
    echo "<div class=\"grid_type\">".$gridtype."</div>";
    echo "<div class='indent'>";
    foreach($rgs as $rg)
    {
        echo "<div class=\"resource_group\">".$rg->name."</div>";
        $id = $rg->resource_group_id;
        $count = $this->r_counts_arrays[$gridtype][$id];

        if($count == 0) {
            echo "<div class=\"indent\">Has no resource</div>";
        } else {
            $url = fullbase()."/tree/item?type=resource_group_resource&id=".$id;
            echo "<div class='indent'>";
            echo outputAjaxToggle("Resources ($count)", $url);
            echo "</div>";
        }
    }
    echo "</div>";
}
echo "</div>";

?>
<script type="text/javascript">
$(document).ready(function() {
<?=$js?>
});
</script>
