<style>
#events .eventnew {
display: none;
}
span.show_detail_button,
span.hide_detail_button {
text-decoration: underline;
cursor: pointer;
color: #999;
}
.event {
margin: 3px;
margin-bottom: 5px;
padding: 3px;
padding-left: 8px;
box-shadow: 1px 1px 2px #ccc;
}
.rsv .tag {
display: inline-block;
margin-top: 5px;
}
.help-block {
color: #999;
}
.event_ticket .resource {
    background: url("../images/tag_orange.png") no-repeat scroll 2px 3px #CCCCCC;
}
.event_ticket pre {
    background-color: inherit;
}
.event_oim .resource {
    background: url("../images/potato.png") no-repeat scroll 2px 3px #CCCCCC;
    padding: 2px 2px 2px 25px;
}
div.transparent {
opacity: 0.5;
}
</style>
<script>
function ISODateString(d){
     function pad(n){return n<10 ? '0'+n : n}
     return d.getUTCFullYear()+'-'
          + pad(d.getUTCMonth()+1)+'-'
          + pad(d.getUTCDate())+'T'
          + pad(d.getUTCHours())+':'
          + pad(d.getUTCMinutes())+':'
          + pad(d.getUTCSeconds())+'Z'
}    

function renderEvent(event, c) {
    var html = "";
    html += "<div class=\""+c+" event_"+event.exchange+"\">";
    var strt = event.time
    var dt = new Date(strt);
    html += "<time class=\"sidenote\" datetime=\""+strt+"\">"+dt.toLocaleString()+"</time>"; 

    switch(event.exchange) {
    case "oim": html += renderOIMEvent(event);break;
    case "rsv": html += renderRSVEvent(event);break;
    case "ticket": html += renderTicketEvent(event);break;
    }
    html += "</div>";//event
    return html;
}

function renderOIMEvent(event) {
    var key = event.key.split(".");
    var model = key[0];
    var action = key[1];

    var dnid = event.content.OIMEvent.DNID[0];
    var comment = event.content.OIMEvent.Comment[0];
    var fields = event.content.OIMEvent.Log[0].Fields[0].Field;
    var record_keys = event.content.OIMEvent.Log[0].Keys;
    var logid = event.content.OIMEvent.LogID[0];

    var contact = getContactFromDNID(dnid);

    //I have to normalize fields since it could be array, or single item
    var fields_n = fields;
    if(fields_n && !fields_n.length) {
        fields_n = [fields];
    }

    var html = "";
    var logurl = "<a href=\"<?php echo config()->oim_url?>/log?type=3&id="+logid+"\">OIM Log "+logid+"</a>";
    var contact_name = "N/A";
    if(contact != null) contact_name = contact.name;

    if(action == "update") {
        html += "<div>"+logurl+" "+contact_name+" updated "+model+"</div>";

        if(comment != undefined && comment != "null") {
            html += "<p class=\"help-block\">"+comment+"</p>";
        }
    } else if(action == "insert") {
        html += "<div>"+logurl +" "+contact_name+" inserted "+model+"</div>";

        if(comment) {
            html += "<p class=\"help-block\">"+comment+"</p>";
        }
    } else if(action == "remove") {
        html += "<div>"+logurl +" "+contact_name+" removed "+model+"</div>";

        if(comment) {
            html += "<p class=\"help-block\">"+comment+"</p>";
        }
    } else {
        console.log("unknown action:"+action);
    }

    return html;
}
function renderRSVEvent(event) {
    var html = "";
    var resource_name = event.key;
    var resource_group_id = event.content.ResourceStatusChange.ResourceGroupID;
    var resource_id = event.content.ResourceStatusChange.ResourceID;
    var old_status = event.content.ResourceStatusChange.OldStatus;
    var new_status = event.content.ResourceStatusChange.NewStatus;
    var note = event.content.ResourceStatusChange.Note;

    html += "<div>Resource <a href=\"<?php echo fullbase()?>/rgcurrentstatus/index?datasource=currentstatus&rg=on&rg_"+resource_group_id+"=on\">"+resource_name+"</a> status changed</div>";

    html += "<div class=\"row-fluid\">";
    html += "<div class=\"span2 transparent status_"+old_status+"\">"+old_status+"</div>";
    html += "<div class=\"span1\"><span class=\"ui-icon ui-icon-arrowthick-1-e\"></span></div>";
    html += "<div class=\"span9 status_"+new_status+"\"><p>"+new_status+"<br><span class=\"help-block\">"+note+"</span></div>";
    html += "</div>";

    return html;
}
function renderTicketEvent(event) {
    var html = "";
    var key = event.key.split(".");
    var submitter_id = event.content.ticket.submitter;
    var title = event.content.ticket.title;
    var desc = event.content.ticket.description;
    var ticket_id = key[0];
    var action = key[1];
    if(action == "update") {
        html += "<div>"+submitter_id+" updated <a href=\"<?php echo config()->gocticket_url?>/"+ticket_id+"\">"+ticket_id+": "+title+"</a></div>";
        html += "<pre>"+desc+"</pre>";
    } else if(action == "create") {
        html += "<div>"+submitter_id+" opened ticket <a href=\"<?php echo config()->gocticket_url?>/"+ticket_id+"\">"+ticket_id+": "+title+"</a></div>";
        html += "<pre>"+desc+"</pre>";
    }
    return html;
}

var contacts = [
<?php 
$first = true;
//slog(print_r($this->dns, true));
foreach($this->dns as $dn) {
if($first) $first = false; else echo ",\n";
    echo "{\"dn_id\": ".$dn->id.", \"contact_id\": ".$dn->contact_id.", \"name\": \"".$dn->name."\"}";
}
?>
];
function getContactFromDNID(dnid) {
    for(var i = 0;i < contacts.length; i++) {
        var contact = contacts[i];
        if(contact.dn_id == dnid) return contact;
    }
    return null;
}

var event = io.connect('<?php echo config()->eventjs_url?>');
event.on('events', function (events) {
    //console.dir(events);
    var html = "";
    events.forEach(function(event) {
        html = renderEvent(event, "event") + html;
    });
    $("#events").html(html);
    $("time").timeago();
});
event.on('event', function(event) {
    //console.dir(event);
    html = renderEvent(event, "event eventnew");
    $("#events").prepend(html);
    $(".eventnew").slideDown();
    $("time").timeago();
});

$(function() {
    //update timeago markers periodically
    setInterval(function() {
        $("time").timeago();
    }, 30*60);
});
</script>
<div id="events">Loading ...</div>
