<?php $this->include_timeago = true; ?>
<?php $this->headStyle()->appendStyle("
.rgpfstatus tr.service-head {
background-color: #ddd;
}
.rgpfstatus .resource code.fqdn {
position: relative;
top: -3px;
}
.rgpfstatus pre.cmd-detail {
display: none;
margin-top: 3px;
}
.rgpfstatus td.canshow-detail {
cursor: pointer;
}
.rgpfstatus td.canshow-detail:hover {
background-color: #ccc;
}
");?>
<?php echo $this->render("bootheader.phtml", true)?>
<div class="container-fluid">
<div class="row-fluid content">
    <div class="span9">
        <?=$this->render("banner.phtml", true)?>
        <?=$this->info?>
        <?=$this->render(pagename()."/html.phtml")?>
    </div>
    <div class="span3">
        <?=$this->render("rg/wizard.phtml")?>
        <?=$this->render("feedback.phtml", true)?>
    </div>
</div>
<?=$this->render("footer.phtml", true)?>
</div><!--container-fluid-->
<?=$this->render("bootfooter.phtml", true)?>
