<?
echo "Between ".date(config()->date_format_full, $this->start_time);
echo " and ".date(config()->date_format_full, $this->end_time)."<br/>";
?>
    <table width="100%">
    <tr><th></th><th>Availability</th><th>Reliability</th><th width="100%">&nbsp;</th></tr>
<?
    foreach($this->data as $resource_id=>$resource) {
        if(count($resource) == 0) continue;
        $resource_info = $this->resources[$resource_id];
        $resource_name = $resource_info[0]->name;
        echo "<tr><td colspan=\"4\"><h3><a href=\"".base()."/current?resource_id=$resource_id"."\">$resource_name</a></h3></td></tr>";
        foreach($resource as $service_id=>$data) {
            if($data == null) continue;
            $service_info = $this->services[$service_id];
            $service_name = $service_info[0]->name;
            $a = round((double)$data["availability"]*100, 2);
            $r = round((double)$data["reliability"]*100, 2);
            $graph = fullbase()."/history/graph?resource_id=$resource_id&service_id=$service_id&start=".$this->start_time."&end=".$this->end_time;
            $period=$_REQUEST["period"];
            $history_url = fullbase()."/history?resource_id=$resource_id&period=$period";
            echo "<tr><td>$service_name</td><td>$a%</td><td>$r%</td><td><a href=\"$history_url\"><img width=\"100%\" height=\"20px\" src=\"$graph\"/></a></td></tr>";
        }
        echo "<tr><td colspan=\"3\"></td><td><a href=\"".base()."/aandrhistory?resource_id=".$resource_id."\">Availability History</a></td></tr>";
    }
?>
</table>
<?
    echo "<div class=\"sidenote\">";
    echo "Data calculated at ".date(config()->date_format_full, $this->calc_time);
    echo "</div>";

