<?
echo "Between ".date(config()->date_format_full, $this->start_time);
echo " and ".date(config()->date_format_full, $this->end_time)."<br/>";

if(isset($this->aandr)) {
?>
    <table width="100%">
    <tr><th>&nbsp;&nbsp;&nbsp;</th><th>Service</th><th>Availability</th><th>Reliability</th><th width="100%">&nbsp;</th></tr>
<?
    foreach($this->aandr as $resource_id=>$services) {
        $resource_info = $this->resources[$resource_id];
        $resource_name = $resource_info[0]->name;
        echo "<tr><td colspan=\"5\"><h3>$resource_name</h3></td></tr>";
        foreach($services as $service) {
            $service_id = $service->ServiceID[0];
            $service_info = $this->services[(int)$service_id];
            //$service_name = $service_info[0]->description;
            $service_name = $service_info[0]->name;
            $a = round((double)$service->Availability[0]*100, 2);
            $r = round((double)$service->Reliability[0]*100, 2);
            $graph = fullbase()."/history/graph?resource_id=$resource_id&service_id=$service_id&start=".$this->start_time."&end=".$this->end_time;
            $period=$_REQUEST["period"];
            $history_url = fullbase()."/history?resource_id=$resource_id&period=$period";
            echo "<tr><td></td><td>$service_name</td><td>$a%</td><td>$r%</td><td><a href=\"$history_url\"><img width=\"100%\" height=\"20px\" src=\"$graph\"/></a></td></tr>";
        }
    }
?>
</table>
<?
    echo "<div class=\"sidenote\">";
    echo "Data calculated at ".date(config()->date_format_full, $this->calc_time);
    echo "</div>";
} else {
    echo "<p>Availability and Reliability for this period has not yet been calculated.</p>";
}

