<?
echo "<AR>";
echo "<CalculateTimestamp>".$this->calc_time."</CalculateTimestamp>";
echo "<ReportStartTime>".$this->start_time."</ReportStartTime>";
echo "<ReportEndTime>".$this->end_time."</ReportEndTime>";

echo "<Resources>";
if(isset($this->aandr)) {
    foreach($this->aandr as $resource_id=>$services) {
        echo "<Resource>";
        $resource_info = $this->resources[$resource_id];
        $resource_name = $resource_info[0]->name;
        echo "<ResourceID>$resource_name</ResourceID>";
        echo "<ResourceName>$resource_id</ResourceName>";
        echo "<Services>";
        foreach($services as $service) {
            echo "<Service>";

            $service_id = $service->ServiceID[0];
            $service_info = $this->services[(int)$service_id];
            //$service_name = $service_info[0]->description;
            $service_name = $service_info[0]->name;

            echo "<ServiceID>$service_id</ServiceID>";
            echo "<ServiceName>$service_name</ServiceName>";

            $a = round((double)$service->Availability[0]*100, 2);
            $r = round((double)$service->Reliability[0]*100, 2);

            $graph = htmlentities(fullbase()."/history/graph?resource_id=$resource_id&service_id=$service_id&start=".$this->start_time."&end=".$this->end_time);
            echo "<Graph>$graph</Graph>";

            echo "<Availability>$a%</Availability>";
            echo "<Reliability>$r%</Reliability>";
            echo "</Service>";
        }
        echo "</Services>";
        echo "</Resource>";
    }
}
echo "</Resources>";

echo "</AR>";
