<?=$this->render("full_header.phtml", true)?>
        <div id="primaryContentContainer">
            <div id="primaryContent">
                <h2><?=$this->page_title?></h2>
                <?=$this->render(pagename()."/html.phtml")?>
            </div>
        </div>
        <div id="sideContent">
            <?=$this->render("vo/wizard.phtml")?>
            <?=$this->render("feedback.phtml", true)?>
        </div>
<?=$this->render("full_footer.phtml", true)?>
