<?=$this->render("bootheader.phtml", true)?>
<div class="container-fluid">
<div class="row-fluid content">
    <div class="span9">
        <?=$this->render("banner.phtml", true)?>
        <h2><?=$this->page_title?>
        <small>
        Between <?php echo date(config()->date_format, $this->start_time);?> 
        and <?php echo date(config()->date_format, $this->end_time)?></span><br>
        </small>
        </h2>
        <?=$this->info?>
        <?=$this->render(pagename()."/html.phtml")?>
    </div>
    <div class="span3">
        <?=$this->render("vo/wizard.phtml")?>
        <?=$this->render("feedback.phtml", true)?>
    </div>
</div>
<?=$this->render("footer.phtml", true)?>
</div><!--container-fluid-->
<?=$this->render("bootfooter.phtml", true)?>
