<?
echo $this->header;
function showvolist($list) {
    if(count($list) == 0) {
        echo "<p class=\"info\">No VO under this list.</p>";
    }
    foreach($list as $vo_id=>$vo) {
        echo "<VO>";
        echo "<ID>$vo_id</ID>";
        echo "<Name>".htmlsafe($vo->name)."</Name>";
        echo "<LongName>".htmlsafe($vo->long_name)."</LongName>";
        echo "</VO>";
    }
}
?>
<VOActivation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://my.opensciencegrid.org/schema/voactivation.xsd">
<Active>
<?showvolist($this->active_once_vos);?>
</Active>
<Enabled>
<?showvolist($this->never_active_enabled_vos);?>
</Enabled>
<Disabled>
<?showvolist($this->never_never_vos);?>
</Disabled>
</VOActivation>
