<p class="info">At each OSG site, a RSV monitoring client software runs a set of common tests on OSG resources to check their status, and discover potential issues. This page shows the current set of results that have been received from such clients. For more information - <a href="http://rsv.grid.iu.edu/documentation/" target="_blank">RSV Documentation</a></p>

<?$checked = "";
if(isset($_REQUEST["current_status_attrs_shownc"])) { $checked = "checked=checked"; }?>
<input type="checkbox" name="current_status_attrs_shownc" <?=$checked?>/>
Display information for non-critical metrics: <br/>
<br/>


