<?
echo "<div style='min-height: 400px'>";

if(!uwa()) {
    echo "<div class='indent'>";
    $title = "Resource Groups that are used to generate this graph";
    echo outputToggle("Show $title", "Hide $title", $this->resource_group_names);
    echo "</div>";
    echo "<img src=\"".$this->url."&width=700&height=400&text_size=9&title_size=0&text_padding=3&figure_padding=50\"/>\n";
} else {
    //UWA Graph
    echo "<img src=\"".$this->url."&width=450&height=400&text_size=11&title_size=0&text_padding=3&figure_padding=50\"/>\n";
}

echo "</div>";
