<?
foreach($this->metrics as $id=>$info)
{
    $info = $info[0];

    //header
    echo "<div class=\"metricinfo_header round\">";
    echo "<span class=\"h3\">$info->name</span>";
    echo "</div>";

    ?>
    <table class="summary_table">
    <tr>
        <th>Common Name</th>
        <td><?=htmlentities($info->common_name)?></td>
    </tr>
    <tr>
        <th>Abbreviation</th>
        <td><?=htmlentities($info->abbrev)?></td>
    </tr>
    <tr>
        <th>Description</th>
        <td><?=htmlentities($info->description)?></td>
    </tr>
    <tr>
        <th>Time Interval</th>
        <td><?=htmlentities($info->time_interval)?></td>
    </tr>
    <tr>
        <th>Fresh For</th>
        <td><?=htmlentities($info->fresh_for)?></td>
    </tr>
    <tr>
        <th>WLCG Metric Type</th>
        <td><?=htmlentities($info->wlcg_metric_type)?></td>
    </tr>
    <tr>
        <th>Help URL</th>
        <?
        if($info->help_url == "") {
            echo "<td>(No URL)</td>";
        } else {?>
            <td><a href="<?=$info->help_url?>" target="_blank"><?=htmlentities($info->help_url)?></a></td>
        <?}?>
    </tr>
    </table>
    <?
}
