<style>
.table,
pre {
margin-bottom: 0;
}
.table th,
.table td {
padding: 4px;
}
tr.noborder > th,
tr.noborder > td {
border-top: none;
}
.service {
background-color: gray;
display: inline-block;
color: white;
padding: 1px 6px;
font-weight: bold;
margin-left: 3px;
}
.miscmetric h2 {
padding-bottom: 0px;
margin-bottom: 0px;
border: none;
}
</style>
<div class="miscmetric">

<table class="table">
<thead>
<tr><td><h2><?php echo $this->page_title?></h2></td><th>Common Name</th><th width="100px">Abbr.</th><th width="100px">Time Interval</th><th width="100px">Fresh For</th><th width="100px">Metric Type</th></tr>
</thead>
<tbody>
<?
foreach($this->metrics as $id=>$info)
{
    echo "<tr>";
    $info = $info[0];

    //header
    echo "<td>";
    echo "<div class=\"group_header\"><span class=\"h3\" ref=\"tooltip\" title=\"".htmlsafe($info->description)."\">".htmlsafe($info->name)."</span></div>";
    echo "</td>";

    /* //this is never set really..
    if($info->help_url == "") {
        echo "<td><span class=\"muted\">No URL</span></td>";
    } else {
        echo "<td><a href=\"".$info->help_url."\" target=\"_blank\">".htmlsafe($info->help_url)."</a></td>";
    }
    */

?>
    <td><?=htmlsafe($info->common_name)?></td>
    <td><?=htmlsafe($info->abbrev)?></td>
    <td><?=htmlsafe($info->time_interval)?> seconds</td>
    <td><?=htmlsafe($info->fresh_for)?> seconds</td>
    <td><?=htmlsafe($info->wlcg_metric_type)?></td>
    </tr>

<?php
    echo "<tr class=\"noborder\">";
    echo "<td>";
    echo "</td>";

    echo "<td colspan=\"5\">";
    if(isset($_REQUEST["metric_attrs_showservices"])) {
        if(isset($this->metricservices[$id])) {
            foreach($this->metricservices[$id] as $service) {
                $service_info = $this->services[$service->service_id];
                if($service->critical == 1) {
                    echo "<span class=\"label label-important\">";
                } else {
                    echo "<span class=\"label\">";
                }
                echo $service_info[0]->name."</span> ";
            }
        } else {
            echo "<span class=\"muted\">No Services</span>";
        }
    }
    echo "</td>";
    echo "</tr>";
}
?>
</tbody>
</table>
</div><!--miscmetric-->
<script>
$(function() {
    $("span.h3").tooltip();
});
</script>
