<?
foreach($this->metrics as $id=>$info)
{
    $info = $info[0];

    //header
    echo "<div class=\"metricinfo_header round\">";
    echo "<span class=\"h3\">$info->name</span>";
    echo "</div>";

    ?>
    <table class="summary_table">
    <tr>
        <th>Common Name</th>
        <td><?=htmlsafe($info->common_name)?></td>
    </tr>
    <tr>
        <th>Abbreviation</th>
        <td><?=htmlsafe($info->abbrev)?></td>
    </tr>
    <tr>
        <th>Description</th>
        <td><?=htmlsafe($info->description)?></td>
    </tr>
    <tr>
        <th>Time Interval</th>
        <td><?=htmlsafe($info->time_interval)?></td>
    </tr>
    <tr>
        <th>Fresh For</th>
        <td><?=htmlsafe($info->fresh_for)?></td>
    </tr>
    <tr>
        <th>WLCG Metric Type</th>
        <td><?=htmlsafe($info->wlcg_metric_type)?></td>
    </tr>
    <tr>
        <th>Help URL</th>
        <?
        if($info->help_url == "") {
            echo "<td>(No URL)</td>";
        } else {?>
            <td><a href="<?=$info->help_url?>" target="_blank"><?=htmlsafe($info->help_url)?></a></td>
        <?}?>
    </tr>

    <?if(isset($_REQUEST["metric_attrs_showservices"])) {
    echo "<tr>";
        echo "<th>Services</th>";
        echo "<td>";
        if(isset($this->metricservices[$id])) {
            foreach($this->metricservices[$id] as $service) {
                $service_info = $this->services[$service->service_id];
                echo $service_info[0]->name;
                if($service->critical == 1) {
                    echo " (Critical Metric)";
                } else {
                    echo " (Non-critical Metric)";
                }
                echo "<br/>";
            }
        } else {
            echo "(No Services)";
        }
        echo "</td>";
    echo "</tr>";
    }?>

    </table>
    <?
}
