<?=$this->header?>
<RSVMetrics xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://myosg.grid.iu.edu/schema/miscmetric.xsd">
<?
foreach($this->metrics as $id=>$info)
{
    $info = $info[0];
    //header
    ?><RSVMetric>
<ID><?=htmlsafe($info->id)?></ID>
<Name><?=htmlsafe($info->name)?></Name>
<CommonName><?=htmlsafe($info->common_name)?></CommonName>
<Abbreviation><?=htmlsafe($info->abbrev)?></Abbreviation>
<Description><?=htmlsafe($info->description)?></Description>
<TimeInterval><?=htmlsafe($info->time_interval)?></TimeInterval>
<FreshFor><?=htmlsafe($info->fresh_for)?></FreshFor>
<WLCGMetricType><?=htmlsafe($info->wlcg_metric_type)?></WLCGMetricType>
<?if($info->help_url != "") {?>
<HelpURL><?=htmlsafe($info->help_url)?></HelpURL>
<?}?>

<?if(isset($_REQUEST["metric_attrs_showservices"])) {
echo "<Services>";
if(isset($this->metricservices[$id])) {
    foreach($this->metricservices[$id] as $service) {
        echo "<Service>";
        echo "<ID>".$service->service_id."</ID>";
        $service_info = $this->services[$service->service_id];
        echo "<Name>".htmlsafe($service_info[0]->name)."</Name>";
        echo "<CriticalMetric>";
        if($service->critical == 1) {
            echo "True";
        } else {
            echo "False";
        }
        echo "</CriticalMetric>";
        echo "</Service>";
    }
}
echo "</Services>";
}?>

</RSVMetric>
<?
}
?>
</RSVMetrics>
