<RSVMetrics>
<?
foreach($this->metrics as $id=>$info)
{
    $info = $info[0];
    //header
    ?><RSVMetric>
<ID><?=htmlentities($info->id)?></ID>
<Name><?=htmlentities($info->name)?></Name>
<CommonName><?=htmlentities($info->common_name)?></CommonName>
<Abbreviation><?=htmlentities($info->abbrev)?></Abbreviation>
<Description><?=htmlentities($info->description)?></Description>
<TimeInterval><?=htmlentities($info->time_interval)?></TimeInterval>
<FreshFor><?=htmlentities($info->fresh_for)?></FreshFor>
<WLCGMetricType><?=htmlentities($info->wlcg_metric_type)?></WLCGMetricType>
<?if($info->help_url != "") {?>
<HelpURL><?=htmlentities($info->help_url)?></HelpURL>
<?}?>
    </RSVMetric>
<?
}
?>
</RSVMetrics>
