<?

$resource = $this->resource;

//don't show resource with no services
if(isset($this->resource_services[$resource->id])) {
    $services = $this->resource_services[$resource->id];
} else {
    $services = null;
}

if($services === null) {
    echo "No applicable service exists for this resource";
} else {
    $service_names = "";
    foreach($services as $service) {
        if($service_names != "") $service_names .= " / ";
        if(isset($this->servicetypes[$service->service_id])) {
            $service_names .= $this->servicetypes[$service->service_id][0]->description;
        } else {
            $service_names .= "unknown_service_id:".$service->service_id;
        }
    }

    echo "<div class=\"status_$status\"><h4>".$resource->name." ($service_names)</h4>";
    echo "<span class=\"fqdn\">".$resource->fqdn."</span><br/>";
    echo "$note<br/>";

    if(!isset($_REQUEST["uwa"])) {
        $vonames = "";
        if(isset($this->vos[$resource->id])) {
            $volist = $this->vos[$resource->id];
            foreach($volist as $vo) {
                $vonames .= $vo." ";
            } 
        }
        if($vonames != "") {
            $vonames .= "<br/>";
            echo outputToggle("Show Supported Virtual Organizations", "Hide Supported Virtual Organizations", $vonames);
        }
    }

    if(!isset($_REQUEST["uwa"])) {
        $url = base()."/current?resource_id=".$resource->id;
        echo "<a href=\"$url\">Current Status</a>&nbsp;&nbsp;&nbsp;";
    }            
    if(!isset($_REQUEST["uwa"])) {
        $url = base()."/history?resource_id=".$resource->id;
        echo "<a href=\"$url\">Status History</a>&nbsp;&nbsp;&nbsp;";
    }

    echo "</div>";
}
