<?

$resource = $this->resource;

if($this->services === null) {
    echo "No applicable service exists for this resource";
} else {
    $service_names = "";
    foreach($this->services as $service) {
        if($service_names != "") $service_names .= " / ";
        $service_id = (int)$service->ServiceID;
        if(isset($this->servicetypes[$service_id])) {
            $service_names .= $this->servicetypes[$service_id][0]->description;
        } else {
            $service_names .= "unknown_service_id:".$service_id;
        }
    }

    echo "<div class=\"status_$status\"><h4>".$resource->name." ($service_names)</h4>";
    echo "<span class=\"fqdn\">".$resource->fqdn."</span><br/>";
    echo "$this->note<br/>";

    //show vo list
    $vonames = "";
    if(isset($this->vos[$resource->id])) {
        $volist = $this->vos[$resource->id];
        foreach($volist as $vo) {
            $vonames .= $vo." ";
        } 
    }
    if($vonames != "") {
        $vonames .= "<br/>";
        echo outputToggle("Show Supported Virtual Organizations", "Hide Supported Virtual Organizations", $vonames);
    }

    //show various detail links
    if(!isset($_REQUEST["uwa"])) {
        $url = base()."/current?resource_id=".$resource->id;
        echo "<a href=\"$url\">Current Status</a>&nbsp;&nbsp;&nbsp;";
        $url = base()."/history?resource_id=".$resource->id;
        echo "<a href=\"$url\">Status History</a>&nbsp;&nbsp;&nbsp;";
    }

    echo "</div>";
}
