<?
echo "<Resource>";

$resource = $this->resource;
$resource_status = $this->resource_status[$resource->id];
$note = $resource_status->Note[0];
$status = $resource_status->Status[0];
$services = $this->resource_services[$resource->id];

$service_names = "";
echo "<Services>";
foreach($services as $service) {
    if($service_names != "") $service_names .= " / ";
    echo "<Service>";
    echo "<Name>".$this->servicetypes[$service->service_id][0]->description."</Name>";
    echo "</Service>";
}
echo "</Services>";

echo "<Status>$status</Status>";
echo "<Name>".$resource->name."</Name>";
echo "<Fqdn>".$resource->fqdn."</Fqdn>";
echo "<Note>$note</Note>";

echo "</Resource>";
