<h2>RSV Home</h2>
<p>Welcome to RSV information section. Here you will find various representations for current RSV status and its historical data.</p>

<style>
a.insert
{
    float:left;
    padding: 5px;
}
</style>
<div>
    <h3>Resource Groups</h3>
    <a class="insert" href="<?=fullbase()?>/resources">
        <img src="<?=base()?>/images/screenshots/resource_groups.jpg"/>
        <img src="<?=base()?>/images/screenshots/history.jpg"/>
    </a>
    <p>(Pleas add description..)</p>
</div>
<br clear="all"/>

<div>
    <h3>Virtual Organizations</h3>
    <a class="insert" href="<?=fullbase()?>/vo"><img src="<?=base()?>/images/screenshots/vo.jpg"/></a>
    <p>(Pleas add description..)</p>
</div>
<br clear="all"/>

<div>
    <h3>RSV Status Map</h3>
    <a class="insert" href="<?=fullbase()?>/map"><img src="<?=base()?>/images/screenshots/map.jpg"/></a>
    <p>(Pleas add description..)</p>
</div>
<br clear="all"/>

<div>
    <h3>Documentation</h3>
    <a class="insert" href="http://rsv.grid.iu.edu/documentation/"><img src="<?=base()?>/images/screenshots/rsvdoc.jpg"/></a>
    <p>(Pleas add description..)</p>
</div>
<br clear="all"/>
