<h2>RSV Home</h2>

<div>
    <h3>Resource Groups</h3>
    <a href="<?=fullbase()?>/resources"><img src=""/></a>
    <p>TODO..</p>
</div>

<div>
    <h3>Virtual Organizations</h3>
    <a href="<?=fullbase()?>/vo"><img src=""/></a>
    <p>TODO..</p>
</div>

<div>
    <h3>RSV Status Map</h3>
    <a href="<?=fullbase()?>/map"><img src=""/></a>
    <p>TODO..</p>
</div>

<div>
    <h3>Documentation</h3>
    <a href="http://rsv.grid.iu.edu/documentation/"><img src=""/></a>
    <p>TODO..</p>
</div>
