<?=$this->render("full_header.phtml", true)?>
        <div id="primaryContentContainer">
            <div id="primaryContent">
                <?=$this->render("breadcrumb.phtml", true)?>
                <?=$this->render(pagename()."/html.phtml")?>
            </div>
        </div>
        <div id="sideContent">
            <h3>Links</h3>
            <div class="indent">
                <a target="_blank" href="http://rsv.grid.iu.edu/documentation/">RSV Documentation</a>
            </div>
        </div>
<?=$this->render("full_footer.phtml", true)?>
