<?if(isset($_REQUEST["downtime_attrs_showpast"])) {?>
    <div class="downtime_group round">
    <span class="h3">Past Downtimes</span>
    </div>
    <?
    showdowntimes($this->past_downtimes);
}
?>

<div class="downtime_group round">
<span class="h3">Current Downtimes</span>
</div>
<?
showdowntimes($this->current_downtimes);
?>

<div class="downtime_group round">
<span class="h3">Future Downtimes</span>
</div>
<?
showdowntimes($this->future_downtimes);

function showdowntimes($downtimes) {
    echo "<div class=\"downtime_detail\">";
    if(count($downtimes) == 0) {
        echo "No downtimes";
    }
    foreach($downtimes as $downtime)
    {
        echo "<div class='resource h4 round'>";
        echo "<span class=\"hierarchy\">".htmlentities($downtime["rg_name"])." (Resource Group) &gt; </span>";
        echo htmlentities($downtime["name"]);
        echo "</div>";
        echo "<table class=\"summary_table\">";

        echo "<tr><th>FQDN</th><td>".htmlentities($downtime["fqdn"])."</td></tr>";
        echo "<tr><th>Start Time</th><td>".$downtime["start_time"]."</td></tr>";
        echo "<tr><th>End Time</th><td>".$downtime["end_time"]."</td></tr>";

        echo "<tr><th>Class</th><td>".htmlentities($downtime["class"])."</td></tr>";
        echo "<tr><th>Severity</th><td>".htmlentities($downtime["severity"])."</td></tr>";
        echo "<tr><th>DN</th><td>".htmlentities($downtime["dn"])."</td></tr>";

        echo "<tr><th>Affected&nbsp;Services</th><td>";
        foreach($downtime["services"] as $service) {
            echo htmlentities($service->name)."<br/>";
        }
        echo "</td></tr>";
        
        
        //show downtime detail
        echo "<tr><th>Detail</th><td>";
        echo htmlentities($downtime["desc"]);
        echo "</td></tr>";

        echo "</table>";
    }
    echo "</div>";
}

