<?=$this->render("full_header.phtml", true)?>
        <div id="primaryContentContainer">
            <div id="primaryContent">
                <?=$this->render("breadcrumb.phtml", true)?>
                <h2><?=$this->page_title?></h2>
                <?=$this->info?>
                <?=$this->render(pagename()."/html.phtml")?>
            </div>
        </div>
        <div id="sideContent">
            <?=$this->render("rg/wizard.phtml")?>
            <div class="indent">
            <a target="_blank" href="<?=fullbase()."/".pagename()."/ical?".$_SERVER["QUERY_STRING"]?>">iCal</a>
            </div>
            <?=$this->render("feedback.phtml", true)?>
        </div>
<?=$this->render("full_footer.phtml", true)?>
