<Downtimes>
<?if(isset($_REQUEST["downtime_attrs_showpast"])) {?>
    <PastDowntimes>
    <?showdowntimes($this->past_downtimes); ?>
    </PastDowntimes>
<?}?>
<CurrentDowntimes>
<?showdowntimes($this->current_downtimes); ?>
</CurrentDowntimes>
<FutureDowntimes>
<?showdowntimes($this->future_downtimes); ?>
</FutureDowntimes>
</Downtimes>
<?
function showdowntimes($downtimes) {
    foreach($downtimes as $downtime)
    {
        echo "<Downtime>";
        echo "<ID>".$downtime["id"]."</ID>";
        echo "<ResourceID>".htmlentities($downtime["resource_id"])."</ResourceID>";
	echo "<ResourceGroup>";
	echo "<GroupName>".htmlentities($downtime["rg_name"])."</GroupName>";
	echo "</ResourceGroup>";
        echo "<ResourceName>".htmlentities($downtime["name"])."</ResourceName>";
        echo "<ResourceFQDN>".htmlentities($downtime["fqdn"])."</ResourceFQDN>";
        echo "<StartTime>".$downtime["start_time"]."</StartTime>";
        echo "<EndTime>".$downtime["end_time"]."</EndTime>";
        echo "<Class>".htmlentities($downtime["class"])."</Class>";
        echo "<Severity>".htmlentities($downtime["severity"])."</Severity>";
        echo "<DN>".htmlentities($downtime["dn"])."</DN>";

        echo "<Services>";
        foreach($downtime["services"] as $service) {
            echo "<Service>";
            echo "<ID>".htmlentities($service->id)."</ID>";
            echo "<Name>".htmlentities($service->name)."</Name>";
            echo "<Description>".htmlentities($service->description)."</Description>";
            echo "</Service>";
        }
        echo "</Services>";
        echo "<Description>".htmlentities($downtime["desc"])."</Description>";
        echo "</Downtime>";
    }
}
