<?=$this->header?>
<Downtimes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://myosg.grid.iu.edu/schema/rgdowntime.xsd">
<?if(isset($_REQUEST["downtime_attrs_showpast"])) {?>
    <PastDowntimes>
    <?showdowntimes($this->past_downtimes); ?>
    </PastDowntimes>
<?}?>
<CurrentDowntimes>
<?showdowntimes($this->current_downtimes); ?>
</CurrentDowntimes>
<FutureDowntimes>
<?showdowntimes($this->future_downtimes); ?>
</FutureDowntimes>
</Downtimes>
<?
function showdowntimes($downtimes) {
    foreach($downtimes as $downtime)
    {
        echo "<Downtime>";
        echo "<ID>".$downtime["id"]."</ID>";
        echo "<ResourceID>".htmlsafe($downtime["resource_id"])."</ResourceID>";
        echo "<ResourceGroup>";
        echo "<GroupName>".htmlsafe($downtime["rg_name"])."</GroupName>";
        echo "<GroupID>".htmlsafe($downtime["rg_id"])."</GroupID>";
        echo "</ResourceGroup>";
        echo "<ResourceName>".htmlsafe($downtime["name"])."</ResourceName>";
        echo "<ResourceFQDN>".htmlsafe($downtime["fqdn"])."</ResourceFQDN>";
        echo "<StartTime>".$downtime["start_time"]."</StartTime>";
        echo "<EndTime>".$downtime["end_time"]."</EndTime>";
        echo "<Class>".htmlsafe($downtime["class"])."</Class>";
        echo "<Severity>".htmlsafe($downtime["severity"])."</Severity>";
        if(!user()->isGuest()) {
            echo "<DN>".htmlsafe($downtime["dn"])."</DN>";
        }

        echo "<Services>";
        foreach($downtime["services"] as $service) {
            echo "<Service>";
            echo "<ID>".htmlsafe($service->id)."</ID>";
            echo "<Name>".htmlsafe($service->name)."</Name>";
            echo "<Description>".htmlsafe($service->description)."</Description>";
            echo "</Service>";
        }
        echo "</Services>";
        echo "<Description>".htmlsafe($downtime["desc"])."</Description>";
        echo "</Downtime>";
    }
}
