<div class="miscpfmesh">
<h2><?php echo $this->page_title?></h2>
<table class="table table-bordered">
<?php
foreach($this->configs as $config) {
    echo "<tr>";
    echo "<th colspan='2'>".$this->escape($config->desc)."</th>";
    echo "<td>";
    $url = fullbase()."/pfmesh?name=".$config->name;
    echo "<a href=\"$url\">$url</a>";
    echo "</td>";
    echo "</tr>";
}

/*
$first = true;
$vocount = count($this->vos);
foreach($this->vos as $void=>$vo)
{
    echo "<tr>";
    if($first) {
        $first = false;
        echo "<th rowspan='$vocount'>";
        echo "VO Specific Matrix";
        echo "</th>";
    }
    echo "<td>$vo->name</td>";
    $url = fullbase()."/pfmesh/json?vo_id=$void";
    echo "<td><a href=\"$url\">$url</a></td>";
    echo "</tr>";
}
*/
?>
</table>
</div><!-- miscpfmesh -->
