<div class="psmesh">
<h2><?php echo $this->page_title?></h2>

<p class="alert">This page is still under development. Please contact GOC for more information.</p>

<div class="well">
    <legend>Auto Mesh Config</legend>
    <p>Please enter the hostname of your perfsonar toolkit instance to generate a mesh config containing all tests that uses your host as endpoints.</p>
    <div class="input-append">
        <input type="text" id="auto-hostname" placeholder="perfsonar-bw.grid.iu.edu"/>
        <button class="btn" id="auto-hostname-gen">Generate</button>
    </div>
</div>

<script>
$(function() {
    $("#auto-hostname-gen").click(function() {
        document.location = "<?php echo fullbase()?>/psmesh/mine/hostname/"+$("#auto-hostname").val();
    });
});
</script>

<table class="table table-bordered">
<?php
foreach($this->configs as $config) {
    echo "<tr>";
    echo "<th>".$this->escape($config->desc)."</th>";
    $url = fullbase()."/psmesh/json/name/".$config->name;
    echo "<td>";
    echo "<a href=\"$url\">$url</a>";
    echo "</td>";
    echo "</tr>";
}
?>

<tr class="all">
<?php 
$url = fullbase()."/psmesh/all"; 
//$url_33 = "$url/version/v33";
echo "<th>All Mesh config</th>";
echo "<td><a href=\"$url\">$url</a></td>";
?>
</tr>
</table>

</div><!-- psmesh -->
