<style>
.address {
padding: 5px;
margin-bottom: 3px;
background-color: #eee;
}
.avatar {
margin: 2px;
max-height: 80px;
max-width: 80px;
}
tr.noborder > th,
tr.noborder > td {
border-top: none;
}
.table {
margin-bottom: 0;
}
.table th,
.table td {
padding: 3px;
}
table th {
width: 200px;
}
</style>

<?php

echo "<table class=\"table\">";
foreach($this->contacts as $cid => $contact) {
    $contact = $contact[0];

    //name header
    echo "<tr class=\"noborder\"><th colspan=\"3\">";
    echo "<div class=\"group_header\">";
    echo "<span class=\"h3\">".htmlsafe($contact->name)."</span>";
    echo "</div>";
    echo "</th>";
    echo "</tr>";

    //image
    echo "<tr>";
    echo "<td>";
    if(trim($contact->photo_url) != "") {
        echo "<img class=\"avatar\" src=\"$contact->photo_url\"/>";
    } else {
        //show gravatar
        $url = "http://www.gravatar.com/avatar/".md5($contact->primary_email);
        echo "<img class=\"avatar\" src=\"$url\"/>";
    }
    echo "</td>";

    //profile
    echo "<td>";
    if(trim($contact->profile) != "") {
        echo "<p>".htmlsafe($contact->profile)."</p>";
    } else {
        echo "<p class=\"muted\">No profile information provided</p>";
    }
    if(trim($contact->contact_preference) != "" && trim($contact->contact_preference) != trim($contact->profile)) {
        echo "<p>Contact Preference: ".htmlsafe($contact->contact_preference)."</p>";
    }
    echo "</td>";

    //profile detail
    if(!user()->isGuest()) {
        echo "<td width=\"60%\">";
        echo formatEmail($contact->primary_email);
        echo formatEmail($contact->secondary_email);
        echo formatPhone($contact->primary_phone, $contact->primary_phone_ext);
        if(trim($contact->im) != "") {
            echo "<b>IM</b> ".htmlsafe($contact->im)."<br>";
        }
        $dns = $this->contacts_dns[$contact->id];
        echo "<ul>";
        foreach($dns as $dn) {
            echo "<li>".htmlsafe($dn->dn_string)."</li>";
        }
        echo "</ul>";
        echo "</td>";
    }
    echo "</tr>";
}
echo "</table>";

function formatEmail($email) {
    if(trim($email) == "") return "";
    $out = "<i class=\"icon-envelope\"></i> <a href=\"mailto: $email\">".htmlsafe($email)."</a><br>";
    return $out;
}

function formatPhone($phone, $ext) {
    if(trim($phone) == "") return "";
    $out = "<i class=\"icon-headphones\"></i> ".htmlsafe($phone)." ";
    if(trim($ext) != "") {
        $out .= "(ext. ".htmlsafe($ext).")";
    }
    $out .= "<br>";
    return $out;
}
