<style>
* {
margin: 0px;
padding: 0px;
}
body {
font-family: "Arial";
color: #333;
line-height:1.5em;
font-size: 10pt;
height: 100%;
}
h2, h3 {
border-bottom:1px dotted #AAAAAA;
padding-bottom:0.3em;
margin-bottom: 3px;
}
h3, h4, h5 {
font-size: 90%;
margin-bottom: 2px;
}
a {
color:white;
cursor:pointer;
text-decoration:underline;
}
p {
margin-bottom: 1px;
}
<?
require_once("config.php");
?>
</style>

<link href="<?=fullbase()?>/css/html.css" rel="stylesheet" type="text/css" />
<script type='text/javascript' src='<?=fullbase()?>/lib/jquery-ui-1.8.1/js/jquery-1.4.2.min.js'></script>
<script type="text/javascript" src="//maps.googleapis.com/maps/api/js?sensor=false"></script>
<script type="text/javascript">
<?=$this->render(pagename()."/js.phtml");?>
$(document).ready(function() {
    init(false);//scroll wheel -- off
});
</script>
<?=$this->render(pagename()."/html.phtml");?>
<style>
#map_canvas {
height: 100%;
}
</style>
