<style>
* {
margin: 0px;
padding: 0px;
}
body {
font-size: 11px;
font-family: "Verdana";
}
p {
margin-bottom: 1px;
}
<?
require_once("config.php");
?>
</style>
<link href="<?=base()?>/css/html.css" rel="stylesheet" type="text/css" />
<script type='text/javascript' src='<?=base()?>/lib/jquery-ui-1.8.1/js/jquery-1.4.2.min.js'></script>
<script src="http://maps.google.com/maps?file=api&v=2&key=<?=config()->gmap_key?>" type="text/javascript"></script>
<script type="text/javascript">
<?=$this->render(pagename()."/js.phtml");?>
$(document).ready(function() {
    init();
});
</script>
<?=$this->render(pagename()."/html.phtml");?>

