<?=$this->render("full_header.phtml", true)?>
<script src="http://maps.google.com/maps?file=api&v=2&key=<?=config()->gmap_key?>" type="text/javascript"></script>
<script type="text/javascript">
<?=$this->render(pagename()."/js.phtml");?>
$(document).ready(function() {
    init();
});
</script>
<div id="primaryContentContainer">
    <div id="primaryContent">
        <?=breadcrumb($this->page_title)?>
        <h2><?=$this->page_title?></h2>
        <?=$this->render(pagename()."/html.phtml");?>
    </div>
</div>
<div id="sideContent">
    <h3>Subscribe</h3>
    <?
    $param = $_SERVER["QUERY_STRING"];
    $moduleurl = urlencode(fullbase()."/".pagename()."/uwa?$param");
    ?>
    <p><a href="http://www.netvibes.com/subscribe.php?module=UWA&moduleUrl=<?=$moduleurl?>"><img src="images/subscribe.png"/></a></p>
    <p><a href="http://www.google.com/ig/add?moduleurl=http%3A%2F%2Fwww.netvibes.com%2Fapi%2Fuwa%2Fcompile%2Fgoogle.php%3FmoduleUrl%3D<?=urlencode($moduleurl)?>"><img src="images/google.png"/></a></p>
<!--
    <p><a href="<?=base()?>/<?=pagename()?>/xml?<?=$param?>">XML</a></p>
-->
</div>
<?=$this->render("full_footer.phtml", true)?>
