var map;
var anchor;
var marker_id = {};
var infowindow = new google.maps.InfoWindow({maxWidth: 300});

function update_anchor() {
    var pos = map.getCenter();
    var new_anchor ="#"+pos.toUrlValue()+"|"+map.getZoom()+"|"+map.getMapTypeId();
    if(anchor != new_anchor) {
        document.location.hash=pos.toUrlValue()+"|"+map.getZoom()+"|"+map.getMapTypeId();
        anchor = new_anchor;
    }
    setTimeout("update_anchor()", 1000);
}

function init(scrollwheel) {
    //default
    //var location = new google.maps.LatLng(38.61687,-96.767578);
    var location = new google.maps.LatLng(29.22889,-90.08789);//show south americas
    var zoom = 4;
    var maptype = google.maps.MapTypeId.TERRAIN;
    
    //overrride with hash params
    anchor = document.location.hash.split("#")[1];
    <?php 
    //allow anchor override via parameter
    if(isset($_REQUEST["__anchor"])) {
        echo "anchor = '".$_REQUEST["__anchor"]."';"; 
    }
    ?>
    if(anchor) {
        var params = anchor.split("|");
        var coords = params[0].split(",");
        location = new google.maps.LatLng(coords[0], coords[1]);
        zoom = parseInt(params[1]);
        maptype = params[2];
    }

    //create map
    map = new google.maps.Map(document.getElementById('map_canvas'), {
        scrollwheel: scrollwheel,
        center: location,
        zoom: zoom,
        mapTypeControl: false,
        mapTypeId: maptype
    });

    //setup listeners
    setTimeout("update_anchor()", 1000);//don't hook centerre_changed event.. it fires too often now
    
    //add sites
    <?
    foreach($this->sites as $site) {

        //status counter    
        $status_ok = 0;
        $status_warning = 0;
        $status_critical = 0;
        $status_unknown = 0;
        $status_downtime = 0;

        if(!isset($this->rgs[$site->id])) continue;
        $rgs = $this->rgs[$site->id];
        if(count($rgs) == 0) continue; //don't show site with no resource group
        if($site->active == 0 || $site->disable == 1) continue; //don't show sites that are not active

        $html = "";
        $site_has_status = false;
        foreach($rgs as $rg) {
            $rgname = $rg->name;

            //this is now done by the controller
            //if($rg->active == 0 || $rg->disable == 1) continue;

            $target = "target=\"_blank\"";
            $gid = $rg->id;
            $html .= "<div class=\"resource_group_header round\"><span class=\"h3\">Resource Group: <a $target href=\"".fullbase()."/rgsummary?datasource=summary&rg=on&rg_$gid&summary_attrs_showdesc=on&summary_attrs_showservice=on&summary_attrs_showrsvstatus=on\">$rgname</a></span></div>";

            $rhtml = "";
            if(isset($this->resources_bygid[$rg->id])) {
                $rs = $this->resources_bygid[$rg->id];
                foreach($rs as $r) {
                    if($r->active == 0 || $r->disable == 1) continue;
                    $name = $r->name;
                    if(isset($this->downtime[$r->id])) {
                        $status = "DOWNTIME";
                        $note = "This resource is currently under maintenance.";
                    } else if(isset($this->resource_status[$r->id][0])) {
                        $rstatus = $this->resource_status[$r->id][0];
                        $status = Status::getStatus($rstatus->status_id);

                        //treat status change that happened long time ago as non-reporting
                        $expire = time()-3600*24*config()->status_expires_days;
                        $note = $rstatus->detail;
                        if($rstatus->timestamp < $expire && $status != "OK") {
                            $rhtml .= "<div class=\"resource round\" style=\"margin-bottom: 0;\"><span class=\"h4\">$name</span></div><div class=\"status_$status\"><span class=\"round tag\" style=\"background-color: #da0;\">Status Expired</span> $note</div>";
                            continue;//don't count this as a valid status
                        }
                    } else {
                        //resource status is not calculated - skip this resource
                        $rhtml .= "<div class=\"resource round\" style=\"margin-bottom: 0;\"><span class=\"h4\">$name</span></div><div class=\"status_UNKNOWN\">Status not calculated</div>";
                        continue;
                    }
                    $rhtml .= "<div class=\"resource round\" style=\"margin-bottom: 0;\"><span class=\"h4\">$name</span></div><div class=\"status_$status\">$note</div>";

                    //determine site status
                    if($status == "OK") $status_ok++;
                    if($status == "WARNING") $status_warning++;
                    if($status == "CRITICAL") $status_critical++;
                    if($status == "UNKNOWN") $status_unknown++;
                    if($status == "DOWNTIME") $status_downtime++;
                    $site_has_status = true;
                }
            }
            if($rhtml == "") {
                $html .= "<p class=\"warning\">No active resource</p>";
            } else {
                $html .= $rhtml;
            }
        }

        //if there are no resource to show..
        $wrap_html = "<h2>Site: $site->name</h2><div style=\"overflow: auto; max-height: 300px; width: 300px;\">$html</div>";
        $show = false;
        if(!$site_has_status) {
            if(isset($_REQUEST["map_attrs_shownr"])) {
                //show as "non reporting"
                $status = "nr";
                $show = true;
            }
        } else {
            //decide site status
            if($status_critical > 0) $status = "critical";
            else if($status_downtime > 0) $status = "downtime";
            else if($status_warning > 0) $status = "warning";
            else if($status_unknown > 0) $status = "unknown";
            else if($status_ok > 0) $status = "ok";
            else $status = "unknown"; //no info!?

            //show marker
            if($site->latitude == null) $site->latitude = 0;
            if($site->longitude == null) $site->longitude = 0;
            $show = true;
        }
        if($show) {
            switch($status) {
            case "nr": $zindex = 0;break;
            case "warning": $zindex = 1;break;
            case "ok": $zindex = 2;break;
            case "unknown": $zindex = 3;break;
            default: $zindex = 4;
            }
            ?>
            var marker = new google.maps.Marker({
                position: new google.maps.LatLng(<?php echo $site->latitude?>, <?php echo $site->longitude?>),
                map: map,
                zIndex: <?php echo $zindex?>,
                icon: '<?php echo fullbase()?>/images/status_<?php echo $status?>_map.png',
                title: '<?php echo addslashes($site->name)?>'
            });
            marker_id[<?php echo $site->id?>] = marker;
            setInfoWindow(<?php echo $site->id?>, marker,'<?php echo addslashes($wrap_html);?>');
            <?php
            echo "$(\"#site\").append(\"<option value='$site->id'>$site->name</option>\");\n";
        }
    }
    ?>

    $("#site").change(function() {
            var id = $(this).val();
            var marker = marker_id[id];
            if(marker) {
                google.maps.event.trigger(marker, 'click');
            } else {
                infowindow.close();
            }
    });

    <?php
    if(isset($_REQUEST["map_attrs_showcampusgrid"])) {
        //add campus grid icons
        foreach($this->campusgrid_icons as $icon) {
            ?>
            var campus_marker = new google.maps.Marker({
                position: new google.maps.LatLng(<?php echo $icon["lat"]?>, <?php echo $icon["lon"]?>),
                map: map,
                icon: '<?php echo fullbase()."/images/smallpin.png";?>',
                title: '<?php echo addslashes($icon["name"])?>'
            });
            setInfoWindow(null, campus_marker, "<h2><?php echo $icon["name"]?> Campus Grid</h2><p><?php echo $icon["desc"]?></p><img style=\"float: right; padding-right: 10px;\" src=\"<?php echo fullbase()."/".$icon["icon"];?>\">");
            <?php
        }
    }
    ?>
    google.maps.event.addListener(infowindow, 'closeclick', function() {
        $("#site option[value=]").attr("selected", "selected");
    });
}

function setInfoWindow(id,marker, content) {
    google.maps.event.addListener(marker, 'click', function() {
        infowindow.close();
        infowindow.setContent(content);
        infowindow.open(map, marker);
        if(id != null) {
            $("#site option[value='"+id+"']").attr("selected", "selected");
        }
    });
}
