
function init_icon(type, img)
{
    var icon = new GIcon();
    icon.image = "<?=fullbase();?>/images/" + img;
    icon.iconAnchor = new GPoint(12, 12);
    icon.infoWindowAnchor = new GPoint(12, 12);
    icon.iconSize = new GSize(24, 24);
    icon.shadow = "<?=fullbase();?>/images/shadow.png";
    icon.shadowSize = new GSize(30, 30);

    return icon;
}

var marker_id = {}
var map = null;

function init() {
  if (GBrowserIsCompatible()) {
    map = new GMap2(document.getElementById("map_canvas"));
    map.addControl(new GSmallMapControl());
    map.addControl(new GMapTypeControl());
    map.enableScrollWheelZoom();

    //map.setCenter(new GLatLng(37, -100), 4); //U.S. only
    map.setCenter(new GLatLng(20, 0), 2);

    GEvent.addListener(map, "infowindowclose", function() {
        $("#site option[value=]").attr("selected", "selected");
    });

    //generate icons
    var icon = {};
    var type = "ok";
    icon[type] = init_icon(type, "status_ok.png");
    type = "warning";
    icon[type] = init_icon(type, "status_warning.png");
    type = "unknown";
    icon[type] = init_icon(type, "status_unknown.png");
    type = "critical";
    icon[type] = init_icon(type, "status_critical.png");
    type = "downtime";
    icon[type] = init_icon(type, "status_downtime.png");

    function createMarker(id, point, markerOptions, html) {
      var marker = new GMarker(point, markerOptions);
      marker_id[id] = marker;
      GEvent.addDomListener(marker, "click", function() {
        marker.openInfoWindowHtml(html);
        var latlng = marker.getLatLng();
        map.panTo(latlng);
        $("#site option[value="+id+"]").attr("selected", "selected");
      });
      return marker;
    }
<?
foreach($this->sites as $site) {
    //status counter    
    $status_ok = 0;
    $status_warning = 0;
    $status_critical = 0;
    $status_unknown = 0;
    $status_downtime = 0;

    $site_id = $site->site_id;
    $name = $site->name;

    $rgs = $this->rgs[$site_id];
    if(count($rgs) == 0) continue; //don't show site with no resource group

    $html = "";
    foreach($rgs as $rg) {
        $rgid = $rg->resource_group_id;
        $rgname = $rg->name;
        if(uwa()) {
            $target = "target=\"blank\"";
        } else {
            $target = "";
        }
        $html .= "<h3>Resource Group: <a $target href=\"".fullbase()."/wizardsummary?datasource=summary&rg=on&rg_$rgid=on\">$rgname</a></h3>";
        if(isset($this->resources_bygid[$rg->resource_group_id])) {
            $rs = $this->resources_bygid[$rg->resource_group_id];
            foreach($rs as $r) {
                if(isset($this->resource_status[$r->resource_id][0])) {
                    $rstatus = $this->resource_status[$r->resource_id][0];
                    $name = $r->name;
                    $status = Status::getStatus($rstatus->status_id);
                    $html .= "<div class=\"status_$status\"><h4>$name</h4>";
                    $html .= $rstatus->detail . "<br/></div>";
                } else {
                    $name = $r->name;
                    $status = "UNKNOWN";
                    $html .= "<div class=\"status_$status\"><h4>$name</h4>";
                    $html .= "Resource status is not calculated for this resource.<br/></div>";
                    
                }
                
                //determine site status
                if($status == "OK") $status_ok++;
                if($status == "WARNING") $status_warning++;
                if($status == "CRITICAL") $status_critical++;
                if($status == "UNKNOWN") $status_unknown++;
                if($status == "DOWNTIME") $status_downtime++;
            }
        } else {
            $html .= "No active resource exists under this resource group.";
            $status_unknown++; //treat this as unknown
        }
    }

    //decide site status
    if($status_critical > 0) $status = "critical";
    else if($status_downtime > 0) $status = "downtime";
    else if($status_warning > 0) $status = "warning";
    else if($status_unknown > 0) $status = "unknown";
    else $status = "ok";

    $html = addslashes($html);
    echo "map.addOverlay(createMarker($site_id, new GLatLng(".$site->latitude.", ".$site->longitude."), {icon:icon[\"$status\"]}, '$html'));\n";
    echo "$(\"#site\").append(\"<option value='$site_id'>$name</option>\");\n";
}

?>
    

  }
    $("#site").change(function() {
        var id = $(this).val();
        var marker = marker_id[id];
        if(marker) {
            $(marker).trigger('click');
        } else {
            map.closeInfoWindow();
        }
    });
}
