<style type="text/css">
<?include("css/uwa.css.php");?>
.moduleContent
{
    padding: 0px;
    margin: 0px;
}
</style>
 
<script type="text/javascript">
    <?=$this->render(pagename()."/js.phtml");?>
</script>
    <iframe src='<?=fullbase();?>/<?=pagename()?>/iframe?uwa&<?=$_SERVER["QUERY_STRING"]?>#<?=$_REQUEST["__anchor"]?>' width='100%' height='300px' scrolling='no' frameborder='0'>
</iframe>
