<?php echo $this->render("full_header.phtml", true)?>
<div id="primaryContentContainer" style="margin: 0px;padding: 0px;">
    <div id="primaryContent" style="margin: 0px;padding: 0px;">
        <h2><?=$this->page_title?></h2>
        <input type="checkbox" name="acro" <?if(isset($_REQUEST["acro"])) echo "checked=checked";?> onclick="var url = '<?=fullbase()?>/map/promo'; if(this.checked) url += '?acro'; document.location = url;"> Show Acronyms (and group close sites)
        <img src="<?=fullbase()?>/map/promo2<? if(isset($_REQUEST["acro"])) echo "?acro=true";?>"/>
    </div>
</div>
<?=$this->render("full_footer.phtml", true)?>
