<?echo "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n";?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" 
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" 
  xmlns:widget="http://www.netvibes.com/ns/">
  <head>
 
    <meta name="author" content="OSG GOC" />
    <meta name="description" content="A descriptive description" />
 
    <meta name="apiVersion" content="1.0" />
    <meta name="autoRefresh" content="20" />
    <meta name="debugMode" content="true" />
 
    <link rel="stylesheet" type="text/css" href="http://www.netvibes.com/themes/uwa/style.css" />
    <script type="text/javascript" src="http://www.netvibes.com/js/UWA/load.js.php?env=Standalone"></script>
 
    <title><?=$this->page_title?></title>
    <link rel="icon" type="image/png" href="http://www.example.com/favicon.ico" />
 
<style type="text/css">
<?include("css/mobile.css.php");?>
.moduleContent
{
    padding: 0px;
    margin: 0px;
}
</style>
 
<script type="text/javascript">
    <?=$this->render(pagename()."/js.phtml");?>
    widget.onLoad = function() {
        text = "<iframe src='<?=fullbase();?>/<?=pagename()?>/iframe?uwa&<?=$_SERVER["QUERY_STRING"]?>#<?=$_REQUEST["__anchor"]?>' width='100%' height='300px' scrolling='no' frameborder='0'></iframe>";
        widget.setBody(text);
    }
</script>
</head>

<body>
    <p>Loading...</p>
</body>
</html>
