<?php
require "/usr/local/myosg/vendor/autoload.php";
$client_id = config()->cilogon_client_id;
$redirect_url=config()->cilogon_client_redirect;
$client_host=config()->cilogon_client_host;
$client_secret=config()->cilogon_client_secret;
$oidc = new OpenIDConnectClient($client_host,                                                                            
				$client_id,                                 
				$client_secret);       
$oidc->setRedirectURL($redirect_url);
$oidc->addScope("openid");                                                                                                                                        
$oidc->addScope("email");                                                                                                                                         
$oidc->addScope("profile");                                                                                                                                       
$oidc->addScope("org.cilogon.userinfo");                                                                                                                          
$oidc->authenticate();                                                                                                                                            
$name = $oidc->requestUserInfo('email');                                                                                                                          

if(preg_match("/opensciencegrid/",$_SESSION['ref_loc'])){
  $redirect_url=config()->cilogon_client_redirect;
  elog("redirect: opensciencegrid");
}else{
  $redirect_url=config()->cilogon_client_redirect_grid;
  elog("redirect: grid.iu.edu");
}
elog("callback url:". $redirect_url);


if($_SESSION['access_token']==""){                                                                                                                             
    
  if (isset($_REQUEST['code'])) {                                                                                                                                   
    $_SESSION['access_token'] = $oidc->getAccessToken();                                                                                                            
    $_SESSION['email'] = $oidc->requestUserInfo('email');                                                                                                           
    $_SESSION['family_name'] = $oidc->requestUserInfo('family_name');                                                                                               
    $_SESSION['given_name'] = $oidc->requestUserInfo('given_name');                                                                                                 
    $_SESSION['idp'] = $oidc->requestUserInfo('idp');                                                                                                               
    $_SESSION['idp_name'] = $oidc->requestUserInfo('idp_name');

    //    header("location: https://".$_SERVER['SERVER_NAME']."/");
    if($_SESSION["ref_loc"]!=""){
      header("location: ".$_SESSION["ref_loc"]."/");

    }else{
      header("location: https://".$_SERVER['SERVER_NAME']."/");

    }
                                                                                             
  }                 
                                                                                                                                                
}else{                                                                                                                                                         
  if($_SESSION['email']!=""){                                                                                                                  
    // header("location: https://".$_SERVER['SERVER_NAME']."/");
    if($_SESSION["ref_loc"]!=""){
      header("location: ".$_SESSION["ref_loc"]."/");

    }else{
      header("location: https://".$_SERVER['SERVER_NAME']."/");
    }

  }                                                                                                                                            
}                                                    
?>