<div class="pfmesh">
<h2><?php echo $this->page_title?></h2>

<p class="alert">This page is still under development. Please contact GOC for more information.</p>

<div class="well">
    <legend>Host Specific Config</legend>
    <p>Please use following URL to generate mesh config with all tests with your host as endpoints.</p>
    <?php 
    $url = fullbase()."/pfmesh/mine/hostname/"; 
    echo "<a href=\"$url\">$url</a>";
    ?>
</div>

<table class="table table-bordered">
<tr><th></th><th>v3.3</th><th>v3.4</th></tr>
<?php
foreach($this->configs as $config) {
    echo "<tr>";
    echo "<th>".$this->escape($config->desc)."</th>";
    $url = fullbase()."/pfmesh/json/name/".$config->name;
    $url_33 = "$url/version/v33";
    //$url_34 = "$url/version/v34";
    $url_34 = $url; //let 34 use default url
    echo "<td>";
    echo "<a href=\"$url_33\">$url_33</a>";
    echo "</td>";
    echo "<td>";
    echo "<a href=\"$url_34\">$url_34</a>";
    echo "</td>";
    echo "</tr>";
}
?>

<tr class="all">
<?php 
$url = fullbase()."/pfmesh/all"; 
$url_33 = "$url/version/v33";
$url_34 = "$url/version/v34";
echo "<th>All Mesh config</th>";
echo "<td><a href=\"$url_33\">$url_33</a></td>";
echo "<td><a href=\"$url_34\">$url_34</a></td>";
?>
</tr>
</table>

</div><!-- pfmesh -->
