<?
echo "<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?>\n";

echo "<history_detail>";

echo "<date_range>";
echo "<from>".date(config()->date_format_full, $this->start_time)."</from>";
echo "<to>".date(config()->date_format_full, $this->end_time)."</to>";
echo "</date_range>";

$metrics_model = new Metrics();

echo "<status_changes>";
$first = true;
foreach($this->status_changes as $status_change) {
    $timestamp = $status_change->timestamp;
    $status = $status_change->overall_status;
    $detail = $status_change->detail;
    $time = date("F j, Y, g:i a", $timestamp);
    $responsible_mid = $status_change->responsible_metric_id;

    if($first) {
        echo "<initial_status>";
    } else {
        echo "<status_change>";
    }

    echo "<status>$status</status>";
    echo "<time>$time</time>";
    echo "<detail>".htmlsafe($time)."</detail>";
    echo "<responsible_metric>$responsible_mid</responsible_metric>";

    if($first) {
        echo "</initial_status>";
    } else {
        echo "</status_change>";
    }
    $first = false;
}
echo "</status_changes>";
echo "</history_detail>";
