<?=$this->render("full_header.phtml", true)?>

        <div id="primaryContentContainer">
            <div id="primaryContent">
                <?=$this->render("breadcrumb.phtml", true)?>
                <h2><?=$this->page_title?></h2>
                <?=$this->render(pagename()."/html.phtml");?>
            </div>
        </div>
        <div id="sideContent">
            <h3>Graph Period</h3>
            <?
            outputSelectBox2("period", array(
                "1day"=>"Last 24 Hours", 
                "3day"=>"Last 3 Days", 
                "week"=>"Last 7 Days", 
                "30days"=>"Last One Month", 
                "year"=>"Last One Year"
            ));
            ?>
            <h3>Subscribe</h3>
            <h4>Subscribe to Current View</h4>
            <?
            $param = $_SERVER["QUERY_STRING"];
            $moduleurl = urlencode(fullbase()."/".pagename()."/uwa?$param");
            ?>
            <p><a href="http://www.netvibes.com/subscribe.php?module=UWA&moduleUrl=<?=$moduleurl?>"><img src="images/subscribe.png"/></a></p>
            <p><a href="http://www.google.com/ig/add?moduleurl=http%3A%2F%2Fwww.netvibes.com%2Fapi%2Fuwa%2Fcompile%2Fgoogle.php%3FmoduleUrl%3D<?=urlencode($moduleurl)?>"><img src="images/google.png"/></a></p>
            <!--p><a href="<?=base()?>/<?=pagename()?>/xml?<?=$param?>">XML</a></p-->
            <p>* Non-interactive graph only</p>

            <?=$this->render("legend_rsvhistory.phtml", true)?>
            <?=$this->render("feedback.phtml", true)?>
        </div>
<?=$this->render("full_footer.phtml", true)?>
