<?=$this->render("full_header.phtml", true)?>

        <div id="primaryContentContainer">
            <div id="primaryContent">
                <?
                $resources_query = session()->query["resources"];
                ?>
                <div id="breadcrumb"><p>You are here &gt; <a href="<?=base()."/resources?$resources_query";?>">Resource Groups</a> &gt; <?=$this->page_title?></p> </div>
                <h2><?=$this->page_title?></h2>
                <?=$this->render(pagename()."/html.phtml");?>
            </div>
        </div>
        <div id="sideContent">
            <h3>Subscribe</h3>
            <p>Non-interactive graph only</p>
            <?
            $param = $_SERVER["QUERY_STRING"];
            $moduleurl = urlencode(fullbase()."/".pagename()."/uwa?$param");
            ?>
            <p><a href="http://www.netvibes.com/subscribe.php?module=UWA&moduleUrl=<?=$moduleurl?>"><img src="images/subscribe.png"/></a></p>
            <p><a href="http://www.google.com/ig/add?moduleurl=http%3A%2F%2Fwww.netvibes.com%2Fapi%2Fuwa%2Fcompile%2Fgoogle.php%3FmoduleUrl%3D<?=urlencode($moduleurl)?>"><img src="images/google.png"/></a></p>
            <!--p><a href="<?=base()?>/<?=pagename()?>/xml?<?=$param?>">XML</a></p-->
        </div>
<?=$this->render("full_footer.phtml", true)?>
