<p><b>One-stop location for various OSG information</b></p>
<div class="info_box">
<h2>Sample Pages</h2>
<table width="100%">
<tr>
    <td width="33%">
        <?$url = "rgsummary/index?datasource=summary&summary_attrs_showservice=on&summary_attrs_showrsvstatus=on&summary_attrs_showgipstatus=on&summary_attrs_showfqdn=on&summary_attrs_showwlcg=on&summary_attrs_showenv=on&summary_attrs_showcontact=on&gip_status_attrs_showtestresults=on&gip_status_attrs_showfqdn=on&account_type=cumulative_hours&ce_account_type=gip_vo&se_account_type=vo_transfer_volume&start_type=7daysago&start_date=03%2F20%2F2009&end_type=now&end_date=03%2F27%2F2009&all_resources=on&gridtype=on&gridtype_1=on&service_4=on&service_1=on&service_5=on&service_2=on&service_3=on&active=on&active_value=1&disable_value=1'";?>
        <p><a href="<?=$url?>"><b>Resource Group Summary</b></a><br/>
        <a href="<?=$url?>"><img class="screenshot" src="<?=fullbase()?>/images/screenshots/summary.png" align="top"/></a><br/>
        <br clear="all"/> 
        </p>
    </td>
    <td width="33%">
        <?$url = "rgstatushistory/index?datasource=statushistory&account_type=cumulative_hours&ce_account_type=gip_vo&se_account_type=vo_transfer_volume&start_type=7daysago&start_date=02%2F04%2F2009&end_type=now&end_date=02%2F11%2F2009&all_resources=on&gridtype=on&gridtype_1=on&service_1=on&service_5=on&active=on&active_value=1&disable_value=1";?>
        <p><a href="<?=$url?>"><b>RSV Status History</b></a><br/>
        <a href="<?=$url?>"><img class="screenshot" src="<?=fullbase()?>/images/screenshots/statushistory.png" align="top"/></a><br/>
        <br clear="all"/>
        </p>
    </td>
    <td width="33%">
        <?$url = "rgcurrentstatus/index?datasource=currentstatus&summary_attrs_showservice=on&summary_attrs_showrsvstatus=on&summary_attrs_showfqdn=on&current_status_attrs_shownc=on&gip_status_attrs_showtestresults=on&gip_status_attrs_showfqdn=on&account_type=cumulative_hours&ce_account_type=gip_vo&se_account_type=vo_transfer_volume&start_type=7daysago&start_date=04%2F08%2F2009&end_type=now&end_date=04%2F15%2F2009&all_resources=on&gridtype=on&gridtype_1=on&service_4=on&service_1=on&service_5=on&service_2=on&service_3=on&active=on&active_value=1&disable_value=1";?>
        <p><a href="<?=$url?>"><b>Current RSV Status</b></a><br/>
        <a href="<?=$url?>"><img class="screenshot" src="<?=fullbase()?>/images/screenshots/current.png" align="top"/></a><br/>
        <br clear="all"/>
        </p>
    </td>
</tr>
<tr>
    <td>
        <?$url = "rggipstatus/index?datasource=gipstatus&summary_attrs_showservice=on&summary_attrs_showrsvstatus=on&summary_attrs_showfqdn=on&account_type=cumulative_hours&ce_account_type=gip_vo&se_account_type=vo_transfer_volume&start_type=7daysago&start_date=02%2F23%2F2009&end_type=now&end_date=03%2F02%2F2009&all_resources=on&gridtype=on&gridtype_1=on&service=on&service_1=on&gip_status_attrs_showtestresults=on&gip_status_attrs_showfqdn=on";?>
        <p><a href="<?=$url?>"><b>GIP Validation Results</b></a><br/>
        <a href="<?=$url?>"><img class="screenshot" src="<?=fullbase()?>/images/screenshots/gipvalidate.png" align="top"/></a><br/>
        <br clear="all"/> 
        </p>
    </td>
    <td>
        <?$url = "map?all_sites=on&active=on&active_value=1&disable_value=1&gridtype=on&gridtype_1=on";?>
        <p><a href="<?=$url?>"><b>Status Map</b></a><br/>
        <a href="<?=$url?>"><img class="screenshot" src="<?=fullbase()?>/images/screenshots/statusmap.png" align="top"/></a><br/>
        <br clear="all"/> 
        </p>
    </td>
    <td>
        <?$url = "rgaccount/index?datasource=account&summary_attrs_showservice=on&summary_attrs_showrsvstatus=on&summary_attrs_showfqdn=on&gip_status_attrs_showtestresults=on&gip_status_attrs_showfqdn=on&account_type=daily_hours_byusername&ce_account_type=gip_vo&se_account_type=vo_transfer_volume&start_type=30daysago&start_date=04/08/2009&end_type=now&end_date=04/15/2009&all_resources=on&gridtype=on&gridtype_1=on&active=on&active_value=1&disable_value=1";?>
        <p><a href="<?=$url?>"><b>Gratia Accounting</b></a><br/>
        <a href="<?=$url?>"><img class="screenshot" src="<?=fullbase()?>/images/screenshots/gratia_accounting.png" align="top"/></a><br/>
        <br clear="all"/> 
        </p> 
    </td>
</tr>
</table> 
</div>

<div class="info_box">
<div class="sidenote">Edit at <a target="_blank" href="https://twiki.grid.iu.edu/bin/view/Operations/UserContributedViews">TWiki</a></div>
<h2>User Contributed MyOSG Views</h2>
<?
foreach($this->ucv as $ucv)
{
echo "<div class=\"sidenote\">by ".htmlsafe($ucv[4])." (".htmlsafe(trim($ucv[3])).")</div>";
echo "<b><a href=\"".$ucv[2]."\">".htmlsafe($ucv[1])."</a></b>";
echo "<p>".$ucv[5]."</p>";
}
?>
</div>

<!--div class="info_box">
<h2>Coming Soon !</h2>
<p>We plan to implement the following updates in the near future.</p>
    <div class="indent">
    <ol> 
        <li>In the medium term future (summer), we also expect to put in place an OIM hierarchy selector for the facilities -> sites -> resource_group -> resource hierarchy.</li>
        <li>In the medium term future (summer/fall), we also expect to add a presentation layer for ReSS based service information
        </li>
    </ol>
    </div>
</div-->
