<p>MyOSG is a web interface for OSG Operations Information Center. Its primary goal is to provide a one-stop location for all of OSG related information by allowing you to quickly find and export the information in the format that you'd like.</p>

<h2>Sample MyOSG Pages</h2>
<table width="100%">
<tr>
    <td width="50%">
        <p><a href="map"><b>Status Map</b>
        <img class="screenshot" src="<?=fullbase()?>/images/screenshots/statusmap.png" align="left"/>
        </a><br/>
        "Status Map" shows the current overall site statues on Google Map.
        <br clear="all"/> 
        </p>
    </td>
    <td width="50%">
        <p><a href="wizardstatushistory/index?datasource=statushistory&start_type=30daysago&start_date=02%2F04%2F2009&end_type=today&end_date=02%2F11%2F2009&sc=on&sc_29=on&site_10088=on&gt=on&gt_1=on&service=on&service_1=on&service_5=on&has_status=on#detail%3Fresource_id%3D4%26service_id%3D1%26time%3D1233467481"><b>Status History</b>
        <img class="screenshot" src="<?=fullbase()?>/images/screenshots/statushistory.png" align="left"/>
        </a><br/>
        This sample page shows last 30 days status history of all resources that are supported by USATLAS. You can click on a graph to display the metric details of a particular point in time.
        <br clear="all"/>
        </p>
    </td>
</tr>
<tr>
    <td>
        <p><a href="wizardsummary/index?datasource=summary&start_type=yesterday&start_date=02%2F04%2F2009&end_type=today&end_date=02%2F11%2F2009&all_resources=on&gt=on&gt_1=on&has_status=on"><b>Resource Summary</b>
        <img class="screenshot" src="<?=fullbase()?>/images/screenshots/summary.png" align="left"/>
        </a><br/>
        Current status summary from all resources that are reporting RSV status.
        <br clear="all"/> 
        </p>
    </td>
    <td><p><a href="wizardgipstatus/index?datasource=gipstatus&summary_attrs_showservice=on&summary_attrs_showrsvstatus=on&summary_attrs_showfqdn=on&account_type=cumulative_hours&ce_account_type=gip_vo&se_account_type=vo_transfer_volume&start_type=7daysago&start_date=02%2F23%2F2009&end_type=now&end_date=03%2F02%2F2009&all_resources=on&gridtype=on&gridtype_1=on&service=on&service_1=on"><strong>GIP Validation Results</strong><img class="screenshot" src="<?=fullbase()?>/images/screenshots/gipvalidate.png" align="left"/></a><br/>
        Current GIP validation status for all production resources that provide the CE service. Click <a href="wizardgipstatus/index?datasource=gipstatus&summary_attrs_showservice=on&summary_attrs_showrsvstatus=on&summary_attrs_showfqdn=on&account_type=cumulative_hours&ce_account_type=gip_vo&se_account_type=vo_transfer_volume&start_type=7daysago&start_date=02%2F23%2F2009&end_type=now&end_date=03%2F02%2F2009&all_resources=on&gridtype=on&gridtype_2=on&service=on&service_1=on"><strong>here to access GIP validation results for ITB resources</strong></a>.
        <br clear="all"/> 
        </p>
    </td>
</tr>
</table> 


<h2>External Links</h2>
<table width="100%">
<tr>
    <td width="50%">
        <p><a target="_blank" href="https://oim.grid.iu.edu"><b>OIM</b>
        <img class="screenshot" src="<?=fullbase()?>/images/screenshots/oim.png" align="left"/>
        </a><br/>
        OSG Information Management System (OIM) manages various aspects of OSG information. This is where OSG users can register their contact information or OSG admin to registere their resources, virtual organization, etc..
        <br clear="all"/> 
        </p>
    </td>
    <td width="50%">
        <p><a target="_blank" href="http://osggoc.blogspot.com"><b>GOC Operations News and Announcement</b>
        <img class="screenshot" src="<?=fullbase()?>/images/screenshots/news.png" align="left"/>
        </a><br/>
        This page shows the latest public GOC news and announcements. You can also subscribe to our<br/>
        <img src="<?=fullbase()?>/images/rss.png"/> <a href="http://osggoc.blogspot.com/feeds/posts/default">GOC News RSS Feed</a>
        <br clear="all"/>
        </p>
    </td>
</tr>
<tr>
    <!--td>
        <p><a target="_blank" href="http://gratia-osg-prod.opensciencegrid.org/gratia-reporting"><b>Gratia Reporting</b>
        <img class="screenshot" src="<?=fullbase()?>/images/screenshots/gratia.png" align="left"/>
        </a><br/>
        Gratia provides various runtime metric information of OSG resources in various graphs and formats.
        <br clear="all"/> 
        </p>
    </td-->
    <td>
        <p><a target="_blank" href="https://oim.grid.iu.edu/gocticket"><b>GOC Ticket Submiter / Viewer</b>
        <img class="screenshot" src="<?=fullbase()?>/images/screenshots/gocticket.png" align="left"/>
        </a><br/>
If you need assistance or report a problem, please open a ticket using this form.
        <br clear="all"/> 
        </p>
    </td>
    <td>
        <p><a target="_blank" href="http://twiki.grid.iu.edu/bin/view"><b>OSG TWiki</b>
        <img class="screenshot" src="<?=fullbase()?>/images/screenshots/twiki.png" align="left"/>
        </a><br/>
 This twiki is the home for OSG's collaborative work. Work in OSG is done in "Activities", coordinated through this TWiki, regularly scheduled phone conferences, and mailing lists. All of these communication modes are open to new members.  The collaborative work area comprises separate "webs" for each of the activities, for documentation, and for other "hands-on" topics. 
        <br clear="all"/> 
        </p>
    </td>


</tr>
<tr>
    <td>
        <p><a target="_blank" href="http://software.grid.iu.edu/"><b>OSG Software Cache</b>
        <img class="screenshot" src="<?=fullbase()?>/images/screenshots/yum.png" align="left"/>
        </a><br/>
This software cache provides OSG-specific components like VO package, GUMS template, etc. that are not provided by the VDT software distribution. The GOC also maintains a <a target="_blank" href="http://yum.grid.iu.edu/"><b>OSG Yum Repository</b></a> that provides components like the OSG CA Certifcates.
        <br clear="all"/> 
        </p>
    </td>

    <td>
    </td>

</tr>
</table> 


