<?=$this->render("full_header.phtml", true)?>
<div id="primaryContentContainer">
    <div id="primaryContent">
        <?=$this->render("breadcrumb.phtml", true)?>
        <h2><?=$this->page_title?></h2>
        <?=$this->render(pagename()."/html.phtml")?>
    </div>
</div>
<div id="sideContent">
    <h3>Other GOC Services</h3>
    <div class="indent">
        <p><a target="_blank" href="https://oim.grid.iu.edu"><b>OIM</b><br/>
        <img class="screenshot" src="<?=fullbase()?>/images/screenshots/oim.png" align="left"/>
        </a>
        Register new resources, update your profile and various OSG topology information.
        <br clear="all"/> 
        </p>

        <p><a target="_blank" href="http://osggoc.blogspot.com"><b>GOC News</b><br/>
        <img class="screenshot" src="<?=fullbase()?>/images/screenshots/news.png" align="left"/>
        </a>
        The latest public GOC news and announcements.<br/>
        <img src="<?=fullbase()?>/images/rss.png"/> <a href="http://osggoc.blogspot.com/feeds/posts/default">RSS Feed</a>
        <br clear="all"/>
        </p>

        <p><a target="_blank" href="http://twiki.grid.iu.edu/bin/view"><b>TWiki</b><br/>
        <img class="screenshot" src="<?=fullbase()?>/images/screenshots/twiki.png" align="left"/>
        </a>
        Online document management system for OSG.
        <br clear="all"/> 
        </p>

        <p><a target="_blank" href="http://software.grid.iu.edu/"><b>OSG Software Cache</b><br/>
        <img class="screenshot" src="<?=fullbase()?>/images/screenshots/yum.png" align="left"/>
        </a>
        Provides OSG-specific components that are not provided by the VDT.
        <br clear="all"/> 
        </p>
    </div>

    <?if($_SERVER['SERVER_NAME'] != "myosg-itb.grid.iu.edu") {?>
        <h3>Upcoming Release</h3>
        <div class="indent">
            <p>If you use MyOSG as a datasource for your script, please test it against <a target="_blank" href="http://myosg-itb.grid.iu.edu/"><b>MyOSG ITB Instance</b></a></p>
        </div>
    <?}?>

    <?=$this->render("feedback.phtml", true)?>
</div>
<?=$this->render("full_footer.phtml", true)?>
