<?=$this->render("full_header.phtml", true)?>
<div id="primaryContentContainer">
    <div id="primaryContent">
        <?=$this->render("breadcrumb.phtml", true)?>
        <?=$this->render(pagename()."/html.phtml")?>
    </div>
</div>
<div id="sideContent">
    <h3>News</h3>
    <div class="indent">
        <img class="screenshot" src="<?=fullbase()?>/images/screenshots/news.jpg" align="left"/>

        <a target="_blank" href="http://osggoc.blogspot.com"><b>Operations News</b></a><br/>
        <p>The latest public GOC news and announcements.</p>

        <a target="_blank" href="http://osgsec.blogspot.com"><b>Security News</b></a><br/>
        <p>The latest OSG security news and announcements.</p>

        <br clear="all"/>
    </div>

    <h3>Other GOC Services</h3>
    <div class="indent">
        <p><a target="_blank" href="https://ticket.grid.iu.edu/goc"><b>GOC Ticket</b><br/>
        <img class="screenshot" src="<?=fullbase()?>/images/screenshots/gocticket.jpg" align="left"/>
        </a>
        Submit a problem or assistance request regarding OSG.
        <br clear="all"/> 
        </p>

        <p><a target="_blank" href="https://oim.grid.iu.edu"><b>OIM</b><br/>
        <img class="screenshot" src="<?=fullbase()?>/images/screenshots/oim.jpg" align="left"/>
        </a>
        Register new resources, update your profile and various OSG topology information.
        <br clear="all"/> 
        </p>

        <p><a target="_blank" href="http://twiki.grid.iu.edu/bin/view"><b>TWiki</b><br/>
        <img class="screenshot" src="<?=fullbase()?>/images/screenshots/twiki.jpg" align="left"/>
        </a>
        Online document management system for OSG.
        <br clear="all"/> 
        </p>

        <p><a target="_blank" href="http://display.grid.iu.edu"><b>OSG Display</b><br/>
        <img class="screenshot" src="<?=fullbase()?>/images/screenshots/display.jpg" align="left"/>
        </a>
        Bird's eye view of current OSG statistics.
        <br clear="all"/> 
        </p>

        <p><a target="_blank" href="http://blogs.grid.iu.edu"><b>Planet OSG</b><br/>
        <img class="screenshot" src="<?=fullbase()?>/images/screenshots/blogs.jpg" align="left"/>
        </a>
        Blog Aggregator for blogs written by people from the OSG community
        <br clear="all"/> 
        </p>

        <p><a target="_blank" href="http://gratiaweb.grid.iu.edu"><b>GratiaWeb</b><br/>
        <img class="screenshot" src="<?=fullbase()?>/images/screenshots/gratiaweb.jpg" align="left"/>
        </a>
        External access to the current OSG activity statistics / graphs.
        <br clear="all"/> 
        </p>

        <p><a target="_blank" href="http://software.grid.iu.edu/"><b>OSG Software Cache</b><br/>
        </a>
        Provides OSG-specific components that are not provided by the VDT.
        <br clear="all"/> 
        </p>
    </div>

    <?if($_SERVER['SERVER_NAME'] != "myosg-itb.grid.iu.edu") {?>
        <h3>Upcoming Release</h3>
        <div class="indent">
            <p>If you use MyOSG as a datasource for your script, please test it against <a target="_blank" href="http://myosg-itb.grid.iu.edu/"><b>MyOSG ITB Instance</b></a></p>
        </div>
    <?}?>

    <br><br>
    <div class="indent">

        <p><a target="_blank" href="https://spreadsheets.google.com/viewform?hl=en&formkey=dEd1bnlINzJVYmc4VGNjSVZkdXNVU3c6MQ#gid=0">
        <b>Feedback Form</b><br/>
        <img class="screenshot" src="<?=fullbase()?>/images/screenshots/feedback.jpg" align="right"/>
        </a>
        We'd like to hear from you about how we can improve MyOSG. Please submit your feedback.
        <br clear="all"/> 
        </p>

    </div>

</div>
<?=$this->render("full_footer.phtml", true)?>
