<?

foreach($this->vos as $vo) {
    echo "<h3>".$vo->Name[0]."</h3>"; 

    //ownership chart
    $attrs = $vo->attributes();
    $void = (int)$attrs["id"];
    $resources = $this->voownership[$void];
    echo "<div class=\"indent\">";
    if($resources !== null) {
        $out = "<table width='300'><tr><th>Resource Name</th><th>Percentage</th></tr>";
        $rclass = "rowA";
        foreach($resources as $resource) {
            if($rclass == "rowA") {
                $rclass = "rowB";
            } else {
                $rclass = "rowA";
            }
            //find resource info
            foreach($this->resources as $resinfo) {
                if($resinfo->id == $resource->resource_id) {
                    $url = base()."/current?resource_id=".$resinfo->id;
                    $out .= "<tr class='$rclass'><td><a href='$url'>".$resinfo->name."</a></td><td>".$resource->percent."%</td></tr>";
                    break;
                }
            }
        }
        $out .= "</table>";
        echo outputToggle("Show Resource Ownership", "Hide Resource Ownership", $out);
    } else {
        echo "This VO does not own any resource";
    }
    echo "</div>";

    //member resources

    $out = "";
    foreach($vo->Members[0]->Resource as $resource) {
        $url = base()."/current?resource_id=".$resource->ResourceID;
        $out .= "<a href=\"$url\">".$resource->ResourceName[0]."</a><br/>";
    }
    if($out == "") {
        echo "No Member Resources";
    } else {
        //echo "<h4>Member Resources</h4>";
        $out = "<p>$out<p>";
        echo "<div class=\"indent\">";
        echo outputToggle("Show Member Resources", "Hide Member Resources", $out);
        echo "</div>";
    }
    

}
