<?

foreach($this->vos as $vo) {
    echo "<h3>".$vo->Name[0]."</h3>"; 

    $out = "";
    foreach($vo->Members[0]->Resource as $resource) {
        $url = base()."/current?resource_id=".$resource->ResourceID;
        $out .= "<a href=\"$url\">".$resource->ResourceName[0]."</a><br/>";
    }
    if($out == "") {
        echo "No Member Resources";
    } else {
        //echo "<h4>Member Resources</h4>";
        $out = "<p>$out<p>";
        echo "<div class=\"indent\">";
        echo outputToggle("Show Member Resources", "Hide Member Resources", $out);
        echo "</div>";
    }
    

}
