<p class="info">Show basic information about Virtual Organization.</p>

<?$checked = "";
if(isset($_REQUEST["summary_attrs_showdesc"])) { $checked = "checked=checked"; }?>
<input type="checkbox" name="summary_attrs_showdesc" <?=$checked?>/> Show Description<br/>

<?$checked = "";
if(isset($_REQUEST["summary_attrs_showmember_resource"])) { $checked = "checked=checked"; }?>
<input type="checkbox" name="summary_attrs_showmember_resource" <?=$checked?>/> Show Member Resources<br/>

