
<style type="text/css">
.list
{
    padding: 2px;
    background-color: #eee;
    margin-bottom: 10px;
    margin-left: 16px;
    width: 90%;
}
.scrolled_list
{
    height: 160px;
    overflow: auto;
}
</style>

<form method="get" id="wizard">
    <input type="button" onclick="wizard_submit('index');" value="&nbsp;&nbsp;&nbsp;Update Page&nbsp;&nbsp;&nbsp;"/>
    <h3>Information to display</h3>
    <div class="indent" id="datasource_area">
        <select name="datasource">
        <option value="">(Please Select)</option>
        <option value="summary">Virtual Organization Summary</option>
        <option value="activation">Activation Status</option>
        <option value="vomsstatus">VOMS Status</option>
        </select>

        <p>

            <div id="summary_attrs" class="attrs indent hidden">
                <?=$this->render("vo/wizard_summary.phtml")?>
            </div>
            <div id="activation_attrs" class="attrs indent hidden">
                <?=$this->render("vo/wizard_activation.phtml")?>
            </div>
            <div id="_daterange_attrs" class="attrs indent hidden">
                <?=$this->render("rg/wizard__daterange.phtml")?>
            </div>
            <div id="vomsstatus_attrs" class="attrs indent hidden">
                <?=$this->render("vo/wizard_vomsstatus.phtml")?>
            </div>

        </p>
    </div>

    <div class="list_filter">

        <h3>VO to display</h3>
        <div class="indent">
            <div id="vo_area_standby">
                <p>Please select the information to display first.</p>
            </div>
            <div id="vo_area" class="hidden">
                <?
                $checked = "";
                if(isset($_REQUEST["all_vos"])) { $checked = "checked=checked"; }
                echo "<input type=\"checkbox\" name=\"all_vos\" $checked onclick=\"if(this.checked) { disable(this);} else {enable(this);}\"/> All Virtual Organization<br/>";

                echo "<div class=\"hidden list\" id=\"all_vos_attrs\">";
                    $checked = "";
                    if(isset($_REQUEST["show_disabled"])) { $checked = "checked=checked"; }
                    echo "<input type=\"checkbox\" name=\"show_disabled\" $checked/> Show Removed Virtual Organization<br/>";
                echo "</div>";

                $model = new VirtualOrganization();
                $vos = $model->get();
                $kv = array();
                foreach($vos as $vo) { $kv[$vo->id] = array($vo->name, $vo->long_name); }
                echo fblist("vo", "Specific Virtual Organization".helpbutton("Virtual_Organization"), $kv);
                
                ?>
            </div>
        </div>

        <h3>Filter By</h3>
        <div class="indent">
            <div id="filter_area_standby">
                <p>Please select the information to display first.</p>
            </div>
            <div id="filter_area" class="hidden">
                <?
                $kv = array();
                $kv[0] = "Inactive";
                $kv[1] = "Active";
                echo radiolist("active", "Active Status", $kv, 1); //1 by default

                $model = new SupportCenters();
                $scs = $model->get();
                $kv = array();
                foreach($scs as $sc) { 
                    //grab active, non-disabled records
                    if($sc->active == 1 and $sc->disable == 0) {
                        $kv[$sc->id] = array($sc->name, "");
                    }
                }
                echo fblist("sc", "VO Applications supported by following SCs".helpbutton("Support_Center"), $kv);
                ?>
            </div>
        </div>

        <h3>Sort By</h3>
        <div class="indent">
            <div id="sort_area_standby">
                <p>Please select the information to display sort options.</p>
            </div>
            <div id="sort_area" class="hidden">
                <?

                if(isset($_REQUEST["sort_key"])) {
                    $key = $_REQUEST["sort_key"];
                } else {
                    $key = "name";
                }

                $checked = "";
                if($key == "name") { $checked = "checked=checked"; }
                echo "<input type=\"radio\" name=\"sort_key\" $checked value=\"name\" /> Name<br/>";

                $checked = "";
                if($key == "long_name") { $checked = "checked=checked"; }
                echo "<input type=\"radio\" name=\"sort_key\" $checked value=\"long_name\" /> Long Name<br/>";

                $checked = "";
                if($key == "sc") { $checked = "checked=checked"; }
                echo "<input type=\"radio\" name=\"sort_key\" $checked value=\"sc\" /> Support Center<br/>";

                echo "<br/>";

                $checked = "";
                if(isset($_REQUEST["sort_reverse"])) { $checked = "checked=checked"; }
                echo "<input type=\"checkbox\" name=\"sort_reverse\" $checked /> Sort in reverse order<br/>";
                ?>
            </div>
        </div>

 
    </div>

    <br/>
    <input type="button" onclick="wizard_submit('index');" value="&nbsp;&nbsp;&nbsp;Update Page&nbsp;&nbsp;&nbsp;"/>
    <?=$this->render("subscribe.phtml")?>

</form>

<script type="text/javascript">

function showhide_attrs(show_speed)
{
    var v = $("select[name=datasource]").val();
    $(".attrs").hide();
    if(v != "") {
        $("#"+v+"_attrs").show(show_speed);
        $("#vo_area").show(show_speed);
        $("#filter_area").show(show_speed);
        $("#sort_area").show(show_speed);

        $("#vo_area_standby").hide();
        $("#filter_area_standby").hide();
        $("#sort_area_standby").hide();
        if(v == "activation") {
            $("#_daterange_attrs").show(show_speed);
        }
    } else {
        $("#vo_area").hide();
        $("#filter_area").hide();
        $("#sort_area").hide();

        $("#vo_area_standby").show();
        $("#filter_area_standby").show();
        $("#sort_area_standby").show();
    }
    if(v == "activation") {
        $('.list_filter').hide();
    } else {
        $('.list_filter').show();
    }
}

$(document).ready(function() {

    //setup form
    $("select[name=datasource]").change(function() {
        showhide_attrs('normal');
    });

    function list_click()
    {
        $("#all_vos_attrs").hide();
        if(this.checked) { $("input[name=all_vos]").attr("checked", ""); }
    }
    var items = $("input[name=all_vos]").siblings("input");
    $(items).click(list_click);


    <?
    //select currently selected datasouce
    if(isset($_REQUEST["datasource"])) {
        $datasource = $_REQUEST["datasource"];
        switch($datasource) {
        case "summary":
        case "activation":
        case "vomsstatus":
            echo "$('select[name=datasource] option[value=$datasource]').attr('selected', 'selected');\n";
            echo "showhide_attrs();\n";
        }
    }

    if(isset($_REQUEST["all_vos"])) {
        echo "disable($('input[name=all_vos]'));";
    }
    ?>
});

function wizard_submit(format)
{
    var action = '<?=fullbase()?>/vo'+$('select[name=datasource]').val(); 
    action += "/"+format;
    $('#wizard').attr('action', action);
    $('#wizard').submit(); 
    return false;
}

function disable(e)
{
    var items = $(e).siblings(); 
    $("#all_vos_attrs").show();

    $('#vo_area .fblist_container').hide();
    var items = $(e).siblings("input");
    $(items).attr('checked', '');
}

function enable(e)
{
    $("#all_vos_attrs").hide();
}

</script>
