
<style type="text/css">
.list
{
    padding: 2px;
    background-color: #eee;
    margin-bottom: 10px;
    margin-left: 16px;
    width: 90%;
}
.scrolled_list
{
    height: 160px;
    overflow: auto;
}
span.disabled_span
{
    color: gray;
}
</style>

<form method="get" id="wizard">
    <input type="button" onclick="wizard_submit('index');" value="&nbsp;&nbsp;&nbsp;Update Page&nbsp;&nbsp;&nbsp;"/>
    <h3>Information to display</h3>
    <div class="indent" id="datasource_area">
        <select name="datasource">
        <option value="">(Please Select)</option>
        <option value="summary">Virtual Organization Summary</option>
        </select>

        <div id="summary_attrs" class="attrs indent hidden">
            <?=$this->render("vo/wizard_summary.phtml")?>
        </div>
    </div>

    <h3>VO to display</h3>
    <div class="indent">
        <div id="vo_area_standby">
            <p>Please select the information to display first.</p>
        </div>
        <div id="vo_area" class="hidden">
            <p>Select VO that you want to show above information (conditions are or-ed).</p>
            <?
            $checked = "";
            if(isset($_REQUEST["all_vos"])) { $checked = "checked=checked"; }
            echo "<input type=\"checkbox\" name=\"all_vos\" $checked onclick=\"if(this.checked) { disable(this);} else {enable(this);}\"/> All Virtual Organization<br/>";
            echo "<div class=\"hidden list\" id=\"all_vos_attrs\">";
                $checked = "";
                if(isset($_REQUEST["show_disabled"])) { $checked = "checked=checked"; }
                echo "<input type=\"checkbox\" name=\"show_disabled\" $checked/> Show Removed Virtual Organization<br/>";
            echo "</div>";

            $model = new VirtualOrganization();
            $vos = $model->get();
            $kv = array();
            foreach($vos as $vo) { $kv[$vo->id] = $vo->name; }
            echo checklist("vo", "Specific Virtual Organization".helpbutton("Virtual_Organization"), $kv);
            
            ?>
        </div>
    </div>

    <h3>Filter</h3>
    <div class="indent">
        <div id="filter_area_standby">
            <p>Please select the information to display first.</p>
        </div>
        <div id="filter_area" class="hidden">
            <p>Only show VO that matches following criteria (conditions are and-ed).</p>
            <?
            $kv = array();
            $kv[0] = "Inactive";
            $kv[1] = "Active";
            echo radiolist("active", "Active Status", $kv, 1); //1 by default
            ?>
        </div>
    </div>

    <br/>
    <input type="button" onclick="wizard_submit('index');" value="&nbsp;&nbsp;&nbsp;Update Page&nbsp;&nbsp;&nbsp;"/>
    <?=$this->render("subscribe.phtml")?>
</form>

<script type="text/javascript">

function showhide_attrs(show_speed)
{
    var v = $("select[name=datasource]").val();
    $(".attrs").hide();
    if(v != "") {
        $("#"+v+"_attrs").show(show_speed);
        $("#vo_area").show(show_speed);
        $("#filter_area").show(show_speed);
        $("#vo_area_standby").hide();
        $("#filter_area_standby").hide();

        if(
            v == "foo_page_that_hasdatarange"
        ) {
            $("#_daterange_attrs").show(show_speed);
        }
    } else {
        $("#vo_area").hide();
        $("#filter_area").hide();
        $("#vo_area_standby").show();
        $("#filter_area_standby").show();
    }
}

$(document).ready(function() {

    //setup form
    $("select[name=datasource]").change(function() {
        showhide_attrs('normal');
    });

    <?
    //select currently selected datasouce
    if(isset($_REQUEST["datasource"])) {
        $datasource = $_REQUEST["datasource"];
        switch($datasource) {
        case "summary":
            echo "$('select[name=datasource] option[value=$datasource]').attr('selected', 'selected');\n";
            echo "showhide_attrs();\n";
        }
    }

    if(isset($_REQUEST["all_vos"])) {
        echo "disable($('input[name=all_vos]'));";
    }
    ?>
});

function wizard_submit(format)
{
    var action = '<?=fullbase()?>/vo'+$('select[name=datasource]').val(); 
    action += "/"+format;
    $('#wizard').attr('action', action);
    $('#wizard').submit(); 
    return false;
}

function disable(e)
{
    var items = $(e).siblings(); 
    $(items).find('input').attr('disabled', 'disabled');
    $(items).find('span').addClass('disabled_span');
    $("#all_vos_attrs").show();
    $("#all_vos_attrs").find('input').removeAttr('disabled');
}
function enable(e)
{
    var items = $(e).siblings(); 
    $(items).find('input').removeAttr('disabled');
    $(items).find('span').removeClass('disabled_span');
    $("#all_vos_attrs").hide();
    $("#all_vos_attrs").find('input').attr('disabled', 'disabled');
}
</script>
