<?
if(isset($_REQUEST["group"]) && $_REQUEST["group"] == "resource") {
    echo "<ResourceOwnerships>";
    foreach($this->resource_ownerships as $resource_id=>$ownership) {
        foreach($this->resources as $resource) {
            if($resource->id == $resource_id) {
                echo "<Resource>";
                echo "<ResourceID>".$resource->id."</ResourceID>";
                echo "<ResourceName>".$resource->name."</ResourceName>";
                echo "<Ownership>";
                $total = 0;
                foreach($ownership as $item) {
                    echo "<Percentage VO=\"".$item->name."\">".$item->percent."</Percentage>";
                    $total += $item->percent;
                }
                if($total < 100) {
                    $left = 100 - $total;
                    echo "<Percentage VO=\"other\">".$left."</Percentage>";
                }
                echo "</Ownership>";
                echo "</Resource>";
            }
        }
    }
    echo "</ResourceOwnerships>";
} else {
?>
    <VirtualOrganizations>
    <?
    foreach($this->vos as $vo) {
        echo "<VirtualOrganization>";
        echo "<Name>".$vo->Name[0]."</Name>"; 
        echo "<Members>";
        foreach($vo->Members[0]->Resource as $resource) {
            echo "<Resource>".$resource->ResourceName[0]."</Resource>";
        }
        echo "</Members>";
        echo "<ResourceOwnerships>";
        $attr = $vo->attributes();
        $id = (int)$attr->id[0];
        $ownerships = $this->voownership[$id];
        foreach($ownerships as $ownership) {
            $resource_name = "";
            //find resource info
            foreach($this->resources as $resinfo) {
                if($resinfo->id == $ownership->resource_id) {
                    $resource_name = $resinfo->name;
                }
            }

            echo "<ResourceOwnership>";
            echo "<ResourceID>".$ownership->resource_id."</ResourceID>";
            echo "<ResourceName>".$resource_name."</ResourceName>";
            echo "<Percentage>".$ownership->percent."</Percentage>";
            echo "</ResourceOwnership>";
        }
        echo "</ResourceOwnerships>";
        echo "</VirtualOrganization>";
    }
    ?>
    </VirtualOrganizations>
<?
}
?>
