<p class="info">You can edit your profile at <a target="_blank" href="https://oim.grid.iu.edu/oim/profileedit">OIM</a>. This page is only available for registered OIM users.</p>
<?
$model = new Contact();
$contacts = $model->getindex(array("person"=>1));
$kv = array();
foreach($contacts as $contact) {
    $contact = $contact[0];
    if($contact->disable == 1) continue;
    $kv[$contact->id] = array($contact->name, ""); 
}
echo fblist("contacts", "Show Following Users", $kv);



