<p class="info">Show number of services per grid type.</p>

<?

$checked = "";
if(isset($_REQUEST["count_total"])) { $checked = "checked=checked"; }
echo "<input type=\"checkbox\" name=\"count_total\" $checked/> Show Total Resource Count<br/>";

$model = new ServiceGroup();
$service_groups = $model->getindex();
echo "<h4>Service Groups</h4>";
foreach($service_groups as $id=>$service_group) {
    $checked = "";
    if(isset($_REQUEST["count_sg_".$id])) { $checked = "checked=checked"; }
    echo "<input type=\"checkbox\" name=\"count_sg_".$id."\" $checked/> Show ".$service_group[0]->name."<br/>";
}

