
<style type="text/css">
.list
{
    padding: 2px;
    background-color: #eee;
    margin-bottom: 10px;
    margin-left: 16px;
    width: 90%;
}
.scrolled_list
{
    height: 160px;
    overflow: auto;
}
span.disabled_span
{
    color: gray;
}
</style>

<form method="get" id="wizard">
    <div class="form-actions">
        <input type="button" class="btn btn-primary" onclick="wizard_submit('index');" value="&nbsp;&nbsp;&nbsp;Update Page&nbsp;&nbsp;&nbsp;"/>
    </div>
    <h3>Information to display</h3>
    <div id="datasource_area">
        <select id="datasource">
            <option value="">(Please Select)</option>
            <option value="miscmetric">RSV Metrics</option>
            <option value="misccpuinfo">CPU Information</option>
            <option value="miscproject">Projects</option>
            <option value="misccount">Resource Service Counts</option>
            <option value="miscstatus">Operations Status Overview</option>
            <option value="miscevent">GOC Realtime Events</option>
            <option value="pfmesh">Perfsonar Mesh Configurations</option>
            <?if(!user()->isGuest()) {?>
                <option value="miscuser">OSG Users</option>
            <?}?>
        </select>

        <p>
            <div id="miscmetric_attrs" class="attrs hidden">
                <?=$this->render("misc/wizard_metric.phtml")?>
            </div>
            <div id="misccpuinfo_attrs" class="attrs hidden">
                <?=$this->render("misc/wizard_cpuinfo.phtml")?>
            </div>
            <div id="miscproject_attrs" class="attrs hidden">
                <?=$this->render("misc/wizard_project.phtml")?>
            </div>
            <div id="misccount_attrs" class="attrs hidden">
                <?=$this->render("misc/wizard_count.phtml")?>
            </div>
            <div id="miscstatus_attrs" class="attrs hidden">
                <?=$this->render("misc/wizard_status.phtml")?>
            </div>
            <?if(!user()->isGuest()) {?>
                <div id="miscuser_attrs" class="attrs hidden">
                    <?=$this->render("misc/wizard_user.phtml")?>
                </div>
            <?}?>
            <div id="miscevent_attrs" class="attrs hidden">
                <?=$this->render("misc/wizard_event.phtml")?>
            </div>
        </p>
    </div>

    <?=$this->render("subscribe.phtml")?>
</form>

<script type="text/javascript">

function showhide_attrs(v, show_speed)
{
    //var v = $("select[name=datasource]").val();
    $(".attrs").hide();
    if(v != "") {
        $("#"+v+"_attrs").show(show_speed);
    }
}
$(document).ready(function() {

    //setup form
    $("#datasource").change(function() {
        showhide_attrs(this.value, 'normal');
    });

    <?
    //select currently selected datasouce
    $front = Zend_Controller_Front::getInstance();
    $controllerName = $front->getRequest()->getControllerName();
    echo "$('#datasource option[value=$controllerName]').attr('selected', 'selected');\n";
    echo "showhide_attrs('$controllerName');\n";

    if(isset($_REQUEST["all_vos"])) {
        echo "disable($('input[name=all_vos]'));";
    }
    ?>
});

function wizard_submit(format)
{
    var action = '<?=fullbase()?>/'+$('#datasource').val(); 
    action += "/"+format;
    $('#wizard').attr('action', action);
    $('#wizard').submit(); 
    return false;
}

</script>
