<link rel="stylesheet" type="text/css" href="<?=fullbase()?>/css/hierarchy.css"/>
<?
foreach($this->rgs as $resource_group_id=>$resource_list) {
    $resource_group = $this->resourcegroups[$resource_group_id][0];
    $gridtype_name = $this->gridtypes[$resource_group->osg_grid_type_id][0]->description;
    echo "<div class='resource_group_header round'>";
    if(!uwa()) {
        echo "<div class=\"sidenote\">";
        echo $gridtype_name. " Group";
        echo "</div>";
    }
    //echo "<div class=\"resource_group\">";
    $group_name = $resource_group->name;
/*
    if(isset($_REQUEST["summary_attrs_showhierarchy"])) {
        $hierarchy = $this->hierarchy[$resource_group_id];
        $group_name = "<span class=\"hierarchy\">".$hierarchy["facility"]." (Facility) &gt; ".$hierarchy["site"]." (Site) &gt; </span>".$group_name;
    }
*/

    if($resource_group->disable == 1) {
        $group_name .= " (Removed)";
    }
    echo "<span class='h3'>".$group_name."</span>";
    if(isset($_REQUEST["summary_attrs_showdesc"])) {
        echo "<br/>";
        if($resource_group->description != "") {
            echo $resource_group->description;
        } else {
            echo "(No resource group description)";
        }
    }

    //echo "</div>"; //resource_group
    echo "</div>"; //resourcee_group_header

    echo "<table class=\"summary_table\">";
    if(isset($_REQUEST["summary_attrs_showgipstatus"])) {
        echo "<tr>";
        echo "<th>GIP&nbsp;Validation</th>";
        echo "<td>";
        //search for the resultt
        $gipstatus = "NA";
        foreach($this->gipstatus as $gip) {
            if($resource_group->name == $gip->Name) {
                $gipstatus = (string)$gip->OverAllStatus;
                break;
            }
        } 
        switch($gipstatus) {
        case "OK":
            $status = "OK"; 
            $note = "GIP validation is passing all test";
            break;
        case "FAIL":
            $status = "CRITICAL";
            $note = "At least one test is failing";
            break;
        case "NA":
            $status = "UNKNOWN";
            $note = "GIP Validation is not available for this resource group";
            break;
        default:
            $status = "UNKNOWN";
            $note = "GIP Validation is returning unknown status";
        }

        $detail_url = htmlsafe(fullbase()."/rggipstatus/index?datasource=gipstatus&rg=on&rg_$resource_group_id=on&gip_status_attrs_showtestresults=on");
        $note = "<div>$note<br/><a href=\"$detail_url\">Validation Detail</a></div>";
        echo "<div class=\"status_$status\">";
        echo $note;
        echo "</div>";
        echo "</td></tr>";
    }

    if(isset($_REQUEST["summary_attrs_showhierarchy"])) {
        $hierarchy = $this->hierarchy[$resource_group_id];

        echo "<tr><th>OIM&nbsp;Hierarchy</th><td>";
    
        echo "<table width=\"100%\" class=\"plain\"><tr><td>";

            echo "<div class=\"hierarchy_facility round\">";
            echo "<b>".$hierarchy["facility"]->name."</b>&nbsp;<span>Facility</span>";

            echo "<div class=\"hierarchy_site round\">";
            echo "<b>".$hierarchy["site"]->name."</b>&nbsp;<span>Site</span>";

            echo "<div class=\"hierarchy_rg round\">";
            echo "<b>".$group_name."</b>&nbsp;<span>Resource Group</span>";

            echo "</div>"; //rg
            echo "</div>"; //site

            //show sigling sites
            foreach($this->sites as $site_id=>$site) {
                if($site_id == $hierarchy["site"]->id) continue;
                if($site[0]->facility_id == $hierarchy["facility"]->id) {
                    echo "<div style=\"width: 60%\" class=\"hierarchy_site round\">";
                    echo "<b>".$site[0]->name."</b>&nbsp;<span>Site</span>";
                    echo "</div>";
                }
            }

            echo "</div>"; //facility

        echo "</td><td>";
        
        echo "<div class=\"hierarchy_sc round\">";
        echo "<b>".$hierarchy["sc"]->name."</b> Support Center";
        echo "</div>";
        echo "<div class=\"hierarchy_supports\">";
        echo "Supports";
        echo "<img class=\"arrowhead\" src=\"".fullbase()."/images/arrow_head.png\"/>";
        echo "</div>";
        
        echo "</td></tr></table>";
        echo "</td></tr>";
    }
    echo "</table>";

    //show resources 
    echo "<table width=\"100%\">";
    if(count($resource_list) == 0) {
        echo "<tr><td colspan=2><p class=\"warning\">There are no resources that match your current filter</p></td></tr>";
    }
    foreach($resource_list as $rid=>$resource) {
        echo "<tr>";
        $disabled = "";
        if($resource->disable == 1) {
            $disabled = "disabled";
        }
        echo "<td class=\"$disabled\">";

        //show resource name & desc
        echo "<div class=\"round resource\">";
        echo "<a target=\"_gocticket\" href=\"".config()->gocticket_url."/resource?resource_type=".$resource_group->osg_grid_type_id."&resource_id=$rid\" class=\"sidenote\">";
        echo "<img src=\"".fullbase()."/images/tea.png\" alt=\"Open GOC Ticket\"/ title=\"Open GOC Ticket\"></a>";
        echo "<span class=\"h4\">".$resource->name."</span>";
        if($resource->disable == 1) {
            echo " (Removed)";
        }
        if($resource->active == 0) {
            echo " (Inactive)";
        }
        if(isset($_REQUEST["summary_attrs_showdesc"])) {
            echo "<br/>";
            if($resource->description != "") {
                echo $resource->description;
            } else {
                echo "(No resource description)";
            }
        }
        echo "</div>";

        ///////////////////////////////////////////////////////////////////////////////////////////
        //Optional Information
        echo "<table class='summary_table'>";
        if(isset($_REQUEST["summary_attrs_showservice"])) {
            echo "<tr>";
            echo "<th>Services</th>";
            echo "<td>";
            if(isset($this->resource_services[$rid]) == 0) {
                echo "This resource has no grid service.";
            } else {
                $services = $this->resource_services[$rid];
                $service_names = "";
                foreach($services as $service) {
                    echo "<div class=\"service_info\">";
                    echo "<div class=\"service round\">";
                    if(isset($this->servicetypes[$service->service_id])) {

                        $service_info = $this->servicetypes[$service->service_id][0];


                        if($service->central == 1) {
                            echo "<span class=\"round tag\" style=\"background-color: #99b\">Central Service</span>";
                        }
                        if($service->hidden == 1) {
                            echo "<span class=\"round tag\" style=\"background-color: #9b9\">Hidden Service</span>";
                        }

                        echo "<span class=\"sidenote fqdn\">";
                        if ($service->endpoint_override != "") {
                            //bold this since it's not default
                            echo "<b>$service->endpoint_override</b>";
                        } else {
                            echo $resource->fqdn.":".$service_info->port;
                        }
                        echo "</span>";


                        echo "<b>".htmlsafe($service_info->name)."</b>";

                    } else {
                        echo "(Unknown Service ID:".$service->service_id.")";
                    }
                    echo "</div>";
                    echo "</div>";
                }
            }
            echo "</td></tr>";
        }

        if(isset($_REQUEST["summary_attrs_showrsvstatus"])) {
            echo "<tr>";
            echo "<th>RSV&nbsp;Status</th>";
            echo "<td>";
            if(!isset($this->resource_status[$rid])) {
                $note = "<div>Resource status is not calculated for this resource.</div>";
                $status = "UNKNOWN";
            } else {
                $detail_url = htmlsafe(fullbase()."/rgcurrentstatus/index?datasource=currentstatus&rg=on&rg_$resource_group_id=on&end_type=now");
                $history_url = htmlsafe(fullbase()."/rgstatushistory/index?datasource=statushistory&start_type=7daysago&end_type=now&rg=on&rg_$resource_group_id=on");
                $resource_status = $this->resource_status[$rid][0];
                $note = "<div>".$resource_status->detail."<br/><a href=\"$detail_url\">Current Status Detail</a> <a href=\"$history_url\">Status History</a></div>";
                $status = Status::getStatus($resource_status->status_id);
            }

            if(isset($this->downtime[$rid])) {
                $downtime = $this->downtime[$rid][0];
                $instatus = $status;
                $status = "DOWNTIME";
                $downtime_desc = $downtime->downtime_summary;
                $internal_note = $note;
                $note = "This resource is currently under maintenance.<br/>";
                $note .= "<div class=\"downtime\"><b>Maintenance Summary:</b><div>$downtime_desc</div>";
                $note .= "<b>Internal status:</b><div class=\"status_$instatus\">$internal_note</div></div>";
            }

            echo "<div class=\"status_$status\">";
            echo $note;
            echo "</div>";
            echo "</td></tr>";
        }

        if(isset($_REQUEST["summary_attrs_showfqdn"])) {
            echo "<tr><th>FQDN</th><td>";
            echo htmlsafe($resource->fqdn);
            echo "</td></tr>";

            echo "<tr><th>FQDN Alias</th><td>";
            if(isset($this->aliases[$rid])) {
                foreach($this->aliases[$rid] as $alias) {
                    echo htmlsafe($alias->resource_alias);
                }
            } else {
                echo "(No Alias)";
            }
            echo "</td></tr>";
        }

        if(isset($_REQUEST["summary_attrs_showvomembership"])) {
            echo "<tr>";
            echo "<th>Supported&nbsp;VOs</th>";
            echo "<td>";
            if(isset($this->vos_supported[$rid])) {
                $volist = $this->vos_supported[$rid];
                $vonames = "";
                foreach($volist as $vo) {
                    $vo_name = $vo;
                    $attrs = $vo->attributes();
                    $vo_id = $attrs["id"];
                    $vonames .= "<span class=\"round tag\" style=\"background-color: gray\" onclick=\"document.location='".fullbase()."/vosummary/index?datasource=summary&vo=on&vo_$vo_id=on';\">$vo_name</span> ";
                }                
                echo $vonames;
            } else {
                echo "(Information not reported)";
            }
            echo "</td></tr>";
        }

        if(isset($_REQUEST["summary_attrs_showvoownership"])) {
            echo "<tr>";
            echo "<th>VO&nbsp;Ownership</th>";
            echo "<td>";
            if(!isset($this->resource_ownerships[$rid])) {
                echo "(Information not available)";
            } else {
                $ownership = $this->resource_ownerships[$rid];
                $chd = "";
                $chl = "";
                $total = 0;
                foreach($ownership as $item) {
                    if($chd != "") $chd .= ",";
                    $chd .= $item->percent;
                    if($chl != "") $chl .= "|";
                    $chl .= $item->name."(".$item->percent."%)";
                    $total += $item->percent;
                }
                if($total < 100) {
                    if($chd != "") $chd .= ",";
                    $left = 100 - $total;
                    $chd .= $left;
                    if($chl != "") $chl .= "|";
                    $chl .= "Other($left%)";
                }
                $background = "";
                if($resource->disable == 1) {
                    $background = "&chf=bg,s,eeeeee";
                }
                //for google chart api, look http://code.google.com/apis/chart/styles.html
                $url = "http://chart.apis.google.com/chart?chco=00cc00&cht=p3&chd=t:$chd&chs=280x65&chl=$chl$background";
                echo "<img src='$url'/>";
            }
            echo "</td></tr>";
        }

        if(isset($_REQUEST["summary_attrs_showwlcg"])) {
            echo "<tr><th>WLCG Information</th><td>";
            if(!isset($this->resource_wlcg[$rid][0]->interop_bdii)) {
                echo "(Information not available)<br/>";
            } else {
                $info = $this->resource_wlcg[$rid][0];
                echo "<table class=\"summary_subtable\">";

                $value = "False";
                if($info->interop_bdii == 1) { 
                    $value = "True ($info->ldap_url)"; 
                }
                echo "<tr><th>Interop BDII</th><td>$value</td></tr>";

                $value = "False";
                if($info->interop_monitoring == 1) { $value = "True"; }
                echo "<tr><th>Interop Monitoring</th><td>$value</td></tr>";

                $value = "False";
                if($info->interop_accounting == 1) { $value = "True"; }
                echo "<tr><th>Interop Accounting</th><td>$value</td></tr>";

                echo "<tr><th>Accounting Name</th><td>$info->accounting_name</td></tr>";
                echo "<tr><th>KSI2K Min</th><td>$info->ksi2k_minimum</td></tr>";
                echo "<tr><th>KSI2K Max</th><td>$info->ksi2k_maximum</td></tr>";
                echo "<tr><th>Storage Capacity Min</th><td>$info->storage_capacity_minimum TB</td></tr>";
                echo "<tr><th>Storage Capacity Max</th><td>$info->storage_capacity_maximum TB</td></tr>";
                echo "<tr><th>HEPSPEC Value</th><td>$info->hepspec</td></tr>";

                echo "</table>";
            }
            echo "</td></tr>";
        }

        if(isset($_REQUEST["summary_attrs_showenv"])) {
            echo "<tr><th>Environment Parameters</th><td>";
            $xml = @$this->envs[$rid];
            if($xml === null) {
                echo "<p class=\"warning\">Information Not available</p>";
            } else {
                echo "<table class=\"summary_subtable\">";
                foreach($xml as $key=>$value) {
                    echo "<tr><th>".htmlsafe($key)."</th><td>".htmlsafe($value)."</td></tr>";
                }
                echo "</table>";
            }
            echo "</td></tr>";
        }

        if(isset($_REQUEST["summary_attrs_showcontact"])) {
            echo "<tr><th>Contacts</th><td>";
            if(isset($this->contacts[$rid])) {
                $contact_types = $this->contacts[$rid];
                foreach($contact_types as $type_name=>$contacts) {
                    echo "<h4>$type_name</h4>";
                    foreach($contacts as $contact) {
                        if(user()->isGuest()) {
                            echo htmlsafe($contact->name)."<br/>";
                        } else {
                            echo "<div class=\"contact_info\">";
                            echo "<h3>".htmlsafe($contact->name)."</h3>";
                            echo "<table class=\"summary_subtable\">"; 
                            echo "<tr><th>Email</th><td>".emailaddress($contact->primary_email)."</td></tr>";
                            echo "<tr><th>Phone</th><td>".htmlsafe($contact->primary_phone)."</td></tr>";
                            if($contact->sms_address != null) {
                                echo "<tr><th>SMS Address</th><td>".htmlsafe($contact->sms_address)."</td></tr>";
                            }
                            echo "</table>";
                            echo "</div>";
                        }
                    }
                }
            }
            echo "</td></tr>";
        }

        echo "</table>";
        echo "</td>";
    }
    echo "</tr></table>";
}
