<?=$this->header?>
<ResourceENV>
<?
foreach($this->envs as $resource_id=>$xml) {
    $resource = $this->resources[$resource_id][0];
    echo "<Resource>";
    echo "<ID>".$resource->id."</ID>";
    echo "<Name>".$resource->name."</Name>";

    echo "<Active>";
    if($resource->active == 1) { 
        echo "True"; 
    } else {
        echo "False"; 
    }
    echo "</Active>";

    echo "<Disable>";
    if($resource->disable == 1) { 
        echo "True"; 
    } else {
        echo "False"; 
    }
    echo "</Disable>";

    echo "</Resource>";
}
?>
</ResourceENV>
