<?
$count_resources = 0;
foreach($this->resource_groups as $resource_group) {
    if(isset($this->resources_index[$resource_group->resource_group_id])) {
        $resource_list = $this->resources_index[$resource_group->resource_group_id];
        $count_resources += count($resource_list);

        if(count($resource_list) != 0) {
            echo "<div class=\"border\">";
            $gridtype_name = $this->gridtypes[$resource_group->osg_grid_type_id][0]->description;
            echo "<div class='resource_group_header'>";
            if(!isset($_REQUEST["uwa"])) {
                echo "<div class=\"sidenote\">";
                echo $gridtype_name;
                echo "</div>";
            }
            echo "<div class=\"resource_group\">";
            echo "<span class='h3'>".$resource_group->name."</span>";
            if(!isset($_REQUEST["uwa"])) {
                if($resource_group->description != "") {
                    echo "<br/>".$resource_group->description;
                }
            }
            echo "</div>";
            echo "</div>";

            $cols = 2; //number of columns to show
            if(isset($_REQUEST["uwa"])) {
                $cols = 1; //only show sequentially on UWA mode
            }
            $col_p = 100 / $cols;

            $col = 0; //current column 
            echo "<table width=\"100%\" style=\"margin: 0px;\"><tr>";
            foreach($resource_list as $resource) {
                $col++;
                if($col > $cols) {
                    $col = 1;
                    echo "</tr><tr>";
                }

                echo "<td style=\"padding: 0px;\" valign=\"top\" width=\"$col_p%\">";
                $rid = (int)$resource->resource_id;
                if(!isset($this->resource_status[$rid])) {
                    $note = "Resource status is not calculated for this resource...";
                    $status = "UNKNOWN";
                } else {
                    $resource_status = $this->resource_status[$rid][0];
                    $note = $resource_status->detail;
                    $status = Status::getStatus($resource_status->status_id);
                }

                //don't show resource with no services
                $services = @$this->resource_services[$rid];
                if(count($services) == 0) {
                    $service_names = "no applicable service exists";
                } else {
                    $service_names = "";
                    foreach($services as $service) {
                        if($service_names != "") $service_names .= " / ";
                        if(isset($this->servicetypes[$service->service_id])) {
                            $service_names .= $this->servicetypes[$service->service_id][0]->description;
                        } else {
                            $service_names .= "unknown_service_id:".$service->service_id;
                        }
                    }
                }
            
                echo "<div class=\"status_$status\"><h4><div class=\"resource\">".$resource->name." ($service_names)</div></h4>";
                echo "<span class=\"fqdn\">".$resource->fqdn."</span><br/>";
                echo "$note<br/>";

                //show various details requested
                if(isset($this->vos_supported)) {
                    $vonames = "";
                    if(isset($this->vos_supported[$resource->resource_id])) {
                        $volist = $this->vos_supported[$resource->resource_id];
                        foreach($volist as $vo) {
                            $vonames .= $vo." ";
                        }
                    }
                    if($vonames != "") {
                        $vonames .= "<br/>";
                        //echo outputToggle("Show Supported Virtual Organizations", "Hide Supported Virtual Organizations", $vonames);
                        echo "Supported Virtual Organizations: ".$vonames;
                    } else {
                        echo "Supported Virtual Organization information is not available for this resource.<br/>";
                    }
                }
            
                if(isset($this->resource_ownerships)) {
                    $ownership = $this->resource_ownerships[$resource->resource_id];
                    if($ownership === null) {
                        echo "Virtual Organization Ownership information is not available for this resource.<br/>";
                    } else {
                        $chd = "";
                        $chl = "";
                        $total = 0;
                        foreach($ownership as $item) {
                            if($chd != "") $chd .= ",";
                            $chd .= $item->percent;
                            if($chl != "") $chl .= "|";
                            $chl .= $item->short_name."(".$item->percent."%)";
                            $total += $item->percent;
                        }
                        if($total < 100) {
                            if($chd != "") $chd .= ",";
                            $left = 100 - $total;
                            $chd .= $left;
                            if($chl != "") $chl .= "|";
                            $chl .= "Other($left%)";
                        }
                        $url = "http://chart.apis.google.com/chart?chco=00cc00&cht=p3&chd=t:$chd&chs=270x65&chl=$chl";
                        echo "Virtual Ogranization Ownership<br/>";
                        echo "<img src='$url'/><br/>";
                    }
                }

                if(!isset($_REQUEST["uwa"])) {
                    $url = base()."/current?resource_id=".$resource->resource_id;
                    echo "<a href=\"$url\">Current Status</a>&nbsp;&nbsp;&nbsp;";
                    $url = base()."/history?resource_id=".$resource->resource_id;
                    echo "<a href=\"$url\">Status History</a>&nbsp;&nbsp;&nbsp;";
                }

                echo "</div>";
                echo "</td>";
            }
            echo "</tr></table>";

            echo "</div>";
        }
    }
}

if($count_resources == 0) {
    echo "<p>No resource group / resource matches the current filter options.</p>";
}
