<?

$count_resources = 0;
foreach($this->resource_groups as $resource_group) {
    if(isset($this->resources_index[$resource_group->id])) {
        $resource_list = $this->resources_index[$resource_group->id];
        $count_resources += count($resource_list);

        if(count($resource_list) != 0) {
            echo "<div class=\"resource_group\">";
            $gridtype_name = $this->gridtypes[$resource_group->osg_grid_type_id][0]->description;
            echo "<h3>".$resource_group->name."</h3>";

            if(!isset($_REQUEST["uwa"])) {
                echo "<div class=\"sidenote\">";
                echo $gridtype_name;
                echo "</div>";
                if($resource_group->description != "") {
                    echo "<p>".$resource_group->description."</p>";
                }
            }

            foreach($resource_list as $resource) {

                if(!isset($this->resource_status[$resource->id])) {
                    elog("Resource Status for ".$resource->id." is unknown...");
                    $note = "";
                    $status = "";
                    $services = array();
                } else {
                    $resource_status = $this->resource_status[$resource->id];
                    $note = $resource_status->Note[0];
                    $status = $resource_status->Status[0];
                    $services = $this->resource_services[$resource->id];
                }

                //don't show resource with no services
                if(count($services) == 0) continue;

                $service_names = "";

                foreach($services as $service) {
                    if($service_names != "") $service_names .= " / ";
                    if(isset($this->servicetypes[$service->service_id])) {
                        $service_names .= $this->servicetypes[$service->service_id][0]->description;
                    } else {
                        $service_names .= "unknown_service_id:".$service->service_id;
                    }
                }
            
                echo "<div class=\"status_$status\"><h4>".$resource->name." ($service_names)</h4>";
                echo "<span class=\"fqdn\">".$resource->fqdn."</span><br/>";
                echo "$note<br/>";

                if(!isset($_REQUEST["uwa"])) {
                    $vonames = "";
                    if(isset($this->vos[$resource->id])) {
                        $volist = $this->vos[$resource->id];
                        foreach($volist as $vo) {
                            $vonames .= $vo." ";
                        } 
                    }
                    if($vonames != "") {
                        $vonames .= "<br/>";
                        echo outputToggle("Show Supported Virtual Organizations", "Hide Supported Virtual Organizations", $vonames);
                    }
                }

                if(!isset($_REQUEST["uwa"])) {
                    $url = base()."/current?resource_id=".$resource->id;
                    echo "<a href=\"$url\">Current Status</a>&nbsp;&nbsp;&nbsp;";
                }            
                if(!isset($_REQUEST["uwa"])) {
                    $url = base()."/history?resource_id=".$resource->id;
                    echo "<a href=\"$url\">Status History</a>&nbsp;&nbsp;&nbsp;";
                }

                echo "</div>";
            }

            echo "</div>";
        }
    }
}

if($count_resources == 0) {
    echo "<p>No resource group / resource matches the current filter options.</p>";
}
