<?=$this->render("full_header.phtml", true)?>
        <div id="primaryContentContainer">
            <div id="primaryContent">
                <div id="breadcrumb"><p>You are here &gt; <?=$this->page_title?></p> </div>
                <h2><?=$this->page_title?></h2>
                <?=$this->render(pagename()."/html.phtml")?>
            </div>
        </div>
        <div id="sideContent">
            <h3>Filter</h3>
            <?
            $model = new ResourceGroup();
            outputSelectBox("resourcegroup", "Resource Group", $model, "id", "name");
            $gridtypes = new GridTypes();
            outputSelectBox("gridtype", "Grid Type", $gridtypes, "grid_type_id", "short_name"/*"description"*/);
            $model = new VirtualOrganization();
            outputSelectBox("vo", "Supported Virtual Organization", $model, "vo_id", "short_name");
            $servicetypes = new ServiceTypes();
            outputSelectBox("servicetype", "Sevice Type", $servicetypes, "service_id", "description");
            $status_model = new Status();
            outputSelectBox("status", "Resource Status", $status_model, "metric_status_description", "metric_status_description");

            outputClearFilterButton();
            ?>

            <h3>Subscribe</h3>
            <h4>Subscribe to Current View</h4>
            <?
            $param = $_SERVER["QUERY_STRING"];
            $moduleurl = urlencode(fullbase()."/".pagename()."/uwa?$param");
            ?>
            <p><a href="http://www.netvibes.com/subscribe.php?module=UWA&moduleUrl=<?=$moduleurl?>"><img src="images/subscribe.png"/></a></p>
            <p><a href="http://www.google.com/ig/add?moduleurl=http%3A%2F%2Fwww.netvibes.com%2Fapi%2Fuwa%2Fcompile%2Fgoogle.php%3FmoduleUrl%3D<?=urlencode($moduleurl)?>"><img src="images/google.png"/></a></p>
            <p><a href="<?=fullbase()?>/<?=pagename()?>/xml?<?=$param?>">XML</a></p>

            <h4>Subscribe to Status Changes</h4>
            <p><a href="<?=fullbase()?>/statuschanges/rss?<?=$param?>"><img src="images/atom_feed.gif"/></a></p>
            <p>

<a href="http://www.addthis.com/feed.php?pub=soichih&h1=http%3A%2F%2Frsv.grid.iu.edu%2Ftrunk%2Fstatuschanges%2Frss&t1=" title="Subscribe using any feed reader!"><img src="http://s7.addthis.com/button0-fd.gif" width="83" height="16" border="0" alt="AddThis Feed Button" /></a>

            </p>

        </div>
<?=$this->render("full_footer.phtml", true)?>
