<?=$this->render("full_header.phtml", true)?>
        <div id="primaryContentContainer">
            <div id="primaryContent">
                <?=$this->render("breadcrumb.phtml", true)?>
                <h2><?=$this->page_title?></h2>
                <?=$this->render(pagename()."/html.phtml")?>
            </div>
        </div>
        <div id="sideContent">
            <h3>Filter</h3>
            <?
            $model = new ResourceGroup();
            outputSelectBox("resourcegroup", "Resource Group", $model, "resource_group_id", "name");

            $gridtypes = new GridTypes();
            outputSelectBox("gridtype", "Grid Type", $gridtypes, "grid_type_id", "short_name"/*"description"*/);

            $model = new VirtualOrganization();
            outputSelectBox("vo", "Supported Virtual Organization", $model, "vo_id", "short_name");
            echo "<div class='indent'><p>* Show resources that supports selected VO.</p></div>";
            outputSelectBox("voowner", "Virtual Organization Ownership", $model, "vo_id", "short_name");
            echo "<div class='indent'><p>* Show resources that are owned by selected VO.</p></div>";

            $params = array();
            $params["service_group_id"] = 1;
            $servicetypes = new ServiceTypes($params);
            outputSelectBox("servicetype", "Sevice Type", $servicetypes, "service_id", "description");

            $status_model = new Status();
            outputSelectBox("status", "Resource Status", $status_model, "metric_status_description", "metric_status_description");

            outputClearFilterButton();

            echo "<h3>Additional Details</h3>";
            echo "Virtual Organization:<br/>";
            outputCheckboxList("detail", array("vomembers"=>"VO Membership", "voowner"=>"VO Ownership Graph"));
            ?>

            <h3>Subscribe</h3>
            <h4>Subscribe to Current View</h4>
            <?
            $param = $_SERVER["QUERY_STRING"];
            $moduleurl = urlencode(fullbase()."/".pagename()."/uwa?$param");
            ?>
            <p><a href="http://www.netvibes.com/subscribe.php?module=UWA&moduleUrl=<?=$moduleurl?>"><img src="images/subscribe.png"/></a></p>
            <p><a href="http://www.google.com/ig/add?moduleurl=http%3A%2F%2Fwww.netvibes.com%2Fapi%2Fuwa%2Fcompile%2Fgoogle.php%3FmoduleUrl%3D<?=urlencode($moduleurl)?>"><img src="images/google.png"/></a></p>
            <p><a href="<?=fullbase()?>/<?=pagename()?>/xml?<?=$param?>">XML</a></p>

            <h4>Subscribe to Status Changes</h4>
            <p><a href="<?=fullbase()?>/statuschanges/rss?<?=$param?>"><img src="images/atom_feed.gif"/></a></p>
            <p>

            </p>
            <?=$this->render("status_legend.phtml", true)?>
            <?=$this->render("feedback.phtml", true)?>
        </div>
<?=$this->render("full_footer.phtml", true)?>
