<?=$this->render("full_header.phtml", true)?>
        <div id="primaryContentContainer">
            <div id="primaryContent">
                <div id="breadcrumb"><p>You are here &gt; <?=$this->page_title?></p> </div>
                <h2><?=$this->page_title?></h2>
                <?=$this->render("resources/html.phtml")?>
            </div>
        </div>
        <div id="sideContent">
            <h3>Filter</h3>
            <?
            $model = new ResourceGroup();
            outputSelectBox("resourcegroup", "Resource Group", $model, "id", "name");
            $gridtypes = new GridTypes();
            outputSelectBox("gridtype", "Grid Type", $gridtypes, "grid_type_id", "description");
            $servicetypes = new ServiceTypes();
            outputSelectBox("servicetype", "Sevice Type", $servicetypes, "service_id", "description");
            $status_model = new Status();
            outputSelectBox("status", "Resource Status", $status_model, "metric_status_description", "metric_status_description");

            outputClearFilterButton();
            ?>

            <h3>Subscribe</h3>
            <?
            $param = $_SERVER["QUERY_STRING"];
            $moduleurl = urlencode(fullbase()."/resources/uwa?$param");
            ?>
            <p><a href="http://www.netvibes.com/subscribe.php?module=UWA&moduleUrl=<?=$moduleurl?>"><img src="images/subscribe.png"/></a></p>
            <p><a href="http://www.google.com/ig/add?moduleurl=http%3A%2F%2Fwww.netvibes.com%2Fapi%2Fuwa%2Fcompile%2Fgoogle.php%3FmoduleUrl%3D<?=urlencode($moduleurl)?>"><img src="images/google.png"/></a></p>
            <p><a href="<?=base()?>/resources/xml?<?=$param?>">XML</a></p>

            <? //echo $this->render("full_menu.phtml", true); ?> 
        </div>
<?=$this->render("full_footer.phtml", true)?>
