<ResourceGroups>
<?
foreach($this->resource_groups as $resource_group) {
    if(isset($this->resources_index[$resource_group->id])) {
        $resource_list = $this->resources_index[$resource_group->id];

        if(count($resource_list) != 0) {
            echo "<ResourceGroup>";
            $gridtype_name = $this->gridtypes[$resource_group->osg_grid_type_id][0]->description;
            echo "<ID>".$resource_group->osg_grid_type_id."</ID>";
            echo "<Name>".$resource_group->name."</Name>";
            echo "<GridType>$gridtype_name</GridType>";
            echo "<Description>".$resource_group->description."</Description>";

            echo "<Resource>";
            foreach($resource_list as $resource) {

                $resource_status = $this->resource_status[$resource->id];
                $note = $resource_status->Note[0];
                $status = $resource_status->Status[0];
                $services = $this->resource_services[$resource->id];

                if(count($services) == 0) continue;
                
                $service_names = "";
                echo "<Services>";
                foreach($services as $service) {
                    if($service_names != "") $service_names .= " / ";
                    echo "<Service>";
                    echo "<Name>".$this->servicetypes[$service->service_id][0]->description."</Name>";
                    echo "</Service>";
                }
                echo "</Services>";
            
                echo "<Status>$status</Status>";
                echo "<Name>".$resource->name."</Name>";
                echo "<Fqdn>".$resource->fqdn."</Fqdn>";
                echo "<Note>$note</Note>";
            }
            echo "</Resource>";
            echo "</ResourceGroup>";
        }
    }
}
?>
</ResourceGroups>
