<?=$this->header?>
<StatusHistory>
<?
echo "<StartTime>$this->start_time</StartTime>";
echo "<EndTime>$this->end_time</EndTime>";
foreach($this->resources as $rid=>$resource)
{
    echo "<Resource>";
    echo "<Name>".htmlsafe($resource->name)."</Name>";
    echo "<ID>$rid</ID>";
    
    foreach($this->services[$rid] as $service) {
        echo "<Service>";
        echo "<Description>".htmlsafe($service->description)."</Description>";
        echo "<ID>$service->service_id</ID>";
        echo "<GraphURL>";
        $url = fullbase()."/history/graph?resource_id=$rid&amp;&service_id=$service->service_id&amp;start=$this->start_time&amp;end=$this->end_time";
        echo htmlsafe($url);
        echo "</GraphURL>";
        echo "</Service>";
    }
    echo "</Resource>";
}
?>
</StatusHistory>
