<?
foreach($this->resource_groups as $resource_group_id=>$resource_list) {
    $resource_group = $this->resourcegroups[$resource_group_id][0];
    echo "<div class=\"border\">";
    $gridtype_name = $this->gridtypes[$resource_group->osg_grid_type_id][0]->description;
    echo "<div class='resource_group_header'>";
    if(!uwa()) {
        echo "<div class=\"sidenote\">";
        echo $gridtype_name;
        echo "</div>";
    }
    echo "<div class=\"resource_group\">";
    echo "<span class='h3'>".$resource_group->name."</span>";
    if(!uwa()) {
        if(isset($_REQUEST["summary_attrs_showdesc"])) {
            echo "<br/>";
            if($resource_group->description != "") {
                echo $resource_group->description;
            } else {
                echo "(No resource group description)";
            }
        }
    }
    echo "</div>";
    echo "</div>";

    $cols = 2; //number of columns to show
    if(uwa()) {
        $cols = 1; //only show sequentially on UWA mode
    }
    $col_p = 100 / $cols;

    $col = 0; //current column 
    echo "<table width=\"100%\" style=\"margin: 0px;\"><tr>";
    foreach($resource_list as $rid=>$resource) {
        $col++;
        if($col > $cols) {
            $col = 1;
            echo "</tr><tr>";
        }

        echo "<td style=\"padding: 0px;\" valign=\"top\" width=\"$col_p%\">";
        if(!isset($this->resource_status[$rid])) {
            $note = "<div>Resource status is not calculated for this resource</div>";
            $status = "UNKNOWN";
        } else {
            $resource_status = $this->resource_status[$rid][0];
            $note = "<div>".$resource_status->detail."</div>";
            $status = Status::getStatus($resource_status->status_id);
        }

        if(isset($this->downtime[$rid])) {
            $downtime = $this->downtime[$rid][0];
            $status = "DOWNTIME";
            $downtime_desc = $downtime->downtime_summary;
            $internal_note = $note;
            $note = "This service is currently under maintenance.<br/>";
            $note .= "<div style='background-color: #ddf; padding: 3px;'><b>Maintenance Summary:</b><div>$downtime_desc</div>";
            $note .= "<b>Internal status:</b>$internal_note</div>";
        }

        $services = $this->resource_services[$rid];
        if(count($services) == 0) {
            $service_names = "no applicable service exists";
        } else {
            $service_names = "";
            foreach($services as $service) {
                if($service_names != "") $service_names .= " / ";
                if(isset($this->servicetypes[$service->service_id])) {
                    $service_names .= $this->servicetypes[$service->service_id][0]->description;
                } else {
                    $service_names .= "unknown_service_id:".$service->service_id;
                }
            }
        }
    
        if(uwa()) {
            $cls = "";
        } else {
            $cls = "resource";
        }
        echo "<div class=\"status_$status\"><h4><div class=\"$cls\">".$resource->name." ($service_names)</div></h4>";
        echo $note;

        if(isset($_REQUEST["summary_attrs_showdesc"])) {
            echo "<b>Description:</b> ";
            echo "<div>";
            if($resource->description != "") {
                echo $resource->description;
            } else {
                echo "(No resource description)";
            }
            echo "</div>";
        }
        if(isset($_REQUEST["summary_attrs_showfqdn"])) {
            echo "<div><span class=\"fqdn\">".$resource->fqdn."</span></div>";
        }
        if(isset($_REQUEST["summary_attrs_showvomembership"])) {
            echo "<b>Supported VOs: </b>";
            echo "<div>";
            if(isset($this->vos_supported[$rid])) {
                $volist = $this->vos_supported[$rid];
                $vonames = "";
                foreach($volist as $vo) {
                    $vonames .= $vo." ";
                }                
                echo $vonames;
            } else {
                echo "(Information not reported)";
            }
            echo "</div>";
        }
        if(isset($_REQUEST["summary_attrs_showvoownership"])) {
            echo "<b>This resource is owned by following VO(s):</b>";
            echo "<div>";
            if(!isset($this->resource_ownerships[$rid])) {
                echo "(Information not available)<br/>";
            } else {
                $ownership = $this->resource_ownerships[$rid];
                $chd = "";
                $chl = "";
                $total = 0;
                foreach($ownership as $item) {
                    if($chd != "") $chd .= ",";
                    $chd .= $item->percent;
                    if($chl != "") $chl .= "|";
                    $chl .= $item->short_name."(".$item->percent."%)";
                    $total += $item->percent;
                }
                if($total < 100) {
                    if($chd != "") $chd .= ",";
                    $left = 100 - $total;
                    $chd .= $left;
                    if($chl != "") $chl .= "|";
                    $chl .= "Other($left%)";
                }
                $url = "http://chart.apis.google.com/chart?chco=00cc00&cht=p3&chd=t:$chd&chs=280x65&chl=$chl";
                echo "<img src='$url'/><br/>";
            }
            echo "</div>";
        }


        echo "</div>";
        echo "</td>";
    }
    echo "</tr></table>";

    echo "</div>";
}
