<?
foreach($this->resource_groups as $resource_group_id=>$resource_list) {
    $resource_group = $this->resourcegroups[$resource_group_id][0];
    $gridtype_name = $this->gridtypes[$resource_group->osg_grid_type_id][0]->description;
    echo "<div class='resource_group_header round'>";
    if(!uwa()) {
        echo "<div class=\"sidenote\">";
        echo $gridtype_name. " Group";
        echo "</div>";
    }
    echo "<div class=\"resource_group\">";
    if($resource_group->disable == 1) {
        $group_name .= " (Removed)";
    }
    if($resource_group->active == 0) {
        $group_name .= " (Inactive)";
    }
    $group_name = $resource_group->name;
    echo "<span class='h3'>".$group_name."</span>";
    if(isset($_REQUEST["summary_attrs_showdesc"])) {
        echo "<br/>";
        if($resource_group->description != "") {
            echo $resource_group->description;
        } else {
            echo "(No resource group description)";
        }
    }
    echo "</div>";
    echo "</div>";

    $cols = 1; //number of columns to show
    if(uwa()) {
        $cols = 1; //only show sequentially on UWA mode
    }
    $col_p = 100 / $cols;

    $col = 0; //current column 
    echo "<table width=\"100%\"><tr>";
    foreach($resource_list as $rid=>$resource) {
        $col++;
        if($col > $cols) {
            $col = 1;
            echo "</tr><tr>";
        }

        $disabled = "";
        if($resource->disable == 1) {
            $disabled = "disabled";
        }
        echo "<td width=\"$col_p%\" class=\"$disabled\">";

        //show resource name & desc
        echo "<div class=\"round resource\">";
        echo "<span class=\"h4\">".$resource->name."</span>";
        if($resource->disable == 1) {
            echo " (Removed)";
        }
        if($resource->active == 0) {
            echo " (Inactive)";
        }
        if(isset($_REQUEST["summary_attrs_showdesc"])) {
            echo "<br/>";
            if($resource->description != "") {
                echo $resource->description;
            } else {
                echo "(No resource description)";
            }
        }
        echo "</div>";

        ///////////////////////////////////////////////////////////////////////////////////////////
        //Optional Information
        echo "<table class='summary_table'>";

        if(isset($_REQUEST["summary_attrs_showservice"])) {
            echo "<tr>";
            echo "<th>Services</th>";
            echo "<td>";
            if(isset($this->resource_services[$rid]) == 0) {
                $service_names = "no applicable service exists";
            } else {
                $services = $this->resource_services[$rid];
                $service_names = "";
                foreach($services as $service) {
                    if($service_names != "") $service_names .= "<br/>";

                    $service_name = "";
                    if(isset($this->servicetypes[$service->service_id])) {
                        $service_info = $this->servicetypes[$service->service_id][0];
                        $service_name .= $service_info->description;

                        //Service URI
                        $service_name .= "<span class=\"fqdn\"> (";
                        if ($service->endpoint_override != "") {
                          $service_name .= $service->endpoint_override;
                        } else {
                          $service_name .= $resource->fqdn.":".$service_info->port;
                        }
                        $service_name .= ")</span>";

                    } else {
                        $service_name .= "unknown_service_id:".$service->service_id;
                    }

                    $service_names .= $service_name;
                }
            }
            echo $service_names;
            echo "</td></tr>";
        }
        if(isset($_REQUEST["summary_attrs_showrsvstatus"])) {
            echo "<tr>";
            echo "<th>RSV&nbsp;Status</th>";
            echo "<td>";
            if(!isset($this->resource_status[$rid])) {
                $note = "<div>Resource status is not calculated for this resource.</div>";
                $status = "UNKNOWN";
            } else {
                $detail_url = htmlentities(fullbase()."/wizardcurrentstatus/index?datasource=currentstatus&r=on&r_$rid=on");
                $history_url = htmlentities(fullbase()."/wizardstatushistory/index?datasource=statushistory&start_type=7daysago&end_type=today&r=on&r_$rid=on");
                $resource_status = $this->resource_status[$rid][0];
                $note = "<div>".$resource_status->detail."<br/><a href=\"$detail_url\">Status Detail</a> <a href=\"$history_url\">Status History</a></div>";
                $status = Status::getStatus($resource_status->status_id);
            }

            if(isset($this->downtime[$rid])) {
                $downtime = $this->downtime[$rid][0];
                $instatus = $status;
                $status = "DOWNTIME";
                $downtime_desc = $downtime->downtime_summary;
                $internal_note = $note;
                $note = "This resource is currently under maintenance.<br/>";
                $note .= "<div class=\"downtime\"><b>Maintenance Summary:</b><div>$downtime_desc</div>";
                $note .= "<b>Internal status:</b><div class=\"status_$instatus\">$internal_note</div></div>";
            }

            echo "<div class=\"status_$status\">";
            echo $note;
            echo "</div>";
            echo "</td></tr>";
        }

        if(isset($_REQUEST["summary_attrs_showgipstatus"])) {
            echo "<tr>";
            echo "<th>GIP&nbsp;Validation</th>";
            echo "<td>";
            //search for the resultt
            $gipstatus = "NA";
            foreach($this->gipstatus as $gip) {
                if($resource->name == $gip->Name) {
                    $gipstatus = (string)$gip->OverAllStatus;
                    break;
                }
            } 
            switch($gipstatus) {
            case "OK":
                $status = "OK"; 
                $note = "GIP validation is passing all test.";
                break;
            case "FAIL":
                $status = "CRITICAL";
                $note = "At least one test is failing";
                break;
            case "NA":
                $status = "UNKNOWN";
                $note = "GIP Validation is not available for this resource.";
                break;
            default:
                $status = "UNKNOWN";
                $note = "GIP Validation is returning unknown status.";
            }

            $detail_url = htmlentities(fullbase()."/wizardgipstatus/index?datasource=gipstatus&r=on&r_$rid=on");
            $note = "<div>$note<br/><a href=\"$detail_url\">Validation Detail</a></div>";
            echo "<div class=\"status_$status\">";
            echo $note;
            echo "</div>";
            echo "</td></tr>";
        }

        if(isset($_REQUEST["summary_attrs_showfqdn"])) {
            echo "<tr><th>FQDN</th><td>";
            echo "<span class=\"fqdn\">".$resource->fqdn."</span>";
            echo "</td></tr>";
        }

        if(isset($_REQUEST["summary_attrs_showvomembership"])) {
            echo "<tr>";
            echo "<th>Supported&nbsp;VOs</th>";
            echo "<td>";
            if(isset($this->vos_supported[$rid])) {
                $volist = $this->vos_supported[$rid];
                $vonames = "";
                foreach($volist as $vo) {
                    $vo_name = $vo;
                    $attrs = $vo->attributes();
                    $vo_id = $attrs["id"];
                    $vonames .= "<a href=\"".fullbase()."/vosummary/index?datasource=summary&vo=on&vo_".$vo_id."=on"."\">".$vo_name."</a> ";
                }                
                echo $vonames;
            } else {
                echo "(Information not reported)";
            }
            echo "</td></tr>";
        }

        if(isset($_REQUEST["summary_attrs_showvoownership"])) {
            echo "<tr>";
            echo "<th>VO&nbsp;Ownership</th>";
            echo "<td>";
            if(!isset($this->resource_ownerships[$rid])) {
                echo "(Information not available)";
            } else {
                $ownership = $this->resource_ownerships[$rid];
                $chd = "";
                $chl = "";
                $total = 0;
                foreach($ownership as $item) {
                    if($chd != "") $chd .= ",";
                    $chd .= $item->percent;
                    if($chl != "") $chl .= "|";
                    $chl .= $item->name."(".$item->percent."%)";
                    $total += $item->percent;
                }
                if($total < 100) {
                    if($chd != "") $chd .= ",";
                    $left = 100 - $total;
                    $chd .= $left;
                    if($chl != "") $chl .= "|";
                    $chl .= "Other($left%)";
                }
                $url = "http://chart.apis.google.com/chart?chco=00cc00&cht=p3&chd=t:$chd&chs=280x65&chl=$chl";
                echo "<img src='$url'/>";
            }
            echo "</td></tr>";
        }

        if(isset($_REQUEST["summary_attrs_showwlcg"])) {
            echo "<tr><th>WLCG Information</th><td>";
            $info = @$this->resource_wlcg[$rid][0];
            if($info == null) {
                echo "(Information not available)<br/>";
            } else {
                echo "<table class=\"summary_subtable\">";

                $value = "False";
                if($info->interop_bdii == 1) { 
                    $value = "True ($info->ldap_url)"; 
                }
                echo "<tr><th>Interop BDII</th><td>$value</td></tr>";

                $value = "False";
                if($info->interop_monitoring == 1) { $value = "True"; }
                echo "<tr><th>Interop Monitoring</th><td>$value</td></tr>";

                $value = "False";
                if($info->interop_accounting == 1) { $value = "True"; }
                echo "<tr><th>Interop Accounting</th><td>$value</td></tr>";

                echo "<tr><th>Accounting Name</th><td>$info->accounting_name</td></tr>";
                echo "<tr><th>KSI2K Min</th><td>$info->ksi2k_minimum</td></tr>";
                echo "<tr><th>KSI2K Max</th><td>$info->ksi2k_maximum</td></tr>";
                echo "<tr><th>Storage Capacity Min</th><td>$info->storage_capacity_minimum TB</td></tr>";
                echo "<tr><th>Storage Capacity Max</th><td>$info->storage_capacity_maximum TB</td></tr>";


                echo "</table>";
            }
            echo "</td></tr>";
        }

        if(isset($_REQUEST["summary_attrs_showenv"])) {
            echo "<tr><th>Environment Parameters</th><td>";
            $xml = @$this->envs[$rid];
            if($xml === null) {
                echo "<p class=\"warning\">Information Not available</p>";
            } else {
                echo "<table class=\"summary_subtable\">";
                foreach($xml as $key=>$value) {
                    echo "<tr><th>".htmlentities($key)."</th><td>".htmlentities($value)."</td></tr>";
                }
                echo "</table>";
            }
            echo "</td></tr>";
        }
        if(isset($_REQUEST["summary_attrs_showcontact"])) {
            echo "<tr><th>Contacts</th><td>";
            $contact_types = @$this->contacts[$rid];
            foreach($contact_types as $type_name=>$contacts) {
                echo "<h4>$type_name</h4>";
                foreach($contacts as $contact) {
                    if(user()->isGuest()) {
                        echo htmlentities($contact->name)."<br/>";
                    } else {
                        echo "<div class=\"contact_info\">";
                        echo "<h3>".htmlentities($contact->name)."</h3>";
                        echo "<table class=\"summary_subtable\">"; 
                        echo "<tr><th>Email</th><td>".emailaddress($contact->primary_email)."</td></tr>";
                        echo "<tr><th>Phone</th><td>".htmlentities($contact->primary_phone)."</td></tr>";
                        echo "</table>";
                        echo "</div>";
                    }
                }
            }
            echo "</td></tr>";
        }

        echo "</table>";
        echo "</td>";
    }
    echo "</tr></table>";
}
