<!--
This XML contains the requested resource summary information.

Structure:
    * () shows number of elements. N means there could be any number of them

    ResourceSummary (1)
        ResourceGroup (N)
            GridType (1)                                Grid Type for the resource group
            GroupName (1)                               Name of the Resource Group
            GroupDescription (0 or 1)                   Description for the resource group as stored in OIM
            Resources (1)
                Resource (N)
                    Name (1)                            Name of the resource
                    Services (0 or 1)                   Services that are supported by this resource
                        Service (N)
                            Name (1)                    Name of the service
                    Description (0 or 1)
                    FQDN (0 or 1)
                    SupportedVOs (0 or 1)
                        VO (N)
                            (Name of the VO)
                    VOOwnership (0 or 1)                Shows the list of VOs that owns this resource and how much percentage it owns
                        Ownership (1)
                            Percent (1)
                            VO (1)                      Name of the VO (could be "(Other)"

-->
<ResourceSummary>
<?
foreach($this->resource_groups as $resource_group_id=>$resource_list) {

    $resource_group = $this->resourcegroups[$resource_group_id][0];
    echo "<ResourceGroup>";
    $gridtype_name = $this->gridtypes[$resource_group->osg_grid_type_id][0]->description;
    echo "<GridType>";
    echo htmlentities($gridtype_name);
    echo "</GridType>";

    echo "<GroupName>".$resource_group->name."</GroupName>";
    if(isset($_REQUEST["summary_attrs_showdesc"])) {
        echo "<GroupDescription>";
        if($resource_group->description != "") {
            echo htmlentities($resource_group->description);
        } else {
            echo "(No resource group description)";
        }
        echo "</GroupDescription>";
    }


    echo "<Resources>";
    foreach($resource_list as $rid=>$resource) {
        echo "<Resource>";
        echo "<Name>".$resource->name."</Name>";

        if(isset($_REQUEST["summary_attrs_showservice"])) {
            echo "<Services>";
            if(isset($this->resource_services[$rid]) == 0) {
                echo "no applicable service exists";
            } else {
                $services = $this->resource_services[$rid];
                foreach($services as $service) {
                    if(isset($this->servicetypes[$service->service_id])) {
                        echo "<Service><Name>".$this->servicetypes[$service->service_id][0]->description."</Name></Service>";
                    } else {
                        echo "<Service>unknown_service_id:".$service->service_id."</Service>";
                    }
                }
            }
            echo "</Services>";
        }

        if(isset($_REQUEST["summary_attrs_showrsvstatus"])) {
            if(!isset($this->resource_status[$rid])) {
                $note = "Resource status is not calculated for this resource";
                $status = "UNKNOWN";
            } else {
                $resource_status = $this->resource_status[$rid][0];
                $note = $resource_status->detail;
                $status = Status::getStatus($resource_status->status_id);
            }

            if(isset($this->downtime[$rid])) {
                $downtime = $this->downtime[$rid][0];
                $status = "DOWNTIME";
                $downtime_desc = $downtime->downtime_summary;
                $internal_note = $note;
                $note = "This resource is currently under maintenance.\n";
                $note .= "Maintenance Summary: $downtime_desc\n";
                $note .= "Internal status: $internal_note\n";
            }
            echo "<RSVStatus><Status>$status</Status><Note>".htmlentities($note)."</Note></RSVStatus>";
        }

        if(isset($_REQUEST["summary_attrs_showservice"])) {
            if(isset($this->resource_services[$rid]) == 0) {
                $service_names = "no applicable service exists";
            } else {
                $services = $this->resource_services[$rid];
                $service_names = "";
                foreach($services as $service) {
                    if($service_names != "") $service_names .= " / ";
                    if(isset($this->servicetypes[$service->service_id])) {
                        $service_names .= $this->servicetypes[$service->service_id][0]->description;
                    } else {
                        $service_names .= "unknown_service_id:".$service->service_id;
                    }
                }
            }
        }

        if(isset($_REQUEST["summary_attrs_showdesc"])) {
            echo "<Description>";
            if($resource->description != "") {
                echo htmlentities($resource->description);
            } else {
                echo "(No resource description)";
            }
            echo "</Description>";
        }

        if(isset($_REQUEST["summary_attrs_showfqdn"])) {
            echo "<FQDN>".$resource->fqdn."</FQDN>";
        }

        if(isset($_REQUEST["summary_attrs_showvomembership"])) {
            echo "<SupportedVOs>";
            if(isset($this->vos_supported[$rid])) {
                $volist = $this->vos_supported[$rid];
                foreach($volist as $vo) {
                    echo "<VO>$vo</VO>";
                }
            } else {
                echo "(Information not reported)";
            }
            echo "</SupportedVOs>";
        }

        if(isset($_REQUEST["summary_attrs_showvoownership"])) {
            echo "<VOOwnership>";
            $ownership = $this->resource_ownerships[$rid];
            if($ownership === null) {
                echo "(Information not available)";
            } else {
                $chd = "";
                $chl = "";
                $total = 0;
                foreach($ownership as $item) {
                    echo "<Ownership><Percent>$item->percent</Percent><VO>$item->short_name</VO></Ownership>";
                    if($chd != "") $chd .= ",";
                    $chd .= $item->percent;
                    if($chl != "") $chl .= "|";
                    $chl .= $item->short_name."(".$item->percent."%)";
                    $total += $item->percent;
                }
                if($total < 100) {
                    if($chd != "") $chd .= ",";
                    $left = 100 - $total;
                    $chd .= $left;
                    if($chl != "") $chl .= "|";
                    $chl .= "Other($left%)";

                    echo "<Ownership><Percent>$left</Percent><VO>(Other)</VO></Ownership>";
                }
                $url = htmlentities("http://chart.apis.google.com/chart?chco=00cc00&cht=p3&chd=t:$chd&chs=280x65&chl=$chl");
                echo "<ChartURL>$url</ChartURL>";
            }
            echo "</VOOwnership>";
        }
        echo "</Resource>";
    }
    echo "</Resources>";
    echo "</ResourceGroup>";
}
?>
</ResourceSummary>
