<!--
This XML contains the requested resource summary information.

Structure:
    * () shows number of elements. N means there could be any number of them

    ResourceSummary (1)
        ResourceGroup (N)
            GridType (1)                                Grid Type for the resource group
            GroupID (1)                                 Resource Group ID in database
            GroupName (1)                               Name of the Resource Group
            GroupDescription (0 or 1)                   Description for the resource group as stored in OIM
            Resources (1)
                 Resource (N)
                      ID (1)                            Resource id in database
                    Name (1)                            Name of the resource
                    Active (1)                          Show Active / Inactive Status flag
                    Disable (1)                         Show Disable flag
                    Services (0 or 1)                   Services that are supported by this resource
                        Service (N)
                            ID (1)                      Service id in database
                            Name (1)                    Name of the service
                    RSVStatus (0 or 1)
                        Status (1)
                        Note (1)
                    GIPStatus (0 or 1)
                        Status (1)
                    Description (0 or 1)
                    FQDN (0 or 1)
                    SupportedVOs (0 or 1)
                        VO (N)
                            (Name of the VO)
                    VOOwnership (0 or 1)                Shows the list of VOs that owns this resource and how much percentage it owns
                        Ownership (1)
                            Percent (1)
                            VO (1)                      Name of the VO (could be "(Other)"
                    WLCGInformation (0 or 1)
                        InteropBDII (1)
                            (True / False)
                        InteropMonitoring (1)
                            (True / False)
                        InteropAccounting (1)
                            (True / False)
                        AccountingName (1)
                        KSI2KMin (1)
                        KSI2KMax (1)
                        StorageCapacityMin (1)
                        StorageCapacityMax (1)
                    ENV (0 or 1)                       Environment Parameters
                        (Various ENV parameters)
                    ContactLists (0 or 1)
                        ContactList (N)
                            ContactType (1)
                            Contacts (1)
                                Contact (N)
                                    Name (1)
                                    Email (1)
                                    Rank (1)
-->
<ResourceSummary>
<?
foreach($this->resource_groups as $resource_group_id=>$resource_list) {

    $resource_group = $this->resourcegroups[$resource_group_id][0];
    echo "<ResourceGroup>";
    $gridtype_name = $this->gridtypes[$resource_group->osg_grid_type_id][0]->description;
    echo "<GridType>";
    echo htmlentities($gridtype_name);
    echo "</GridType>";

    echo "<GroupID>".$resource_group->id."</GroupID>";
    echo "<GroupName>".$resource_group->name."</GroupName>";
    if(isset($_REQUEST["summary_attrs_showdesc"])) {
        echo "<GroupDescription>";
        if($resource_group->description != "") {
            echo htmlentities($resource_group->description);
        } else {
            echo "(No resource group description)";
        }
        echo "</GroupDescription>";
    }


    echo "<Resources>";
    foreach($resource_list as $rid=>$resource) {
        echo "<Resource>";
        echo "<ID>".$resource->id."</ID>";
        echo "<Name>".$resource->name."</Name>";

        echo "<Active>";
        if($resource->active == 1) { 
            echo "True"; 
        } else {
            echo "False"; 
        }
        echo "</Active>";

        echo "<Disable>";
        if($resource->disable == 1) { 
            echo "True"; 
        } else {
            echo "False"; 
        }
        echo "</Disable>";

        if(isset($_REQUEST["summary_attrs_showservice"])) {
            echo "<Services>";
            if(isset($this->resource_services[$rid]) == 0) {
                echo "no applicable service exists";
            } else {
                $services = $this->resource_services[$rid];
                foreach($services as $service) {
                    if(isset($this->servicetypes[$service->service_id])) {
                        echo "<Service>".
                          "<ID>".$service->service_id."</ID>".
                          "<Name>".$this->servicetypes[$service->service_id][0]->name."</Name>".
                          "<Description>".htmlentities($this->servicetypes[$service->service_id][0]->description)."</Description>";
                        echo "<ServiceUri>";

                        if ($service->endpoint_override != "") {
                          echo $service->endpoint_override;
                        }
                        else {
                          echo $resource->fqdn.":".$this->servicetypes[$service->service_id][0]->port; 
                        }
                        echo "</ServiceUri>";
                        echo "</Service>";
                    } else {
                        echo "<Service>unknown_service_id:".$service->service_id."</Service>";
                    }
                }
            }
            echo "</Services>";
        }

        if(isset($_REQUEST["summary_attrs_showrsvstatus"])) {
            if(!isset($this->resource_status[$rid])) {
                $note = "Resource status is not calculated for this resource";
                $status = "UNKNOWN";
            } else {
                $resource_status = $this->resource_status[$rid][0];
                $note = $resource_status->detail;
                $status = Status::getStatus($resource_status->status_id);
            }

            if(isset($this->downtime[$rid])) {
                $downtime = $this->downtime[$rid][0];
                $status = "DOWNTIME";
                $downtime_desc = $downtime->downtime_summary;
                $internal_note = $note;
                $note = "This resource is currently under maintenance.";
                $note .= "Maintenance Summary: $downtime_desc";
                $note .= "Internal status: $internal_note";
            }
            echo "<RSVStatus><Status>$status</Status><Note>".htmlentities($note)."</Note></RSVStatus>";
        }

        if(isset($_REQUEST["summary_attrs_showgipstatus"])) {
            $status = "UNKNOWN";
            foreach($this->gipstatus as $gip) {
                if($resource->name == $gip->Name) {
                    $status = (string)$gip->OverAllStatus;
                    break;
                }
            } 
            echo "<GIPStatus><Status>$status</Status></GIPStatus>";
        }


        if(isset($_REQUEST["summary_attrs_showservice"])) {
            if(isset($this->resource_services[$rid]) == 0) {
                $service_names = "no applicable service exists";
            } else {
                $services = $this->resource_services[$rid];
                $service_names = "";
                foreach($services as $service) {
                    if($service_names != "") $service_names .= " / ";
                    if(isset($this->servicetypes[$service->service_id])) {
                        $service_names .= $this->servicetypes[$service->service_id][0]->description;
                    } else {
                        $service_names .= "unknown_service_id:".$service->service_id;
                    }
                }
            }
        }

        if(isset($_REQUEST["summary_attrs_showdesc"])) {
            echo "<Description>";
            if($resource->description != "") {
                echo htmlentities($resource->description);
            } else {
                echo "(No resource description)";
            }
            echo "</Description>";
        }

        if(isset($_REQUEST["summary_attrs_showfqdn"])) {
            echo "<FQDN>".$resource->fqdn."</FQDN>";
        }

        if(isset($_REQUEST["summary_attrs_showvomembership"])) {
            echo "<SupportedVOs>";
            if(isset($this->vos_supported[$rid])) {
                $volist = $this->vos_supported[$rid];
                foreach($volist as $vo) {
                    echo "<VO>$vo</VO>";
                }
            } else {
                echo "(Information not reported)";
            }
            echo "</SupportedVOs>";
        }

        if(isset($_REQUEST["summary_attrs_showvoownership"])) {
            echo "<VOOwnership>";
            $ownership = @$this->resource_ownerships[$rid];
            if($ownership === null) {
                echo "(Information not available)";
            } else {
                $chd = "";
                $chl = "";
                $total = 0;
                foreach($ownership as $item) {
                    echo "<Ownership><Percent>$item->percent</Percent><VO>$item->name</VO></Ownership>";
                    if($chd != "") $chd .= ",";
                    $chd .= $item->percent;
                    if($chl != "") $chl .= "|";
                    $chl .= $item->name."(".$item->percent."%)";
                    $total += $item->percent;
                }
                if($total < 100) {
                    if($chd != "") $chd .= ",";
                    $left = 100 - $total;
                    $chd .= $left;
                    if($chl != "") $chl .= "|";
                    $chl .= "Other($left%)";

                    echo "<Ownership><Percent>$left</Percent><VO>(Other)</VO></Ownership>";
                }
                $url = htmlentities("http://chart.apis.google.com/chart?chco=00cc00&cht=p3&chd=t:$chd&chs=280x65&chl=$chl");
                echo "<ChartURL>$url</ChartURL>";
            }
            echo "</VOOwnership>";
        }

        if(isset($_REQUEST["summary_attrs_showwlcg"])) {
            echo "<WLCGInformation>";
            if(isset($this->resource_wlcg[$rid])) {
                echo "(Information not available)";
            } else {
                $info = $this->resource_wlcg[$rid][0];
                $value = "False";
                if($info->interop_bdii == 1) { $value = "True"; }
                echo "<InteropBDII>$value</InteropBDII>";
                echo "<LDAPURL>$info->ldap_url</LDAPURL>";

                $value = "False";
                if($info->interop_monitoring == 1) { $value = "True"; }
                echo "<InteropMonitoring>$value</InteropMonitoring>";

                $value = "False";
                if($info->interop_accounting == 1) { $value = "True"; }
                echo "<InteropAccounting>$value</InteropAccounting>";

                echo "<AccountingName>$info->accounting_name</AccountingName>";
                echo "<KSI2KMin>$info->ksi2k_minimum</KSI2KMin>";
                echo "<KSI2KMax>$info->ksi2k_maximum</KSI2KMax>";
                echo "<StorageCapacityMin>$info->storage_capacity_minimum TB</StorageCapacityMin>";
                echo "<StorageCapacityMax>$info->storage_capacity_maximum TB</StorageCapacityMax>";
            }
            echo "</WLCGInformation>";
        }

        if(isset($_REQUEST["summary_attrs_showenv"])) {
            echo "<ENV>";
            $xml = @$this->envs[$rid];
            if($xml === null) {
                echo "(Information Not available)";
            } else {
                foreach($xml as $key=>$value) {
                    echo "<".htmlentities($key).">".htmlentities($value)."</".htmlentities($key).">";
                }
            }
            echo "</ENV>";
        }
        if(isset($_REQUEST["summary_attrs_showcontact"])) {
            $contact_types = @$this->contacts[$rid];
            echo "<ContactLists>";
            foreach($contact_types as $type_name=>$contacts) {
                echo "<ContactList>";
                echo "<ContactType>$type_name</ContactType>";
                echo "<Contacts>";
                foreach($contacts as $contact) {
                    echo "<Contact>";
                    echo "<Name>".$contact->name."</Name>";
                    if(isset($contact->primary_email)) {
                        echo "<Email>".$contact->primary_email."</Email>";
                    }
                    echo "<ContactRank>".$contact->rank_type."</ContactRank>";
                    echo "</Contact>";
                }
                echo "</Contacts>";
                echo "</ContactList>";
            }
            echo "</ContactLists>";
        }

        echo "</Resource>";
    }
    echo "</Resources>";
    echo "</ResourceGroup>";
}
?>
</ResourceSummary>
