<?=$this->render("full_header.phtml", true)?>
        <div id="primaryContentContainer">
            <div id="primaryContent">
                <?=$this->render("breadcrumb.phtml", true)?>
                <h2><?=$this->page_title?></h2>
                <p>This page queries Gratia DB directly via <a href="http://gratiaweb.grid.iu.edu" target="_blank">OSG GratiaWeb Service</a>. It could take a few minutes to render graphs.</p>
                <?=$this->info?>
                <?=$this->render(pagename()."/html.phtml")?>
            </div>
        </div>
        <div id="sideContent">
            <?=$this->render("rg/wizard.phtml")?>
            <?=$this->render("feedback.phtml", true)?>
        </div>
<?=$this->render("full_footer.phtml", true)?>
