<?php

$pageid = getuid();

?>

<div id="detail_overall_status_<?=$pageid?>">
    <div class="x-panel-body">
<?
    $metricstatus = $this->overall_status["status"];
    $div_class = "status_$metricstatus";
    $detail = $this->overall_status["detail"];
?>

        <div class='metric <?=$div_class?>'>
        <div class='metric_name'><?=$metricstatus?></div>
        <p><?=$detail?></p>
        </div>
        
    </div>
</div>
<?
foreach($this->service_types as $service_type) {
    $service_id = $service_type->service_id;
?>
<br />
    <div id="detail_core_metrics_<?=$service_id?>_<?=$pageid?>">
        <div class="x-panel-body">
        <?
        foreach($this->metrics as $metric) {
            if($metric->isCriticalFor($service_id)) {
                output_metric($metric);
            }
        }
        ?>
        </div>
    </div>
<? } ?>

<br />
<div id="detail_other_metrics_<?=$pageid?>">
    <div class="x-panel-body">
    <?
    $other_metric_count = 0;
    foreach($this->service_types as $service_type) {
        $service_id = $service_type->service_id;
        foreach($this->metrics as $metric) {
            if($metric->isNonCriticalFor($service_id)) {
                //for noncritical probes, only show it if we have data
                if($metric->hasData()) {
                    output_metric($metric);
                    $other_metric_count++;
                }
            }
        }
    }
    if($other_metric_count == 0) {
        echo "<div class='metric'>No other non-critical metrics are associated with any of the service type associated for this resource.</div>";
    }
    ?>
    </div>
</div>

<script type="text/javascript">
new Ext.Panel({
    title: 'Overall Status',
    collapsible:true,
    autoWidth:true,
    autoHeight:true,
    applyTo: 'detail_overall_status_<?=$pageid?>'
});

<?
foreach($this->service_types as $service_type) {
    $service_id = $service_type->service_id;
    $service_name = $service_type->description;
    ?>
        new Ext.Panel({
            title: '<?=$service_name?> Critical Metrics',
            collapsible:true,
            autoWidth:true,
            autoHeight:true,
            applyTo: 'detail_core_metrics_<?=$service_id?>_<?=$pageid?>'
        });
    <?
}
?>

new Ext.Panel({
    title: 'Noncritcal Metrics',
    collapsible:true,
    autoWidth:true,
    autoHeight:true,
    applyTo: 'detail_other_metrics_<?=$pageid?>'
});

$("#detail_overall_status_<?=$pageid?> .metric:last").css("border-bottom", "none");
<?  foreach($this->service_types as $service_type) {
    $service_id = $service_type->service_id;
?>
    $("#detail_core_metrics_<?=$service_id?>_<?=$pageid?> .metric:last").css("border-bottom", "none");
<?  } ?>
$("#detail_other_metrics_<?=$pageid?> .metric:last").css("border-bottom", "none");
</script>


<?
function output_metric($metric)
{
    if($metric->hasData()) {
        output_metric_detail($metric);
    } else {
        output_metric_holder($metric); //data not available..
    }
}

function output_metric_holder($metric)
{
    $metricname = $metric->getCommonName();

    echo "<div class='metric status_UNKNOWN'>";
    echo "<div class='metric_name'>$metricname</div>";
    echo "<p class='error'>This metric has never been reported for this resource. No data available.</p>";
    echo "</div>";
}

/*
function status2class($status)
{
    switch($status) {
    case "CRITICAL":
        return "status_critical"; 
    case "OK":
        return "status_ok"; 
    case "WARNING":
        return "status_warning"; 
    case "UNKNOWN":
    default:
        return "status_unknown"; 
    }
}
*/

function output_metric_detail($status)
{

    $div_class = "metric";
    $metricname = $status->getCommonName();
    $metric_id = $status->getMetricID();

    $metricstatus = $status->getStatus();
    $div_class .= " status_$metricstatus";
    echo "<div class='$div_class'>";

    $timestamp = $status->getUnixTimestamp();
    $timestamp_str = date(config()->date_format_full, $timestamp);
    $sec_ago = time() - $timestamp;
    $min = (int)($sec_ago / 60);
    if($min < 2) {
        $ago = $sec_ago." seconds ago";
    } else {
        $hour = (int)($min / 60);
        if($hour < 2) {
            $ago = $min." minutes ago";
        } else {
            $day = (int)($hour / 24);
            if($day < 2) {
                $ago = $hour." hours ago";
            } else {
                $ago = $day." days ago";
            }
        }
    }
    echo "<span class='post-date'>($ago) $timestamp_str UTC<br/></span>";
    echo "<div class='metric_name'>$metricname</div>";

    //is metric too old?
    if($status->isOld()) {
        echo "<p class='error'>Old data.</p>";
    }

    $detail = $status->getDetailsData();
    if(trim($detail) == "") {  
        echo "<div class='detail'><pre>(No Details)</pre></div>";
    } else {
        $divid = getuid();
        ?>
        <div id='show_<?=$divid?>' class='button'><img src='images/plusbutton.gif'/> Show Detail</div>
        <div id='hide_<?=$divid?>' class='hidden button'><img src='images/minusbutton.gif'/> Hide Detail</div>
        <script type='text/javascript'>
        $('#show_<?=$divid?>').click(function() {
            $('#detail_<?=$divid?>').slideDown();
            $('#show_<?=$divid?>').hide();
            $('#hide_<?=$divid?>').show();
            Ext.getCmp('detailpanel').doLayout();
        });
        $('#hide_<?=$divid?>').click(function() {
            $('#detail_<?=$divid?>').slideUp();
            $('#hide_<?=$divid?>').hide();
            $('#show_<?=$divid?>').show();
            Ext.getCmp('detailpanel').doLayout();
        });
        </script>
        <div class='detail hidden' id='detail_<?=$divid?>'><pre><?=$detail?></pre></div>
        <?
    }
    echo "</div>";
}
?>


