<div class="sidenote">Status calculated at <?=date(config()->date_format_full, $this->timestamp)?></div>

<h3>Overall Status</h3>
<div class="status_<?=$this->status?>">
<p><?=$this->note?></p>
</div>

<?
function outputMetricInfo($metric)
{
    $detail = $metric->Detail;
    $out = "";
    $out .= "<div class=\"bottom_border status_".$metric->Status."\">";
    if($metric->Timestamp != "") {
        $out .= "<div class=\"sidenote\">Reported ".agoCalculation((int)$metric->Timestamp)."</div>";
    }
    $out .= "<span class=\"h4\">".$metric->MetricName."</span>"; 
    if(isset($_REQUEST["uwa"])) {
        $out .= "<pre>$detail</pre>";
    } else {
        if(trim($detail) == "") {
            $out .= "<br/>(No detail provided)<br/>";
        } else {
            $detail = "<pre>$detail</pre>";
            $out .= outputToggle("Show Detail", "Hide Detail", $detail);
        }
    }
    $out .= "</div>";

    return $out;
}

foreach($this->services as $service) {
    echo "<h3>".$service->ServiceDescription." Service Status</h3>"; 
    echo "<div class=\"status_".$service->Status."\">";

    echo $service->Note;
    //critical metrics
    $out = "";
    foreach($service->CriticalMetrics[0] as $metric) {
        $out .= outputMetricInfo($metric);
    }
    $title = "<span class=\"h3\">Critical Metrics</span>";
    echo outputToggle($title, $title, $out, true);

    //non-critical metrics
    if(!isset($_REQUEST["uwa"])) {
        $out = "";
        foreach($service->NonCriticalMetrics[0] as $metric) {
            $out .= outputMetricInfo($metric);
        }
        if($out == "") {
            $out = "<div class=\"indent\">There are no non-critical metrics associated with this service.</div>";
        }
        $title = "<span class=\"h3\">Non-Critical Metrics</span>";
        echo outputToggle($title, $title, $out);
    }
    echo "</div>";

}
