<div class="sidenote"><?if(!uwa()) { echo "Status calculated ";}?> at <?=date(config()->date_format_full, $this->timestamp)?></div>

<h3>Overall Status</h3>
<div class="status_<?=$this->status?>">
<p><?=$this->note?></p>
</div>

<?
function outputMetricInfo($metric, $timestamp)
{
    //check expiration
    $freshfor = $metric->MetricFreshFor;
    $expired = !MetricData::isFresh($metric->Timestamp, $freshfor, $timestamp);

    $detail = $metric->Detail;
    $out = "";
    $expired_css = "";
    if($expired) $expired_css = "expired";
    $out .= "<div class=\"bottom_border status_".$metric->Status." $expired_css\">";
    if($metric->Timestamp != "") {
        $out .= "<div class=\"sidenote\">Reported ".agoCalculation((int)$metric->Timestamp)." ago</div>";
    }
    $name = $metric->MetricCommonName;
    $desc = $metric->MetricDescription;
    $help_url = config()->default_rsvforum;
    if(isset(config()->rsvforum[(int)$metric->MetricID])) {
        $help_url = config()->rsvforum[(int)$metric->MetricID];
    }
    if($expired) $name .= " (Expired)";
    $out .= "<span class=\"h4\"><a title=\"$desc\" href=\"$help_url\">".$name."</a></span>";
    if(!isset($_REQUEST["uwa"])) {
        if(trim($detail) == "") {
            $detail = "(No detail provided)<br/>";
        } else {
            $detail = "<pre>$detail</pre>";
            $id = $metric->MetricDataID;
            $detail .= "Metric Data ID: $id ";
            $fresh_for = $metric->MetricFreshFor;
            $detail .= "Fresh for: ".humanDuration($fresh_for);
            $detail .= "<br/>";
        }
        //wrap detail with toggler
        $detail = outputToggle("Show Detail", "Hide Detail", $detail);

        $out .= $detail;
    }
    $out .= "</div>";

    return $out;
}

foreach($this->services as $service) {

    $service_status = $service->Status;
    $note = $service->Note;

    echo "<h3>".$service->ServiceDescription." Service Status</h3>"; 
    echo "<div class=\"status_$service_status\">";
    echo $note;

    //critical metrics
    $out = "";
    foreach($service->CriticalMetrics[0] as $metric) {
        $out .= outputMetricInfo($metric, $this->timestamp);
    }
    if(!isset($_REQUEST["uwa"])) {
        $title = "<span class=\"h3\">Critical Metrics</span>";
        echo outputToggle($title, $title, $out, true);
    } else {
        echo $out;
    }

    //non-critical metrics
    if(!isset($_REQUEST["uwa"])) {
        $non_critical_metrics = $service->NonCriticalMetrics[0];
        $out = "";
        foreach($non_critical_metrics as $metric) {
            if($metric->Detail != "") {
                $out .= outputMetricInfo($metric, $this->timestamp);
            }
        }
        if($out != "") {
            $title = "<span class=\"h3\">Non-Critical Metrics</span>";
            echo outputToggle($title, $title, $out);
        }
    }
    echo "</div>";

}
