<?php
echo "resource_id,name,uri,url,overall_status,service_types,summary";
if(user()->hasRole(role::$view_admin_email)) {
    echo ",admin_name,admin_email";
}
echo "\n";

foreach($this->resources as $resource_id => $resource) {

    $row = $resource["info"];
    $status = $resource["status"];
    $detail = $resource["detail"];
    $counts = $resource["counts"];

    //output basic info about this resource
    $name = $row->name;
    $uri = $row->uri;
    $url = $row->url;

    echo $resource_id.",";
    echo "\"".$name."\",";
    echo "\"".$uri."\",";
    echo "\"".$url."\",";
    echo "\"".$status."\",";

    //get service types
    $service_types = $this->resource_service_types->getServiceTypes($resource_id);
    $s_first = true;
    $all = "";
    foreach($service_types as $service_type) {
        if(!$s_first) $all .= " ";
        $s_first = false;
        $all .= $service_type->description;
    }
    echo "\"".$all."\",";

    echo "\"".str_replace("\"", "\"\"", $detail)."\"";

    if(user()->hasRole(role::$view_admin_email)) {
        $admin_name = trim(str_replace("\n", "", trim($row->first_name." ".$row->last_name)));
        $admin_email = trim(str_replace("\n", "", $row->primary_email));

        echo ",\"".$admin_name."\",";
        echo "\"".$admin_email."\"";
    }
    echo "\n";
}
