
<link rel="stylesheet" type="text/css" href="http://<?=$_SERVER["SERVER_NAME"].base()?>/css/gadget.css" />

<div class="gadget">

<table width="100%">

<?
    foreach($this->resources as $resource_id => $resource) {
        echo "<tr>";
        $row = $resource["info"];
        $status = $resource["status"];
        $detail = $resource["detail"];

        //output basic info about this resource
        $name = $row->name;
        $uri = $row->uri;
        $url = $row->url;
/*

        $admin_name = trim(str_replace("\n", "", trim($row->first_name." ".$row->last_name)));
        $admin_email = trim(str_replace("\n", "", $row->primary_email));
*/

        //echo "'url':'$url',";

        /*
        if(user()->hasRole(role::$view_admin_email)) {
            echo "'admin_name':'$admin_name',";
            echo "'admin_email':'$admin_email',";
        }
        */


/*
        //get service types
        $service_types = $this->resource_service_types->getServiceTypes($resource_id);
        $s_first = true;
        echo "<td>";
        foreach($service_types as $service_type) {
            if(!$s_first) echo " / ";
            $s_first = false;
            echo $service_type->description;
        }
        echo "</td>";
*/

        switch($status) {
            case "OK":
                $icon = "small_ok.png";
                break;
            case "CRITICAL":
                $icon = "small_cross.png";
                break;
            case "WARNING":
                $icon = "error.png";
                break;
            case "UNKNOWN":
                $icon = "s.gif";
                break;
        }
        echo "<td><img src=\"http://".$_SERVER["SERVER_NAME"].base()."/images/$icon\"/></td>";
        echo "<td>$name</td>";
        echo "<td>$uri</td>";

        $summary = $detail;
        //echo "'summary':'".htmlentities($summary, ENT_QUOTES)."'";
        echo "</tr>";

    }

?>
</table>

</div>
