<? $count = count($this->vos); ?>
{
    'results': <?=$count?>, 'rows': [
<?
        $first = true;
        foreach($this->vos as $row) {
            if(!$first) echo ",";
            $first = false;

            echo "{";
            echo "'id': ".$row->id.",";
            echo "'resource_id': ".$row->resource_id.",";
            echo "'name':'".$row->name."',";
            echo "'vo':'".$row->vo_id."',";
            echo "'vo_name':'".$row->long_name."'";
            echo "}\n";
        }
?> 
    ]
}

