<?
foreach($this->cache as $rid=>$cache) {
    $timestamp = (int)$cache->Timestamp[0];
    $status = $cache->Status[0];
    $note = $cache->Note[0];
    $services = $cache->Services[0];

    $resource = $this->resources[$rid];
    $resource_name = $resource->name;
    $resource_fqdn = $resource->fqdn;

    ?>
    <div class="border">
    <div class="status_<?=$status?>">
    <span class="h4"><div class="resource">
    <?
    if(uwa()) {
        echo "<a target=\"_blank\" href=\"".fullbase()."/wizardcurrentstatus/index?datasource=currentstatus&current_status_attrs_shownc=on&r=on&r_$rid=on\">$resource_name (<tt>$resource_fqdn</tt>)</a>";
    } else {
        echo $resource_name . " (<tt>" . $resource_fqdn . "</tt>)";
    }
    ?>
    </div></span>

    <p><?=$note?></p>
    </div>
    <div class="indent">
    <?
    foreach($services as $service) {

        $service_status = $service->Status;
        $note = $service->Note;

        echo "<h3>".$service->ServiceDescription." Service Status</h3>"; 
        echo "<div class=\"status_$service_status\">";
        echo $note;

        //critical metrics
        $out = "";
        foreach($service->CriticalMetrics[0] as $metric) {
            $out .= outputMetricInfo($metric, $timestamp);
        }
        if(!isset($_REQUEST["uwa"])) {
            $title = "<span class=\"h3\">Critical Metrics</span>";
            echo outputToggle($title, $title, $out, true);
        } else {
            echo $out;
        }

        //non-critical metrics
        if(!isset($_REQUEST["uwa"]) and isset($_REQUEST["current_status_attrs_shownc"])) {
            $non_critical_metrics = $service->NonCriticalMetrics[0];
            $out = "";
            foreach($non_critical_metrics as $metric) {
                if($metric->Detail != "") {
                    $out .= outputMetricInfo($metric, $timestamp);
                }
            }
            if($out != "") {
                $title = "<span class=\"h3\">Non-Critical Metrics</span>";
                echo outputToggle($title, $title, $out);
            }
        }
        echo "</div>";
    }
    echo "</div>";//indent
    echo "</div>";//border
}


function outputMetricInfo($metric, $timestamp)
{
    //check expiration
    $freshfor = $metric->MetricFreshFor;
    $expired = !MetricData::isFresh($metric->Timestamp, $freshfor, $timestamp);

    $detail = $metric->Detail;
    $out = "";
    $expired_css = "";
    if($expired) $expired_css = "expired";
    $out .= "<div class=\"bottom_border status_".$metric->Status." $expired_css\">";
    if($metric->Timestamp != "") {
        $out .= "<div class=\"sidenote\">Reported ".agoCalculation((int)$metric->Timestamp)." ago</div>";
    }
    $name = $metric->MetricCommonName;
    $desc = $metric->MetricDescription;
    $help_url = config()->default_rsvforum;
    if(isset(config()->rsvforum[(int)$metric->MetricID])) {
        $help_url = config()->rsvforum[(int)$metric->MetricID];
    }
    if($expired) $name .= " (Expired)";
    $out .= "<span class=\"h4\">$name</span>";
    if(!uwa()) {
        $out .= " <a target=\"_help\" href=\"$help_url\"><img src=\"".fullbase()."/images/help.png\" style='align: bottom;'/></a>";
        $out .= "<br/><span class=\"note\">$desc</span>";
    }
    if(!isset($_REQUEST["uwa"])) {
        if(trim($detail) == "") {
            $detail = "(No detail provided)<br/>";
        } else {
            $detail = "<pre>$detail</pre>";
            $id = $metric->MetricDataID;
            $detail .= "Metric Data ID: $id ";
            $fresh_for = $metric->MetricFreshFor;
            $detail .= "Fresh for: ".humanDuration($fresh_for);
            $detail .= "<br/>";
        }
        //wrap detail with toggler
        $detail = outputToggle("Show Detail", "Hide Detail", $detail);

        $out .= $detail;
    }
    $out .= "</div>";

    return $out;
}

