<h3>Currently Under Maintenance</h3>
<?
showdowntimes($this->current_downtimes);
?>

<h3>Future Maintenance</h3>
<?
showdowntimes($this->future_downtimes);
?>

<?
function showdowntimes($downtimes) {
    foreach($downtimes as $downtime)
    {
        echo "<div class='border'>";

        echo "<h4><div class='resource'>".$downtime["name"]."</div></h4>";
        
        echo "<div class=\"indent\">";
        echo "<table class=\"summary_table\">";

        echo "<tr><th>Start Time</th><td>".$downtime["start_time"]."</td></tr>";
        echo "<tr><th>End Time</th><td>".$downtime["end_time"]."</td></tr>";

        echo "<tr><th>Affected&nbsp;Services</th><td>";
        foreach($downtime["services"] as $service) {
            echo $service."<br/>";
        }
        echo "</td></tr>";

        //show downtime detail
        echo "<tr><th>Detail</th><td><div class=\"downtime\">";
        echo "<p>".$downtime["desc"]."</p>";
        echo "</div></td></tr>";

        echo "</table>";
        echo "</div>";

        echo "</div>";//border
    }
}

