<Downtimes>
<?if(isset($_REQUEST["downtime_attrs_showpast"])) {?>
    <PastDowntimes>
    <?showdowntimes($this->past_downtimes); ?>
    </PastDowntimes>
<?}?>
<CurrentDowntimes>
<?showdowntimes($this->current_downtimes); ?>
</CurrentDowntimes>
<FutureDowntimes>
<?showdowntimes($this->future_downtimes); ?>
</FutureDowntimes>
</Downtimes>
<?
function showdowntimes($downtimes) {
    foreach($downtimes as $downtime)
    {
        echo "<Downtime>";
        echo "<ID>".$downtime["id"]."</ID>";
        echo "<ResourceName>".htmlsafe($downtime["name"])."</ResourceName>";
        echo "<ResourceID>".htmlsafe($downtime["resource_id"])."</ResourceID>";
        echo "<StartTime>".$downtime["start_time"]."</StartTime>";
        echo "<EndTime>".$downtime["end_time"]."</EndTime>";
        echo "<Class>".htmlsafe($downtime["class"])."</Class>";
        echo "<Severity>".htmlsafe($downtime["severity"])."</Severity>";
        echo "<DN>".htmlsafe($downtime["dn"])."</DN>";

        echo "<Services>";
        foreach($downtime["services"] as $service) {
            echo "<Service>";
            echo "<ID>".htmlsafe($service->id)."</ID>";
            echo "<Name>".htmlsafe($service->name)."</Name>";
            echo "<Description>".htmlsafe($service->description)."</Description>";
            echo "</Service>";
        }
        echo "</Services>";
        echo "<Description>".htmlsafe($downtime["desc"])."</Description>";
        echo "</Downtime>";
    }
}
