<Downtimes>
<CurrentDowntime>
<?showdowntimes($this->current_downtimes); ?>
</CurrentDowntime>
<FutureDowntime>
<?showdowntimes($this->future_downtimes); ?>
</FutureDowntime>
</Downtimes>
<?
function showdowntimes($downtimes) {
    foreach($downtimes as $downtime)
    {
        echo "<Downtime>";
        echo "<ResourceName>".htmlentities($downtime["name"])."</ResourceName>";
        echo "<StartTime>".$downtime["start_time"]."</StartTime>";
        echo "<EndTime>".$downtime["end_time"]."</EndTime>";

        echo "<Services>";
        foreach($downtime["services"] as $service) {
            echo "<Service>".$service."</Service>";
        }
        echo "</Services>";
        echo "<Description>".htmlentities($downtime["desc"])."</Description>";
        echo "</Downtime>";
    }
}
