<style>
div.resource {
margin-bottom: 0px;
}
table th {
max-width: 300px;
}
.table th, 
.table td {
padding: 3px;
}
tr.noborder > th,
tr.noborder > td {
border-top: none;
}
</style>
<h2><?php echo $this->page_title?> 
<small>
Between <?php echo date(config()->date_format, $this->start_time);?> 
and <?php echo date(config()->date_format, $this->end_time)?></span><br>
</small>
</h2>
<table class="table">
<?
    $first_rg = true;
    foreach($this->rgs as $rgid=>$rg) {

        //show resource group header
        $resource_group = $this->resource_groups[$rgid][0];
        $resource_group_header = "<div class=\"group_header\">";
        $resource_group_header .= "<span class='h3'>".$resource_group->name."</span>";
        $resource_group_header .= " <small>".$resource_group->grid_type."</small>";
        $resource_group_header .= "</div>";
        if($first_rg) {
            echo "<tr class=\"noborder\"><th>$resource_group_header</th><th></th><th>Availability</th><th>Reliability</th>";
            $first_rg = false;
        } else {
            echo "<tr class=\"noborder\"><td colspan='4'>$resource_group_header</td></tr>";
        }

        foreach($rg as $resource_id=>$resource_info) {
            $resource_th = "<th>";
            $resource_th .= "<div class=\"resource\">";
            $resource_th .= "<span class=\"h4\">".$resource_info->name."</span>";
            $resource_th .= " <code>$resource_info->fqdn</code>";
            $resource_th .= "</div>";
            $resource_th .= "</th>";

            if(isset($this->data[$resource_id])) {
                $resource = $this->data[$resource_id];
                $resource_name = $resource_info->name;

                $first = true;
                foreach($resource as $service_id=>$data) {
                    if($data == null) continue;
                    $service_info = $this->services[$service_id];
                    $service_name = $service_info[0]->name;
                    $a = round((double)$data["availability"]*100, 2);
                    $r = round((double)$data["reliability"]*100, 2);

                    echo "<tr>";
                    if($first) {
                        echo $resource_th;
                        $first = false;
                    } else {
                        echo "<th style=\"border: none\"></th>";//don't show resource name.
                    }
                    echo "<td>$service_name</td><td>$a%</td><td>$r%</td>";
                    echo "</tr>";
                }
            } else {
                echo "<tr>".$resource_th;
                echo "<td colspan='3'><span class=\"muted\">No data available for this resource</span></td>";
                echo "</tr>";
            }
        }
    }
?>
</table>

