<?
$name = $this->detail->Name[0];
$details = $this->detail->Detail;

if(count($details) == 0) {
    echo "(No issue found)";
} else {
    foreach($details as $detail) {

        //ok, so here is something that I'd really rather not do..
        //basically, there is some kind of bug in the pre-wrap behavior of 
        //almost all browser, that if there is a single word that is longer than
        //the available width of the container div, the text won't get correrctly
        //wrapped.. GIP detail has tons of extremely wrong word (LDAP path..) that
        //causess this and until I find a way to fix it (or wait until the browsers/
        //are fixed) I have to keep this workaround in place..
        $detail = str_replace(",", ", ", $detail);

        echo "<p><pre>$detail</pre><p>";
    }
}
