<p class="info">Show basic information about Support Centers.</p>

<?$checked = "";
if(isset($_REQUEST["summary_attrs_showdesc"])) { $checked = "checked=checked"; }?>
<input type="checkbox" name="summary_attrs_showdesc" <?=$checked?>/> Show Description<br/>

<?$checked = "";
if(isset($_REQUEST["summary_attrs_showcontact"])) { $checked = "checked=checked"; }?>
<input type="checkbox" name="summary_attrs_showcontact" <?=$checked?>/> Show Contact Information<br/>

<?$checked = "";
if(isset($_REQUEST["summary_attrs_showsites"])) { $checked = "checked=checked"; }?>
<input type="checkbox" name="summary_attrs_showsites" <?=$checked?>/> Show Supported Sites<br/>


