
<script type="text/javascript" src="<?=fullbase()?>/lib/jquery-1.3.1/ui/ui.datepicker.js"></script>
<link type="text/css" href="<?=fullbase()?>/lib/jquery-1.3.1/themes/base/ui.core.css" rel="Stylesheet" />
<link type="text/css" href="<?=fullbase()?>/lib/jquery-1.3.1/themes/base/ui.theme.css" rel="Stylesheet" />
<link type="text/css" href="<?=fullbase()?>/lib/jquery-1.3.1/themes/base/ui.datepicker.css" rel="Stylesheet" />

<style type="text/css">
.list
{
    padding: 2px;
    background-color: #eee;
    margin-bottom: 10px;
    margin-left: 16px;
    width: 90%;
}
.scrolled_list
{
    height: 160px;
    overflow: auto;
}
span.disabled_span
{
    color: gray;
}
</style>

<form method="get" id="wizard">
    <input type="button" onclick="wizard_submit('index');" value="&nbsp;&nbsp;&nbsp;Update Page&nbsp;&nbsp;&nbsp;"/>
    <h3>Information to display</h3>
    <div class="indent" id="datasource_area">
        <select name="datasource">
        <option value="">(Please Select)</option>
        <option value="summary">Support Center Summary</option>
        </select>

        <div id="summary_attrs" class="attrs indent hidden">
            <?=$this->render("sc/wizard_summary.phtml")?>
        </div>
    </div>

    <h3>Support Centers to display</h3>
    <div class="indent">
        <div id="sc_area_standby">
            <p>Please select the information to display first.</p>
        </div>
        <div id="sc_area" class="hidden">
            <p>Select support center that you want to show above information (conditions are or-ed).</p>
            <?
            function checklist($id, $title, $kv)
            {
                //output title check box
                $checked = "";
                if(isset($_REQUEST[$id])) { 
                    $checked = "checked=checked"; 
                    ?>
                    <script type="text/javascript">
                    $(document).ready(function() {
                        $("#<?=$id?>__list").show();
                    });
                    </script>
                    <?
                }
                $title = "<input type=\"checkbox\" name=\"$id\" $checked onclick=\"if(this.checked) {\$('#${id}__list').show('normal');} else {\$('#${id}__list').hide();}\"/> <span>$title</span><br/>";

                //determine list class
                $c = "hidden ";
                if(count($kv) > 8) { 
                    $c .= "scrolled_list ";
                }

                //output list
                $list = "";
                $list .= "<div class=\"$c list\" id=\"${id}__list\">";
                foreach($kv as $key=>$value) {
                    $name = "${id}_$key";
                    $checked = "";
                    if(isset($_REQUEST[$name])) {
                        $checked = "checked=checked";
                    }
                    $list .= "<input type=\"checkbox\" name=\"$name\" $checked/> <span>$value</span><br/>";
                }
                $list .= "</div>";

                return "<div id=\"$id\">".$title.$list."</div>";
            }

            function radiolist($id, $title, $kv, $default)
            {
                //output title check box
                $checked = "";
                if(isset($_REQUEST[$id])) { 
                    $checked = "checked=checked"; 
                    ?>
                    <script type="text/javascript">
                    $(document).ready(function() {
                        $("#<?=$id?>__list").show();
                    });
                    </script>
                    <?
                }
                $title = "<input type=\"checkbox\" name=\"$id\" $checked onclick=\"if(this.checked) {\$('#${id}__list').show('normal');} else {\$('#${id}__list').hide();}\"/> <span>$title</span><br/>";

                //determine list class
                $c = "hidden ";
                if(count($kv) > 8) { 
                    $c .= "scrolled_list ";
                }

                //output list
                $list = "";
                $list .= "<div class=\"$c list\" id=\"${id}__list\">";

                //set default 
                $current_value = $default; 
                $name = "${id}_value";
                if(isset($_REQUEST[$name])) {
                    $current_value = $_REQUEST[$name];
                }

                foreach($kv as $key=>$value) {
                    $checked = "";
                    if($current_value == $key) {
                        $checked = "checked=checked";
                    }
                    $list .= "<input type=\"radio\" name=\"$name\" value=\"$key\" $checked/> <span>$value</span><br/>";
                }
                $list .= "</div>";

                return "<div id=\"$id\">".$title.$list."</div>";
            }
             
            $checked = "";
            if(isset($_REQUEST["all_scs"])) { $checked = "checked=checked"; }
            echo "<input type=\"checkbox\" name=\"all_scs\" $checked onclick=\"if(this.checked) { disable(this);} else {enable(this);}\"/> All Support Centers<br/>";
            echo "<div class=\"hidden list\" id=\"all_scs_attrs\">";
                $checked = "";
                if(isset($_REQUEST["show_disabled"])) { $checked = "checked=checked"; }
                echo "<input type=\"checkbox\" name=\"show_disabled\" $checked/> Show Removed Support Centers<br/>";
            echo "</div>";

            function helpbutton($type)
            {
                return "<a target=\"_help\" href=\"https://twiki.grid.iu.edu/bin/view/Operations/OIMTermDefinition#$type\"><img src=\"".fullbase()."/images/help.png"."\"/></a>";
            }

            $model = new SupportCenters();
            $scs = $model->get();
            $kv = array();
            foreach($scs as $sc) { $kv[$sc->id] = $sc->name; }
            echo checklist("sc", "Specific Support Centers".helpbutton("Support_Center"), $kv);
            
            ?>
        </div>
    </div>

    <h3>Filter</h3>
    <div class="indent">
        <div id="filter_area_standby">
            <p>Please select the information to display first.</p>
        </div>
        <div id="filter_area" class="hidden">
            <p>Only show sc that matches following criteria (conditions are and-ed).</p>
            <?
            $kv = array();
            $kv[0] = "Inactive";
            $kv[1] = "Active";
            echo radiolist("active", "Active Status", $kv, 1); //1 by default
            ?>
        </div>
    </div>

    <br/>
    <input type="button" onclick="wizard_submit('index');" value="&nbsp;&nbsp;&nbsp;Update Page&nbsp;&nbsp;&nbsp;"/>

    <?=$this->render("subscribe.phtml")?>

</form>

<script type="text/javascript">

function showhide_attrs(show_speed)
{
    var v = $("select[name=datasource]").val();
    $(".attrs").hide();
    if(v != "") {
        $("#"+v+"_attrs").show(show_speed);
        $("#sc_area").show(show_speed);
        $("#filter_area").show(show_speed);
        $("#sc_area_standby").hide();
        $("#filter_area_standby").hide();

        if(
            v == "foo_page_that_hasdatarange"
        ) {
            $("#_daterange_attrs").show(show_speed);
        }
    } else {
        $("#sc_area").hide();
        $("#filter_area").hide();
        $("#sc_area_standby").show();
        $("#filter_area_standby").show();
    }
}

$(document).ready(function() {

    //setup form
    $("select[name=datasource]").change(function() {
        showhide_attrs('normal');
    });

    <?
    //select currently selected datasouce
    if(isset($_REQUEST["datasource"])) {
        $datasource = $_REQUEST["datasource"];
        switch($datasource) {
        case "summary":
            echo "$('select[name=datasource] option[value=$datasource]').attr('selected', 'selected');\n";
            echo "showhide_attrs();\n";
        }
    }

    if(isset($_REQUEST["all_scs"])) {
        echo "disable($('input[name=all_scs]'));";
    }
    ?>
});

function wizard_submit(format)
{
    var action = '<?=fullbase()?>/sc'+$('select[name=datasource]').val(); 
    action += "/"+format;
    $('#wizard').attr('action', action);
    $('#wizard').submit(); 
    return false;
}

function disable(e)
{
    var items = $(e).siblings(); 
    $(items).find('input').attr('disabled', 'disabled');
    $(items).find('span').addClass('disabled_span');
    $("#all_scs_attrs").show();
    $("#all_scs_attrs").find('input').removeAttr('disabled');
}
function enable(e)
{
    var items = $(e).siblings(); 
    $(items).find('input').removeAttr('disabled');
    $(items).find('span').removeClass('disabled_span');
    $("#all_scs_attrs").hide();
    $("#all_scs_attrs").find('input').attr('disabled', 'disabled');
}
</script>
