<?
$js = "";
echo "<div class='indent'>";
foreach($this->contact_types as $type=>$contacts)
{
    echo "<b>".$type."</b><br/>";
    foreach($contacts as $contact) {
        $rank = $contact->rank_type;
        echo "<div class=\"indent contact\">";
        echo $contact->first_name. " ".$contact->last_name." ($rank)";
        echo "</div>";
        $id = $contact->person_id;
    }
}
echo "</div>";

?>
<script type="text/javascript">
$(document).ready(function() {
<?=$js?>
});
</script>
