<?
$js = "";

echo "<h3>Support Center</h3>";
$count = $this->sc_count;
$url = fullbase()."/tree/item?type=sc";
echo "<div class=\"indent\">";
echo outputAjaxToggle("Support Centers ($count)", $url);
echo "</div>";

echo "<h3>Facilities</h3>";
$count = $this->facility_count;
$url = fullbase()."/tree/item?type=facility";
echo "<div class=\"indent\">";
echo outputAjaxToggle("Facilities ($count)", $url);
echo "</div>";

?>

<script type="text/javascript">
$(document).ready(function() {
<?=$js?>
});
</script>
