<?
$js = "";

echo "<div class=\"indent\">";
foreach($this->supportcenters as $support_center)
{
    echo "<div class=\"support_center\">";
    echo $support_center->short_name;
    echo "</div>";
    $id = $support_center->sc_id;

    $count = $this->site_counts[$id];
    if($count == 0) {
        echo "<div class=\"indent\">Has no associated sites</div>";
    } else {
        $url = fullbase()."/tree/item?type=supportcenter_site&id=".$id;
        echo "<div class=\"indent\">";
        echo outputAjaxToggle("Sites ($count)", $url);
        echo "</div>";
    }

    $count = $this->contact_counts[$id];
    if($count == 0) {
        echo "<div class=\"indent\">Has no SC contacts</div>";
    } else {
        $url = fullbase()."/tree/item?type=supportcenter_contact&id=".$id;
        echo "<div class=\"indent\">";
        echo outputAjaxToggle("SC Contacts ($count)", $url);
        echo "</div>";
    }

    $count = $this->vo_counts[$id];
    if($count == 0) {
        echo "<div class=\"indent\">Has no Virtual Organization</div>";
    } else {
        $url = fullbase()."/tree/item?type=supportcenter_vo&id=".$id;
        echo "<div class=\"indent\">";
        echo outputAjaxToggle("Virtual Organizations ($count)", $url);
        echo "</div>";
    }
}
echo "</div>";

?>
<script type="text/javascript">
$(document).ready(function() {
<?=$js?>
});
</script>
