<?
$js = "";
echo "<div class='indent'>";
foreach($this->sites as $site)
{
    echo "<div class=\"site\">";
    echo $site->name;
    echo "</div>";
    $id = $site->site_id;
    $count = $this->rg_counts[$id];

    if($count == 0) {
        echo "<div class=\"indent\">Has no resource groups</div>";
    } else {
        $url = fullbase()."/tree/item?type=site_resource_groups&id=".$id;
        
        echo "<div class=\"indent\">";
        echo outputAjaxToggle("Resource Groups ($count)", $url);
        echo "</div>";
    }
}
echo "</div>";

?>
<script type="text/javascript">
$(document).ready(function() {
<?=$js?>
});
</script>
